Interkarma/daggerfall-unity

- Scripts/DaggerfallUnity.cs
- Scripts/GenerateDiagLog.cs
- Scripts/GenerateDiagLog.cs.meta
Log Generator for standalone builds.
> Log generator

- Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
renamed ENHANCED_SKY_AVAILABLE define into ENHANCED_SKY_CODE_AVAILABLE to make it clear that it is a define used to enable/disable code lines dependent on if the mod's code is available
same for REFLECTIONSMOD_CODE_AVAILABLE
there are now 2 boolean flags isActiveReflectionsMod, isActiveEnhancedSkyMod which are set to true at startup if the corresonding mods are active
these flags are used to control IncreasedTerrainDistance mod's behaviour dependent on the available other mods (this should for example fix the nullpointer error when reflectionsmod is disabled)
console command "location" now gives feedback to which location the player has been teleported
> detection of other mods and dependent behavior improved

- Scripts/Game/UserInterface/TextLabel.cs
Recent change to apply a max characters value to the text label will raise an
indexing error if max characters > length of the string
> Fix for indexing bug in TextLabel.SetText()

- Scripts/Game/UserInterface/DaggerfallVideo.cs
Set DaggerfallVideo textures to use the "clamp" repeat mode, which fixes wrapping artifacts when enlarged using smooth filtering (most easily visible in the live-action intro with the torch on the side of the screen).
> Fixed texture wrapping artifacts on video textures.

- Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs
- Scripts/Game/InputManager.cs
created a default keybinding for ToggleConsole key in SetupDefaults()
ConsoleController now sets consoleKey after InputManager.OnLoadedKeyBind event
is triggered to make sure it isn't set before keybinds.ini has been parsed by inputmanager.
"BackQuote": "ToggleConsole", entry needs to be added to KeyBinds.ini
> Added keybind events that are raised when bindings are loaded / saved.

- Scripts/Game/InputManager.cs
- Scripts/Game/PlayerDeath.cs
Adds PlayerDeathInProgress getter to PlayerDeath, 
fixes camera height bug in death animation in PlayerDeath
Stops InputManager from opening windows during death animation (settings window still works), and includes a temp. fix for the constant forward movement when the player dies
> Small changes to InputManager

- Scripts/API/DFBlock.cs
- Scripts/Editor/DaggerfallActionEditor.cs
- Scripts/Game/PlayerActivate.cs
- Scripts/Game/PlayerCollision.cs
- Scripts/Game/PlayerCollision.cs.meta
- Scripts/Game/PlayerCollisionHandler.cs
- Scripts/Game/PlayerCollisionHandler.cs.meta
- Scripts/Game/WeaponManager.cs
- Scripts/Internal/DaggerfallAction.cs
- Scripts/Internal/DaggerfallActionCollision.cs
- Scripts/Internal/DaggerfallActionDoor.cs
- Scripts/Utility/RDBLayout.cs
The "hurt" type actions work like in Daggerfall now.
Added a functioning Drain magicka action.
Fixed up the collision handling for actions
The trigger flags now work like they should in Daggerfall, and  the action will only trigger if the type is valid for that flag
WeaponManager will check for DaggerfallAction component on gameobject the player attacks
DaggerfallActionDoor will check for DaggerfallAction component when its opened / closed
> Action updates

- Game/Addons/IncreasedTerrainDistanceMod/Scripts/CloneCameraPositionFromMainCamera.cs
- Game/Addons/IncreasedTerrainDistanceMod/Scripts/CloneCameraRotationFromMainCamera.cs
- Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedTerrainSampler.cs
- Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedWorldTerrain.cs
- Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Game/Addons/IncreasedTerrainDistanceMod/Scripts/RenderSkyboxWithoutSun.cs
- Game/Addons/IncreasedTerrainDistanceMod/Shaders/DaggerfallIncreasedTerrainTilemap.shader
- Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs
- Game/Addons/ReflectionsMod/Scripts/MirrorReflection.cs
- Game/Addons/ReflectionsMod/Scripts/UpdateReflectionTextures.cs
- Game/Addons/ReflectionsMod/Shaders/DaggerfallTilemapWithReflections.shader
- Game/Addons/ReflectionsMod/Shaders/FloorMaterialWithReflections.shader
- Scripts/Game/DaggerfallAutomap.cs
ReflectionMod improvements
transition should work correct now in all cases (also building2dungeon and dungeon2building)
removed event listening for the approach suggested originally for the automap - but for the reflection mod it really makes things easier ;)
code cleanup
replaced DestroyImmediate with Destroy
removed version number from files (does not make much sense since everything is in git now anyway)
> ReflectionsMod fixes and code cleanup

- Scripts/Game/DaggerfallAutomap.cs
- Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
changed the way camera settings are preserved in 3D mode when closing and reopening the automap window
not all settings are preserved though:
e.g. slice level is reset and pivot axis is always reset to player position
camera is still focusing the player after reopening the map - this is intended
> automap camera settings are now preserved

- Assets/Scripts/Game/DaggerfallAutomap.cs
small fix - this should make vanilla behavior work once save system is wired up (reason for change: even when numberOfDungeonMemorized is 0 there must be one entry in the list of dungeons when saving inside a dungeon - this was incorrectly handled before)
> automap - fixed save state behaviour if numberOfDungeonMemorized is 0

- Assets/Scripts/Game/DaggerfallAutomap.cs
- Assets/Shaders/DaggerfallAutomap.shader
issue was caused by emission color on some textures (for the moment just ignoring emission in the automap shader
added code to remove texture animation for automap geometry (since it is not necessary for automap)
> automap - fireplaces are now correctly shown on automap

- Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
actually these are really good news! I found a fix for global fog to work with the far terrain camera stack. It was easier than expected in the end. only had to fix some bugs on my side and uncheck the checkbox "Exclude Far Pixels" in GlobalFog script. I do this by script when FarTerrain mod is enabled automatically - so it should not break anything when FarTerrain is not active.
you can try it out, go to a location in the mountains (so you see far terrain) and than go to the lighting tab to fog settings and change them (don't let yourself get confused by unity's message about fog and deferred shading - (the message is actually misleading since global fog still uses these values - it should have better been called "without global fog script attached to camera component these values do not …
> FarTerrain - found a fix for global fog to work with camera stack

- Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Assets/Game/Addons/ReflectionsMod/Scripts/MirrorReflection.cs
FarTerrain - sky texture and water height are reassigned in Update() - got lost sometimes otherwise
ReflectionsMod - global fog is used for reflection (when in deferred) - looks correct now with heavy fog
> FarTerrain and ReflectionMod improvements

- Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Assets/Game/Addons/ReflectionsMod/Scripts/MirrorReflection.cs
Reverts Interkarma/daggerfall-unity#127
Cannot use UnityEditor namspace in builds.
> Revert "FarTerrain and ReflectionMod improvements"

- Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Assets/Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs
was a sideeffect of a change to IncreasedTerrainDistanceMod - now the corresponding value that needs to be synched (extraTranslationY) is queried from IncreasedTerrainDistanceMod and applied to ReflectionsMod
> ReflectionsMod - fixed bug with billboards reflecting in sea tiles

- Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs
- Assets/Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs
FarTerrain - starting up with EnhancedSky on/off should now work correctly
toggle between EnhancedSky and vanilla sky at runtime is not working due to a unity bug - see my forum post in the IncreasedTerrainDistanceMod thread in the creator's corner
> FarTerrain - starting up with EnhancedSky on/off now works correctly

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
I tested all the men's clothing in the game, and set the ones that have variants.
I also reordered the existing variant clothing to match the ordering of the enums.
Apparently, though, the number of variants isn't being read correctly from the data files or something. The shirts only cycle through two variants, if any.
For reference, here are the testing results, including the number of clickable variants I saw.
Clothing,                                          Has clickable variants, # of clickable variants
Straps						n
Armbands					n
Kimono						n
Fancy_Armbands				n
Sash						        n
Eodoric						n
Shoes						n
Tall_Boots					        n
Boots						n
Sandals						n
Casual_pants 				        n
Breeches					        n
Short_skirt					n
Casual_cloak				        y, 6
Formal_cloak …
> Set all men's clothing that have variants

- Assets/Scripts/SoundClips.cs
This identifies some of the sounds in SoundClips.cs that weren't identified yet. I wasn't sure what 382 was so I left that undefined.
I will gladly set these to play on equipping the appropriate items if you like. Or is there a reason you would prefer to hold off on that for now? The only issue I'm aware of is that it will play the equip sound  when you load a game.
> Identify equipment sounds and open book sound

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemEquipTable.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SoundClips.cs
This makes items play the correct sounds when equipped, as far as I know. I tested all the weapon equip sounds, etc. I could only test one artifact that I had a save game for, but it played the correct sound, so hopefully those work correctly.
I also made the correct sound play for drawing a weapon, which is the same as the equip sounds. I didn't change the swing sound.
I also changed the spelling of "jewelry" I had added to "jewellery," to match the British spelling you were using. :) It's probably a good idea to keep references to things using the same spelling.
The "equip on load" was pretty jarring if you had a lot of items being equipped. I added in some code to stop it from happening.
Let me know if there is anything you want me to change.
> Play equipping sounds and correct weapon draw sounds

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SoundClips.cs
With this PR the player's weapons will play the correct weapon sounds (as far as I know.)
There are comments in the code about varying the pitch of weapon swings according to attack speed. As far as I can see, this is not what happens in Daggerfall. It just plays one of three sound effects. Two of these were labeled as "EnemySwing1" and "EnemySwing2," but these are used by the player as well, so I renamed them.
The sound effect used seems to be based on the type of weapon. I tried a few different materials of the weapons, and swinging some of them with two different characters, and I got the same results.
I'm not completely sure what all the stuff about attack speeds and sound pitches in the comments is, so I'll leave it to you Interkarma if you want to remove the related TODO comments or …
> Play correct weapon swing sounds

- Assets/Scripts/API/TextFile.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
Just a minor fix. I noticed that the Strength attribute description had a few stray parentheses not there in original Daggerfall. I poked around and found that the check for the "PositionPrefix" token that what comes after it is not a normal character seems to be wrong. This was causing it to show the parentheses instead of use them for PositionPrefix. As far as I saw you can use any value there other than 0x00, which causes Daggerfall to show endless gibberish and crash.
Also Daggerfall Unity was summing together the PositionPrefix to the x cursor but it should be used as an absolute position and not summed. Summing it would cause the second use of PositionPrefix on a line to be moved over too far.
Edit: I wrote various things here about how I thought there should be a default …
> Fix parsing of PositionPrefix format token

- Assets/Scripts/API/TextFile.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharReflexSelect.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
This is a number of minor fixes to the UI windows. I'll try to explain it all here, and please let me know if you want me to change anything.
1. Identify 0xf8 format token.
This token appears in TEXT.RSC for the gold drop input message, and for two tavern room renting input messages. From testing with the gold drop message, it looks like it positions the input cursor. Without it, the cursor appears in the middle of the text window, overlapping other text, so it seems to be used for that. I put in a debug message for it that will show instead of the "Unknown formatting token" one that was showing before.
2. Change panel margins from 12 to 10.
From testing with the text in Daggerfall, I know at least that attribute popup text can go as close as 10 pixels to the left edge, and the top can be …
> Fixes to appearance of UI windows

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Minor change to use the original Daggerfall text. I did the same thing that is done for the drop gold message to replace the token for the location name, and marked it as a temporary hack as it is marked there.
The message from TEXT.RSC is
> Do you wish to travel toý %tcn?ý
Using `GetRSCTokens` to put this into `TextFile.Token[] textTokens` the "%tcn?" is stored in `textTokens[2].text,` while `textTokens[0].text` holds the "Do you wish to travel to" part and  `textTokens[1].text` is null. I don't really understand why there is a null in between them, but this was how it was, so I tell the code to look in `textTokens[2].text` for the token to replace.
> Use original Daggerfall text for travel message

- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterface/TextBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Here are various changes to make the UI text look more like original Daggerfall. Everything in the UI windows I worked on should be positioned like Daggerfall now except for buttons, which are still at the bottom of the window as before this PR, and the items in the misc skills window.
I'll go through the changes here.
1. Skills windows were changed to match what I saw in original Daggerfall, using tabs and no spaces. Tabs of 35 spaces are used, not 45.
2. I determined through experimentation that having a text entry that ends with justify left in original Daggerfall  adds the final newline into the length of the text, while ending with a justify center does not. Unity Daggerfall was adding the newline to the length in either case. Doing the same thing as original Daggerfall allows the …
> Various changes to make UI text positioning more like original Daggerfall

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
Does as the title says. I used the positioning token for this, as it seemed well-suited for it.
As far as I know, all the message windows currently in Daggerfall Unity should be aligned like original Daggerfall now.
> Make misc skills display alignment match classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
Edit: I had a few other changes but I decided I want to reconsider them. I left this one in that I felt was probably worthwhile. It's possible in original Daggerfall to close message windows with the big enter key and the little enter key on the keypad, which in the unity engine means the `Return` KeyCode and the `KeypadEnter` KeyCode.
> Allow return key and keypad enter key to close message boxes

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
This makes the colors for location pixels and the identify flash be pulled from the FMAP_PAL.COL file, like they are in original Daggerfall. I checked the indexes that are used by hex-editing the palette file and watching which ones changed the colors in the original game. I put the RGB values that are read from the file in comments.
With this PR the RGB values will be exactly what they are defined as in the palette file. I can't really tell a difference in the colors that were being used and these colors, but they are slightly different if you look at the rgb values of the pixels. The rgb values of the pixels in DOSBox are slightly different from both of these, and change slightly depending on what you select for "output" in the DOSBox configuration file, or whether you use emulated vga …
> Use palette file for travel map location colors

- Assets/Scripts/Game/FPSWeapon.cs
After some testing in Daggerfall, I found that unarmed hits, including those as a werecreature, only play two of the possible hit sounds. Weapons seem to play all of them.
I made sure by using the program DaggerSound to replace the hit sounds with ones that were easy to tell apart. This made it obvious that only the 3rd and 4th of the 5 possible hit sounds play for unarmed hits.
This is also true for enemy hits. Unarmed enemies only play those same two hit sounds, while enemies with weapons play all of them. This PR only affects the sounds for when the player hits an enemy.
> Differentiate between unarmed hit sounds and weapon hit sounds

- Assets/Scripts/Game/PlayerMotor.cs
If we stand just right on an enemy, the player camera will get unstable. This still allows use to stand on an enemy, however.
> Don't treat enemies as moving platforms

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
- ProjectSettings/TagManager.asset
This isn't a perfect solution, but I figured I'd put it up and see if anyone else has ideas on how to solve this in a simple, elegant manner (without using NavMeshes because I'm not sure if that should be introduced at this stage of development).
In the original game, enemies could overlap if they got close to you. But I assume that isn't the desired behavior for Daggerfall Unity.
> Prevent Rat Stacks

- Assets/Game/Addons/RealGrass/RealGrass ReadMe.txt
- Assets/Game/Addons/RealGrass/RealGrass.cs
Console got a bunch of error messages when I exited the starting dungeon during winter.
It's a grassy climate, but there should be no grass because it's winter. But the code was trying to set the grass texture details (probably with garbage/invalid data). Since grass isn't present during winter, don't try to set texture details.
Original error message:
```
Detail index out of bounds in DetailDatabase.SetLayers
UnityEngine.TerrainData:SetDetailLayer(Int32, Int32, Int32, Int32[,])
DaggerfallWorkshop.Game.RealGrass:AddGrass(DaggerfallTerrain, TerrainData) (at Assets/Game/Addons/RealGrass/RealGrass.cs:245)
DaggerfallWorkshop.DaggerfallTerrain:RaiseOnPromoteTerrainDataEvent(TerrainData) (at Assets/Scripts/Terrain/DaggerfallTerrain.cs:343) …
```
> Fix errors when rendering during winter

- Assets/Game/Addons/RealGrass/RealGrass ReadMe.txt
- Assets/Game/Addons/RealGrass/RealGrass.cs
Grass felt a little sparse and uniform. The main change was adding ranges to the grass width/heights so Unity will generate some more variety in grass patches. The values were tweaked to make the grass look a little more lush and varied.
The grass billboard counts for thick/sparse patches were also tweaked. There'd be grass "walls" where the grass patches stop, which looked odd. So the sparse patches are even sparser and can even be empty, which gives a more natural, decreasing, scattered look near non-grass terrain.
`AddGrass` stop watch times at an outdoor location:
* Original: 2.5 - 4.4 ms
* Change: 3.5 - 6.8 ms
This is approximate from eye-balling the log output after loading my save state.
Also refactoring, cleanup, comments.
Screenshot before:
Screenshot after:
> More natural looking grass

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/DFMeshReplacement.cs
- Assets/Scripts/DFTextureReplacement.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/MeshReader.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/ImageReader.cs
- Assets/Scripts/Utility/RDBLayout.cs
- Assets/Scripts/Utility/RMBLayout.cs
Mesh replacement 
-------------------
(by Uncanny_Valley)
Enable replacement of vanilla 3d models with custom meshes, and flats with custom prefabs.
Models and respective materials need to be placed in Resources during compile.
Texture replacement
----------------------
Enable real-time import of custom textures and images.
* textures for (vanilla) models:
_archive_record-frame.png_ (ex: 9_1-0.png) -and, if necessary, _archive_record-frame_Emission.png_- in
Application.persistentDataPath/textures
* .IMGs:
_imagefile.png_ (ex: REST02I0.IMG.png) in
Application.persistentDataPath/textures/img
* .CIFs and .RCIs:
_CifFile_record-frame.png_ (ex: INVE16I0.CIF_1-0.png) in
Application.persistentDataPath/textures/cif
> Mesh and Texture replacement - Add initial support

- Assets/Game/Addons/RealGrass/RealGrass ReadMe.txt
- Assets/Game/Addons/RealGrass/RealGrass.cs
Grass generated from a previous area wasn't being cleared when the player travels to a non-grass area (season or climate).
> Fix no grass clearing

- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SettingsManager.cs
Mouse movement is now tracked as a gesture. The travel distance and final gesture vector is used to compute the angle of attack.
Practically, this doesn't feel much different from the original way of computing weapon attacks. Initially this was an attempt to get attacks working nicely on a trackpad, but after some thought I think the trackpad compatibility is more about tweaking the sensitivity and threshold values.
The advantage of this approach is gives a bit more control over how attacks can be initiated, how angles are computed, and gives a more natural abstraction of the user input to control (no longer have to maintain the same mouse direction over N frames/cycles).
> Compute attacks from mouse gestures

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Implements stat-based health restoration when resting, based on http://forums.dfworkshop.net/viewtopic.php?f=4&t=270 and my own testing. I get the expected health restoration amount for all my test cases and all of those in the thread.
I found what looks like a bug in original Daggerfall. The research thread I linked to says the negative endurance modifier is limited to -4, but what really happens is negative modifiers are treated as modifer + 1. So a -1 modifier is the same as a 0 modifier, a -5 modifier is treated like a -4 modifier, etc. I decided to use the correct value since this looks like a bug rather than a design decision.
> Implement stat-based health restoration on rest

- Assets/Scripts/Game/WeaponManager.cs
Simply implements hand-to-hand damage based on what the Daggerfall Chronicles says. I also did some quick testing in original Daggerfall and there was no difference in the number of hand-to-hand hits it took to kill an enemy with an up-to-down hit and a down-to-up hit, so I think all hand-to-hand hits might be the same.
> Implement stat-based player hand-to-hand damage

- Assets/Scripts/Game/WeatherManager.cs
If the field is public, it gets set to 4s for some reason. Nothing in the code directly accessed this so it seems to be something Unity is doing.
> Fix fast weather switching

- Assets/Scripts/DFMeshReplacement.cs
* Avoid assigning filtermode in case of a missing material or texture,
which would cause a NullReferenceException and consequently would break
the entire placement of models in the given area.
* Minor changes to organization of code.
> Mesh and Texture replacement - check integrity of materials

- Assets/Scripts/DFTextureReplacement.cs
- Assets/Scripts/Internal/DaggerfallBillboard.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
I enabled import of custom textures for statics billboards in interiors a few days ago, now this introduce support for animations, too.
The user can import any number of texture to be used as frames, independently from the original number used in Daggerfall, and it is possible to import emission maps, which i see it could be pretty useful for texture artists.
https://i.imgur.com/G5bn52P.png
I haven't enabled import of normal maps instead, because i'm not sure how they could be of any help for sprites. Do you think i should do it?
It's to note that textures are placed on original billboard meshes so they look fine as long as they have the same proportions as originals. Maybe in the future we can provide even more possibility of customization using XML files as you suggested and creating …
> Mesh and Texture replacement - animated billboards

- Assets/Game/Addons/ReflectionsMod/Resources/configInjectionTextures.ini.txt
- Assets/Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs
- Assets/Scripts/API/DFLocation.cs
- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Game/DaggerfallAutomap.cs
- Assets/Scripts/Game/EnablePlayerTorch.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/PlayerAmbientLight.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Utility/ClimateSwaps.cs
This recreates the music playlists of classic Daggerfall, based on what look like playlists in FALL.EXE. In-game testing seems to confirm it.
Also I renamed references to "palace" throughout the code with "castle." In classic Daggerfall, the rulers' structures in Daggerfall, Wayrest and Sentinel are all called "-- Castle" on the automap, while the ones for minor rulers in other places are called "Palace." I think this also is consistent with the text of quests that send you to palaces. The only inconsistency I saw is that the castle music is called "gpalac."
Some things remain to be done. One is that "palaces" are insisting on playing the "castle" music for some reason. I can't figure this out, and I'm asking for your help Interkarma if you know what's going on. It seems to be bypassing …
> Recreate classic Daggerfall's music playlists

- Assets/Scripts/Game/WeatherManager.cs
some recent changes to WeatherManager broke the camera fog (the kind of fog one will always want even on a sunny day).
don't disable RenderSettingsFog! Rendering Fog != Weather Fog
to see the broken fog: uncomment the line that is now commented out (and should finally be removed), go to privateer's hold (outside) on a sunny day with all mods disabled and see that there is no transition from foreground to background - this is wrong
> fixed broken fog

- Assets/Scripts/Game/SongManager.cs
New songs are being chosen when switching between contexts with the same playlist (e.g. going from dungeon exterior at night to wilderness area at night, or weather changing at night). This is not what happens in classic, and this PR prevents it.
I noticed something when testing this. For some reason, the area just outside Privateer's Hold is being classified as "Wilderness" instead of "DungeonExterior." If you walk away from the entrance to the west somewhat, you'll enter a DungeonExterior area, and going farther away will put you in the wider Wilderness area. A couple other dungeons I looked at, including the same class of dungeon as Privateer's Hold, didn't seem to have this problem.
Edit: Accidentally added a heart emoji for my own message, lol. Oh well.
> Don't choose a new song for the same playlist

- Assets/Scripts/Game/DaggerfallExteriorAutomap.cs
exterior automap gameobject is now correctly hidden via SetActive(false) function and shown via SetActive(true) function when going indoors resp. outdoors
this will fix a bug which can be seen in youtube video (https://www.youtube.com/watch?v=ANNVZfJqk48) minutes:seconds 14:52
> exterior automap gameobject is now correctly hidden when inside

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
What this PR does:
1. Available gold is displayed when fast traveling, and is removed after travel. If the player doesn't have enough, the "You do not have enough gold." popup shows.
2. Tried to recreate the cost calculations of classic Daggerfall. It should be basically correct. The calculations for the amount of time are producing different results from classic, though, so the resulting costs are also different. For one thing, inland lakes or relatively short trips across bays don't cause ship travel while they do in classic Daggerfall. I looked and no "ocean" terrains were being processed in this case.
3. Implemented healing for cautious travel.
4. Set the modifier for ship travel based on some limited testing in classic Daggerfall.
5. Changed the "Do you wish to travel to" popup to …
> Implement travel costs

- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/RDBLayout.cs
Enemies with a set gender, like in the castles, will be set according to it.
Also fixes the issue that `DFRandom.random_range` in `DaggerfallMobileUnit.cs` was always choosing 0 because it is exclusive of the maximum, so enemies with unspecified gender were always being male.
> Read gender of human enemies and allow unspecified to be female

- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Right now model import and texture import are completely separated,
which means that if a user install some replacement for vanilla textures
these are applied only on vanilla models, and not on custom models which
use these same textures.  This commit bring some modularity as the
'textures' folder on disk available to players is now used for a global
injection, so custom and vanilla assets should blend nice together no
matter which custom textures are used. This should be especially useful
for the most vanilla-friendly models. It can also be used to import
optional bump maps where the original materials doesn't have them.
> Mesh and Texture replacement - texture consistency between models

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/RMBLayout.cs
* More on AssetBundle import
* It's now possible to import models from more AssetBundles.  It's a
simple method for now which uses a little assetbundle for each model
(ID.model or Archive_Texture.flat for billboards), so it shouldn't
impact loading times too much.
* Textures, Models and Flats folders are now in StreamingAssetPath
* Moved option in main menu with the other settings
> Mesh and Texture replacement - More on assetbundle

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
Keyboard keys can now be changed and saved through the classic interface. Mouse, joystick, and set default button not implemented yet. Currently there is nothing preventing the player from setting duplicate keybinds, but the old keybind is removed and only the new keybind is applied. 
If the game is closed with an invalid key configuration (duplicate or empty keybind), the controls will reset to default when the game is restarted. Valid configurations are saved between restarts.
> Change and save controls through classic interface

- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Internal/DaggerfallSongPlayer.cs
Fixes the problem of songs not repeating, mentioned here
http://forums.dfworkshop.net/viewtopic.php?f=24&t=423. I don't know anything about the crash mentioned there.
I don't know the whole path of execution, but when songs were stopping, it looks like PlayCurrentSong() was called from Update() in SongManager, then PlayCurrentSong() was returning immediately because the `songPlayer.Song == currentSong` condition was true, even though the song had stopped playing. I added a check for `songPlayer.IsPlaying,` and this fixed the problem.
Adding this check caused a stutter in the music when loading a new context, though. Apparently IsPlaying wasn't being updated quickly enough, so `(songPlayer.Song == currentSong && songPlayer.IsPlaying)` would evaluate to false and the song would restart …
> Fix songs not repeating

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/FacePicker.cs
- Assets/Scripts/Game/UserInterface/HUDCompass.cs
- Assets/Scripts/Game/UserInterface/HUDCrosshair.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs.meta
Allow higher resolution textures for certain UI elements, using xml files to get rect size. This also means that user can customize these values, for example to change the size of the compass on screen.
> Mesh and Texture replacement - Import rect sizes from xml files

- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLocation.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/RDBLayout.cs
- Assets/Scripts/Utility/RMBLayout.cs
* Minor changes for exteriors billboards.
* Minor changes in RDB and code organization
* Models that replace billboards have a random rotation. This should be particularly useful for trees, as they look more natural and not all facing the same direction. I used a value from Position as seed so the rotation is always the same.
> Mesh and Texture replacement - More changes

- Assets/Scripts/API/Save/SpellRecord.cs
- Assets/Scripts/Utility/DaggerfallSpellReader.cs
- Assets/Scripts/Utility/DaggerfallSpellReader.cs.meta
DaggerfallSpellReader -  can parse a SPELLS.STD file or spell records from SAVETREE.DAT
Spellrecord - Added SpellRecordData & EffectRecordData for storing raw spell data, and ReadNativeSpellData() which uses DaggerfallSpellReader.ReadSpellData()
> Changes to SpellRecord & Added DaggerfallSpellReader

- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
interior automap (DaggerfallAutomapWindow.cs) - slice level can now be adjusted with middle mouse button:
hold down middle mouse button over main panel and move up/down to adjust the slice level
BaseScreenComponent.cs:
support for middle mouse button added, right mouse double-click added
> automap - slice level can now be adjusted with middle mouse button

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
default automap render mode (automap opened for new location) is now dependent on if player is inside building or dungeon/palace:
building: cutout
dungeon/palace: transparent
this is done because: in buildings higher level floors easily distract when viewing the interior map, in dungeons people that don't know all the functions of the map often think the map is bugged when they don't see geometry above the slice level (I watched several youtube videos with confused people)
double click on left mouse button now switches between beacons
double click on right mouse button now resets view
double click on middle mouse button now switches rendering modes
> automap - default rendermode dep. on building/dungeon,double-click left/right/middle

- Assets/Scripts/API/DFRegion.cs
- Assets/Scripts/Editor/AtlasEditorWindow.cs
- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Categorizes covens as dungeons on the travel map, like Daggerfall classic. Also plays "Dungeon Exterior" music for covens and poor homes like Daggerfall classic.
> Changes for covens and poor homes

- Assets/Scripts/SoundClips.cs
- Assets/Scripts/Utility/EnemyBasics.cs
The gargoyle's attack sound was noted as missing, but actually it was being assigned to the orc shaman. For some reason, even though Daggerfall Jukebox will extract three sounds for the orc shaman, with the attack sound being identical to that of a regular orc (the files are identical), this index seems to be skipped over in Daggerfall Unity. I reassigned the orc shaman to use the regular orc's attack sound.
> Fix gargoyle sounds

- Assets/Scripts/Game/PlayerEnterExit.cs
Daggerfall Unity used the castle music and lighting in Orsinium, until you got out of the first block and into the dungeon area. In classic, it has dungeon music and lighting throughout.
> Make Orsinium have dungeon music and lighting throughout

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
With this PR the player will always arrive during daylight hours when using cautious travel, like Daggerfall classic.
From testing Daggerfall classic, I found that if the player's arrival would be between 6 p.m. and 6:10 a.m. it will be advanced to 6:10 a.m. This does the same for Daggerfall Unity.
> Make cautious traveling arrive during daylight

- Assets/Scripts/Game/UserInterface/Panel.cs
As mentioned in https://github.com/Interkarma/daggerfall-unity/pull/288, an error appears in the console when turning pages in books.
I borrowed a solution for the same error from here:
http://answers.unity3d.com/questions/290595/enumeration-operation-may-not-execute-problem-with.html
The error is gone, and I can't see any difference in behavior when turning pages or opening and closing the various panels.
> Fix enumerator error

- Assets/Scripts/Game/PlayerDeath.cs
Another tiny PR. I know you could easily add this yourself, so if you don't want these kinds of tiny PRs, just say so.
This adds the player death yell, which I'm sure is all too familiar to people who've played the original Daggerfall. :)
Classic Daggerfall uses this same voice for both male and female player characters. As you know there are various unused male and female pain sounds in the game. Maybe the player could be offered a choice of voice, and/or they could be used for human enemies. For now, anyway, this is just the Classic Daggerfall voice.
> Add player death sound

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/WeaponManager.cs
Here are some changes to make the combat feel a little more like Daggerfall classic.
Daggerfall Unity's swing sound played at the start of an attack, played whether an enemy was hit or not, and the hit didn't register until after the animation finished.
In classic the swing seems to play at just about the frame after the middle frame. It plays if the player misses or the player hits a door, but not if they hit an enemy. The hit registers at about this same time.
This PR tries to make the above behavior like classic.
> Adjust attack-related timings to resemble classic

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Utility/TextProvider.cs
Shows the hand to hand damage in the character sheet, like classic Daggerfall.
In classic, this text is colored a light blue. I don't know off the top of my head if there are any other places with other-colored text like this, but if I'm not mistaken at the moment Daggerfall Unity only supports one color of text per text label/message box.  I want to change just the color of this one token, but the only way I thought of was to add a color property to `TextFile.Token,` and I thought you might not want that, so for now the text is the default color.
> Show hand-to-hand damage in character sheet

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Based on discussion in https://github.com/Interkarma/daggerfall-unity/pull/289, this is how I understand you would like to declare the text ID variables. This gets rid of the classic text ID regions and puts the variables in method scope, since none are used in more than one place.
Very minor point: Do you prefer "ID" or "Id" in the variable names? I assume "Id" since that's what had been used before in the armor, weapon and misc item variables, so that's what I used for this PR.
> Move text ID variables to method scope

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/SoundClips.cs
Sets the same ambient dungeon effects as classic, which are all next to each other in the list of sounds.
Alternate ambient sounds might be fun, too, but I figure we want to at least have the same ones as classic ready for use.
> Set same ambient dungeon effects as classic

- Assets/Scripts/SoundClips.cs
This identifies more sound clips. The main thing is pain sounds based on race and gender. These are unused in classic Daggerfall but I'm almost sure that's what they were for, since their sound ID and the way they sound matches with the order of the races.
> Identify more sound clips

- Assets/Scripts/Utility/EnemyBasics.cs
I can see why it was set without, but the gargoyle should have a blood splash like in classic, because it has blood in its corpse texture.
> Set gargoyle to have blood splash

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
Track fatigue internally at 64 times the value shown in the character sheet, the same as classic does. This will allow for implementing loss of fatigue values in the same way.
> Track fatigue at 64 times character sheet value

- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
Loot containers use custom textures when loaded from a save.
> TextureReplacement: Loot containers serialization

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/WeaponManager.cs
Adds fatigue loss for jumping and attacking, as well as per minute of game time based on whether the player is running or not. The values are from the Daggerfall Chronicles and I confirmed by testing in classic.
> Add fatigue loss for some actions

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
The problem with the resting function was with the endurance modifier. If you had a negative endurance modifier you could regain no health or even lose health. In classic you regain a minimum of 1 no matter how low your endurance modifier is, and this PR makes DF Unity the same.
> Fix rest health rate calculation

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
A while ago i reported that the songplayer value in tdbg always shows that no song is playing.
This is caused by having more than one songplayer in scene, as two of them are detected but the correct one seems to be always the second. 
I don't know if this information can be trusted, so i have implemented a foreach to to seek wich one is playing.
On an unrelated note, i noticed that you started updating the copyright date, do you wish contributors to do the same when they submit a PR?
> Fix issue with more than one songplayer in scene and tdbg command

- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/PlayerMotor.cs
I should have checked that IsJumping is false again before resetting the bool to check for decreasing fatigue and tallying skill uses. When a jump ends, Update() in DaggerfallEntityBehaviour.cs would run a few times in the interval between when IsGrounded is set to true and IsJumping is set to false, so fatigue and skill tallying were happening multiple times per jump.
Also I renamed the variable isJumping to jumping, to match with other booleans in there like sliding and falling, and only set it to false when needed.
> Fix fatigue loss and skill tallying for jumping

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
This implements the game behavior when the player runs out of fatigue. There are two cases, depending on whether there are enemies nearby:
Enemies nearby: "you are easy prey for monsters" message, and player dies
No enemies nearby: "you awaken one hour later" message, and player is forced to rest for one hour
I redid the CanPlayerRest() function into a AreEnemiesNearby() function, because I needed this functionality separated out from the rest function.
There are a few issues that could be ironed out.
1. When the player dies with the "you are easy prey for monsters" message, he can still move the view and move slightly, unlike when you die from damage. I don't know why.
2. The player death sound plays while "you are easy prey for monsters" message is up.
3.  If you lose your last fatigue …
> Implement zero-fatigue behavior

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Implements the formulas from classic for recovering fatigue and spell points. This was easy because they are both just += (max points / 8). Also tallies the medical skill. This is all confirmed from testing in classic.
A pedantic point but I don't think the term "magicka" is used in Daggerfall, just "spell points," so that's what I used. If you want to refer to it as magicka I can change it.
> Implement remaining formulas for resting

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
- Assets/Scripts/Utility/RDBLayout.cs
Here's an implementation of lockpicking.
I've found what I think is the formula for lockpicking interior doors in FALL.EXE. It involves randomness so it's hard to test in-game. It seems like I have higher success in the original game but that might have just been luck.
I also made an educated guess that the lock value of doors should be divided by 8 compared to what it is in DF Unity. DF Unity was marking a lock of 160 or more as magically locked, while original Daggerfall shows the magically-locked message for a value of 20 or more. Dividing the DF Unity lock values by 8 produces what seems like correct values for the locked doors in the Castle Daggerfall throne room.
The basic lockpicking behavior also replicates this behavior from the original game:
1. If you click on a locked door …
> Implement lockpicking

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
Implements lockpicking messages. I noted what seems to be an oversight in classic: the lockpicking difficulty messages in classic are always for the harder of two lockpicking formulas. That harder formula is used (I think) on exterior doors that lead into interiors, while an easier one is used for lockpicking the animating doors in interiors. I don't know whether the oversight is that the difficulty messages only account for one of the formulas, or if its that there are two different formulas.
I have hooked up the text to use the interior door formula (since DF Unity right now only has locked doors in interiors), so you will get accurate messages instead of the ones you will get in classic.
BTW, to be like classic, the text should be in the middle of the screen, the same spot currently …
> Implement lockpicking difficulty messages

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Editor/SaveExplorerWindow.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Through a combination of testing with the save editor DagHex and confirming in-game, new values have been identified in classic saves. Current health, spell points and fatigue are imported as they are into DF Unity, as are skill use counts.
The player's reputation with commoners, nobility, scholars, merchants and underworld is based on the message you get about your reputation being higher or lower during character creation. DagHex has nobility and merchants switched compared to this, and DaggeD, another save editor, has the reputations in the opposite order of how they're shown in-game. I'm going with the in-game display as most reliable until it can be confirmed somehow.
> Identify and import more data from classic saves

- Assets/Scripts/Game/Entities/DaggerfallSkills.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements skill raising. From testing classic, I think the only factors that affect how many skill uses are needed to raise a skill are the skill value (it's percentage) and the player's level. Different skills have different modifiers to how many uses they need. Running has such a high one because it is tallied very quickly while moving.
> Implement skill raising

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
Exception will occur in master when resting with a new character when TallySkill tries to access the uninitialized SkillUses array.
> Fix for uninitialized skillUses with new character

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
In an earlier PR I fixed null reference to skillUses[] on a new character, but it also happens with Unity saves that were saved before the additional data. This PR initializes the array in that case. It also sets EstimateStartingLevelUpSkillSum() to only be called if the skillsum is 0 because nothing was in the save file.
I guess stuff will continue to be added to the save file, so is this the way to handle missing data? Maybe defaults should be set first and things only assigned from the loaded file if they are non-null/non-0.
> Fix for null reference on Unity saves

- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/DaggerfallSkills.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Stat raising calculations should now be correct with this PR. This works for all the test cases I've used.
In a werewolf save I'm using (downloaded from the Internet), it looks like the skills raised by being a werewolf also have their advancement modifier halved, so they rise more easily. The character in the save is in human form but gets this benefit it seems. There may be something similar with vampires. This will need some more testing but I'm not going to bother with it for now.
> Correct stat raising calculations

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs
- Assets/Scripts/Internal/DaggerfallAction.cs
This is sort of a patched-on-top fix for overlapping text when you click on the banner/statue at Shedungent. This problem has been around since one of the changes I made some time ago to text formatting.
What classic seems to actually do is add these input text prompts to the same "popup text" lines used for things like "-- just died."
> Fix input text overlapping

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
This imports the pitch and yaw values from classic saves, resolving http://forums.dfworkshop.net/viewtopic.php?f=24&t=424&sid=3e361409f513f292e15381a7752cc11f.
After the pitch and yaw data is what seems to be a copy of the player position data found in the header. It is this position data, and not the player position data in the header, that determines where the player is when a save is loaded in classic. There is additional data after that, but I don't know what it is.
> Import player orientation from classic saves

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
Tested and confirmed working in a build using latest master, both from a DF Unity new game and from an imported classic save.
> Fix spinner missing on level-up screen in builds

- Assets/Scripts/Game/DaggerfallUI.cs
Currently in DF Unity if you push the rest key while in the air you get the "There are enemies nearby." message. With this PR instead nothing happens, the same as classic.
> Do nothing if rest key is pushed while in air

- Assets/Scripts/Game/Questing/Foe.cs
I saw the comment about foe spawn limits and decided to test it. I found no limit to the number of spawns classic can do of the same foe at a time.
I know for 100% sure it can spawn 20 at a time, as I was able to count them. I then raised it to 50, and what looked like 50 (I didn't actually count this time) spawned. An additional 50 (or what looked like 50) of another enemy spawned at the same time. If there is any limit it is very high.
> Raise foe max spawn limit

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
Fixed a few problems with the rapid healing formula.
1. I accidentally set rapid healing in darkness so it worked in light.
2. Interiors should be considered a dark environment.
> Fix rapid healing formula

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/SaveTreeBaseRecord.cs
- Assets/Scripts/API/Save/SaveTreeHeader.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
I identified quite a lot more data from classic saves with the help of Donald Tipton's save-viewing program chunktcl. I also found on my own that pitch and yaw seem to be default properties of all records.
The player's location is now gotten from the type 0x04 record, which I named "CharacterPositionRecord." I renamed the old CharacterPositionRecord to  HeaderCharacterPositionRecord.
Some of the record root data already being read into SaveTreeBaseRecord was reading data from the wrong location, but they should be reading from the correct spots now.
One thing that I think would now be possible is to recreate nearby monsters from save games, since I found the monster record and it includes their position. They have their name at the beginning of their data, so we could use that to …
> Identify more data from classic saves

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
The same issue of an hour passing for a 0-hour rest or loiter also applied for doing an "until fully healed" rest when at full health. No time should pass in that case.
> Don't pass time for full rest if at full health

- Assets/Scripts/API/Save/SaveVars.cs
Currently in master, if you load a classic save that has both the invulnerability cheat and the cheat to reveal all map locations active, godmode will not be activated.
Also includes code for reading the cheat to reveal all map locations. This is commented out for now until DF Unity supports hidden map locations, to avoid the unused variable warning.
> Correctly read cheat variable for godmode

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
addresses a bug reported by user "electrorobobody" on forums - the bug prevented one to find locations with their names being a substring of a different location, e.g. in province Daggerfall "Kingsly Manor" could not be found via search because there exists a "Buckingsly Manor" that was returned instead
> bug fix for travel map find (location name occlusion issue)

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/SaveTreeHeader.cs
- Assets/Scripts/Editor/SaveExplorerWindow.cs
Identified data in the classic save tree header and modified the SaveExplorer a little to match.
To keep compatibility with the current loading behavior, which uses the byte at 18 as the record length of SaveTreeLocationDetail, I reset the stream here for that class, but that byte is actually the current environment of the player.
> Identify classic save tree header data

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
For level up, I was just adding the Career.HitPointsPerLevelOrMonsterLevel. Actually it is a random number between this value and half of it, plus the endurance modifier.
> Fix hit point calculations

- Assets/Scripts/Game/Items/ItemEnums.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
The group that was marked Error is furniture, according to the save game editor Daghex, which seems to be accurate about these sorts of things.
> Add enums for furniture items

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Here are some fixes to damage values from the player's weapon hits.
It turns out there were a number of inaccurate things in the information Daggerfall gives about damage values, which were throwing me off until I figured them out. One is that the diagonal slash down to the right is actually a weaker attack than the horizontal attacks. The other diagonal attack is stronger, and the manual groups them together as both being stronger.
Another was that the strength damage modifier is different from what classic shows in the character sheet. It's actually (STR - 50) / 5, roughly twice the value that classic shows, in either negative or positive direction.
And then another was that the damage display for weapons with material modifiers (those other than steel and silver) is also incorrect! The …
> Fix damage values

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Editor/DaggerfallCareerViewerWindow.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Utility/EnemyBasics.cs
This adds the stats for monsters' level, armor value and multiple attacks. I need to look into the attacks a little more but I think a monster with multiple damage values gets multiple damage rolls each time they attack. I think that Daggerfall actually supports (or at least there is room in the character/monster record) for up to 5 attacks, but no monsters have more than 3. I also fixed the health calculation for enemy classes.
> Add more enemy stats and fix health calculation

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/WeaponManager.cs
These are hit and miss calculations for the player. It's reverse-engineered from the executable so I think it's correct. There's no easy way to test it since it uses probabilities, but the results seem to match classic well.
> Implement hit/miss calculations for player

- Assets/Scripts/API/VidFile.cs
- Assets/Scripts/Game/UserInterface/DaggerfallVideo.cs
This prevents a stream of errors in case someone didn't set up their daggerfall directory properly and is missing video files.
If the vidFile is unable to Load endOfFileReached is set to true so the video player just skips it and won't stay on a black screen forever.
> Minor fail-safe to video loading / playing

- Assets/Scripts/DaggerfallUnity.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
There were a couple of stragglers that used the old style of FindObjectOfType. These were not trying to get an interface for example so the non generic version wasn't required.
Did a similar search for GetComponent but those were all generic.
> Replaced any remaining non generic FindObjectOfType calls with generic version

- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Prefabs/Player/PlayerStandalone.prefab
- Assets/Scripts/Game/PlayerMotor.cs
As the PlayerMotor uses FixedUpdate to calculate movement; the camera can feel choppy if your FPS is over 50. Increasing the fixed time step much higher will result in a lot of physics calls that affect FPS in general so that's not a good option. 
This adds the option to smooth out a transform child of PlayerMotor. This child will smoothly lag behind the motor so there is no perceivable stutter. It detects if the player has teleported when the distance travelled is larger than the velocity of motor allows, including a fairly large margin. When teleported the smoothing is reset so you don't see the camera lerping through the entire scene.
A few notes; smoothing reset also happens when the player switches to or from crouching. Currently this change is a hard jump anyway so I don't think …
> Smoothed out camera

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyDeath.cs
- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Added player armor to the hit calculations, and miss sounds and collapse sound on death for enemies.
I wanted to add sounds for when enemies hit the player (two types, when the attack is done without a weapon and with), but I wasn't sure how that should be handled as far as what audio source to use.
> Add player armor calculations and enemy combat sounds

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Enemy classes might as well use the GameManager.Instance.PlayerXXX variables instead of grabbing the player themselves on Start.
- EnemySenses's DirectionToPlayer was not normalized.
- Moved hasEncounteredPlayer handling outside of CanHearPlayer and CanSeePlayer functions.
> Minor changes to Enemy classes.

- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Sorry for the long delay :P
Add a trigger to imported gameobjects for NPCs. Flats with an action are already given a trigger on [AddAction()](https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Utility/RDBLayout.cs#L853) so custom flats should be already covered for that.
> Action component for flat->3d object /2

- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Directly and only resets the armor values to their starting value of 100 when loading DF Unity saves, since the previous attempt of calling PlayerEntity.reset() also reset faction data, which wasn't wanted.
Another approach would be to save the armor values in DF Unity saves, and then we could just copy without worrying about resetting the values or calculating the armor values when loading a game. Loading from classic saves is already working this way, since classic saves have the armor values in them.
> Initialize player armor values to 100 when loading

- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
This also solves the issue where an empty prefab is used as parent.
> MeshReplacement: Set filtermode to materials in children

- Assets/Scripts/Game/DaggerfallExteriorAutomap.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
when exterior automap is opened player position is now always in focus
exterior automap gameobject is now always deactivated correctly when a savegame is loaded with pc in an interior location (this would have resulted in a phantom player marker somewhere on the interior automap)
> bugfixes for exterior automap

- Assets/Scripts/Game/UserInterface/FacePicker.cs
When clicking the next face button, the last possible face for each race/gender is skipped due to an off-by-one error. This should fix it.
> Bugfix: face picker skipped a face

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
I found out a little more how lockpicking works in classic.
It turns out that when the player fails to pick a lock (not counting magic locks), the door stores the player's lockpicking skill, and subsequent attempts fail if the player's lockpicking skill matches that value. I thought you couldn't try again at all if you failed once (unless you left and re-entered the area), but you can try again if your lockpicking skill rises.
> Change lockpicking to be closer to classic

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/SaveTreeBaseRecord.cs
- Assets/Scripts/Editor/SaveExplorerWindow.cs
Details:
1) Corrected some magic effect enums (just comments in the CharacterRecord right now)
2) Verified UnknownTownLink records are doors
3) Identified Creature2 as record for dead mobiles
4) Renamed some fields and records to match what the Fixsave utility calls them. Fixsave seems to call recordID "mapID" or "map identifier" but I didn't change to that because at the moment recordID seems like a better name to me. Also it calls "container" an "item holder" but I didn't change to that because container was already being referenced and had a file named after it.
5) A little bit of other renaming of as-yet unused records to try to make the descriptions more accurate.
> Identify more classic save data

- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/VideoReplacement.cs
Prevents issue with Mod.LoadAllAssetsFromBundleAsync(true)
> MeshReplacement: do not seek into unloaded assetbundles

- Assets/Scripts/Game/Items/LootTables.cs
This makes loot generation chance closer to classic.
I had noticed that in DF Unity tons of loot would be found by higher level characters. DF Unity multiplies the chance of finding all item types by the player's level, but classic only does this for the first four categories of items (ingredients). Everything else is just the chance seen in the loot matrices regardless of player level.
Also, classic's compare is (random value from 0 to 99) <= chance, so even a 0% chance category can create an item. This also means the values in the matrices are effectively 1 higher. My guess is that this is probably unintended, so I didn't recreate it.
> Make loot generation chance closer to classic

- Assets/Scripts/Game/Items/LootTables.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Matches monster loot lists to classic. Also a few minor cleanups to the enemyBasics.cs file.
Looks like Bethesda probably decided to cut back on magic item spawns in between the time of the data Chronicles uses and the game's release. Similar to how they disabled magic item repair.
This PR doesn't touch loot from enemy classes.
> Match monster loot lists to classic

- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
Fixes long text messages going off screen, which could happen with many of the pickpocketing messages where you find nothing useful.
It doesn't intelligently wrap by word, but by letter, but Daggerfall is the same way and it doesn't really bother me.
> Wrap long text messages over multiple lines

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyDeath.cs
- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/LootTables.cs
- Assets/Scripts/Utility/EnemyBasics.cs
This PR implements enemy equipment. Enemy classes and some monsters receive it, and the equipment can be found on their bodies when they die. Enemies with weapons use it for their attack damage now. I haven't yet implemented the effect of the armor on enemies' armor values. Also, right now the materials are using the random material methods in ItemBuilder, but I haven't looked into how classic chooses material.
Also, enemy classes now use the same loot table keys as classic. Their equipped items are added on top of this.
> Implement enemy equipment

- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Internal/DaggerfallAction.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
This partially implements Action 99, which displays text at the top of the screen when clicking on some doors in info mode. Cases I know of that exist:
1) Doors in Castle Daggerfall off of throne room.
2) Doors in Castle Wayrest off of entrance area and in basement area before dungeon.
3) Doors in back of Orsinium throne room.
There's a few other texts in the used area of TEXT.RSC that might be unused or there might be a few other doors somewhere with this action.
There's an issue with this that I wanted your help with Interkarma. This action displays text at the top of the screen, but the text used is multi-line text. Is there currently a way to display this? Right now the text just runs off the screen.
This action can also cause castle guards to go hostile but this isn't implemented …
> Add DoorText action

- Assets/Scripts/Game/Questing/Actions/RevealLocation.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Internal/PlayerGPS.cs
Hi Interkarma!
I added static function checkIfLocationTypeAlwaysKnown to PlayerGPS - reason is because I added a check to location discovery function DiscoverCurrentLocation which checks if the location type is one of those that should always be known to the player like town, village, temple, common graveyard - I did add the check so that discovery dictionary (and savegame data) remains as small as possible - imagine a player that travels a lot will have lots of locations in there that could be saved
BUT: if you don't like it JUST remove the check (line 604, 605) - then the function checkIfLocationTypeAlwaysKnown could be moved over to DaggerfallTravelMapWindow.cs...
added 2 console commands (in DaggerfallTravelMapWindow.cs): map_reveallocations and map_hidelocations (it is only a …
> travelmap location discovery implemented

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
Currently in master, DF Unity is far more generous giving out weapons and armors of high materials than classic is. This PR replicates what I've found of the armor generation function in classic.
It uses random numbers so it's hard to say for sure, but it seems like classic is a little more generous with materials than the results from this PR. I don't think I'm missing anything from the generation function, so maybe it's a difference in the random number generators of classic and Unity, or maybe there's another factor somewhere that affects material generation.
Also, this PR sets weight, gold value, condition and enchantment points by material type. Variants aren't set yet and are always variant 0. as they are in master.
> Flesh out armor and weapon generation closer to classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Internal/PlayerGPS.cs
added console command map_reveallocation [regionName] [locationName]
reverted behavior: forgotten graveyards are not known automatically (more investigations are needed of classic daggerfall behavior with graveyard - seems like common graveyards are always known, some forgotten graveyards are always known and some forgotten are not...)
> improvements to discovery implementation of travelmap

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/PlayerMotor.cs
This PR approximates classic player movement speeds.
First I recorded the length of time it took to walk the same distance with the same speed stat in classic and Unity. Comparing the movement values used in FALL.EXE for to those of DF Unity I found the ratio was about 39.5 to 1, meaning a speed value of 39.5 in classic is about the same as a speed value of 1 in DF Unity. This is probably slightly off. For one thing movement is classic seems to be instant stop-and-go but there is acceleration and deceleration in DF Unity.
The walk, crouch and run formulas are matched to classic. The run formula is also in DF Chronicles and matched what I saw in the assembly code.
One little thing I found: the "maxSpeed" value in z.cfg can be used to modify walk speed in Daggerfall version 1.0 but as of …
> Approximate classic player movement speeds

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements:
- All buildings except houses should have the same hours for the doors being locked/unlocked. You can get a message for stores' opening and closing hours by clicking info mode, as in classic.
- Houses 1 through 4 are open during the day and closed at night, and you get a greeting when you enter, like in classic.
To be done:
- There's something more to how the houses' open hours are calculated, but I haven't figured it out yet.
- Since exterior doors don't have lock values and can't be picked or bashed yet, you can get in through any exterior door right now by clicking in steal mode.
> Implement building opened/closed hours

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Utility/BuildingNames.cs
Does these changes:
1. Houses on sale now identified as "House for sale" when clicked in info mode, and on automap
2. Clicking on buildings only discovers them (unless door is clicked) and shows shop times if in info mode
3. Buildings are discovered when their doors are clicked, in any mode
This all matches classic behavior as far as I can tell.
> Make building discovery closer to classic

- Assets/Scripts/Internal/DaggerfallLoot.cs
Classic has these in a byte array in FALL.exe and uses them for loot piles in dungeons or when the player drops loot.
> Match possible treasure pile sprites to classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
this is done via coroutines
had to implement it with a helper class that inherits from MonoBehaviour so that coroutines could be used (since DaggerfallTravelPopUp class is not inheriting from MonoBehaviour)
this works reasonable well
unfortunately there are these limitations:
- location loading and countdown cannot be done in parallel - since unity does not allow different threads with calls to unity api functions (this would be needed since the gui needs to be updated and location loading also calls unity api funcions like gameobject creation etc., current approach with coroutines does  no concurrent processing
- countdown is done before actual fast travel actions right now
- since coroutines are involved now: camera updates happen now that did not before (I guess in between coroutines …
> travel time countdown implemented for worldmap

- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/TextureReader.cs
I removed a method used before my recent changes. I noticed it was also called for terrain but a more specific method exists for the purpose, so i swapped them. I took the occasion to add a few error messages for the log.
Nystul may want to review this PR but these should be pretty minor changes; all features, including normal map import, are preserved.
> TextureReplacement: minor optimization and logs for terrain

- Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleUI.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/TransportManager.cs
- Capsule height and camera height now set correctly. Height when riding is now 2.6m and camera is always set at 9cm below the top of the capsule. (execpt for when crouching cos that is strange and I didn't want to mess with it)
- Speed is calculated using the base units from DF provided by Allofich (thanks!) and affected by speed skill level. (moved numbers into constants)
- Sounds and animations stop when game is paused.
> Fix issues with horse riding

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
This hopefully helps lay the groundwork for info popups on items. This doesn't parse anything, it just assigns the correct popup, or in the case of potions, inserts a TODO with information for implementing it later.
> Assign correct info popup window based on item

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyDeath.cs
- Assets/Scripts/Game/FPSWeapon.cs
Adds hit sounds when enemy hits player based on their weapon, or lack of, and also plays an appropriate miss sound if the player isn't in range of their attack.
> Add sounds when enemy hits player or swing misses

- Assets/Scripts/Game/PlayerMotor.cs
Thanks for pointing out why the y axis capsule center needs repositioning.
Also realised I had re-allowed crouching at some point. Horses cant crouch right?
> Fix horse casule height and prevent horse crouching

- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
Enabled ship option of transport menu.
Teleports to ship at 2,2
Stores player boarding position for transport back.
Saves and loads boarding position.
Handles terrain sampler changes on stored position.
Would like to do other ships but no idea where they are in gameworld, so they can wait.
> Transport menu - ship basics

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemEnums.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Weapons and armor take damage now.
For now at least, I've copied classic behavior of only damaging non-magical weapons and armor when a damage-causing hit is made with a weapon. I know Morrowind has the same thing where creature hits don't damage armor, so this may have been a conscious decision.
I found what seems to be an oversight in classic, in that there is no code for damaging shields, only the weapons and the armor on the body part that gets hit, so I introduced an attempt at adding shield damage in. Going on the assumption that an attacked target first tries to avoid an attack completely with agility, luck, etc. and then uses their shield and then any armor equipped under the shield, I put in a "what if" calculation that looks at whether the attack gets avoided at the shield …
> Implement weapons and armor taking damage

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Monster speed is the same formula as the player has when walking.
Also bumped up monster attack animation to be closer to classic. The speed of the swing in classic is not dependent on the monster's speed, and I think it may vary depending on the speed of the computer (or the "cycles" in DosBox), but I put it at what seems to me like a reasonable value that doesn't look overly fast.
I was also looking at adjusting the point in the animation swing where damage is applied. Interestingly, it seems like it varies by enemy in classic. Also I noticed, for example, that the imp plays its attack animation forward and then backward in classic. I don't know where this information is stored, though.
> Adjust monster speeds

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterface/UserInterfaceManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
- Added identified state to items. (first use of flags)
- Most item names now match classic, including unidentified magic items.
- Artifacts not currently identified by item system but names will be correct once that has been done.
- Tooltips also now match item titles on popups.
- Book title & author now shown on popups.
- DaggerfallMessageBox can now have a next message box added which will be displayed when user clicks. The last message box will close all of them. As far as I know Daggerfall only ever uses 2, but I wrote it so you can nest to any level. (of course) Actually found a couple of the artifacts do use 3! (skele key & mask)
- Add second info popup for health status.
- Implement magic item powers popup using multiline macros. Just displays "Power number N" for each power for …
> Multi popups and item name fixes

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
This just passes down the wrapText parameter from where pickpocketing happens. It ends up passing a bool through a bunch of functions, which might not be to your liking. Feel free to reject this if you have something better in mind.
I removed maxWidth as a parameter for now, since it's not currently used.
> Pass down wrapText parameter

- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Identifies several values in savevars, and uses the mod to avoiding hits that can be set during character generation in the combat formula.
I also identified the other mods that can be set during character generation (you get one of these as the result of the "You have the most trouble ___." question.) The only one I haven't found yet is the reaction modifier, which I think affects how much NPCs like you. The modifiers I found were all next to each other but the reaction one didn't show up.
> Identify more save vars, use avoidHit mod

- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
Imports 3d models for treasures and lootable corpses. 
I don't think this is the best way to deal with the fact that the treasure prefab is loaded from resources, but if I replace the entire gameobject (and add lootable script and sphere collider) i have troubles preserving serialization. I'm open for suggestions.
> MeshReplacement: Treasures

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Changes:
1) Implements "You are too far away..." message, shown when player tries to activate various objects out of range.
2) Implements "You see a/an %s." when you click on an enemyMobile in info mode.
3) Activation ranges match classic. Buildings and enemy mobiles can be identified from far away like in classic.
4) Fixed being able to activate things through walls (ex. pickpocketing guards in Daggerfall castle through the wall)
To do this, I upped the raycast length when activating things to a long one. There was a problem with this though: I was able to click on things behind walls. There was a comment that RayCastAll was being used because when things block the raycast, it feels unresponsive to the player, but changing to RayCast fixed my problem and also fixed being able to activate …
> Updates to activating objects

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
Does as title says.
I think that classic still has a monster's stats within a corpse, so I did it the same way (adding an EnemyEntity field to the loot container) instead of just adding a name string and isEnemyClass bool.
Corpses EnemyEntity field isn't saved in DF Unity saves yet, so clicking on them after loading a DF Unity won't show anything.
> Implement clicking in info mode on dead mobiles.

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/WeaponManager.cs
This starts the thieves guild and dark brotherhood quests in the same manner as classic. The necessary data is also imported from classic saves.
Problems:
- I don't know Unity and its "components" and stuff very well and couldn't figure out how to make a blood splash appear when a citizen is killed. Copying the approach used in the file for hitting an enemyMobile didn't work. I guess that mobileNPCs need to have "EnemyBlood" assigned to them somehow.
- The population manager may need to be told when a mobileNPC is killed. I don't know much about it and haven't touched it.
- The thieves guild quest and dark brotherhood quest might not necessarily work. Are we only activating quests that are curated? Should these be commented out from starting for now?
- Variables aren't saved in Unity …
> Implement starting crime guild quests

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
Identifies and imports the biography reaction mod, serializes new player entity data (minMetalToHit, biography mods, thieves guild and dark brotherhood) and disables starting dark brotherhood and thieves guild quests or tallying their requirements.
The only piece of data I didn't serialize was that for the enemy entity in corpses. I gave it a quick go, just saving and loading the EnemyEntity in SerializableLootContainer, but not all the data was being saved, as it would just show "You see a dead ." after killing an enemy, saving, loading the save and clicking the corpse again. Interkarma, do you know what needs to be done there?
> Reaction mod, serialize data, disable crime quests

- Assets/Scripts/Internal/DaggerfallActionDoor.cs
Hazelnut noticed that looking at a lockpick with a 95% chance of success caused an out of bounds exception on  the array of descriptions. This fixes it.
I think this is pretty much of an edge case because you have to be very good at lockpicking and facing a level 1 lock (weakest possible), and classic doesn't handle this situation right. It shows the next entry in the array which is "This is a magically held lock." I made it continue to show the easiest difficulty message for any chance 95% or higher.
> Fix looking at lockpicks with 95 or better chance

- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Utility/ImageReader.cs
I changed an array of Texture2D to an array of ImageData in TransportManager in order to maintain the correct size on screen with different resolutions. This is often an issue with daggerfall hud images where texture size is used as rect. Width and Height of Imagedata always refers to Daggerfall file, while Texture2D properties are the actual resolution of texture.
> TextureReplacement: support for cfa files

- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Implements classic cost formula for selling.
Prices in classic are influenced by a value, set for each region in the game, that changes every in-game day. This value is imported from classic saves now. It's in a big chunk of data I called RegionData, but I'm just assuming it's all region-related. Most of it is 0 in my saved game I was using for research, but a few other values are set. For now I'm storing the regional price adjustments in the player entity for convenience, but we might want to have some sort of storage for regional data in the future, so I didn't include it in DF Unity saves. When starting a new game or loading a DF Unity save the values will be randomized to the same range they are randomized to in a new game in classic.
I haven't implemented the daily change in the …
> Implement classic cost formula for selling

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/TrappedSoulRecord.cs
- Assets/Scripts/API/Save/TrappedSoulRecord.cs.meta
- Assets/Scripts/Game/DaggerfallBankManager.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
Not sure if the TrappedSoulRecord is right since the data with the soul monster id is at 0x1B which is part of the root record - SpriteIndex in fact.
All the records seem to have above the root record is a single byte, value = 150
Anyway after mapping to the corresponding MobileEnemy, the soul names are now displaying correctly. Guess there will be more to do once magic is implemented.
> Read trapped souls from classic saves and display info

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
This should hopefully give correct greetings based on reputation. A few other things, (masque of clavicus, something to do with guilds) in classic can affect NPC reaction to player, which isn't in yet.
The reputation modifiers with the general social groups (commoners, merchants, etc.) are imported from classic saves. They aren't saved in DF Unity yet because I want to be sure that the manner I'm storing them in the player entity is OK, which is as an array, to make it simple to access using the sgroup values from faction.txt.
> Implement correct greetings based on reaction

- Assets/Scripts/Game/UserInterface/TextLabel.cs
this can be used to set text scaling, e.g. 0.5 is half text size
text and word wrapping will adapt accordingly
> TextLabel now supports text scaling (property TextScale)

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/SettingsManager.cs
Enabled by a setting, disabled by default.
Thanks to Nystul for the text scaling.
> Item hover info panel in inventory

- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Fixes the game freezing. Also moves player-specific code out of DaggerfallEntityBehaviour and into PlayerEntity.
The `lastGameMinutes` variable is also in PlayerEntity now and is set to the current game minute whether starting a new game, loading a Unity save or loading a classic save. Feel free to get rid of this variable and replace it with a more elegant solution if you like, it's just a simple way to handle events that are based on in-game minutes passing.
> Re-enable and fix price adjustments

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
Both exterior and interior map windows locked up and broke when tooltips are turned off, so I fixed it. Just clumped all of the tooltip delay set statements in a conditional null check.
Also added the trapped soul variable set from importing classic to be saved in DFU.
> Fix map windows bug with tooltips off and save souls

- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Info panel now appears on trade windows as well.
- Inventory tooltops no longer suppressed if info panel enabled.
- Backpack icon & weight displayed for carried items, i.e. player inventory.
> Implement inventory icon and move info panel

- Assets/Resources/FLATS.CFG.txt
- Assets/Resources/FLATS.CFG.txt.meta
- Assets/Scripts/Game/TalkManager.cs
fix for common female faces derived from factions
fix for blue-cloaked woman at court wayrest using FLATS:CFG.txt in resources folder (gets loaded instead of FLATS.CFG in Arena2 folder)
one can add missing billboard to face mappings in there for npcs
> Talkwindow - fixes: female faces derived from factions and faces defined in FLATS.CFG.txt

- Assets/Scripts/API/FlatsFile.cs
Identified the gender flag in flats.cfg, which was marked as unknown. It's either 1 for male or 2 for female, but if it's preceded by a ?, this marks the flat to be censored (not displayed) in ChildGard mode.
I think this gender flag may be used for determining the gender of flats for quests and filling out some gender-based macros, like getting an appropriate name. I don't know if it might help you in any way for the quest system, Interkarma.
> Identify gender flag from flats.cfg

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Fixes and adjustments for enemy animations. I'll go through everything below.
1. (not animation related) Fixed an incorrect null assignment (from my earlier PR) that made a warning in Unity.
2. Fixed rat being flipped horizontally. For some reason there was specifically code to flip the rat. Instead, the same code was used to flip the giant bat and the imp, who both needed it. There is also existing code to flip the scorpion, but I haven't tested it yet to see if that is functioning properly.
3. Fixed enemies not playing the first frame of their attack animation. currentFrame was incremented immediately in AnimateEnemy() of DaggerfallMobileUnit, so the first frame didn't show.
4. Adjusted animation speeds. Slightly sped up enemy attacks, lowered enemy movement animation and added faster …
> Animation fixes and adjustments for enemies

- Assets/Scripts/Utility/EnemyBasics.cs
I accidentally set the daedra seducer's to hit on frame 3 instead of 2, which is outside of the frame range.
> Fix Daedra Seducer attack

- Assets/Scripts/Game/Entities/PlayerEntity.cs
Implements running skill tallying.
In classic, the function to tally the running skill is called by what seems to be a constant update loop, and because of this the rate at which it is tallied varies by how fast the game is running. I did a few tests and found that in both a town and dungeon environment, in my DosBox setup (running at 30000 cycles) the tally rate is about 16 per second that the run key is held down as long as you aren't riding a horse, even if you aren't moving. I set it so that PlayerMotor.isRunning has to be true for the tally to occur.
> Implement tallying of running skill

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/DaggerfallSkills.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
Fixes and adjustments to training to make it more like classic.
1. Fixed black screen background on message popups.
2. Added "You don't have enough gold" popup and prevent training if player doesn't have enough gold.
3. Fatigue loss is now defaultFatigueLoss per minute * 180 minutes, which I think is what it is in classic.
4. Number of skill tallies gained matches classic.
5. Time of last training is imported from classic saves.
Hazelnut, I think I can add in all of the trainers and their lists of offered skills pretty easily, too, unless you want to do it.
> Fixes for training

- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Questing/Item.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Utility/MacroHelper.cs
Imports and saves region data structures from classic. A lot of the data is still unknown, but I've been able to determine the data size of them. I think a lot of them are flags for various region events, things like a ruler dying or some group becoming a public enemy, the stuff you see in rumors or on the signboards at city entrances.
Right now, the game play benefit is that regional price variations are saved and loaded, and so will no longer be re-randomized every time you open a DF Unity save.
The region data includes the legal reputation per region. I went ahead and hooked this up to the status pop-up (and fixed a problem that caused all legal reputations under 0 to be shown as "undependable"), but I see that some groundwork has already been laid in place for storing legal reputation …
> Import and save region data structures from classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Fixes prohibited armor material checking. My earlier fix attempt by changing the shift direction was incorrect. First, I wasn't thinking straight -- if you have two bytes and want to shave off the right one and just use the left one, you can shift to the right, but if you do the same thing in the other direction to try to use only the right byte, you would need to again shift back after shaving off the left byte or the number would be too large.
Second, I didn't pay attention to the fact that the DF Unity material enum is a 4-byte int, so my shift didn't even shave off the left bit, it just made the number bigger.
For the fix this time I just cancel out everything but the rightmost byte. Tested on a character with prohibited leather, iron and steel equipping daedric armor (which Hazelnut …
> Fix prohibited armor material check

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
This is a very manually, trial-and-error type of fix (found that upper right corner of Cybiades in its zoomed-in view and the less zoomed-in view from Sentinel seemed to match, and went from there), but the results seem to work. Fixes http://forums.dfworkshop.net/viewtopic.php?f=24&t=764.
> Fix for clicking on other regions from Cybiades

- Assets/Scripts/Utility/ClimateSwaps.cs
2 Fixes.
1. Fixes http://forums.dfworkshop.net/viewtopic.php?f=24&t=376.
I found that classic omits and of the 3rd exterior door records from being climate-swapped. This fixes the dungeon door mentioned in the bug report and also the doors at Daggerfall Castle (out on the towers in the courtyard). In the bug report you mentioned that you had patched out some doors this way but I couldn't find the code for it, and without this PR there are tavern doors on the courtyard towers of Daggerfall Castle. Was that code removed or never applied to master? If it does exist in master maybe we should remove it.
2. Added the swamp temple interior textures. These were disabled as "missing" but they aren't missing. They exist under "Swamp Temple Int." and are used in classic. They do look pretty unusual …
> Texture fix

- Assets/Scripts/Game/PlayerEnterExit.cs
Fixes a bug I found where if you enter a dungeon while jumping, you take falling damage when the dungeon loads.
> Cancel player movement when entering interior

- Assets/Scripts/Internal/PlayerGPS.cs
Fixes an out-of-bounds array error with legal reputation and the blank place names when using the status popup outside of a political region (in "High Rock sea coast").
> Fix getting High Rock sea coast region index

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Forces ocean travel costs as if player didn't own a ship so that ocean travel costs can be tested for a while.
> Temporarily ignore player ship for travel costs

- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Internal/DaggerfallAction.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
This implements castle guards going hostile. The main thing I was aiming for was finishing up the "DoorText" action I worked on earlier. Guards will go hostile now when you open the doors to restricted areas in the castles, like in classic. Also, guards will go hostile when you attack any one of them that was passive. All guards in the area will be set to hostile. I think in classic it might just be those that are within loaded range or something, but this behavior seems fine to me, rather than potentially having some guards standing around and ignoring the fight.
As for the DoorText trespassing action, the classic behavior is emulated, but it is somewhat broken IMO.
- The descriptive messages that warns you about areas being off limits are only seen if you click the doors in info mode, …
> Implement castle guards going hostile

- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/Internal/DaggerfallAction.cs
- Assets/Scripts/Utility/RDBLayout.cs
Gets the lock value for doors in the same manner as classic.
For regular locks the value will be the same, but apparently magical doors can have a few different values, which wouldn't be correct before this PR. Maybe those values matter when using lock-opening spells.
> Get door lock value like classic

- Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
* Implemented MultipleChoices as sliders (take up a single line, not affected by number of items)
Something like [this](http://support.amd.com/PublishingImages/Support/KB/Witcher4.png). Basically hides the index with the corresponding string set in scriptableobject config, no more need to write all possibilities in tooltip :)
* Organization in settingswindow and reader classes
* Added method Deserialize() in ModSettings which parse known settings values (int, float, tuple, color etc., the same that can be chosen in SO inspector to show in window) of a section in a class at once.
> Modsettings

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/DungeonTextureTables.cs
- Assets/Scripts/Internal/DaggerfallDungeon.cs
- Assets/Scripts/SettingsManager.cs
Adds settings.ini options for dungeon textures.
0 = classic textures
1 = climate-based textures, using classic algorithm for picking among them. Main story dungeons have classic textures.
2 = climate-based textures for all dungeons
3 = Random selection from all textures (DF Unity implementation from before). Main story dungeons have classic textures. Sewer texture fix added so out-of-range textures shouldn't be used.
4 = Random selection from all textures (DF Unity implementation from before) for all dungeons. Sewer texture fix.
> Add dungeon texture options

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/TalkManagerMCP.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
progress:
%oath macro resolved
BaseScreenComponent now supports restricted render area
support for texture replacement (some stuff will not work right now):
what should work: background and topic/mode selection
what will not work right now: portrait and navigation stuff
support for interior automap texture replacement added
support for exterior automap texture replacement added
> Talkwindow - progress, support for texture replacement talkwindow, interior and exterior automap 

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
The player's left-hand weapon was being ignored for damage calculation. Fixed now. Also did a little clean up in removing "DaggerfallConnect" in FormulaHelper where it wasn't needed, which shortens some of the longer lines.
> Fix player's left-hand weapon being ignored in damage calculation

- Assets/Scripts/API/DFRegion.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Editor/AtlasEditorWindow.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/Scripts/Utility/ContentReader.cs
Gets most pre-discovered locations in the same manner as classic.
Some DFRegion.LocationTypes.GraveyardForgotten type locations that start the game known in classic are not gotten yet, but this is the same in the current implementation in master. I haven't been able to find how these are gotten yet.
As far as I know this is functionally identical to master, but it's a step toward correctly reading the map files and could be helpful as reference in figuring out how to import discovered location data from classic saves or how to get the remaining locations that start the game known so I think it's worth merging, but I'll leave the call to you Interkarma.
I also removed what looked like a couple out-of-date TODO comments.
> Get most pre-discovered locations like classic

- Assets/Scripts/API/DFLocation.cs
- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Internal/DaggerfallBillboard.cs
- Assets/Scripts/Internal/DaggerfallDungeon.cs
This identifies the dungeon water level value, which is contained in the "SoundIndex" value of a block's start marker.
I don't know if I'm propagating the value up in a way you would like, Interkarma, so feel free to change that. I just poked around at it until I found a way to get it through the various data structures up to the PlayerEnterExit class, which is where I suppose it is wanted.
Start markers also contain the value that determines whether a dungeon block is a main story castle block with NPCs, initially non-hostile guards, etc. Since we can use that I put that in and removed the check based on block name, but functionally it should be the same. If you would prefer it continue to be done by block name that is fine.
> Identify dungeon water level and castle block data

- Assets/Scripts/API/DFRegion.cs
- Assets/Scripts/Utility/RDBLayout.cs
I missed this in my PR on the map data. A leftover shift was causing all dungeons to have crypt monsters.
> Remove no longer needed bit shifts

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/PlayerFootsteps.cs
See comments in https://github.com/Interkarma/daggerfall-unity/pull/543.
Makes water environmental sound 2D and distance-based. I tried to roughly match classic's sound dropoff. Also adds water splash when entering, according to same criteria as classic (player.y + 50 classic units is < dungeon water. It's opposite in classic actually, since negative y is up there), with unit conversion as needed.
> Dungeon water sound progress

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/Scripts/Utility/MacroHelper.cs
Works basically like classic. Although UESP says that map items reveal a large undiscovered dungeon, it's actually any undiscovered location, including small dungeons and covens, which I confirmed through testing.
Since I found the flag in my earlier PR that determines whether a location starts the game discovered (not counting some of the graveyard locations which are still a mystery), we now have "discovered" data in two places, that flag in the map tables, and a discovered locations dictionary. Maybe we could get by just using the bit in the map tables? Also there's what feels like a little bit roundabout code in this PR in order to discover the location using the region and location names, which are the parameters for the to be the DiscoverLocation function, but it works fine. If you …
> Implement map item

- Assets/Prefabs/Scene/DaggerfallEnemy [Game Serializable].prefab
- Assets/Prefabs/Scene/DaggerfallEnemy [Standalone].prefab
- Assets/Scenes/DaggerfallUnityGame.unity
- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Implements knocking back enemies. Should be close to classic behavior.
This may give the player a bit of advantage for now. If we implement the player's view getting thrown off when they take a heavy hit, and also correct weapon speeds (the player swings fast now), it will hopefully even out.
I think having this in somewhat alleviates the "enemy constantly pressing forward while you backpedal" feeling of combat.
One thing that is happening in this PR that I don't understand is that sometimes an enemy will resume moving toward the player while still in the hurt animation. I can't see why this happens. The state should always have been reset to "Move" before an enemy gets out of being knocked back. Any idea?
> Implement knocking back enemies

- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
For quite a while now, probably ever since the SmoothFollower stuff was added, I've had a problem with an exception occurring on the line
`float maxPossibleDistanceByMotorVelocity = controller.velocity.magnitude * 2.0f * Time.deltaTime;`
in PlayerMotor.cs when I try to start the game from the editor. It seems like it always happens the first time I try to run the game from the editor after getting the latest update to the master branch.
Has anyone else had the same issue? This check should keep the exception from happening.
BTW, on the topic of fixing issues with the code...
I've noticed that when loading a game, "OnMapPixelChanged" happens twice. Nystul, in TalkManager.cs, AssembleTopicLists() is called 3 times when you load a game, twice from the OnMapPixelChanged event, then once for …
> Prevent exception in SmoothFollower

- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerWeather.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Game/WeatherManager.cs
- Assets/Scripts/Internal/PlayerGPS.cs
This re-introduces weather changes, which are currently disabled, using something close to the way classic does it, and imports weather from classic saves.
- In classic weathers are stored in a 6-byte array, which can be found in SaveVars, with the weather for the player's current climate the one that is used. DF Unity just tracks one weather.
- Thunder (which can be chosen in classic but has no visual or audio effects) and snow have their enums reversed in classic and Unity. This PR switches them when importing from classic.
- Classic changes weather when the date changes, or when the player crosses climate zones. Because of the game's accelerated time versus the speed of real time, I feel this looks OK, even though weathers only change on at a minimum of 24-hour increments. Also, since …
> Implement classic weather selection

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Utility/WeaponBasics.cs
This implements classic fps weapon animation timing that should be very close to classic. The speed attribute is used to determine weapon swing speed and cooldown between bow shots.
Also the special animation sequence for sideways left strikes with hand-to-hand/werecreature is implemented. After playing through normally it plays back the initial frames in reverse.
There is also a general cleanup of the weapon manager code. To me at least, it cleaner and makes more sense now. Its no longer possible to sheathe/unsheathe or switch hands mid-swing, although its possible in classic, because it looks weird and buggy.
Interkarma can I have your feedback on a few things?
1- The attack swing may seem too slow for characters without a high speed attribute. I'm a little worried it could give a poor …
> Implement classic weapon animation timing

- Assets/Scripts/API/DFRegion.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Utility/MacroHelper.cs
Turns out there's keys in the mapTable records for which types of buildings exist in each location.
In classic asking for armorer is bugged and always returns 0, but there was a gap in the flags and it seems to match for armorer, so this PR uses it.
The question text is still unimplemented.
> Implement regional building answers

- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/Internal/DaggerfallAudioSource.cs
- Assets/Scripts/Utility/RMBLayout.cs
Implements animal sounds. Range and frequency should match or be close to matching classic.
One thing though, is that I don't know exactly what's going on with the billboard batching. It looked like I needed to (or it at least be simplest to) remove animal flats from billboard batching so I could add audioSources to them, but maybe they can still be batched? If not, we could remove the animal batch code.
> Implement animal sounds

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Utility/MacroHelper.cs
Implements:
- Identifies and imports skill raised flags from classic saves. In classic these are set when a skill is raised for the current player level and cause the skill to be rendered in blue when looking at skill levels. This PR just imports the flags but doesn't do anything with them, nor are they saved/loaded between Unity saves yet.
- Implemented mastering a primary skill (reaching 100). You get the fanfare sound and the congratulatory message as in classic.
- Implemented %ski macro, which is used in the congratulatory message.
This PR just does things as classic does, but mastering a skill is actually a bit of a restriction, because until you do so you can raise any skill to 100%, but after you master a skill, you can no longer raise any skill over 95%.
What seems like a natural …
> Implement mastering skills, import more skill data

- Assets/Scripts/Game/FPSWeapon.cs
Fixes a problem with the FPS weapon looking glitched when you change weapons because the old weapon's animation data remained. Also put in an optimization to not run UpdateWeapon() from the weapon animation subroutine when there is no reason to.
> Fixes to FPS weapon animations

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
- Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs
- Assets/Scripts/Game/UserInterface/Paginator.cs
- Assets/Scripts/Game/UserInterface/Paginator.cs.meta
I moved the left/right control used in PresetPicker window to its own class, so i could also implement it in ModSettingsWindow.  [picture](https://i.imgur.com/VOZiMBB.png)
> Move next/previous control from PresetPicker to its own class, implement also in ModSettingsWindow

- Assets/Prefabs/Scene/DaggerfallEnemy [Standalone].prefab
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
Implements stealth basics, as well as general tweaking of enemy detection AI.
- The basics of the stealth check in classic are recreated (check every in-game minute, tally player skill, detection formula). There's a bit more that's involved but we need to implement the sneak key first.
- Enemy FOV matched to classic. Vision and hearing range (I don't think enemies have "hearing" in classic) matched to range of stealth check
- Hearing is only active when the player has been detected by that enemy, since otherwise it would interfere with stealth and not allow sneaking up on enemies. The stealth check in classic basically doubles as "hearing" simulation. Since I've increased the hearing range I also force a "false" hearing check when statics are between the enemy and the player, to try to …
> Implement stealth basics

- Assets/Scripts/Game/UserInterface/FacePicker.cs
- Assets/Scripts/Game/UserInterface/HUDCompass.cs
- Assets/Scripts/Game/UserInterface/HUDCrosshair.cs
- Assets/Scripts/Game/UserInterface/LeftRightSpinner.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallListPickerWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs
- Assets/Scripts/Utility/TextureReader.cs
* I simplified XmlManager as it was getting out of hand. Now TextureReplacement has all the methods that deals with size of UI images, which i refactored in the process.
There are a few lines which only differs for a method name, sorry for that.
* MipMaps is enabled for .XXX textures and disabled for img, cif and rci. Is this ok or there is something more specific i should consider?
* Size of MiscFlats atlas is 4096 instead of 2048 when asset import is enabled.
* Minor cleanup and optimization.
* Allow imported emission map to be tinted with window color.
> TextureReplacement: Simplification of Image size methods (including XmlManager), other improvements 

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
This implements backstabbing in the same manner as classic and also has a rewrite of the damage calculation function, including adding a part of the formula I had missed regarding the hit chances for enemies. This actually depends on the reflexes setting but this PR matches the default reflexes setting.
> Implement backstabbing and rewrite damage formula

- Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsConfigurationEditor.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsConfiguration.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsKey.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
No notable new features, just some little improvements. Editor UI in particular is now more confortable to use since i implemented ReorderableList, which allows keys to be dragged and change position without destroying the list. I'm going to provide more details on forum.
Changes:
* Add missing keys when reading file from disk.
* Improved usability of modsettings asset in inspector with ReorderableList, which allow keys to be dragged isnide a section.
* Import a ini file from inspector to create a basic settings asset. This is helpful when upgrading old mods to the new UI system.
* Graphical improvements in inspector view.
* Allow Copy/paste options for multiplechoices between keys.
* Use a red color for sections called "Internal" in inspector (keys hidden from gui).
* Reorganized …
> Modsettings: Minor tweaks

- Assets/Scripts/Internal/DaggerfallSky.cs
With this method, the fake horizon now moves vertically at the same speed as the real horizon, so they should always appear "glued" together. Although having a 2D background against a 3D foreground might still make some people sick, it's about as good as it's going to get without stretching somehow (see the backgrounds in the original Doom).
Another idea I had for improving the fake sky was to have its scale be a function of field of view, because as it stands, the fake horizon has the same size on-screen regardless of what the field of view is.
> Calculate fake sky Y position with Y-shearing

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Imported textures use DXT5 if requested by user settings.
> TextureReplacement: add option for compressed textures

- Assets/Scripts/Utility/EnemyBasics.cs
Enemy mobiles in the walking animation were reversed for the up-right, right and down-right animations. They showed as the left-looking versions.
> Fix some reversed enemy walking animations

- Assets/Scripts/Game/PlayerEnterExit.cs
Would happen if you went off the edge of the loaded dungeon blocks (happened to me while levitating around in the void).
> Fix out-of-bounds array access

- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallListPickerWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Internal/DaggerfallBookshelf.cs
- Assets/Scripts/Internal/DaggerfallBookshelf.cs.meta
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Utility/RMBLayout.cs
Shop shelves have loot containers and initiate trade. (random items for now)
Libraries are not shops - reverted my previous 'correction' and corrected existing code instead
Library shelves are marked as bookshelves and implemented reading (temples & guilds too)
Moved shelf stocking to building interior layout to avoid restock when empty.
Added member message for guilds and temple bookshelves
Refactored loot container handling in PlayerActivate
Added house container handling
Shop shelves are serialized, so persist across save/load but are not persisted when leaving building
> Enable player interaction with shelves

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
In master branch it's possible to die from fast traveling if you hit the fast travel key while you were in the air (jumping for example) and the destination is lower elevation than the place you traveled from.
This fix works by clearing fall damage when teleporting. We might end up needing a different fix, because the player is also teleported to the correct position when loading a saved game, and you should still get fall damage if you saved mid-fall. You don't get any fall damage in master branch either, though, so this isn't a regression.
Or, if we can change the loading code to not use a teleport, maybe we can continue to use this fix.
> Fix dying from fall damage when fast traveling

- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
Also fix bug with drop icon code
Model 41808 should be in house containers but classic has that model work as shop shelves in the shop from the bug report (http://forums.dfworkshop.net/viewtopic.php?f=24&t=852) so I've moved to shelves list.
This may cause wierdness if this model is in any non-shop buildings.. so we'll need to keep a lookout for that and move it back if any occurances are found.
> Add model id 13 to shop shelves and move 808 from house containers

- Assets/Scripts/Game/EnemyMotor.cs
This should fix enemies losing track of the player at close range, and also mitigates the problem of them turning too slow, not by making them turn faster but by having them turn more often to keep the player in sight. This behavior should also be a little closer to classic. It may need more tuning but it seemed to work fairly well in testing.
> Fix enemies losing track of player at close range

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
This implements the following, matched to classic:
1) Same cost formula, including free for Heart's Day
2) Commented out code for free lodging for knights, once we have guilds implemented
3) Different messages depending on how well player bargained
4) Limit on renting days into the future includes days already rented.
Regarding 3, @ajrb, this causes code duplication with the trade window. Classic uses the same function for the display of the Yes/No bartering window. Since you wrote both the trade and tavern windows, maybe you can look at combining them. I started to play with doing so but it looked like it could get messy and I think you'd have a better idea of how to do it.
Btw there's a bug/oversight here in classic. The way the bartering message works is that you get one depending on …
> Implement classic tavern room costs

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Finish merging quest dispensing into guild service code now that we're onto 0.5. 
Should appear completely unchanged to players.
Disabled old code, but leaving in for now so can switch back if issues found.
One thing that that is changed is that in PlayerActivate lines 860-880 the trigger of quest resource behaviour and quest listener check are both now done before the quest dispensing is activated, rather than after. This doesn't seem to affect anything as far as I can see, but I may have missed something so please let me know if I need to preserve the ordering for any reason.
> Merge quest dispensing into guild service code

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Scripts/Internal/DaggerfallSongPlayer.cs
- Assets/Scripts/SoundReader.cs
- Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs
* Added a generic method to ModManager class to seek and import an asset of given type and name from all mods.
* Added support for sound import from mods. It was already possible to import them from disk, now they are also loaded from assetbundles with load order, like we discussed on forum for textures.
I did the same with videos but i prefer to test them a bit more before pushing.
> Asset injection: Import sound files from asset bundles

- Assets/Scenes/DaggerfallUnityGame.unity
- Assets/Scripts/Game/BuildingDirectory.cs
- Assets/Scripts/Game/DaggerfallBankManager.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- ProjectSettings/TagManager.asset
Sorry, far too excited about this so I've just handled loading inside a bank by using the no houses for sale message. I'm happy to switch from using BuildingDirectory to datafiles, but not convinced it's worth it for this edge case. Turned out the radius was easy to get once I had model id. Didn't even need Allofich for the price multiplier.
TODO:
* Only listing buildings for sale - will need to add other houses in due course.
* Selling houses. (should be easy since the name is changed by overriding in PlayerGPS)
Anyway, this is so you can give it a spin when you need a break from magic! This was a while in the works as I gradually learned but it all came together today really nicely. Such a good feeling!
Oh, and you may want to check my changes to Place for preventing quests spawning in …
> House purchasing, ship models & player housing

- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Utility/ImageReader.cs
This follows #629. Native panel size is only used in inventory window, so i wrote a single method that accepts a DFSize argument. A few classic textures were off by one pixel (which is visible at classic resolution) so relative rect is used only when necessary. Tell me if you have any suggestions or requests :)
> Add GetSubTexture() overload for relative subrects

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Entities/DaggerfallDisease.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements:
- Classic diseases' stats (which attributes they affect, etc.)
- Diseases that endlessly lower stats vs. those that don't. When a non-endlessly-lowering disease finishes, it sets its number of days left to 254 (0xFE) in classic. Doing it the same way, which should aid in importing diseases from classic saves.
- Length of disease and damage values gotten like in classic.
- Diseases lower stats in the same manner as classic and can kill the player.
Diseases are disabled now until a way to cure them is implemented.
I haven't figured out how classic does the incubation period yet. Also there is no "you may not survive" message for traveling. Length of disease period will need to be saved and loaded. Poisons aren't implemented yet. Neither are imported from classic saves yet.
> Progress on diseases

- Assets/Scripts/Game/PlayerDeath.cs
This sets the death sound by race and gender.
Background:
There are 3 pain sounds for each race/gender combination in the sound files. Classic only uses one of these, the second in the Male Wood Elf set, for the player regardless of their race or gender in the original game.
By my judgment the sounds generally seem to sound like
1. Hurt/Exertion
2. Hurt/Exertion more
3. Dying
The "hurt" sounds might also be interpreted as exertion while attacking. For example the Breton Female "Hurt 1" is the same as the Nymph's attack. But generally across the board I think they sound more like being hurt than doing an attack. I think the 3rd one is pretty unambiguous across the board as a "dying" sound, so that's the only one I'm using for this so far. I'm thinking maybe the other two could be used as …
> Set player death sound by race and gender

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Guilds/Temple.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
Implements classic cost for cure diseases.
Some additional work needs to be done. @ajrb, I need your help to figure out some stuff. The main thing, which I think should be fixed before this is merged, is displaying the correct cost amount in the dialogue. Temple healers use the same "bartering dialogue" as shopkeepers. However right now the amount given in the dialogue doesn't reflect the actual amount that curing the disease costs. These messages have a `%a` macro that is used in classic, but in DF Unity it looks like this macro is unimplemented. Why do the shopkeepers show the correct value? We need it for this dialogue, too, and the cure calculation will need to be figured out before the message shows, not after as it is now.
Otherwise, this doesn't have to be in right now, but the …
> Implement classic cure disease cost (WIP)

- Assets/Scripts/Game/Guilds/FightersGuild.cs
- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/StreamingAssets/Quests/B0B20Y07.txt
- Assets/StreamingAssets/Quests/B0B60Y12.txt
- Assets/StreamingAssets/Tables/QuestList-Classic.txt
This was a pretty bad and stupid oversight on my part! This fix stores the faction id so that the rep is changed correctly when the quest finishes. Currently it only changes the faction rep if you don't save and reload between taking the quest and completion which is pretty rare.
Would you please create a new build and remove the #102 build once this bugfix is merged and validated. I consider it that serious. (as in it breaks the whole guild system since you can't get promotions)
> Bugfix: save factionId with quest

- Assets/Scripts/Internal/DaggerfallBillboard.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs
- Assets/Scripts/Utility/ImageReader.cs
Textures for billboards can now also be imported from mods, in addition to loose files. This include xml files with optional scale and uv.
I was hesitant to do this at first because there is a possible issue of unwanted mixing of resources when a mod includes a texture with an xml, and another one in a lower position includes the same texture but without the xml. The same may happens for emission maps. If this became a problem we could fix this at a later time loading everything only from the last mod that include the first main texture frame. 
What's left now are textures for 3d meshes. I think it would be a pity not to benefit of Unity materials, so my idea is to load them directly. It's a bit of an hassle for the most simple texture packs with only the albedo, but i believe is the …
> Texture replacement: Import billboard textures from mods

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Utility/RandomEncounters.cs
This adds the groundwork for random enemy encounters implemented like classic. Right now there is are no functional changes.
Adds:
- All enemy encounter lists from classic
- Classic function for choosing enemies (not being used for anything yet, and not tested)
- Incomplete classic function for spawning random enemy encounters
Interkarma, I hope maybe you can give some advice for filling out the remaining parts. These are the remaining issues:
- The main issue: How to spawn a nearby enemy? I know this is implemented for quests, but is it tightly wound up in that, or is there a convenient method available for spawning an enemy nearby, with the only parameter being the enemy type?
A couple of minor issues:
- Need to set and store a variable to disable monster spawning in some …
> Lay groundwork for random enemy encounters

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Utility/RandomEncounters.cs
Random encounters spawn now. Thanks for the FoeSpawner, Interkarma.
I don't know if adding a FoeSpawner to the "options" part of DaggerfallUnity prefab is correct style-wise, I just followed the example of existing uses of InstantiatePrefab.
In game it works fine. While in the wilderness in classic enemies actually spawn from a little farther away, but currently at that distance enemies don't react to the player in DF Unity nor does the "There are enemies nearby" message appear, so for now I just have it using the default FoeSpawner distances.
> Spawn random encounters

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
This is the start of implementing regional conditions. Only famine is handled now, and there are no in-game effects, only debug.log messages about the famine phases. As with randomEncounters, this is being handled in PlayerEntity for now but could be moved later. This is all matched to classic behavior.
> Start implementation of regional conditions

- Assets/Scripts/Game/UserInterface/PaperDoll.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Fixed a few windows reported on forums. Also removed a workaround for paperdoll background which is not necessary anymore since we can cut imported textures now.
> TextureReplacement: some size fixes

- Assets/Scripts/Game/DaggerfallBankManager.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Just a note, I started to add behavior for reading classic's bank records because it wasn't in what I thought was the "usual" spot, in ReadRecords() in SaveTree.cs. It seems like that should be consistent. But at least it meant the work of converting the read data to DF Unity was already done.
Maybe Interkarma though the same thing when he made this bug report?
http://forums.dfworkshop.net/viewtopic.php?f=24&t=788
Or maybe he made that before the code to read the data was added? Anyway the boolean that was being skipped is now read and used, so that report can be closed.
> Add "already defaulted" bank behavior

- Assets/HeadRecoiler.cs
- Assets/HeadRecoiler.cs.meta
- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/Scripts/SettingsManager.cs
Adds head recoil (screen stagger) when taking damage.  "Camera Recoil" Toggle on the first page of settings.  Default is ON.  Camera sway is **increased per point of damage taken**. Formula is in GetRotationVector() in HeadRecoiler.cs.
> Add Camera Recoil to DFU

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
Implements gradual return of reputations to 0, matched to classic.
Also some cleanup, comments, etc.
I removed the unused stuff for legal reputation in PersistentFactionData.cs, trying to keep the mess of all this WIP stuff under control a bit, since legal reputation all being done in the playerEntity's regionData array at the moment. If you want to refactor this stuff later, Interkarma, to make it all more tidy or fit some code organization you have in mind, that's OK with me.
I'm looking into guard spawning, btw, which ties into legal reputation work.
> Implement normalization of reputations

- Assets/Prefabs/Scene/DaggerfallMobilePerson [Standalone].prefab
- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/WeaponManager.cs
This adds blood splashes for killing townspeople and basic guard spawning (only for killing townspeople for now).
I think that guard spawning behavior in classic involves LOS checking from townspeople, and nearby "townsperson guards" and regular townspeople (1/3 chance) are the first choices for spawning guards. The fallback behavior after that is what this PR uses. I may need some help from you Interkarma to do that. Basically I would want to be able to iterate through the townspeople, doing an LOS check from each of them to the player, and also to be able to use the location of a townsperson as a spawn point (not sure if we actually want to do that for regular townspeople, it may have been intended to simulate them "clearing the streets" but it may be more immersive to not do it that …
> Implement blood splash for townspeople and basic guard spawning

- Assets/Scripts/Game/Player/HeadBobber.cs
Improves the camera movement transition from stationary to moving.  It's now much smoother when starting to move, the camera won't jerk about suddenly.  Some people may not have noticed this since the head bob is very subtle, but it was especially noticeable when moving and crouching.
> Improve Headbobber

- Assets/Scripts/API/Save/ContainerRecord.cs
- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/SaveTreeBaseRecord.cs
- Assets/Scripts/Editor/SaveExplorerWindow.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
Recently I found that FALL.EXE contained a collection of strings that matched to the object types, although it's incomplete. This updates the `RecordTypes` in `SaveTree.cs` (I believe these are referred to as "Objects" in classic), noting the names from classic and also information on them I have reversed.
I also improved Save Explorer a little.
- Do not start with the faction drop-down open. This was an annoyance as I had to close it every time.
- Identify all "Container" types, not just the wagon.
And of course the work on identifying record types carries over to Save Explorer.
> More classic data identified + Save Explorer improvements

- Assets/Prefabs/Scene/DaggerfallEnemy [Game Serializable].prefab
- Assets/Prefabs/Scene/DaggerfallEnemy [Standalone].prefab
- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Game/WeaponManager.cs
- Added crime enum and variable to track player's crime to playerEntity, and import this value from classic saves.
- Set the crime variable for the easy cases (murder, pickpocketing, vagrancy). The others will take a little more work to get right.
- Guards spawn further away (max distance should be equal to classic). Enemy sight increased (also FOV, which hadn't been properly updated before. I think I only changed the prefab for the Standalone Enemy and not the Serializable one). I believe the FOV matches classic and the sight matches the maximum distance an enemy can exist in classic (in outdoors environments) before being despawned, which may or may not be the same as sight range. Regardless, pursuing by guards or other monsters works much better.
A couple notes:
- Using the foe …
> More work on guards and crime

- Assets/Scripts/Game/Player/HeadBobber.cs
Changes the statement that assigns the mainCamera.transform.localposition so that it adds the difference between it's current position and new position to the current position.
This allows other code from other classes to modify the localPosition of the camera without the Headbobber dominating the position.
This commit is being made to incease compatibility with other code I'm working on, without changing the functionality of headbobber.
> Improve Headbobber support for other code

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/DaggerfallUIMessages.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs.meta
Crimes now modify player's reputation with "people" factions in the same manner as classic.
Also identified the parts of the faction records in `SAVEVARS.DAT` that were unidentified. If we wanted to it's probably possible to create the parent-child relationships of factions just by reading in and using the 3 pointers at the end of each faction data record from `SAVEVARS.DAT`, rather than creating them by reading `FACTION.TXT`, but of course what we have already works.
> Crimes modify faction reputations

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
Makes it easier to max out the volume bar on sound and music
I want to add more fixes to this branch before it gets merged to master, but I wanted to create it to discuss some potential fixes to making all the sounds scale with the audio volume setting.
PlayerFootsteps uses an AudioSource called customAudioSource and a DaggerfallAudioSource called dfAudioSource.  The former is used for default footsteps and the latter is used for other footsteps. 
TransportManager does something similar for keeping the horse whinny sound separate from riding sounds.
In addition to horse and footstep sounds, it seems like dungeon ambient sounds and enemy sounds aren't being affected.
> Make it easier to max out volume

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/TextureReader.cs
* Terrain textures can be shipped in a single dfmod file.
* Removed some old methods for loose files import which are not needed anymore.
I'm using Shader.PropertyToID() because methods for access to shader properties have an int overload, which is faster than the string one (i believe the string method just call PropertyToID everytime).  I wrote a static class to holds all these values like the post processing stack does. What do you think of moving it to MaterialReader and use it project wide?
> Asset injection: Import terrain textures from mods

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Change silver damage bonus back to Skeletal Warrior.
Recently someone working on OpenTESArena found that original Arena gives silver weapon damage bonuses against undead, so I no longer think this was a mistake. However, it might be a mistake or oversight that it only applies to the Skeletal Warrior and not other undead types. Changing that might affect gameplay too much, though, if it made undead enemies too easy, so I just put it back on the Skeletal Warrior like in classic.
- Make enemies stop when turning while pursuing again (not needed because of the faster turning now). This will remove the odd-looking behavior of dashing off to the side when you approach enemies from behind, etc.
About the turning, though, I think it may be too fast at the moment. Specifically, if an enemy goes …
> Minor adjustments to enemies

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
Moved the message down and removed the background dimming. The court screen is already a dark screen and you can't see it clearly if it is dimmed.
Of course as I'm sure you know Interkarma there is no dimming for any pop-up messages in classic. I've been generally leaving it in place in DF Unity because I assume you put it in because you like it, but I don't know if you have anything decided about it. For this case at least I think it looks better without.
> Refinements to court screen/arresting

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
I noticed a dialogue bug when switching from the "Where is -> Person" to "Where is -> Location". The root cause the variable "inListboxTopicContentUpdate" remaining true after the player asked "Where is -> Person". I rearranged when the variable is set to true to solve this issue.
Relatively small fix, but I'm still getting used to the codebase :)
> Fixed a talk window bug

- Assets/Scripts/Game/EnemyMotor.cs
My earlier fix in https://github.com/Interkarma/daggerfall-unity/pull/657 included removing a limiter on the AI decision code that timed it to classic's slower update rate, but doing so made bow attacks way too rapid. This fixes it by putting it back for the ranged attack (while also avoiding the earlier problem that was the reason I removed it).
> Fix enemies shooting bow too much

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
Player can now choose "Not Guilty" and try to debate or lie.
Time is now passed for prison sentence (still no prison screen).
Flags set for execution/banishment. (No effect yet. They are supposed to cause guards to spawn when player enters a settlement in that region from then on)
Messages positioned correctly.
Unfortunately, the pause at the end when returning the player from the court screen seems to be even longer now (perhaps because of raising time for the prison sentence). People will probably think the game has frozen so this needs to be fixed. Any ideas?
> Progress court screen

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Adds Thieves Guild and Dark Brotherhood bribing judge.
- Fixes enemy-clearing method I added last time (it should have been destroying the game objects)
- Addressed a couple oversights in classic. The player should always be healed and get their reputation partly repaired if they are found not guilty now.
> Add TG and DB bribing judge, and fixes

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Enemy spell lists and a setup for assigning spells to enemies, same method as classic. Nothing is actually assigned yet.
The spell lists are the same as in the executable (although they are each terminated by `0xFF` there), just arrays of bytes that are the spell IDs.
> Preparation for assigning enemy spell lists

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/LevitateMotor.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs.meta
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/WeaponManager.cs
In this commit, all the code related to changing the player's speed is migrated to a separate class PlayerSpeedChanger.  All references to the module-level variables, constants, properties, constants, and methods have been copied and pasted to the new class.   All classes that reference the speed-related members and methods of PlayerMotor.cs (including code within PlayerMotor itself) have been updated to use PlayerSpeedChanger.  I tested it and fixed all null references.
I didn't notice any difference in gameplay with this commit.  Was wondering if it will make your task of rewriting PlayerMotor simpler?
This commit doesn't include the changes from the HeightChanger.  I used Github to see if the branches could be automatically merged and it showed no conflicts so I assume this won't …
> Migrate Speed Changes from PlayerMotor to PlayerSpeedChanger

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
Very minor PR. Just fixes a spelling error and uses the faction enums in a few more spots.
I started to go through the code looking for anywhere that faction IDs were used as numbers, but I wasn't sure of an effective way to search for that, and I came across usage of faction IDs defined within guild files, such as the factionID defined within the `ThievesGuild` class. I just left that alone, but I'm using the enums for the code I write.
> Use a few more faction enums

- Assets/Scripts/Game/Entities/PlayerEntity.cs
~1) Problem with player taking damage from guards if they surrendered while being hit nearly simultaneously by 2 or more guards should be fixed.~ (Removed, still seems to need work)
2) Implemented guards spawning for player with a low legal reputation or who has been banished. Behavior is the same as classic. (Actual spawning behavior of guards is still different, still need to implement LOS-check-based spawning)
> Guard improvements

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
- Assets/Scripts/Utility/QuestMacroHelper.cs
- Assets/StreamingAssets/Quests/A0C00Y12.txt
- Assets/StreamingAssets/Text/ConversationText.txt
- rumors get removed correctly on quest decline now (one part of the bug report in http://forums.dfworkshop.net/viewtopic.php?f=24&t=1002&p=12092#p12092)
exception handling for the reported exception as well - TODO: still have to find out how "tell me about" entries could stay on the list after quest has finished
- npc reject message is now a random msg from text.rsc like in classic when first approaching npc, second time is "you get no response"
- question's answers take into account reputation with the npc now (similar to greeting msg)
- implemented guild member greetings, added macro handlers for %fnpc, %fpc, %fpa and %hnr
- work/questor list is now saved with conversation data
- fixed merchant missing book quest
> Talkwindow - progress and fixes

- Assets/Scripts/Game/DaggerfallExteriorAutomap.cs
- Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
now filtering by factionId of building to show them when player is in guild and thus have them marked on the map
map marking also happens now directly when joining guild in same town - you don't have to reenter the city/town
only shows the tg, dbh guild nameplate when player has joined them
due to the new filtering this had to be handled specially
> thieves guild and dark brotherhood guild buildings are revealed again 

- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Internal/PlayerGPS.cs
exterior automap nameplate filtering mechanism is now working as before when we checked for "Residence" string but now via "isOverrideName" field in DiscoveredBuilding struct (translation safe)
check is: 
`if (!RMBLayout.IsResidence(buildingSummary.BuildingType) || discoveredBuilding.isOverrideName)`
only thing to know is that player has to leave and enter town when loading an old savegame to make the new mechanism work with old savegames. no problem with newly created savegames though
> nameplate filtering mechanism reworked

- Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
tg and dbh guild halls are now also correctly discovered when loading a interior savegame and getting promotion in interior and then leaving building
had to introduce new event in StreamingWorld class:  OnAvailableLocationGameObject so that GameManager.Instance.StreamingWorld.GetCurrentBuildingDirectory() will return the building directory and not null
initially I though existing OnCreateLocationGameObject(dfLocation) event would work but it turned out that it is fired too early (inside the function creating the gameobject, but gameobject is assigned outside afterward)
not sure if OnCreateLocationGameObject should do what OnAvailableLocationGameObject does now but I didn't want to break existing stuff.
> tg and dbh guild halls discovered when loading a interior savegame and getting promoted

- Assets/Scripts/Game/UserInterface/MultiTextBox.cs
- Assets/Scripts/Game/UserInterface/TextBox.cs
TextBox numeric mode only allows positive numbers (I assume this is what's required by classic) but mod settings have keys which allow user input for negative numbers and decimals (specifically _TupleFloatKey_ and _TupleIntKey_). 
So i added an enum property to texbox to safely receive also minus and decimal mark when required. Default option is _Natural_, which is current behaviour. Interkarma are you ok with this? If you prefer, i can replace entirely _isNumeric_ flag with a _None_ option.
> Optionally allow TextBox to receive negative or floating point numbers

- Assets/Scripts/Game/Questing/Actions/AddDialog.cs
- Assets/Scripts/Game/Questing/Actions/DialogLink.cs
- Assets/Scripts/Game/Questing/Item.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
- Assets/Scripts/Utility/QuestMacroHelper.cs
- Assets/StreamingAssets/Quests/A0C00Y12.txt
- Assets/StreamingAssets/Text/ConversationText.txt
talkmanager now can handle multiple resources with same name (e.g. named residence in local and remote town sharing the same name, persons with same name) - the residence case indeed happened
fixed a bug where place quest resource would not show up in "Where Is"->"Location"->"General" group in talk window when quest place was in remote town
Note: running quests from savegames are likely broken since dictionary key is now Symbol.Name instead of caption name
> talkmanager now can handle multiple resources with same name, fix remote quest locations talk stuff

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
according to your example I implemented all remaining windows that benefit from toggle behavior, hope you find this better now ;)
furthermore I fixed status info messagebox bug, status hot-key proceeds messagebox now as implemented in vanilla daggerfall, enter key will proceed, escape key will close messagebox immediately
also status hotkey will now proceed messagebox as convenience feature
hotkey toggling implemented for remaining windows:
- character sheet
- log book
- automaps
- travel map
- rest window
- transportation window
> status info messagebox fix, hotkey window toggling for remaining windows implemented

- Assets/Scripts/API/Save/DiseaseOrPoisonRecord.cs
- Assets/Scripts/API/Save/GuildMembershipRecord.cs
- Assets/Scripts/API/Save/GuildMembershipRecord.cs.meta
- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Imports guilds from classic, including rank and time of last rank change.
The only used guild value I know of that is not imported is one that seems to be involved in guild promotions and rewards.
@ajrb I had to make a couple guild-related methods public so I could access them, I hope that's alright with you. Also I had to do some conversion work to match to the days-since-promotion that you're using. Classic goes by minutes. (As far as I have seen classic always uses minutes for game time related calculations)
> Import guild memberships from classic

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CameraRecoiler.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Prison screen implemented
- Fix to not allow using ESC key to cancel court window or court message boxes, which would mess things up as it wasn't set up to handle it
- Fix to prevent camera recoil when leaving court screen
Also, although it's not in classic, I added a "cheat" key to speed up the day countdown by holding down ESC, which is nice to have while testing if nothing else. I don't know how hardcore people want to be about actually having to wait through the prison sentence.
Interkarma, is there a good way to change the color of text? The text on the prison screen should be different from the default color, as in this screenshot.
> Court screen updates

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
RestoreConversationData now checks for quest resource entries and rumors of orphaned quests (that are no longer running) and removes them
additional checks should prevent some issues I found when above mechanism would not be in place (double net mechanism)
> ConversationData.txt - fixes for old savegame format issues - should fix most of the problems

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
if wanted I will investigate if it is possible to only close regional window when in regional view - currently escape closes travel map window completely when in there
but this is more complex than thought at first glance
> escape key now closes travel map window correctly

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
This is a continuation of my work on the "work" functionality in TalkManager.
I used a separate dictionary because 1. The block structure for castles/dungeons is different than towns and 2. the process of looking for work in a castle is simpler. There's no "work" dialogue in classic for castle questors so an NPC list doesn't need to be pre-populated.
> Add ability to get work inside castles

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/API/Save/SaveVars.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
I finally got through this massive function for handling the background events that set region flags for things like wars, etc., along with changes to faction power caused by this. This is also the basis for non-quest rumors and messages on the town sign boards, which are created by these events (I haven't implemented that).
This follows classic very closely, plus fixing the usual bugs/oversights.
There's one part that seems to be an oversight that I may visit again later. There's a section of data that I found was a list of the bordering regions of all the game's regions (including the "Bjoulsae River" region that isn't in the final game). It's used rather oddly in connection with the other regions that regions will go to war with, because the order doesn't match the region order from …
> Mostly finish up region and faction conditions

- Assets/Scripts/Game/Utility/PopulationManager.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Allow custom scale for wandering npcs as discussed on forums.  Instead of using raycast as previosly said, i left position of parent gameobject with Motor as is, and moved child gameobject with billboard meshrender via transform. This doesn't affect small variations so behaviour with original graphics is unaltered.
> TextureReplacement: read scale from xml (MobilePersonBillboard)

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Utility/BuildingNames.cs
- Assets/StreamingAssets/Text/ConversationText.txt
- implemented "Where am I?" question/answers 
- trimming castle names read from text.rsc when last character is '.' (change to Assets/Scripts/Utility/BuildingNames.cs - should be ok, but pls take a look - I did this because I think it is an improvement since palace name would often break sentences with this '.', discovery system discovers castles without problems after this change - nameplates no longer contain the '.' character as well)
- special npc "where is" answer about location/person topic if in location:
-- for building asked about that is the same building where the npc talk partner is in: npc always knows he is in the very same building and gives special answer now
-- for quest person "where is" answer if npcs knows about person there is also a specific answer if npc is in same …
>  implemented "Where am I?" question/answers,  special npc "where is" answer in same location

- Assets/Scripts/Game/Questing/Actions/StartQuest.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
I've changed the start quest action to pick up quests in the following order
1) Any classic quests in /Quests folder.
2) Any init quests registered by quest list.
3) Any quests in same folder as an init quest.
4) Any guild quests registered by quest list.
5) Any social quests registered by quest list.
> Extend start quest to load from quest packs

- Assets/Scripts/API/DFLocation.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Changes RMB block loading to work in the same manner as classic. This shortens the code and removes the need for special cases for "CUST" blocks.
Along while doing this I identified 2 more bytes of the exterior data, including the one used for the message you get when you try to buy a ship in a location that is not by water.
> Load RMB blocks like classic, add "not a port town" popup

- Assets/Scripts/Game/FadeBehaviour.cs
- Assets/Scripts/Game/HUDFlickerMask.cs
- Assets/Scripts/Game/PlayerDeath.cs
Edits FadeBehavior.FadeHUDToBlack() to have fadeStartColor = a blood red color and fade that to black instead of clear to black.  I tested it in the game and it looks better than the inconsistent behavior that occurs that when you get hit and no flash of any sort occurs and it just fades to black.  Try it out.
> Make death of player show red

- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Player/CameraRecoiler.cs
- Assets/Scripts/Game/Player/HealthChangeDetector.cs
- Assets/Scripts/Game/Player/HealthChangeDetector.cs.meta
This commit takes health change detection code from CameraRecoiler and abstracts it to a new class "HealthChangeDetector" and makes it a component of playerAdvanced.  No Functionality changes.
This will allow easier modding for mods related to changes in Player Health, and other future functions.
Also, one additional Entity property is added to DaggerfallEntity, which allows shorthand way to get the current percentage of max health left of that entity.
This will also be used by the Near Death Experience code.  I figured it's better to make the code available for re-use rather than retype the same code in any new code that requires it.
> Abstracts HealthChangeDetector

- Assets/Scripts/Game/TalkManager.cs
fix for bug report #116: NPC dialogue loops in Daggerfall (fix for unhandled (new?) quest location type)
rumor mill creation fixed (it could happen in the past that only quest rumors got created without generic rumors)
> fix for bug report #116: NPC dialogue loops in Daggerfall, rumor mill creation fixed

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
Implements reputation propagation based on reversing classic code. This is a response to http://forums.dfworkshop.net/viewtopic.php?f=19&t=910 but.
This does not yet 100% replicate classic behavior for quest rewards, just the propagation part. I used http://en.uesp.net/wiki/Daggerfall:The_Infested_House as a test case. In classic the quest reputation reward seems to be given based on the faction ID of the NPC quester, in this case faction 846 ("Questers"), the ID for the NPC in a knightly order who gives quests. DF Unity appears to instead be using the faction ID of the knightly order. This causes a different propagation and different results.
Would it be an easy fix to assign the faction ID of the NPC clicked on rather than of the faction itself? I don't know if that is how it works for …
> Implement classic reputation propagation

- Assets/Scripts/Terrain/DefaultTerrainSampler.cs
- Assets/Scripts/Terrain/NoiseTerrainSampler.cs
- Assets/Scripts/Terrain/SimpleTerrainSampler.cs
- Assets/Scripts/Terrain/TerrainSampler.cs
TerrainSampler implementation extended - reason: mods may need terran height scale (e.g. Distant Terrain mod)
new property MeanTerrainHeightScale and new method TerrainHeightScale added
default use is fixed terrain height scale factor - set MeanTerrainHeightScale in constructor (SimpleTerrainSampler, NoiseTerrainSampler, DefaultTerrainSampler)
more sophisticated use: terrain height scale factor depends on map pixel position - override for method TerrainHeightScale(x,y) happens in this case (used by Distant Terrain Mod's Improved Terrain Sampler)
>  TerrainSampler implementation extended

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerBase.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerBase.cs.meta
- Assets/Scripts/Game/UserInterface/HUDFlickerController.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerController.cs.meta
- Assets/Scripts/Game/UserInterface/HUDFlickerFast.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerFast.cs.meta
- Assets/Scripts/Game/UserInterface/HUDFlickerSlow.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerSlow.cs.meta
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
This version is greatly simplified and cleaner.  Also includes a setting in Advanced Settings window to toggle the effects off.
When the player is reduced to < 40% health.  they will experience a flashing red flicker effect.  If < 20% health, the player fades in and out of darkness until their health is raised above 20% threshold.
> Near death experience simplified

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/MobilePersonMotor.cs
Mobile Town NPCs now won't stop if your weapon is drawn.  
Also makes TODO note for other NPC stop conditions:
**Conditions to do in future:**
Player is in beast form.
Player just got caught committing a crime
Player is invisible.
> NPCs don't stop if weapon drawn

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Guilds/MagesGuild.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
If the player has the NoRegenSpellPoints career property set to true:
->Spell points no longer recover when resting.
->Rest until fully healed doesn't require full magicka.
->The player can recharge spell points at mages guild by clicking any service like in classic.
@Nystul-the-Magician The TextProvider ID is needed for following messages so they can be used in TextProvider.GetRandomTokens.  Do you know the ID?
-> I see your magicka is low. You sorcerors really need to be more careful. Here, let me recharge you.
-> It is customary for the guild to recharge the magicka of sorcerors.
msgbox.SetText is used as a makeshift solution until the GetRandomTokens approach is used.
> Sorceror Magicka restrictions and mages guild benefit.

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
- Assets/StreamingAssets/Tables/QuestList-Classic.txt
- Simplify code, thanks to Allofich for implementing as classic and removing guesswork.
- Works from guild faction ids rather than questor npc id.
- Fixes classic bug with knightly orders where rep isn't propagated to children of generic order.
- Fixes classic bug with knightly orders where rep is doubled for generic order when performing non-member quests.
- Keeps classic behaviour of not propagating for a specific knightly order. I assume due to all affiliated nobles being aloof from such matters, but this is easily changed if we want.
> Re-work classic DF rep propagation algorithm

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs.meta
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs.meta
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Upgraded ItemListScroller component to be flexible for use beyond inventory UI window.
- Fixes column swap issue when scrolling to end of lists with odd numbers of items.
- Implemented the basic buttons, item scrolling and movement for both potion and item maker UI screens. (You can't actually create potions or enchanted items yet)
- These are now prepared for when the effect system is ready to enable their functionality.
I'm really happy how the ItemListScroller handles item display, once I upgraded it the potion screen was really easy to do.
> Potion maker & Item enchanter basic implementation

- Assets/Scripts/API/BsaFile.cs
- Assets/Scripts/API/Save/SaveGames.cs
This implements reading `MAPSAVE.SAV` from classic saves and discovering the locations marked within it as discovered.
Although it works correctly, unfortunately it is extremely slow and will take around 2 or 3 minutes to load a classic save. Interkarma, I'm hoping you will know where the bottleneck is.
> Import discovered locations from classic saves

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Utility/EnemyBasics.cs
This implements enemy AI behavior for when the player has the Invisibility, Shade or Chameleon effects active, in a manner similar to classic.
Spells for these, etc. are not added by this. But you can test the behavior by setting the flags `IsInvisible` `IsAShade` or `IsBlending` in `PlayerEntity`. The effects are dispelled if you do damage to an enemy, the same as in classic.
Invisibility should work identically to classic (except for the "giveUpTimer" as I explain below). For shade and chameleon, though, the behavior differs. This is because, if I understand correctly, these effects are pretty much useless in classic. This is because as soon as an enemy has detected the player during one of its constant updates, they then see the player for the remainder of their "giveUpTimer" (as it's …
> Implement illusion effect behavior and adjust stealth detection

- Assets/Scripts/Game/Player/AcrobatMotor.cs
- Assets/Scripts/Game/Player/HeadBobber.cs
- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/PlayerFootsteps.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Go ahead and give a try.
Includes integration with swimming speed, skill usage, skill tally.
The horse can be mounted/unmounted while swimming. Slight boost to height when mounted.
Known bugs:
When loading a save game, the height is sometimes wrong but can be fixed by crouching once or twice.
Not done yet:
- No footstep change for swimming yet. 
- Will adjust headbobber to bob differently for swimming.  
- Need to adjust EnemyMotor to keep non-flying enemies from going on water tiles.
> Height changer adjustments and partial swim implementation

- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
players can wedge themselves into a slanted wall and climb up and kill themselves by triggering the overhead player crush check.  This fixes it by doing the folllowing:
Disable player crouching while climbing.
Disable Climbing while player crouching
> Fix Crushing bugs

- Assets/Scripts/GenerateDiagLog.cs
This will enable logs to be written even when the game dir is installed
in a system dir.
> Move env log to persistent data path

- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/API/Save/SaveTreeBaseRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
This does a few things:
1. Identifies and imports time-limit data from items created with the "Create Item" spell in classic.
2. Items with a time limit will be removed when the time limit is reached. Note this doesn't happen in classic (items created with "Create Item" never disappear, despite the fact that you can set duration when creating a Create Item spell) due to a mismatch in the flag set and the flag checked. (Byte 43 of the itemRecord is ORed with 0x10, but what is checked for 0x10 is byte 21 of the base record. If you manually set that classic then will remove the item when the duration runs out.)
3. Fixed a bug with unequipping broken weapons. It relied on `GetEquipSlot()`, but for weapons that can be equipped in either slot (one-handed weapons), it would return the unequipped …
> Import and handle expiring items

- Assets/Scripts/Game/SongManager.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1039&hilit=music and https://forums.dfworkshop.net/viewtopic.php?f=24&t=860 (except for the holiday text part).
You can reproduce the problem by doing the following:
1) Start Daggerfall Unity and load a saved game in an exterior
2) Load another saved game in an interior (building or dungeon, doesn't matter)
3) Observe that outdoors music is playing
The problem occurs at the code deleted by this PR, in `Update()` in `SongManager`.
```
if (StreamingWorld)	
{	
if (StreamingWorld.IsInit)	
return;	
}
```
It seems to be that the order of how `StreamingWorld.suppressworld` and `StreamingWorld.init` (both booleans) have been set is involved with the problem. If you load straight into a dungeon save, `StreamingWorld.suppressworld` is true …
> Fix music not updating when loading interior saves

- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/LootTables.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
Creation of magic items in loot (treasure piles, enemy equipment, house containers). Everything should be the same as classic except for the gold value of the items, which I still need to figure out (they'll just have the value of the non-magic versions for now). The magic item stats use the data read from `MAGIC.DEF`.
Also still need to do stocking of magic items by magic item merchants. (would be a separate PR)
> Implement creation of magic items in loot

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/UserInterface/HUDVitals.cs
- Assets/Scripts/Game/UserInterface/VerticalProgressSmoother.cs
This one is a really important fix: Fixes bug introduced by the indicator bars.  Because the property call in DaggerfallHUD for updating the breath bar was discarded in favor of updating the breath bar in the vitals class (to be consistent with the other vitals updating in the class), the SetRemainingBreath method was overlooked, which does more than set the amount, it sets the color of the bar according to the percent left. **Which causes the breath bar not to appear.**  Now the code properly sets the color and the breath bar appears.
Also Fixes bug identified by @Allofich , namely, if you load a game from swimming in a dungeon, you continue at swim speed.  Now the code checks to make sure the player is not on a water tile before clearing the swimming flag.
Also refactors code in the …
> Swimming bug fixes

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Also fixed up list of enemy soul points and added that to enemy definitions.
When magic merchants stock soul traps with souls in them, it's a random selection from 0 through 42.
As far as I can see, there is nothing stopping it from choosing the unused "Horse" or the dragonling with 0 enchantment points. Since other 0-value animals can also be chosen I added a "Horse" stub to the enemy list to allow for the soul to appear. Not sure if we should allow those or not.
However, when an item with a soul bound to it breaks, the stored enemy is supposed to spawn. I assume classic probably crashes or something if an item with a horse soul breaks, so if we allow horse souls we'll have to account for that. We should account for that anyway in event somebody imports a classic save with an item with a …
> Match magic item merchant stock to classic

- Assets/Scripts/Game/Player/VitalsChangeDetector.cs
- Assets/Scripts/Game/UserInterface/HUDVitals.cs
- Assets/Scripts/Game/UserInterface/VerticalProgressSmoother.cs
Overall better interaction between indicator bars and base bars.  If you heal after or before you take damage or heal damage, the bars appear where you'd expect, and won't hide each other except in special cases where you heal completely after losing, then the gain bar will cover the loss bar.  If the player heals while the gain is smoothing, the bar will make a briefer pause than initial pause before continuing to smooth again.  and same goes for loss bar when taking damage repeatedly.  Also refactored the code.
> Vitals fixes

- Assets/Scripts/Game/UserInterface/HUDFlickerBase.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerController.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerFast.cs
- Assets/Scripts/Game/UserInterface/HUDFlickerSlow.cs
When setting breakpoints during the flashing and flickering, the amount of alpha can go past the intended amount because of more time passing due to taking more time to process the breakpoint.  If someone had a slowdown in their computer, this could also happen.  Their player's screen can end up permanently red.  This update fixes that.  Also, fixed some redundancy in code logic and simplified it.
> Fix and clean flicker

- Assets/Scripts/Internal/DaggerfallActionDoor.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=765.
Doors that were mid-open when a game was saved will not play the open sound again when that game is loaded, and they will only open as far as they are supposed to.
Currently in master the "durationScale" that is supposed to make doors only rotate for the remaining duration was only affecting the "time" of the rotation, meaning how fast the door rotated, but not how much it actually rotated.
> Fix doors incorrectly rotating on load

- Assets/Scripts/API/ItemsFile.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/ItemEnums.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=678.
The only check classic does for whether to open the book screen when doing `USE` in the inventory on an item is whether it is in group 7, the books group. Changing DF Unity to also just check this solves this issue.
Also made various fixes to the item template enums that were mixed up and causing some issues. (For example, a book in classic can have group index 1 through 4, which I think is supposed to be for different quality books, but only one of these is "book" in master, causing the books imported from classic to fail)
The changes to the enums are all from data in the .EXE (I found where they are listed) so they should all be correct.
Also included latest ItemTemplates.txt and MagicItemTemplates.txt since these are …
> Fix books from classic saves to open

- Assets/Scripts/API/Save/SaveGames.cs
- Assets/Scripts/Editor/SaveExplorerWindow.cs
- Assets/Scripts/Internal/PlayerGPS.cs
My previous code to import MAPSAVE data from classic saves (https://github.com/Interkarma/daggerfall-unity/commit/fd988d9b12c4ae3cbae5e48ef30f85924f843d9f) is causing Save Explorer to fail with a null exception if you try to open it without the game running in the editor. This happens because `PlayerGPS.dfUnity` isn't instantiated.
We could instantiate it, but I noticed that the MAPSAVE import makes a noticeable delay in Save Explorer as all the up-to-six saves are processed. Since Save Explorer doesn't do anything with that data yet anyway, I just disabled the import for Save Explorer. Ideally the import should be optimized, but I don't know how complex of a fix that would be.
> Fix Save Explorer not opening if game isn't running

- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=936.
Also imports used hand from classic saves.
Existing DF Unity saves will be loaded as if the right hand was being used. Saves made after this PR is applied will load with the correct hand.
> Handle used weapon hand for save/load

- Assets/Scripts/Game/LevitateMotor.cs
- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/UnderwaterFog.cs
- Assets/Scripts/Game/UnderwaterFog.cs.meta
- Assets/Scripts/Internal/DaggerfallSky.cs
- Assets/Scripts/Utility/CameraClearManager.cs
- Implements a smooth underwater fog,  if the player is partially underwater, the fog fades partially in, until the camera is under.  This eliminates the blinking sensation that happens when exiting/entering water.
- commented out a toggle for global fog because it was there to fix an issue with solid camera clear not working in Unity 5.5 because we're not unity 5.5 anymore, and it was preventing underwater fog from working.
- The player will no longer toggle crouch while using crouch key to swim down if player is in water.  Also, if player enters water and is crouching, will automatically stand.
- In some situations, the player could be stuck in the water while levitating.  This simple change allows the player to exit the water if they are levitating.
> Swimming improvements

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/EnemyBasics.cs
This one is a nice improvement. I figured out how to read the `.ANC` files in `MONSTER.BSA`, which define the frame sequences of animations and frames on which damage attempts or arrow shots occur, and probabilities for different frame sequences. I added this information in to the enemy definitions and use it now for enemy attack animations. This allowed me to remove the "hit frame" stopgap solution I put in earlier. In removing that I needed to adjust the calculation for attack timing, and that ended up with raising the distance from which enemies will attempt attacks. It could still use refinements but it makes enemy attacks less predictable and IMO more realistic, and makes it not so easy to just mow them down and never get hit by melee attacks. (Although the game may be tough in the …
> Match enemy attack animations to classic

- Assets/Scripts/Game/EnemySenses.cs
Since I allowed enemies to detect the player through walls with the stealth check (check between the player and the enemy's stealth stats), they are detecting from a little too far away. Someone who did a video on YouTube was wondering if the game was bugged. Adjusting it down to the value in this PR seems to help for now. In classic the actual stealth check uses a distance of 1024 but I think it's also limited by the distance of enemies before they are unloaded, which I don't fully understand but I think is around 768 in interiors (1024 in exteriors).
> Shorten enemy stealth check range

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/RDBLayout.cs
- Assets/Scripts/Utility/RandomEncounters.cs
- Assets/StreamingAssets/Text/GameSettings.txt
This implements the issue raised in https://forums.dfworkshop.net/viewtopic.php?f=24&t=560, which was closed as "intended". It should also address the issue raised here: https://www.reddit.com/r/daggerfallunity/comments/96pmzc/the_enemies_in_daggerfall_unity_are_way_off_and/
Classic selection is enabled by default. Previous random selection can be turned on by enabling "Alternate Random Enemy Selection" at the startup screen. (except the alternate, undead-heavy cemetery list for DF Unity is commented out and classic's list is being used now)
Basically how it works: As you know, there are `RANDOM MON` markers that make random enemies and `MONSTER` markers that make fixed enemies. Random enemies, though, are not completely random in classic. Most seem to have a value set in their "flags" …
> Recreate classic way of choosing random enemies

- Assets/Prefabs/Scene/DaggerfallEnemy [Game Serializable].prefab
- Assets/Prefabs/Scene/DaggerfallEnemy [Standalone].prefab
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
Things this does:
- Implements classic melee timer
- Fix what seems to be oversight in classic where higher speed enemies would instead attack less
- Implements reflexes as in classic. This is in classic, too, but like so many things does not seem to work correctly (I swear, it's like they purposely left the game with a random thing missing/reversed, etc. in every game mechanic so we'd have the fun of patching the holes), because the value it refers to in the enemy object data seems to always be 0 and is not ever set by anything, so no matter what reflexes setting you choose it seems enemies attack at "very high" reflexes in classic. Luckily, although having this correctly refer to the reflexes setting slows down attacks at, for example, the "average" setting of 2, I think the above fix …
> Implement classic melee timer and reflexes

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Seems that at some point we changed from storing region IDs of factions from 0-based to 1-based. Maybe I had something to do with that, I don't remember. This was causing an IndexOutOfRangeException in RegionPowerAndConditionsUpdate(), which subtracted 1 from the region ID because I wrote it assuming the newer, 1-based behavior.
This PR fixes this issue by returning to using 0-based, fixing 1-based saves to be this way. Alternatively we could make them all 1-based, but I prefer 0-based for a few reasons:
1) Classic also converts the 1-based region IDs in FACTION.TXT to 0-based internally, and saves them this way in SAVEVARS.DAT. If we decide to import those region IDs from SAVEVARS.DAT (we aren't now), it will be more straightforward to use the same values.
2) Using 0-based allows me to …
> Fix out-of-bounds array access in older saves

- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/RDBLayout.cs
Should fix https://forums.dfworkshop.net/viewtopic.php?f=24&t=1227, in as much as it generally matches the range to classic.
This could maybe be tidied up a little but I wanted to get it in before the release which is probably upcoming.
Background of the issue:
In classic, enemies can detect the player without having LOS, through walls, etc., depending on a roll against the player's stealth skill. This is why they sometimes open doors and come out of rooms at you, etc. I implemented this a while ago but not the correct range at which the check should happen. Enemies were approaching the player from a lot further than in classic, and enemies weren't being found in their expected spots in Privateer's Hold, etc. This may also have been making it more difficult to find a spot away from …
> Match non-LOS sense of player to classic

- Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsEditorWindow.cs
* Store mod that is being edited for the next session.
* Make save on exit without confirmation optional.
* Fixed an issue which could cause new values to be stored incorrectly to presets if added to settings and immediately saved without a "refresh".
> Improvements for mod settings editor

- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/HeadBobber.cs
- Assets/Scripts/Game/PlayerMotor.cs
Fixes all known bugs with climbing, including falling when climbing a long wall out of the water.  Slips are no longer meaningless.  Implements a skill check system like the system described in UESP for classic DF.
Player now has a chance to climb successfully, a chance to slip, and a lower chance to regain hold and continue climbing.  All chances can be offset by having a high skill in climbing.
70% base chance of success for continuing to climb per skill check.  A player with 50 climbing skill would boost this to 85% and 75 would boost to 92.5%
20% base chance of regaining hold (at 37% of climbing skill check's wait time).  a player with 50 skill would boost this chance to 60%, 75 skill boosts it to 80%
As an added bonus, once the player is climbing, they can swivel around and look in …
> Climb update

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsData.cs
Initially mod settings file was named _modfilename.ini.txt_, then was changed on Lypyl suggestion to _modsettings.ini.txt_ to avoid breaking if mod filename was changed. It's been a while since we moved from plain textboxes to a json-based window with typed controls, so i think it's time to remove support for the oldest one.
I'm confident no mod is using it but tell me if i'm wrong,  I want to be sure not to break any existing mod  :)
I'm not in a hurry to stop supporting _modsettings.ini.txt_, but i slightly changed the log message printed during the automatic local upgrade to reflect this change.
> Remove support for obsolete modsettings format

- Assets/Scripts/Game/EnemySenses.cs
Always reset to false first in case the player teleports from being nearby
enemies to not being nearby enemies.
> Prevent classic spawn check result getting stuck

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/Player/AcrobatMotor.cs
- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
Implements a toggleable, true by default advanced climbing system.
4 directional climbing, the ability to pause climbing, Look around in any direction.
The ability to jump off a wall when climbing, onto another wall (skill check required).  Can also initialize a climb by jumping from the ground onto a wall with a skill check.
Known issue:  The checkbox setting on the gameplay section of the advanced settings page is out of margin, but still clickable.
> 4 Directional Climbing and jumping to and from walls.

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/EnemyBasics.cs
I noticed that there were still several issues with enemy animations, but I think (and hope) this should resolve all the problems.
1) Enemy female thief has a small animation frame in the idle animations when looking diagonally. There used to be a fix for this but I removed it in https://github.com/Interkarma/daggerfall-unity/pull/483 because I noticed the female thief being stretched too large when attacking diagonally. The old fix was for all diagonal animations but it's only the idle animations where the problem is. Also, better than stretching the sprite as the old fix did, there is a correct-size diagonal idle, misplaced among the hurt animations for some reason. Now that is used and it looks correct in-game.
2) In that PR I also removed a fix for the rat, because I noticed it being …
> Fix enemy animations

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
- Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsEditorWindow.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
- Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs
- Assets/Scripts/Utility/Table.cs
This PR aims to provide a standard localization interface for mods.
A mod called **modname** is automatically linked to a file named **mod_modname.txt** in _StreamingAssets/Text_ and/or a file name **textdatabase.txt** inside the mod bundle. The table in _StreamingAssets_ takes precedence.
The file **settings.json** bundled with a mod provides informations used by the mod manager to draw controls in the mod settings window and store values to a local file. This includes setting names and descriptions/tooltips. These text string are seked automatically in the language table using the following patterns:
```
Mod.Description
Settings.SectionName.Name
Settings.SectionName.Description
Settings.SectionName.KeyName.Name
Settings.SectionName.KeyName.Description
Presets.PresetTitle.Title …
```
> Support for mod localization

- Assets/Prefabs/World/SongPlayer.prefab
- Assets/Scripts/Game/SongManager.cs
This recreates classic music selection when playing with a General MIDI midi device, since we were so close to it already. I did notice one video on YouTube where someone remarked that the music in Privateer's Hold was different from classic, but it matches with this PR, as should all dungeons.
The music played when in exteriors or taverns is determined by the game day. So a particular date in the game always plays deterministic songs. Temples play a song determined by the faction of that temple. Dungeons play songs depending on a value only being referred to so far as "Unknown2", and the region number they are in. If you load a classic save and compare importing it to DF Unity, you should have the same music playing in all cases, except when it's snowing and possibly when at night or …
> Implement classic music selection

- Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsEditorWindow.cs
- Assets/Scripts/Utility/Table.cs
Continue #873 using string literals introduced in 9d1502c06a5f67f369bdebd01c0660c08e84dbb6.
> Mod localization: use string literals in exported table

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Guards currently spawn outside the shop due to min spawn distance I think. I like this in one respect that you can't simply flee to the exit and escape like you can in classic, but it does feel like you are getting away with stealing until you leave and see the dozens of guards waiting for you...
Allofich, can you check the formula I added please? I took it from chronicles.  PlayerEntity.SpawnCityGuards() needs more work, as you probably already know.
> Implement shoplifting

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
This PR sets things up for you to implement poisons.
First, what this PR does:
1) Enemies have a chance to get poisoned weapons (matched to classic)
2) Poison inflicted on weapon hit, resistances and saving throws to sop it (matched to classic with bugs fixed)
3) Poison infliction by drugs (matched to classic)
4) Console command to add drugs
5) Includes code for setting up poison properties (minutes until start, damage)
No actual poison effect is in, just a debug message.
There are 12 poisons in the game. 0-7 are weapon poisons, 8 through 11 are the drugs. I just referred to them with an `int`, but you might want to use an enum. In addition to the drugs, I found names in `FALL.EXE` that appear to match for the poisons, so we have a name for all the poisons. See the pseudocode below.
The …
> Framework for implementing poisons

- Assets/Scripts/Game/Guilds/Services.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
- Assets/Scripts/Game/Player/AcrobatMotor.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Also disabled jumping with cart which I always intended to do.
@Allofich It currently re-uses the same calculation for cost. However UESP states "Appraisers will buy magical items from any member who is at least a Filcher in the Guild. They offer higher base prices than other merchants. The final price for your items is affected by your reputation with the faction." This implies that the function will need guild rank to be passed instead of building quality. If you give me the equation for the formula I'm happy to implement it... you do seem to have a few plates spinning right now. :-)
>  Implement selling magic items at fence in TG 

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/PlayerDeath.cs
- Assets/Scripts/Game/PlayerFootsteps.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/SoundClips.cs
- Assets/StreamingAssets/Text/GameSettings.txt
On by default, but can be turned off. Happens a percentage of the time when melee attacking or being hit, both for the player and for enemy classes.
Male sounds are pretty straight-forward, with unique sounds for each race.
Female sounds were a mixture. Some sounds are duplicates, and some races only seemed to have attack sounds or only pain sounds. I spent a fair bit of time listening to the sounds and working out a solution that ends up working pretty well. It basically works out to humans, elves, khajiit and argonians as 4 groups, with various bits of crossover.
Just for the purposes of sounds, each enemy class is randomly assigned a race (Breton through High Elf), to add some variety. This isn't saved or loaded at the moment, and is just intended to be for that character's voice, not …
> Add race/gender attack and hit sounds

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemEnums.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
Uses an enum matched to the IDs that would be found from poisons on weapons in classic.
> Save and load poisons on weapons

- Assets/Scripts/API/BiogFile.cs
- Assets/Scripts/API/BiogFile.cs.meta
- Assets/Scripts/API/BiogFileMCP.cs
- Assets/Scripts/API/BiogFileMCP.cs.meta
- Assets/Scripts/Game/Items/ItemEnums.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/UserInterface/SkillsRollout.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharBiography.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharBiography.cs.meta
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharChooseBio.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharChooseBio.cs.meta
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharClassSelect.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
In classic, the quiz also generates the player's backstory that you can view with the History button but that's another PR's worth of work.
From the testing I've done I see that the granted starter items more or less work for all the classes' quizzes. I haven't tested it with custom quizzes so I don't know if artifacts will work.
I found one minor issue: selecting "a pearl" adds an emerald instead. The item enums match up with the arguments I'm passing to CreateItem but somehow the item that it fetches from the item template list ends up being an emerald.
> Biography quiz for new characters

- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/DaggerfallFont.cs
- Assets/Scripts/Game/UserInterface/ListBox.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
implemented font rendering with textlabel class for exterior automap - supports SDF font rendering now
there is one bug with tooltips - their text is not rendered if tooltip is too big for automap window (background is rendered though) - I am looking into this but it is a bit tricky - related to restrictedRenderArea but could not find the reason for it
hopefully  this pull request works - I tried to rebase before issuing it - this is my first try to rebase and had to create a new local branch since git would not allow me to push it into existing local branch - I don't understand it quite right - but it looks like it should be ok with only one commit now
> SDF support for exterior automap

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Previous fix for the small diagonal sprite was only fixing for the female thief. Other classes use the same textures and needed to be fixed as well. The check is now for the texture used and covers all the cases.
> Fix all enemy classes using female texture 483

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Resources/defaults.ini.txt
- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyHealth.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/EnemyBasics.cs
- Assets/StreamingAssets/Text/GameSettings.txt
This is one I was looking forward to doing, and although it could still do with improvement, mainly in enemy pathfinding, it works pretty well. Please give it some testing, though, as it touches a lot of things and could break something. I think I've fixed all the problems I encountered. There's a lot of raycasting going on but I've tried to avoid too much FPS drop.
I worked on this to prepare for the Sanguine Rose artifact, which allows the player to summon a Daedroth, but I ended up implementing an "enemy infighting" mode that I think is fun to play with.
What's in the PR:
1) Enemies now evaluate targets and choose one, instead of always targeting the player. (Unless "enemy infighting" is turned on, they reject all targets but the player. Later I intend to figure player allies into …
> Implement AI target selection and infighting

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Utility/RDBLayout.cs
1) Quest AI will no longer target or be targeted by other AI. This solves the issue for now but I think we should ideally allow for spawning quest AI that can also fight each other.
2) Expanded AI to target if it can see player, as it could before, instead of limiting it to the classic spawn range. This is because the spawn is pretty small vertically, and sometimes there could be enemies in plain view that wouldn't react. I don't really like tying the AI "activating" it's target-seeking according to having the player in sight, but it works well enough. I also tried just using a wider radius around the player but then enemies were fighting a little too much and killing each other out of view of the player so I settled on player LOS for now, which is what the old behavior before the …
> Misc. fixes

- Assets/Scripts/Game/LevitateMotor.cs
- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/FrictionMotor.cs
- Assets/Scripts/Game/Player/PlayerGroundMotor.cs
- Assets/Scripts/Game/PlayerMotor.cs
Fixes climbing teleportation upon hitting the ground.  Also makes you dismount wall when close enough to the ground.
Fixed bugs where rappel and grasp wall in air would still work even if disabled in settings
> Climb down from top2

- Assets/Resources/NameGen.txt
- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
- Assets/Scripts/Game/Utility/NameHelper.cs
Changes:
1) Painting author generation matches classic.
2) Change to name generation
- Name sets re-identified to what they appear to be in classic
= Khajiit names supported
= Imperial names moved in order to "Argonian" index, as in classic
= "Noble" is a monster type
NameGen.txt edited to match above and match ordering of `NAMEGEN.DAT`
- Name generation rules matched to classic
= Changes to Redguard and Nord names (end in "sen"), and monster names (including nobility titles)
- Should always be possible to get the same names as classic now as long as the same seed is provided to DFRandom.rand()
Notes:
- I'm not sure how classic picks monster names for quests. For now I set it to choose from Monster1 or Monster2, and not the nobility titles, which are in Monster3, since nobility titles …
> Match name generation closer to classic

- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
XMl files for scale of UI textures were only loaded from loose files location. Now they are also correctly loaded from dfmods.
> TextureReplacement: Fix xml custom scale for UI items

- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Scripts/Game/Player/AcrobatMotor.cs
- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/FrictionMotor.cs
- Assets/Scripts/Game/Player/PlayerStepDetector.cs
- Assets/Scripts/Game/Player/PlayerStepDetector.cs.meta
- Assets/Scripts/Game/PlayerMotor.cs
Fixes 2 bugs
Rappelling no longer happens if you step back off short heighted walls or objects.
Anti-bump gravity now is used when going down slopes, but not when walking off cliffs
Does this by Creating a small component class for playerAdvanced called PlayerStepDetector whose value is accessed by AcrobaticMotor and ClimbingMotor.  The component class detects what the player is about to step onto by measuring the distance of RaycastHit by SphereCast downward.  The origin of this ray is offset by the player Movement vector so it detects the distance to the floor that the player is stepping onto instead of the floor directly beneath.  The component class is for efficiency and code reuse, Like VitalsChangeDetector.  Kills two birds with one stone.  Poor birdies.  Good stone. …
> Motor fixes

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
Make IsStackable() even slightly more conservative about what can be
stacked, by not allowing quest items stacking;
That done, stacking no longer need quest items special handling (after a
FindExistingStack() fix, though).
I did allow stacking for "quest" money and standard money, because I
think some quests are paid that way in classic Daggerfall; But that may
be totally irrelevant in DFU.
It would be great to allow stacking potions, because non caster that
depend on potions can have quite a few in their inventory.
> fix: only stack stackable items

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/ListBox.cs
A graphical tweak that makes mouseover actions on list boxes highlight the text to help people see what they are clicking better, and worry less about if they're actually clicking on an item above the one they meant to point click.  It affects saved games list, spell list, talk topics, etc.  I think It turned out quite well.
I tested: Saved games list, spellbook list, Buy spells list, talk topics list.
> Highlight ListBox items with MouseOver events.

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/UserInterface/ListBox.cs
Now the highlight disappears when you aren't pointing at an entry.
Now the highlighted text on parchment background is slightly more readable through increased red value and the shadow of the text.
> ListBox quick tweaks

- Assets/Scripts/Game/Player/AcrobatMotor.cs
The minimum range for applying anti-bump gravity was too high and the max range is increased to 1.10f to compensate for adjusted minRange
> Fix St-st-st-stuttering bumps on gently rolling hills

- Assets/Scripts/Game/Player/AcrobatMotor.cs
Anti- bump was being applied while climbing dungeon walls, and made the player zip to the ground when slipping and climbing.
> Fix anti-bump being applied while climbing and slipping

- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
The knightly order code was still using +1 when checking the region ID, although the FactionData now subtracts 1 from the IDs from `FACTION.TXT` when importing (like classic does) and the +1 check is no longer necessary.
> Fix free room for member of region knightly order

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemySenses.cs
A while ago I set enemies to attack from somewhat beyond their actual range. I think I overdid it, though, and while watching a Youtube video I got the impression the player was learning to wait until the enemy swung, then run in and hit in the cooldown afterwards. That's not necessarily a bad thing, but I don't want enemies to be too easy to predict. This PR reduces the extra distance and also actually takes change of target position into consideration, so there shouldn't be enemies attacking from well out of range when the player is stationary, for example, something that I could see happen with the previous implementation (the one currently in master).
> Refine enemy attack range

- Assets/Prefabs/Scene/DaggerfallEnemy [Game Serializable].prefab
- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyBlood.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/EnemyBasics.cs
Here is the start of enemy casting.
Implemented:
- Enemies assigned spells and spell points like in classic
- Enemies shoot a ranged spell like in classic
Not implemented:
- Spell casting animations
- Touch spells
- Some additional AI logic present in classic (don't cast a spell while it is still active on the target, intelligent enemies may stop casting when target has reflected a spell)
I'm sending a PR now because there is an issue maybe you can help with. For some reason enemies only cast a single spell, then stop. The logic in EnemyMotor.cs is correctly continuing to select spells for casting but something is stopping any more than 1 from shooting.
I had to make a few adjustments related to `EntityEffectManager.cs`:
- The `IsEnemyEntity` was always failing, because everything but the …
> First pass at enemy casting

- Assets/Scripts/Game/Entities/PlayerEntity.cs
The comparison against -1 keeps the function from running on "Random Ruler", which has region of -1. (Regions of -1 in FACTION.TXT are the one exception that doesn't get corrected down 1 to become 0-based. This is already accounted for in the import.)
The problem was the
`regionData[regionID - 1]`
statements, written back when the faction IDs were 1-based. I think I only looked for `regionID + 1` when fixing these and didn't think to check for `regionID - 1`.
> Fix ResetWarDataForRegion using regionId - 1

- Assets/Scripts/Game/Guilds/GuildManager.cs
Unfortunately faction data has some erroneous entries that are marked as guilds (Knightly Orders) and don't match a valid Deity. This was happening when trying to talk to anyone if the PlayerEnterExit.factionID got set to one of these factions.
> Catch exception in GetGuild method and just log it as it can happen due to bad faction data.

- Assets/Scripts/API/BookFile.cs
- Assets/Scripts/API/FileProxy.cs
- Assets/Scripts/Utility/AssetInjection/BookReplacement.cs
- Assets/Scripts/Utility/AssetInjection/BookReplacement.cs.meta
- Assets/Scripts/Utility/TextProvider.cs
- Assets/StreamingAssets/Books.meta
- Assets/StreamingAssets/Books/.gitignore
BOK*.TXT files are seeked from StreamingAssets/Books and inside mod bundles.
This allows to provide overrides via the asset-injection framework without replacing core files on disk.
> Import books from modding locations

- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
Fixes a regression in which sneaking was disabled while riding a horse or cart. Midknightprince has been asking on the forums about this.
https://forums.dfworkshop.net/viewtopic.php?f=19&t=1288&p=16230#p16230
I think the change came when @MeteoricDragon moved player speed changing out to its own class. Perhaps he thought it was a mistake that you can sneak on the horse/cart, but it's possible in classic and there is even a specific sound effect that plays while sneaking on the horse. Or it may have just been an oversight, and not intentionally changed.
> Re-enable sneaking while riding

- Assets/Scripts/Game/MagicAndEffects/Effects/Poisons/PoisonEffect.cs
I noticed this showed when an AI character poisoned another one.
No check is necessary right now for diseases as they only affect the player.
> Only show "feel somewhat bad" for player

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/UserInterface/SkillsRollout.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1366.
The issue: `startingSkillSum`, used to compute when the character gains a level, was being set in DF Unity in `AssignCharacter()`, which was being computed before skills from biography bonuses were added. In classic, it isn't computer until after character creation finishes. This meant not only that the skill bonuses from the character background (if they were a primary, major or minor skill) were being considered as skills raised during active gameplay, getting you to levels 2 and 3 sooner, but it also meant the player would have a lower `startingSkillSum` than they should have, so they would always level up a bit sooner than they should have been.
> Fix incorrect starting skill values

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=742.
It's not realistic that you can cancel and "turn back time" after days have already supposedly passed, but it's good enough for now and is convenient, anyway.
As an aside, in classic, the background world events are actually being run for each day as the counter goes down, so it isn't just decorative like it is for us. And so of course, you can't cancel. We could do that, too, and it might speed up loading of a new location, although as I recall the background event processing doesn't really take up significant time. If we do that, we'd need to remove the ability to cancel, or store all changes to be undone when canceling (would probably be a pain to do that). Also it would be kind of cool if canceling just stopped the …
> Stop fast travel countdown when canceling

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterface/PaperDoll.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
Both are toggled by a new setting.
Arrow count position is centered because I could not figure out how to ensure it was just left of the compass where it looks brilliant. I found that it disappeared under the compass at different resolutions. It would be nice to move it if someone can help.
> Geographic context backgrounds & HUD arrow count

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Don't stack equipped items with other items; and when asked to equip a stack, only equip one of the items.
Limitations:
- when unequipping an item, no attempt is done to stack it with other similar items;
- characters may have equipped stacked items already; Is it worth fixing while loading a gamesave?
> Stacking and equipping

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
A temporary workaround for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1374.
In my experience this happens _every_ time you save with a spell having been cast by an enemy, whether on the player or on another enemy. I'm kind of surprised this hasn't been brought up more on the forum.
I don't know what the underlying cause is, but this treats the symptom and at least allows for loading an affected saved game and continuing play.
By the way, a somewhat pedantic note, but the failure in `GetCasterReference` was throwing an exception. I changed it to `LogError` to indicate the same level of "error", but where this is used for resuming effects, a failure was just a `LogWarningFormat` so there I used a same level `LogWarning`, but unless I'm missing something it seems like these should …
> Temporary fix for saves with missing caster loadID

- Assets/Prefabs/Missiles/ArrowMissile.prefab
- Assets/Prefabs/Missiles/ArrowMissile.prefab.meta
- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Prefabs/Scene/DaggerfallEnemy [Game Serializable].prefab
- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/WeaponManager.cs
This replaces the temporary instant arrow hits with actual 3d projectiles.
This is probably messier than it should be, as I put it together with trial and error. For example, I couldn't use the existing collider used by `DaggerfallMissile`, because it won't work with the concave shape and I had to make the rigidBody kinematic. Instead I use a sphere ray cast for the arrows. Interkarma, please feel free to gut this implementation if you don't like it. Functionally, it works, though.
All existing arrow code was adapted to work with it. I had to account for various things, like getting the player weapon at the time of shooting, not the time of damage calculation, since they might unequip their bow before an arrow hits the target.
Known issues:
- The arrow hit sound plays without any doppler …
> Add 3d arrow projectiles

- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/Panel.cs
Allow a virtual size to be provided for panel border textures. This brings support for override of SPOP.RCI.
> Use virtual size for Panel border textures

- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
Used the suffixes "(northern)" and "(southern)" based on Allofich's suggestion.
> Differentiate duplicate plants in long name (tooltips)

- Assets/Resources/ItemTemplates.txt
- Assets/Scripts/Game/Items/ItemBuilder.cs
* Fixed book display where they show using holy tome icon in old saves. Populating player tex archive + record and then changed GetRandomBook to select one of the 3 variants that are allowed instead of just using the same icon for every book. One of these is the spellbook icon... since classic only uses one icon for books (assuming a bug given variant number) and I think this will be confusing I have reduced variants to 2.
* Also changed the icon for LoC to an unused icon. (was going to be for deeds I think)
> Item Icon variants - books and LoC

- Assets/Scripts/Game/InputManager.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1377&start=10 by changing from a frame-based solution to a time-based one. Based on my testing there that 5 frames worked with a 60 fps area (1/12 of a second) I made the wait be that long. The issue is fixed for me.
Feel free to reject if you had a different solution in mind, Interkarma.
> Make post-pause input delay for 1/12 a second

- Assets/Scripts/Game/Entities/EnemyEntity.cs
I didn't realize that `careerIndex` for `EnemyClass` types would overlap with `EnemyMonster` types. This could cause an exception with city watch as they would be assigned spells and cast them and the program would try to access their non-existent spell frame animations.
> Fix enemy spell assignment

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Fixes
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1420
and 
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1418
Also fixes a new issue I found, which is that if you pressed ESC at the screen where you choose whether questions will be automatically answered or not, it would treat it as if you had selected automatic and proceed to the naming screen.
> Fix cancellation of generation windows

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/SettingsManager.cs
Hi Interkarma, please especially take a look on the 3rd point (the changes to the ini file) - since this is territory I usually don't touch - especially moving the setting "AutomapNumberOfDungeons" to the new "Map" section - if this is done correctly
- zoom settings changed - zoom is now independent of location size
- there is now a flag to change zoom reset behavior on location change
- ini file now has a "Map" section with map related settings: moved "AutomapNumberOfDungeons" to this section, added 2 new settings to this section: "ExteriorMapDefaultZoomLevel" and "ExteriorMapResetZoomLevelOnNewLocation"
> map zoom behavior changed, "Map" section in ini-file contains map related entries now

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1443. Only way I saw to do it was to add special handling for paralysis in the effect manager. If the logic was within `Paralyze.cs`, I think the effect would have started and we'd have to undo the magic rounds that had been added, etc. If you have a better solution in mind, feel free to do it instead.
Also fixes saving throws. I was wondering why a custom class character with immunity to paralysis was not resisting paralysis from some Giant Scorpions I was testing with. Turned out the paralysis spell they use (Spider Touch) has both the paralysis and magic flags. I messed up with the saving throw logic before and made it only check for one and only one flag type, so it didn't work with 2 flag types. Now, like classic, it works with …
> Add missing paralysis resist logic

- Assets/Scripts/API/VidFile.cs
- Assets/Scripts/Game/UserInterface/DaggerfallVideo.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=507.
The problem was that `DaggerfallVideo` seemed to assume that there would always be an audio frame to use to update `nextEventTime`, but there are parts in several of Daggerfall's videos where there are stretches of only video frames. Another issue was that the audioBuffer length when the last audio frame played could be very small, leading to short `frameDelay`. Enforcing a minimum `frameDelay` and accounting for parts where there are no audio frames fixes the speed ups at the end of `ANIM0000.VID` (the book intro) and `ANIM0005.VID` (meeting Lysandus's ghost). It may also slightly improve the timing of the Bethesda logo intro (you can see the sparkle disappear at the end now) and the end frames of some endings.
I tested all …
> Fix overly fast video playback

- Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs
MidnightPrince assembled a kickass soundscape for Daggerfall Unity
https://forums.dfworkshop.net/viewtopic.php?f=14&t=1347#p16078
All songs are replaced with OGG music, and there's a noticeable frames drop when songs (re)start.
This patch uses Unity audioClip streaming for digital songs.
> Stream ogg songs from disk

- Assets/Scripts/Game/DaggerfallUI.cs
Daggerfall classic displays that message if player is swimming, but also if he's levitating.
> "You cannot sleep now." if player is levitating

- Assets/Scripts/Game/Questing/Actions/PlaySound.cs
- Assets/Scripts/Internal/DaggerfallAudioSource.cs
Currently we can skip the first use of audioclips loaded from discrete files, because they're loaded asynchronously and may not be ready at the time of AudioSource.PlayOneShot().
See bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=1414
This patch wraps calls to PlayOneShot() with a coroutine so sound is played when ready, with a delay up to 150ms.
There's some code duplication here, could DaggerfallWorkshop.Game.Questing.Actions.PlaySound use DaggerfallWorkshop.DaggerfallAudioSource?
> Handle asynchronous loading of audioClips

- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
- Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
- Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs.meta
- Assets/Game/Addons/ModSupport/Mod.cs
One of the big limitations of the Mod Sytem is that MonoBehaviours provided my a mod can't be serialized to a prefab, because their type is not known by Unity when they are loaded from the assetbundle. The solution is to add components at runtime with `AddComponent()` but this is quite bothersome, and also impossible when a gameobject is instatiated by Asset-Injection without mod intervention.
As a workaround Lypyl introduced an interface to serialize custom scripts and provide a simple way to deserialize them, but it still requires the mod intervention so it doesn't fully satisfy all needs. For this reason i decided to give it a try with my own take on this issue.
Imported Monobehaviours needs to be assigned the `ImportedComponentAttribute`. Thats's all.
```
[ImportedComponent]
public …
```
> Implemented ImportedComponentAttribute

- Assets/Scripts/Game/Questing/Item.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1454 and https://forums.dfworkshop.net/viewtopic.php?f=24&t=1476, which are both the same issue.
This isn't a fix for those existing items that players already got, it just fixes the quest action to properly give magic items.
> Give correct random magic item rewards

- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/PlayerMotor.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1506&p=17372#p17372.
Also, not a priority or anything, but I think ideally the forced crouch on entering water should be optional, so that behavior closer to classic is still usable.
> Allow standing on surfaces in water

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsEditorWindow.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsData.cs
Old settings files based on INI are now unsupported.
Mod developers are invited to upgrade with the Mod Settings Editor from "Daggerfall Tools" > "Mod Settings".
There is a button named "Import Legacy INI" which should help to provide a smooth transition.
> ModSettings: Remove support for obsolete features

- Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs
An exception was thrown when an invalid preset index was selected after they are all deleted.
> PresetPicker: fixed exception thrown when there are no presets

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Default input value is now the maximum allowed value if stack
splitting is called because of player encumbrance.
- Stack splitting itself checks that you don't try to remove more than
the size of the stack, but encumbrance may enforce an even lower limit;
This wasn't correctly checked after user input.
> better stack splitting default value

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
If the "okay" button is clicked while "things" is selected or if the "people" list is empty then the talk menu no longer responds to double clicks/okay button clicks.
> Prevent talk menu from becoming unresponsive

- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
With enhanced AI on, enemies now predict target movement.
This makes them a bit more active in combat, and makes guards a little harder to avoid.
This also allows enemies to lead their targets with arrows and spells.
Also fixed reversed check when AI was checking if other AI had back turned.
Prediction includes iterative prediction when the target is unseen. For example, if the player ducks moves behind a building, the AI assumes the player, while out of sight, is continuing to move in the last direction it saw the player move. Right now this feature doesn't work so great because of lack of obstacle avoidance, which is the next thing I'm working on.
Also, adding AI leading targets made the issue of the player riding on arrows more prominent, because arrows are more likely to hit the …
> AI target movement prediction

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsData.cs
This exception is also thrown if section and key names are correct but type is not.
Requested type is now also printed to log.
> ModSettings: Log type in KeyNotFound exception

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/TalkManager.cs
This addresses a couple of issues discussed here: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1500
1. The social group NPC reaction adjustments are fixed so that the correct adjustments are read when entering conversation.
2. Social group adjustments are now part of SerializablePlayer so that they persist on save/load.
> Biography fixes

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Since arrows weight is not accounted for, they can always be put back into cart
Bug report  https://forums.dfworkshop.net/viewtopic.php?f=24&t=1532
> Can always put arrows into cart

- Assets/Scripts/Game/LevitateMotor.cs
Mainly, this fixes that the player was able to cheat past the swimming encumbrance limit by looking up and moving forward while pressing jump or float up.
This is fixed by this PR by not allowing up/down movement from forward/reverse, which also matches classic.
GodMode now ignores the encumbrance limit since it can be a nuisance when testing.
Interkarma, if you'd prefer to be able to move up and down using forward/reverse, I can try to think up a solution that keeps that ability. In real life you kind of have to specifically aim for it to swim up or down (well I do anyway) so I don't mind float up/float down being a specific action here. Another idea is to use this float up/float down behavior for swimming, but allow forward/reverse for levitate. Right now this PR is following classic …
> Swimming fixes

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/UnderwaterFog.cs
underwater fog script no longer changes fog settings when outside water or even worse when player is in an exterior location
underwater fog script now stores old fog values before entering water and restores them when leaving water
works with mods now
>  fixed bug with fog settings being changed by UnderwaterFog script breaking mods

- Assets/Scripts/Internal/DaggerfallAction.cs
Previously these methods were using the class member Duration instead of the function parameter duration for tweening.
> Updates TweenToStart & TweenToEnd methods in DaggerfallAction

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
Player can be relocated "to a random marker" in 6 cases:
- when entering/exiting buildings and dungeons;
- after fast travel;
- when going from/to ship;
- when teleported;
- when expelled by court;
- using "location" console command.
This patch implements start coordinates saving, and selection of facing
based on those coordinates as a new RelocationMethod; And then use this
method for fast travel case only.
There's some comment near entering/leaving buildings
(PlayerEnterExit.Respawner) that suggests that the closest start marker
should be chosen, but it's unclear if this new RelocationMethod could
help.
> Arrive from expected direction after fast travelling

- Assets/Scripts/Game/UserInterface/HUDActiveSpells.cs
Fix attempt (947acf6) was necessary but not sufficient;
AlignIcons() must also make use of spells' poolIndex
Bug report
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1517&p=17434
> fix debuff blinking bug

- Assets/Scripts/Game/Player/VitalsChangeDetector.cs
- Assets/Scripts/Game/UserInterface/HUDVitals.cs
This patch fixes:
- reflecting relative health decrease when max health increase after a level up;
- gauges sometimes staying stuck with some highlighted change until stat really changes.
It detect, handle and propagate resets (discontinuities).
Standard code flow can then handle the continuous, normal case.
I checked that HUDVitals receives reset events correctly, other
VitalChangeDetector listeners may benefit from handling reset events
too.
> Vital indicators fixes

- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/RDBLayout.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1515.
The problem was that this particular slaughterfish is a fixed enemy, and no check was done in DF Unity for fixed enemies spawning out of water, only for random enemies.
Classic doesn't allow any aquatic enemies to spawn out of water, regardless if they are fixed or random.
> Don't allow aquatic enemies to spawn out of water

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=1375
It seems classic behavior has not been consistent between releases or something; But it matches the version I used, what I've seen in several streams, seems useful and it looks more consistent with other shops.
The patch is short but I'm not confident in my UI understanding, so please review.
> Close spell merchant interface upon spell double-click only

- Assets/Scripts/Game/TalkManager.cs
Was getting an exception when talking to guild NPCs, who had sGroup of 7. There was already a check, but it was not on the same value used for accessing the array, so the exception wasn't being stopped.
> Fix out-of-range exception when talking to NPCs

- Assets/Scripts/Terrain/StreamingWorld.cs
Not sure it's the final word on that problem, but there's a bug in
CollectLooseObjects() because it uses RemoveAt(i) in a for loop, so if
two consecutive items need to be removed the second will be missed
because RemoveAt(i) will have shifted it down
Bug report https://forums.dfworkshop.net/viewtopic.php?f=28&p=18052#p18051
> Loose objects cleanup fix

- Assets/Scripts/API/Save/CharacterRecord.cs
Classic save import has been incorrectly importing the startingLevelUpSum since
https://github.com/Interkarma/daggerfall-unity/commit/222c142625b37cb42d96d2c485461fa39da469ca,
messing up the leveling of imported characters. This should fix it.
> Fix importing classic save startingLevelUpSum

- Assets/Scripts/Game/DaggerfallBankManager.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
Factorize capacity computations (player carry capacity, wagon hold
capacity, gold dropping into wagon), using floats to avoid rounding down
bugs.
Code that makes horse, wagon and arrows weightless was also factorized.
Gold dropping message was left as-is to preserve Daggerfall classic
behavior; However, when dropping gold into wagon, a post capacity check
was added: if the wagon cannot accomodate the amount, only the gold that
fits is dropped and a message is displayed.
Bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=1587
I found another bug while factorizing: gold weight was counted twice in
wagon, because it was handled with a special case when the common case
was sufficient.
> factorize capacity computations

- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
Sometimes made items blink when scrolling lists because the list was only partially refreshed (Draw() interrupted half way by the exception; This was self healing few frames later when animationFrame was back in valid range hence the flickering).
IndexOutOfRangeException: Array index is out of range.
at DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent.Draw ()
[0x00000] in <filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.Button.Draw () [0x00000] in
<filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.Panel.Draw () [0x00000] in
<filename unknown>:0
at …
> fix IndexOutOfRangeException in inventory

- Assets/Scripts/Game/UserInterface/HorizontalSlider.cs
- Assets/Scripts/Game/UserInterface/VerticalScrollBar.cs
It could be a matter of taste, but it makes troughs provide an additional and
useful feature compared to scroll buttons.
> Page by page scrolling using scrollbar's trough

- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
Bottom items are shifted up when an item is removed from a list; But if the end of list is displayed, the whole list can also at the same time be scrolled down, which can become confusing, specially with enhanced lists.
This patch disables scrolling while removing items from enhanced lists; Scrolling is updated when the mouse pointer is moved away from the list.
They're no doubt ergonomic tradeoffs with that kind of change, so this is just a proposal
> Delay inventory scroll down

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
In classic the yes/no popup which shows on the travel map does not wait for the full four flashes of the crosshair to appear. This change makes the travel UI faster and closer to classic.
> Only flash crosshair twice after selecting a location

- Assets/Scripts/Utility/RDBLayout.cs
Models 55007, 55024, 55018 have this tag and always seem to be action doors. 
There are 2 doors (55007) in Orsinium that also have rotation actions which causes them to operate strangely - original Daggerfall has the same problem.
Relevant bug report:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1597
> Updates RDBLayout to recognize models with the "NEW" tag as action doors

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
Found that one because of clicks going thru (https://forums.dfworkshop.net/viewtopic.php?f=24&t=1153) but anybody can just click on the "copy to log" button and trigger it, too
When the talk window is closed, the whole interface freezes and the game must be killed
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1[DaggerfallWorkshop.Game.UserInterface.ListBox+ListItem].get_Item (Int32 index) [0x00000] in <filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.ListBox.GetItem (Int32 index) [0x00000] in <filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.DaggerfallTalkWindow.OnPop () [0x00000] in <filename unknown>:0
at DaggerfallWorkshop.Game.UserInterface.UserInterfaceManager.RemoveWindow () [0x00000] in …
> Fix exception using "Copy to logbook" with no message selected

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/WeatherManager.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Terrain/DaggerfallTerrain.cs
new experimental ini file setting "TerrainHeightmapPixelError" introduced
this setting can be used to prevent inaccuracies with location placement on terrain - lower values are better, 1 is best
default is 5 (as before) but we can try to lower it to 1
> new experimental ini file setting "TerrainHeightmapPixelError" introduced

- Assets/Scripts/Game/Entities/PlayerEntity.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1617.
Looks like the problem was that if you went far enough away from town and the current dfLocation became null, there would be a null reference.
> Add null check for dfLocation

- Assets/Scripts/Internal/DaggerfallAction.cs
Implements what I mentioned here:
https://github.com/Interkarma/daggerfall-unity/commit/164d88312d6048f3be073094f1e8771fa3767329
I tested Direnni Tower and the spell seems to be coming from the same position as classic now.
> Match triggered spell shot origin to classic

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Entities/RaceTemplate.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
This provides functionality/information for vampire mechanics from classic. Interkarma, please feel free to refactor anything you like, or if this can't merge cleanly with local WIP code you have, just use it as a reference or something.
What's in here:
- Identify and import 3 vampire-related data pieces from classic saves.
1) Last time that need to kill was satiated
2) Vampire clan
3) Whether or not initial vampire quest has been initiated
This data is not serialized in PlayerEntity yet. 1) and 2) are commented out in PlayerEntity, but 3) is used for the quest logic.
- Uncommented Vampire race and temporarily using Breton graphics, to allow for opening classic vampire saves to aid in testing against classic.
(Note that if you load a classic vampire, they will gain several levels because …
> Identify classic vampire data, vampire quests

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallWitchesCovenPopupWindow.cs
- Assets/Scripts/Utility/Table.cs
- Assets/StreamingAssets/Tables/QuestList-Classic.txt
- Assets/StreamingAssets/Tables/QuestList-DFU.txt
- Updated quest dispensing to follow updated rules on UESP (confirmed by Allofich the binary wizard) with a unavoidable change to quest list schema. This will break existing quest packs, so I will work with Jay to ensure his stuff isn't broken for too long.
- Kept the reputation based dispensing for mods, 10+ rep but without any wildcarding
- Adult quests are restricted if player nudity is turned off (nearest thing to childguard)
- Updated the code for vampire quests
- Tracks one time quest acceptance
> Quest dispensing update

- Assets/Scripts/Terrain/StreamingWorld.cs
Relevant bug reports:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1628
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1645
Issue occurs when terrain objects become pooled & their locations are cleaned up. Because updateLocation was being set to false the locations were not being recreated.
> Fixes missing streaming world locations

- Assets/Scripts/Game/EnemyMotor.cs
This fixes the issue of enemies bouncing down inclines, which has existed for a long time. (I was sure I had made a bug report for it on the forums, but I can't find it now). This problem was also visually exacerbated by my recent AI update, since I put AI on hold while falling, so enemies could be bouncing down stairs while not even facing at the player, since their AI won't update while falling to turn toward the player.
I switched land-based enemies to use Move() with a downward element, similar to the player, rather than SimpleMove().
Also, for some reason, the SimpleMove(Vector3.zero) that I have been using for gravity sometimes will never get a mobile to have controller.isGrounded be true, and a mobile can get stuck.
I managed to fix this by comparing against the transform.position …
> Fix enemies bouncing down inclines

- Assets/StreamingAssets/Quests/_TUTOR__.txt
The goal is to adjust the tutorial content to be less confusing and more
helpful for new (DFU) players:
- remove references to icons-based interface, cursor movements mode and
save slots;
- mention WASD, quicksaving/quickloading and controls customization.
I tried to keep the changes minimal to preserve the classic experience.
Pace will probably be too slow for 80% of even new players, but I didn't change it
either.
> Minor tutorial content fixes

- Assets/Scripts/Game/TalkManager.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1683.
The problem was the NPC in question is of the Order of the Lamp faction, which has a gguild of 10, or knightly order. The code would then try to look up a knightly order with the building faction of 40 (Mages Guild) and throw an exception.
When opening dialogue, for NPCs of a faction that is not of type 2, 7, or 9, classic will iterate up through their parents until it finds one that is of these factions (if there is one) and use that faction instead. With this behavior replicated, the NPC in the bug report will now use the parent faction of Mages Guild and give a Mages Guild greeting like in classic.
> Fix NPCs to use parent factions for dialogue

- Assets/Resources/ItemTemplates.txt
Fixes first part of https://forums.dfworkshop.net/viewtopic.php?f=24&t=1660&sid=5ee3de52dcc231329e59ee68733ff5e8.
The issue is that chain greaves use greaves variant 6, but the `TotalVariants` gotten from `ItemTemplates.txt` is 6, and in `DaggerfallUnityItem.cs` the below code modifies the variant to 5:
```
/// <summary>
/// Sets current variant and clamps within valid range.
/// </summary>
void SetCurrentVariant(int variant)
{
if (variant < 0)
currentVariant = 0;
else if (variant >= TotalVariants)
currentVariant = TotalVariants - 1;
else
currentVariant = variant;
}
```
The reason why it works in classic, is that classic does not use the item templates data for armor variants, it only uses it for clothes variants. Armor variants are hard-coded. Changing the `(variant >= TotalVariants)` …
> Fix chain greaves graphic

- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Utility/ImageProcessing.cs
Fixes the second part of https://forums.dfworkshop.net/viewtopic.php?f=24&t=1660&sid=5ee3de52dcc231329e59ee68733ff5e8
DF Unity was using "Steel" dye as the default, unchanged, color, but classic uses "Silver" dye. This is used for both leather and classic. Removed the LeatherHelm fix as it's no longer necessary.
Also, DF Unity displayed Silver and Elven dyes as the same color (both as Silver), but Elven is different. Elven/Silver items from existing DF Unity saves will still appear as Silver. Also, the Orcish dye differed from classic. Any intentional changes?
Color comparisons attached. Left = master branch. Right = this PR (same as classic)
Leather
Elven
Orcish
> Match armor dye colors to classic

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
Fixes to AI movement prediction:
- Due to recent AI PR(s), AI weren't using prediction anymore when they didn't have LOS to the target
- Because of not accounting correctly for the lead on movement prediction (based on time to intercept the target), the iterative prediction when target isn't seen would make bogus predictions
- Enemies stop if their prediction takes them too far, helps with the issue of enemies wandering off during combat.
- Some cleanup
> Fix problems with AI movement prediction

- Assets/Scripts/Game/TalkManager.cs
https://github.com/Interkarma/daggerfall-unity/pull/1127 added an unused variable, making a warning come up in the Unity editor.
> Remove unused variable

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/WeaponManager.cs
Currently uses the best open chance to determine a successful bash.  I used the same formula regardless of whether the door is locked since unlocked doors aren't automatically kicked open on the first try in classic.
> Bash exterior doors

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
Fixes these problems:
- Melee attack completely ignored magical concealment, so enemies would still do a melee attack if you got close to them
- Ranged attacks and spells would still happen regardless of magical concealment as long as the enemy's "give up timer" for pursuing the target had not run out yet. If an enemy could see you (priming the give up timer to maximum), and you then cast Invisibility (can no longer see you so give up timer starts to run out), they would still do these attacks for the next several seconds until the timer reached 0.
> Stop enemies attacking magically-concealed target

- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/GameManager.cs
New functionality is that AI will now switch to its last combat target if the current one dies. This addresses the following situation I noticed during testing:
1) Enemy A follows me into room with Enemy B
2) Enemy A switches target to Enemy B, kills it with back turned to me
3) Enemy A now stands there without target. Looks stupid because it should remember me, who it was pursuing mere seconds ago.
Also, moved the storage of enemy target from DaggerfallEntityBehaviour to EnemySenses, which is mainly what uses it. The previous combat target was already stored in EnemySenses.
> AI uses last target after current one dies + cleanup

- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
When describing a stack, weight is the total weight of the stack, but the price is unitary price; that's not consistent.
It can be fixed in several ways, that patch uses total price.
> fix item info panel discrepancy for stacks

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/FPSSpellCasting.cs
- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/ImageReader.cs
- Assets/Scripts/Utility/TextureReader.cs
This PR allows to specify readonly flag for individual textures used by UI when image data is imported from loose files. We have no control over asset bundles so this is still up to mod authors.
> Texture replacement: allow readonly flag for loose files

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
https://github.com/Interkarma/daggerfall-unity/pull/1120 caused a problem because the adjusted center of the collider interfered with a few calculations that used transform.position and colliders. Specifically, I noticed a Thief and an Orc were no longer able to see each other to fight and would simply stand there looking at each other.
The change in center of the collider is now accounted for.
Also, I found that the player's collider is height 1.78. Enemies now use this value as well. I confirmed the Thief in Privateer's Hold can fit through the door with this value.
> Account for change in center of collider after height adjustment

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
#1084 made notebook fast travel checks too strict, for instance not allowing to fast travel to a town you didn't visit before.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=28&t=1578&p=19594#p19575
This patch reuses DaggerfallTravelMapWindow.CheckLocationDiscovered(), I hope that's the right thing to do.
> reuse CheckLocationDiscovered to allow notebook fast travel

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
1)
If not yielding across frames, only apply climate settings once dfLocation is completely initialised instead of for every block. This needs to be verified as logically correct before merging. I'm pretty sure that it can be moved but I don't have a deep enough understanding of this code to be absolutely sure
Also improved layout times diagnostics.
This optimisation almost halves the time it takes to construct a city location when exiting buildings after loading an interior save. I stumbled across it when analysing the exterior world code to see how it might have parallelisation applied. 
2)
Only check for assets to be injected once by keeping a record of tried assets. This halves the time taken to layout terrain because of the sheer number (hundreds of thousands) of them. Most players …
> Optimise applying climate settings for locations and asset injection checks

- Assets/Scripts/API/MapsFile.cs
In classic, areas under climate value equal or above 230 (MountainWoods) use Breton race and names for town people.
This fixes DFU to match classic.
Actually, another difference with classic I couldn't fix yet is that town people names should not be generated according to climate values. E.g. in classic, Dragontail people use Nord textures (climate value 226, Mountain) with Redguard names, whereas Wrothgarian people (same climate value) use Nord textures with Breton names.
> Make town population textures from areas with 'MountainWoods' climate value match classic

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
For https://forums.dfworkshop.net/viewtopic.php?f=24&t=1531. (I'm going to say, fixes it)
Did this in 3 steps.
1. Matched enemy hit registration calculation to classic. Before you could be hit as long as you were in the enemy FOV, so essentially in a 180 degree arc. Now you have to be in about a 70 degree arc, same as classic (unless enemy is right on top of you (= less than .25f distance), then it hits regardless. This is also matched to classic)
2. After doing the above, I noticed that enemies still initiated the melee animation based on target being in the 180 degree arc. Now they do so with a 45 degree arc, same as classic. (The actual hit registration happens with a 70 degree arc as mentioned above)
3. After doing both of the above, I noticed that enemies pursuing the player could …
> Match enemy melee detection to classic

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1720&sid=39928d1297b723ceeefe6d27d6644408.
I wasn't getting an exception but I was getting the messed up aspect ratio, and noticed what the problem was. The frost daedra is unique in having an attack animation sequence that starts with the hit frame. When I set up the animation sequences that I got from the original .ANC files, I used "-1" to represent the hit frame (in the actual .ANC files it's the sequence `02 01 00` for a melee animation's hit frame and `02 02 00` for a bow animation's frame to release the arrow). I account for the "-1" value in `AnimateEnemy()` (which in this case will initiate a melee hit and then skips over to the next value in the frame sequence) but in the setup where `UpdateOrientation()` is called, the …
> Account for frost daedra melee hit frame

- Assets/Scripts/Game/TalkManager.cs
Although https://forums.dfworkshop.net/viewtopic.php?f=24&t=1500 seems that it may have already been fixed by numidum3rd, this also should fix it. It also implements formula and tallying of skill for etiquette and streetwise in dialogue, addresses some TODOs about when responses are used, and compacts the code significantly by cutting out unnecessary things and implementing directly as classic does.
Daggerfall Unity was using a single reaction value for dialogue, but classic calculates two different reactions. First there is a reaction when clicking an NPC that determines if the NPC will talk to you, and the initial greeting they give you, which is affected by the biography reaction roll. This one was basically already working right, and uses values like -20 through 30, with 0 being …
> Match dialogue reactions close to classic

- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
The light archive contains emissive and non emissive textures. If we want to allow replacing individual textures, we need to load the atlas and override only the imported textures. This includes the emission atlas.
> TextureReplacement: disable emission maps on non-emissive lights

- Assets/Scripts/Game/EnemyAttack.cs
Incorrect parentheses in my recent PR for enemy attacks. Could cause an exception when senses was null.
> Fix logic error

- Assets/Resources/AllowHeight.mat
- Assets/Resources/AllowHeight.mat.meta
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
This PR adds support for heightmaps as requested on forums. I used the name Height instead of Parallax because this is what's used for the inspector and Unity docs.
> TextureReplacement: Support for Height Map

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Internal/AudioSourceExtensionMethods.cs
- Assets/Scripts/Internal/AudioSourceExtensionMethods.cs.meta
- Assets/Scripts/Internal/DaggerfallAudioSource.cs
Allows ambient sound effects and ambient sound loops to play at the same time.
Main issue I have with that code is that I needed to duplicate some of DaggerfallAudioSource features (to work correctly with modded sounds), so it'd better be factorized at some point...
(Lost a lot of time because the compiler was silently failing (Monodevelop added "using System" that made "Random." ambiguous) so I kept running the last version of the game that compiled, not understanding why my changes had no effect :( )
> Rain and thunder

- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/API/RumorFile.cs
- Assets/Scripts/API/Save/SaveGames.cs
- Assets/Scripts/Editor/AtlasEditorWindow.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Utility/MacroHelper.cs
Features:
1. Imports non-quest rumors from classic, including their time limit, flags, etc. Quest rumors are not imported since this is pointless unless we also import quest status from classic saves.
Note that due to a mistake in classic (which I've mentioned before), non-quest rumors are very rarely updated in classic and you will often not have any in saved games where you have progressed in the game. You can be guaranteed to have non-quest rumors for import if you make a new character, for about the first game month until the rumors expire.
2. Non-quest rumors now have time limits, the same as those in classic. They last for about a month.
3. Flag data from classic data recreated. This has things set up for signboard messages, whenever clicking on signboards becomes supported.
4. …
> Non-quest classic rumor implementation

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
1. Adjusted enemy controller height limit down to 1.65f. I had to limit it to this for the enemy thief in Privateer's Hold to really be able to get through the doorway every time without hitching up for a second .
2. Fixed problem with enemies refusing to follow player down staircase corridors because the obstacle check would see the sloping wall in front of them as an obstacle and they would stop moving downwards.
3. Enemies will only try to get to Occasionally I saw enemies wandering off down a wall looking for a way to get to me. Also they would often not follow the player well around corners due to the prediction logic. They now use the last place they saw their target if they don't have a clear path to the predicted spot, which addresses both of these.
> Improve AI pursuit

- Assets/Scripts/Internal/AudioSourceExtensionMethods.cs
Modded loops can be heavier than sound effects to load, and we don't care as much that they start right on time;
So increase the time limit for playing them (hopefully 2s is plenty; I prefer some timeout to no timeout)
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1776
> give more time for sound loops to load

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
EnemyMotor, although generally working okay, had become somewhat of a mess as I've been adding and changing bits of it. I went back over the code execution and made several small cleanups, fixes and a few optimizations.
Fix up MakeEnemyHostileToAttacker()
Simplify rotating check
Use more accurate variable names
Don't do bow or spell attack checks when not available
Remove pointless variable assignments
Remove pointless normalizations
Remove pointless move() call
Move clockwiseCheck reset to FindDetour() so it's only done when needed
Correct assumed spell projectile speed
Use do-while loop in FindDetour so operations done in correct order
Fall check assumes obstacle check was just done, so do before fall check
Use wider angle for detecting doors to open so AI can open them more
easily
> Clean up EnemyMotor

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Internal/DaggerfallAudioSource.cs
Combines all the classic timer updating I had put into separate files into a single timer in GameManager, since only one is needed.
If GameManager isn't where you would want this, I can move it somewhere else.
Should merge cleanly with https://github.com/Interkarma/daggerfall-unity/pull/1184.
> Use a single timer for classic update simulation

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
Some people seem so used to instantaneous repairs that they get their items back before they're repaired; A warning seems appropriate.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1765&p=21086#p21086
> warn the player before taking back an item not fully repaired

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
The changes I made to enemy collider height to allow them to fit through doors caused an issue where the upper part of the enemy would no longer respond to collisions such as arrows or clicking on them for the "You see a %s" message. The taller the enemy the more noticeable the problem would be. It was particularly noticeable with dreughs.
The only solution that came to mind is an imperfect one, but better than what we have currently. That is to only temporarily change collider height for half a second when an enemy brushes up against something. It will then return to normal if after the half-second the enemy is no longer touching anything.
This fixes the dreugh part of
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1751
> Make enemy height change only temporary

- Assets/Prefabs/Missiles/ArrowMissile.prefab
- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/WeaponManager.cs
Combined with https://github.com/Interkarma/daggerfall-unity/pull/1195, this fixes the other issue in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1751 (about the bats).
1. Use colliders instead of ray casts for arrows.
- Enemies pushed around ("Jedi reflexes" of the bug report) less
- Shooting enemies at point-blank range will register hits better now (will still go through them if they are right next to you, but that doesn't bother me too much as it is unrealistic to shoot from that close anyway)
- Maybe a little better performance?, since instead of doing raycasts the collider that existed on the arrows is used.
- Maybe more reliable hit detection, although the ray-cast solution seemed to be working for me except at point-blank ranges.
2. Moved arrow disabling and damage to be …
> Make arrows use colliders for hit checks

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
Minor fixes and cleanup for `EnemySenses`. With enhanced combat on, enemies will now acquire a secondary target that they will switch to if the primary dies, to eliminate them standing still and looking foolish because they had "tunnel vision" and only focused on one target, ignoring everyone else around them. Now they will appear to have a little better situational awareness, since they will switch to another target immediately if they saw it while pursuing the primary target.
I had meant for a more basic version of this feature to already exist, but it wasn't working correctly. This replaces it.
List of fixes:
`lastTarget` was being used inconsistently. Created a new `targetLastUpdate`
variable for tracking whether current target is the same as last update.
`lastTarget` renamed to …
> EnemySenses fixes and cleanup

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
cost only takes into account items that are not already being repaired
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1828
If they're only already repaired items in the remote list, test L721 does not prevent a display a "it will cost 0 gold" trade window in you click on REPAIR button. The same situation happens with identification, so this test could be improved, but I don't understand that code well enough.
Also, I don't understand how repair price seems correct in game (equal to "cost", as computed by UpdateCostAndGold()), when the deduced amount L765 is the value of GetTradePrice() that does not handle the case windowMode == WindowModes.Repair
> Prevent paying repair price several times

- Assets/Scripts/Game/DaggerfallMissile.cs
With the latest code I noticed an exception when `AssignBowDamageToTarget` in `DaggerfallMissile.cs` tried to use the destroyed arrow gameObject in `attack.BowDamage(goModel.transform.forward);`.
I assumed that `DoCollision()` would only run once for arrows but it sometimes happens more than once. Now `DoCollision()` will only run once for arrows.
I don't know if spells are supposed to run `DoCollision()` more than once, but they do. Can you confirm, @Interkarma?
> Prevent arrows from colliding more than once

- Assets/Scripts/Game/Entities/DaggerfallSkills.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
When opening the character sheet, highlight all the skills that have
increased since the last time you opened the character sheet.
Exclude character sheet opening automatically triggered by level ups.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1834
> highlight recently increased skills

- Assets/Scripts/Game/Player/PlayerNotebook.cs
- Assets/Scripts/Game/UserInterface/PopupText.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
This is just a log of recent onscreen messages; The number of messages is bounded, and they are not persisted. The goal is just to provide a way to read messages that went by too fast.
Any way to get a more dense display?
Once text density is fixed, it would be great to set the maximum number of messages to exactly one screen, or to open the messages log to the last page.
> notebook page to log onscreen messages (popup, middle screen)

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Cosmetic fix: currently when you open an empty spellbook, the different icons appear as black empty spaces, which does not look good (specially on a nicely modded spellbook background).
Simply remove the icons altogether in this case.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&p=21577#p21577
> hide icons in empty spellbooks

- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
* Fixed positioning issue with dungeon containers.
* Fixed issue which caused custom loot gameobjects to be instantiated twice at the same position.
> MeshReplacement: Fixes for loot containers

- Assets/Scripts/Game/Items/ItemRepairData.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Display estimated repair times, so you can make better informed choices as to repairing items (and when).
Calling UpdateRepairTimes(false) from Refresh() seems sufficient; Other commented calls may be removed when we become confident it is.
> show estimated repair times

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
fix for bug described in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1611
name of residences is now correctly resolved in macro expansion
> name of local residences is now correctly resolved via macro expansion

- Assets/Scripts/Game/Questing/Message.cs
- Assets/Scripts/Utility/QuestMacroHelper.cs
fix for bug reported by forum user Ferital in this thread: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1678&p=22074#p22074
dialog linked resources are now only resolved if their macro type is NameMacro1 - 
only if their true name (_person) is resolved (not other types like __person)
> quest popups now reveal dialog linked talk options

- Assets/Scripts/API/Arch3dFile.cs
I spent hours (if not days) on this one...
This fixes most of the texture UV coordinates problems uncovered on the forums:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=328: I removed the special case @Interkarma put several years ago for the building window since it is not needed anymore. The weapon store used for The Count's Arsenal in Newtale (@petchema) is also fixed.
https://forums.dfworkshop.net/viewtopic.php?f=28&t=1588: the dungeon room is fixed but not the tavern pillars. @petchema, could you check that the dungeon corridor streched textures you saw are corrected?
To fix this, I used in particular a previously unused and unknown field from the mesh header. It is read as an integer but from my tests, the only values it can take are 0 and 65536, so I think it should actually …
> Fix most remaining texture alignment problems

- Assets/Scripts/Game/MagicAndEffects/Effects/Special/MehrunesRazorEffect.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/MehrunesRazorEffect.cs.meta
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/WabbajackEffect.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectBroker.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
I noticed that saving throws weren't being used for most spells. If this is the desired behavior for now then I don't mind changing it back. Having saving throws active prevents MR from killing targets on the first hit every time.
I also altered the Wabbajack effect. It bypasses saving throws in classic so I added a flag for effects that ignore them. Added a check to prevent Wabbajack from disabling enemies that are in use by a current quest.
> Use saving throws and implement Mehrunes Razor effect

- Assets/Scripts/API/FactionFile.cs
A faction can have its flags value from `FACTION.TXT` be composed by multiple "flags" lines, and these should all be ORed together.
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1887&p=22188#p22188. I wrote a description of the problem there.
> Assign flags from factions.txt with |=

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
Minor tweak. I noticed that with the recent change to AI search behavior I made, starting the search with 1 movement prediction threw them off a little and could cause them to walk into the wall when trying to pursue.
Ex)
`e` = enemy
`p` = player
`-` = wall
`|` = where enemy goes to in pursuit
Master branch:
Player went through doorway and enemy last saw him moving to the right ("right" as seen from top-down view). By starting at prediction iteration "1", enemy heads to first predicted spot (based on player movement rate/direction and last known position) and goes to "|", hitting wall.
```
e
----  -|--
p
```
This PR:
Iteration starts from "0", so enemy starts with no prediction, heading to the last known player position (doorway) first. If it still can't see the player after getting …
> Start target search prediction iteration from 0

- Assets/Scripts/API/Arch3dFile.cs
This provides a starting point to patch some wrong texture UV coordinates in ARCH3D.BSA at runtime.
For now, this fixes the following problems:
- Tavern pillars like in The King's Fairy, Daggerfall
- Compressed wall texture near the entrance of a weapon store like The Count's Arsenal, Newtale, Bhoriane (@petchema)
- Stretched dungeaon corridor floor (from model index 989)
> Fix some incorrect UV coordinates within the data files

- Assets/Scripts/Terrain/StreamingWorld.cs
Billboard trees can swap material at any time but imported 3d trees must be loaded with the correct variation during location setup.
> Immediately get NatureSet and Season for location creation

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/GameManager.cs
2 console commands that will be useful for working on the AI, as well as for just messing around and having fun with AI battles. Also lays some groundwork for implementing the artifact effects that involve summoning an ally.
"CreateMobile" = type "cm" followed by the numerical ID of the enemy type, then the number of the mobile team to spawn it in front of you.
Ex.) cm 0 1
Creates a rat (id 0) on the "player ally" team (team 1, won't attack player)
All teams are hostile to all other teams. Created a new "player enemy" (team 0) for general use in making enemies that are all allied with each other against the player.
Issues)
1: When created, mobiles are rotated to look in the direction the player was looking, but for some reason this seems a little finicky and they will at first briefly be …
> Implement 2 new commands for testing AI

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
In classic Daggerfall, one cannot exit the level up screen until all
ability bonus points have been distributed.
In Daggerfall Unity, this is true when trying to use the EXIT button or
the Escape key, but it was possible to exit the character sheet window
and distribute remaining bonus points later by pressing the character
sheet keyboard shortcut (f5 by default).
This patch closes this loophole, and factorizes some code between the
different ways to close the character sheet.
Bug tracker:
https://github.com/Interkarma/daggerfall-unity/commit/b0f6f52bd3c7d99ff7e6873e18807f6c3f29be11
> prevent f5 from closing level up screen

- Assets/Scripts/Game/UserInterface/PaperDoll.cs
Looks like the Skull of Corruption and Hircine Ring were appearing where they did because of their images' x and y offset values. Other items that don't show on the paper doll like rings, etc. were also drawn but just not where you could see them.
Classic only draws items on the paper doll if they are of the clothing, armor or weapon groups. Using this same check for DFU fixes the Skull of Corruption and Hircine Ring.
The Hircine Ring's x and y offsets, appearance and text description seem to indicate it was going to be a shield at some point, and the graphic still looks like one. 
Bug report: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1870&p=22543#p22543
> Fix Skull of Corruption and Hircine Ring appearing on paper doll

- Assets/Scripts/Game/Entities/PlayerEntity.cs
Prevent random encounter spawns as mentioned here https://forums.dfworkshop.net/viewtopic.php?f=24&t=1918&sid=b161443d647dd3d6ddfe6e86d3b194ed.
They are also prevented in this case in classic.
> Prevent non-guard spawns while in water

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Sort spells by alphabetic order, display spells magicka costs.
I considered greying out spells from the merchant when the magicka cost is over your MaxMagicka; That is, you cannot casts them, even when fully rested.
But greying out usually means stuff you cannot do, and you can still buy those spells, so I finally decided against it (the code is ready for such change though).
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1916
> Spell merchant improvements

- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Powers.meta
I altered a couple of them from classic so that they match their respective paper doll images better.  Let me know if I'm out of line in doing this.
> Apply screen weapon dye overrides for artifacts

- Assets/Prefabs/Missiles/ArrowMissile.prefab
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
Make sure enemies don't get stuck with "avoidObstaclesTimer" > 0 if they
are somehow unable to point at the detour destination.
Raise avoidObstaclesTimer a bit now since it counts down regardless of
direction enemy is pointing, but set to 0 if got close enough to target
spot. 0.3 seems like a good distance for this check.
Make enemies aim at their own height for target when searching for
target, not just when approaching seen target.
Improve RayCheckForObstacle:
- Use a CapsuleCast. This does better at detecting things in the way.
- Adjust height of rays casted for checking for slope. Should still
detect climbable stairs while not treating large, unclimbable
differences in height as climbable.
> AI improvements

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
Removed parent assignments when creating city guards or using the "CreateMobile" command, as they are now redundant because of
https://github.com/Interkarma/daggerfall-unity/commit/88644c22c1063079d811b148c26b4628b3297600
> Remove redundant parent assignments

- Assets/Scripts/Game/TalkManager.cs
Not a complete cleanup, but just some tidying up that should hopefully not raise any objections.
Whitespace cleanup
Merge nested if-statements
Remove empty methods
Rename reactionToPlayer variable masking same-named variable
Remove unnecessary reactionToPlayer parameter
Inline variables where possible
Remove redundant parentheses and redundant else statement
Remove redundant "== true" for bools
> Clean up Talkmanager

- Assets/Scripts/Utility/AssetInjection/Components/ObjectPositioner.cs
- Assets/Scripts/Utility/AssetInjection/Components/ObjectPositioner.cs.meta
Moves an object next to the nearest collider. Can be used to fix bad classic game-data positions.
This is available as a component to modders. If you agree i think we can make a list of classic assets that also benefits from it.
> Added ObjectPositioner

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
Should fix https://www.reddit.com/r/daggerfallunity/comments/bb5yu4/enemies_seem_floaty/.
When I merged all the classicUpdateTimers into one, I put it into the GameManager, and stuck it in its `Update()` along with all the rest of its update work. However, since `FixedUpdate()` and `Update()` are not in sync with each other, accesses to this from `FixedUpdate()` functions were not reliable. Everything needs to be either in `FixedUpdate()` or in `Update()`. Since https://docs.unity3d.com/Manual/ExecutionOrder.html says "All physics calculations and updates occur immediately after FixedUpdate.", and enemy AI is closely related to movement, `FixedUpdate()` seems to be the right place. When frame rates are high `FixedUpdate()` runs quite a lot less than `Update()`. When frame rates are low, …
> Everything using ClassicUpdate uses FixedUpdate

- Assets/Scripts/Game/DaggerfallMissile.cs
Very minor cleanup of 2 things in `DaggerfallMissile`. `arrowCollider` could be made a local variable, and the `AssignBowDamageToTarget(other)` line wasn't indented and made it look a little unclear what was intended to fall under the if statement.
> Minor cleanup

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Allows to import overlays along with texture map, to avoid classic resolution overlay over high resolution map.
> TravelMap: Support for custom overlays

- Assets/Scripts/Game/UserInterface/PopupText.cs
When all popuptext buffer can be displayed on screen, behave just like before;
When more lines are buffered, adjust scrolling speed so lines appear within a fixed time (currently 1.5s, adjustable) after their insertion. This should prevent unbounded lag when a lot of text is generated (spells spamming, info-click on buildings,...)
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1985
> adjust scrolling speed to limit buffering

- Assets/Scripts/Utility/AssetInjection/Components/FaceWall.cs
- Assets/Scripts/Utility/AssetInjection/Components/ObjectPositioner.cs
- Assets/Scripts/Utility/AssetInjection/Components/WallPropPositioner.cs
- Assets/Scripts/Utility/AssetInjection/Components/WallPropPositioner.cs.meta
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
* WallPropPositioner is derived from ObjectPositioner.
* WallPropPositioner allows to set a local space direction instead of expecting the model to be oriented along the Z axis.
* Added IObjectPositioner interface to toggle random flat rotation. Potentially allows mods to provide their own positioning mechanisms.
> Reworked FaceWall as WallPropPositioner

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Allows mods to provide a custom cursor texture. This must use the 'Cursor' texture type and have Read/Write flag enabled. Import from loose files is not supported.
> Added support for cursor override

- Assets/Scripts/Utility/RMBLayout.cs
Broken in 94a2c78b
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2002
> fix city gates regression

- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Game/Serialization/SerializableStateManager.cs
Fix one the two issues raised [here](https://forums.dfworkshop.net/viewtopic.php?p=23300#p23234), specifically the invisible loot containers.
I've not yet been able to replicate issue with loot content.
> MeshReplacement: Ensure DaggerfallBilboard is found on loot

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs
In case current and anchor buildings have the same buildingKey, map pixels must also be compared to be sure it's not the same building.
Discovered data doesn't look good, that may not be the best possible fix.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2018
> fix for building-to-building teleport ending in the Void

- Assets/Scripts/Utility/TextureReader.cs
Terrain Texture Arrays are now created with Graphics.CopyTexture on supported platforms, which is much faster than using Get/SetPixels.
1. Get/SetPixels
2. CopyTexture (DXT1)
3. CopyTexture (RGB)
Beside the fact that the format is the one used by individual textures (which can be compressed), the improvement is that CopyTexture performs a GPU-side copy between textures, which is faster than uploading with Apply(). This also means that Read/Write flag can be unchecked, unless a mod wish to target older platforms with no support for this feature.
> Make Texture Arrays with CopyTexture

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellMakerWindow.cs
- ProjectSettings/ProjectSettings.asset
Supersedes #1252 (Deducts gold when buying spells from spellmaker)
Also, check for spellbook presence. In classic, when you have no spellbook:
- spell merchant does nothing, not explaining why;
- spell maker fails at the last minute ("you have no spellbook to inscribe this spell")
I think that in both cases the player, even without a spellbook, could want to peruse available spells, so I implemented a preliminary warning that does not block the access to the spell merchant and the spell maker.
A second check is done if you try to buy a spell though.
Maybe that's overkill and confusing, and access could simply be denied with an error message?
The simplification I'm considering:
- remove spell merchant warning. The player can peruse the spells, but will be denied to buy any. There's not …
> Paying spellmaker and spellbook check

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellMakerWindow.cs
The current state of spellmaking allows the player to make spells for free (for testing purposes). This was deemed no longer necessary and this commit will deduct gold from the player based on the cost of the spell.
> Deducts gold when buying spells from spellmaker

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
1. Main fix here is that the prediction counter is no longer reset whenever the AI checks for whether it can shoot a spell. This was causing the imp and others with ranged spells to get stuck. (In master branch create an imp with "cm 1" and they should get stuck almost immediately. With this PR they are fixed. This problem surfaced after one of my recent PRs)
2. Enemies can now cast any spell as long as they have at least 1 spell point left. This matches classic and should allow them to cast the same number of times. It's also relevant to the classic AI's spell decision, as it checks for whether it has any spell points left when deciding if it can still cast. (Otherwise, we'd need to check whether it has at least the spell points of its cheapest ranged spell or something like that)
3. …
> Fixes to AI spell casting/shooting

- Assets/Scripts/Game/Entities/RaceTemplate.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Utility/MacroHelper.cs
This fixes the mapping between race numbers from FACTION.TXT and races used in game, when generating a random ruler name when asking a NPC for any news.
> New ruler namegen fix

- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Internal/PlayerGPS.cs
Townsfolk names are not tied to climate settings in classic. Instead, they use an array of 62 byte values hardcoded in FALL.EXE with 0 for Breton and 1 for Redguard. Nord names are never used for town NPCs.
This makes DFU behave the same.
> Townsfolk names now match classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
DaggerfallTradeWindow.OnPush() can be called before Setup() so wagonButton can be null in OnPush(), and its texture not settable there. 
So to cover all the bases the button background texture must also be set in Setup().
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2040
> make sure wagon button is fully reset by buy window

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs
Added support for emission for mobile billboards. This can be used to provide emission maps for enemies such as Fire Atronach.
> TextureReplacement: Emission maps for mobile billboards

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/UserInterface/PopupText.cs
Exponential speedups did not work as well as the math suggested, with large lags the acceleration made all lines disappear from screen in a blink, including the most recent ones; Or get stuck because speedup overflows floats capacity!
Replaced with simple rubberbanding (proportional speedup) for now. I don't like that acceleration profile as much, but it fixes those issues. That may be improved later.
Added a "addpopuptext" console command to push n lines in the buffer for testing.
> scrolling speed adjustments

- Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/BadRepWith.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/GoodRepWith.cs
BTW, Interkarma, I didn't completely understand a couple of comments in `BadRepWith.cs`.
> Sources claim that effect persists even when item in wagon, but this is suspect and not consistent with other item effects.
Not completely sure what you meant but I think it may be true that good rep and bad rep enchantments take effect for any item in inventory in classic even if not equipped. But if so that seems like it may be a mistake as I don't think anything else works like that.
> Classic allows unusual stacking of variants, e.g. all is exclusive to groups but each group not exclusive with itself.
Changed this to work uniformly as per GoodRepWith, which does not allow self-stacking of groups.
Do you mean stacking vs. being exclusive when selecting enchantments in the item maker? I'm not sure …
> Match enchantment reputation mods to classic

- Assets/Scripts/API/Save/ItemRecord.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Questing/Item.cs
Also read "message" from classic data as a ushort as that is what it is in classic
This should hopefully fix
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1845&p=23954#p23954.
I can't reproduce the problem of getting "The First Scroll of Baan Dar" in random loot. Maybe it was fixed as Jay_H's comment suggests. But it does look like quest rewards were neglecting to randomize the book, so that is added in this PR.
I didn't have a save handy to test a book quest reward, but this is a pretty straightforward change so it should work.
> Randomize book quest rewards

- Assets/Scripts/Game/MagicAndEffects/Effects/Special/SkullOfCorruptionEffect.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/SkullOfCorruptionEffect.cs.meta
I made it so both the Skull and Rose only spawn allies if the monsters nearby are not allied with the player.  I'm aware that the Skull in classic only clones non-human enemies in classic but I didn't feel the need to limit it in that way (I'm willing to change it if there are objections).  The behavior otherwise matches classic to the best of my knowledge.  Please let me know if I'm missing anything.
On a side note, I'm impressed at how simplified the process of adding new artifact effects is now.  Well done, Interkarma!
> Add Skull of Corruption effect and Tweak Sanguine Rose

- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
I'm not sure if classic does this, but I removed the "The " prefix from the order names so the quest messages doesn't come up displaying "The The " - anyone have an issue with that?
> Handle %kno macro for quests

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
- Enable holiday effect for closed shops on Suns Rest 
- Enable holiday effects for free & half price curing
** Free on: South_Winds_Prayer, First_Harvest, Second_Harvest
** Half price on: North_Winds_Festival (needs testing)
- Enable holiday effects for half price sales
** Merchants Festival, suns height 10th for normal shops
** Tales and Tallows hearth fire 3rd for mages guild (needs testing)
** Weapons on Warriors Festival suns dusk 20th (needs testing)
> Holiday effect implementation

- Assets/Scripts/Game/SunlightManager.cs
- Assets/Scripts/Game/WeatherManager.cs
When light is scattered, there should be less hard shadows (only ambient occlusion shadows); This is most obvious during heavy fog.
So I modified the shadows to be
- slightly lighter during overcast weathers;
- very light during snowing weather;
- almost inexistant during fog.
> Weaken shadows under scattered light

- Assets/Prefabs/Missiles/ColdMissile.prefab
- Assets/Prefabs/Missiles/FireMissile.prefab
- Assets/Prefabs/Missiles/MagicMissile.prefab
- Assets/Prefabs/Missiles/PoisonMissile.prefab
- Assets/Prefabs/Missiles/ShockMissile.prefab
- Assets/Scripts/Game/DaggerfallMissile.cs
tweak minDistance and maxDistance instead of spatialBlend and volume
volume is never effectively amplified, so setting volume > 1f has no effect.
Instead, one can increase minDistance, so the the sounds stays at nominal volume at a larger range.
maxDistance sets at what distance the sound stops becoming quieter with distance. This is actually better than using spatialBlend, because the sound stays directional, which is important to know where are enemies fighting.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2089&p=24412#p24412
> Spatialized spell missile hit sounds

- Assets/Scripts/Game/Player/FrictionMotor.cs
Do not automatically dip for moving obstacles, like missiles (including your own).
On the other hand, I wonder if enemies can't dodge missiles because of a similar mechanism (in EnemyMotor.HeightAdjst).
Maybe that's the missiles that should be handled differently? I don't know if that's even possible.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2089
> only dip head in front of static obstacles

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
There are some NPCs marked as TG spymasters in various houses, I had suppressed ones in House2 buildings already. I've changed this so all misplaced spymaster NPCs now have special case handling so they act just like regular NPCs instead of just making them disappear. Basically the same as I did for holy order NPCs that are not in a temple. (viewtopic.php?f=28&t=1238)
I also fixed it so the responses are now general ones for spymasters, left it alone for the priests since they already use a parent faction with no guild group.
Additionally the guild responses were getting random messages using strings when the msgs being used have formatting tags, so I fixed that too.
> Make random spymaster NPCs act like non-guild

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
Happened while opening quest log:
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1[DaggerfallWorkshop.Game.UserInterface.ListBox+ListItem].get_Item (Int32 index) [0x00000] in <filename unknown>:0 
at DaggerfallWorkshop.Game.UserInterface.ListBox.get_SelectedItem () [0x00000] in <filename unknown>:0 
at DaggerfallWorkshop.Game.UserInterface.DaggerfallTalkWindow.UpdateListboxTopic () [0x00000] in <filename unknown>:0 
at DaggerfallWorkshop.Game.TalkManager.AssembleTopicLists (Boolean isInstantRebuild) [0x00000] in <filename unknown>:0 
at DaggerfallWorkshop.Game.TalkManager.AddDialogForQuestInfoResource (UInt64 questID, System.String resourceName, QuestInfoResourceType resourceType, Boolean instantRebuildTopicLists) [0x00000] …
> fix an ArgumentOutOfRangeException

- Assets/Scripts/API/Arch3dFile.cs
This fixes the UV processing method. Previous changes I made in PR #1299 were not as robust as they are now.
It now seems DFU even does a better job at processing some of classic UV coordinates. See Bargain Gear Store in Ephesus for an example.
I reworked the method after the following considerations:
- Until proven otherwise, models which require some processing on there UV coords are always exterior buildings, so we can easily filter these since buildings model ids are below 1000.
- Only coordinates above 14335 or below -14335 need to be 'unpacked' (as was already guessed by Interkarma years ago). The only noticeable exception seems to be -7168, which I found on several building planes: this one has always to be processed as well. 
- The correct texture coordinate is given by …
> Rework the UV unpacking method

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
* Moved private methods to `Private Methods` regions.
* Default spacing.
* Removed empty lines.
* Use PascalCase for regions and public members.
* Use camelCase for private fields.
* Use AutoProperties.
* Use the same formatting for all properties.
* Use readonly.
* Reviewed documentation for public members.
* Setter of `Mod.LoadPriority` is now internal.
> Mod System: Cleanup and improved documentation

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
- Assets/StreamingAssets/Text/GameSettings.txt
Wagons can now be accessed when player is within 10m of a dungeon exit.
The access wagon prompt can be disabled in settings.
Added messages informing player why the wagon button does nothing in inventory window.
> Dungeon wagon prompt setting

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Fix issue reported [here](https://www.reddit.com/r/daggerfallunity/comments/bkb1hv/a_question_about_the_resolution_settings_from_the/):  Daggerfall Unity always uses the highest supported so there is no need to show multiple values on UI.
> Do not show the same resolution with multiple refresh rates

- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
PR adds the notebook to deleted files.
Noticed in unity that save folders were not being deleted because they weren't empty. Found they all had one NotebookData.txt file. Adding this line removed the folders and logging errors.
> [SaveLoadManager] Delete Notebook File

- Assets/Scripts/Utility/TextureReader.cs
Batched billboards must have the same size for albedo and emission maps because atlas rects are shared.
> Ensure size of emission map for lights is the same as albedo

- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterface/PaperDoll.cs
- Assets/Scripts/Game/Utility/PaperDollRenderer.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/AssetInjection/XMLManager.cs
Enabled injection of custom textures to new paperdoll renderer. Additional textures named `textureName_Mask` can provide masking defined on alpha channel. Maks provided via assetbundles should use texture type _Single Channel_ to automatically pick format with minimum amount of memory used.
> Enable texture override for paperdoll

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Thinking again about an old patch (#1063), I think it makes more sense to make spell merchant window behavior consistent with all others, and not close on double-click.
On the other hand, display available money since that's an important information for the player. It lands perfectly at the right of cost, just like in standard merchants interface.
> Spell merchant consistency

- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/Questing/Actions/CreateFoe.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/Utility/FoeSpawner.cs
First goal is to make Tedious Travel work more reliably at high time compressions, but future mods could also benefit from this event.
Also, make rest window subscribe to this event to remove some specific code.
> generate OnEncounter event that mods can subscribe to

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
- Assets/Scripts/Utility/MacroHelper.cs
Make the greeting text selection process the same as in classic, with some improvements and a few bug fixes. To do this, I reverse engineered the 3 classic functions used to get the greeting text.
Now to explain the changes I made: in classic, a faction related (mostly guild related in fact) greeting is selected each time the player talks to an NPC which is not a member of a faction of type 14 or 15, i.e. "Court of" or "People of" current region. Then, the correct greeting text is given by checking all player guild affiliations, especially guild enemies and allies. I did the same in DFU, fixing two bugs of the original function.
I also improved the overall selection process in two ways:
- I decided to exclude unique NPCs whose first parent is a province, as this gave weird greetings in …
> Make NPC greetings selection match classic

- Assets/Scripts/Game/PlayerActivate.cs
This triggers the guard spawner after the player says "yes" to the "This looks like private property" dialog box.  Shop interiors are relatively small so the spawner doesn't always find a minimum distance, especially in one-room shops.
I'm thinking of doing an overhaul of interior guard spawns so they are handled in a more reliable way that also makes more gameplay sense.  I'll do that in a separate PR unless you would like to have that in this one.
> Spawn guards after rifling through private property

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/PlayerMouseLook.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/WeaponBasics.cs
- Assets/StreamingAssets/Text/GameSettings.txt
Adds a 2 stage process for shooting arrows with a bow. Hold down right mouse to draw and release to fire. Uses 3 frames of animation which were previously unused due to single stage attack animation process.
1) Draw the bow. frames 0-3
2) Release the arrow. frames 4-6
Set BowDrawback true to enable. Left click releases without firing arrow, this will automatically happen after 10s anyway.
This came out of the discussion here https://forums.dfworkshop.net/viewtopic.php?f=12&t=1748. I had intended the whole thing to be in a mod, but after looking at the weapon handling and animation code, it feels like it would need a massive amount of re-factoring to achieve this. So, I've put this into the core DFU codebase as an option. 
I think it has as much value as click to attack, and is a nice …
> Implement bow drawback option

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Internal/DaggerfallStaticDoors.cs
1. When in a shop, guards will now spawn at the lowest entrance.
2. Stealing private property now tallies Pickpocket and does a check against it.  If the check fails, guards are spawned and PC is accused of stealing.
> Refine indoor guard spawns and private property theft

- Assets/Shaders/DaggerfallTilemapTextureArray.shader
I did perceptual tests on modded terrain textures, then some analysis, using DREAM RC4 and no post processing mod on my screen (1080p).
First I checked that a mipmap level of 8.0 looked smooth in the distance: that works.
Then I checked how far the transition between level 7.0 and 8.0 could be pushed away before aliasing appears. In my tests, 50.0 was about right.
Then I checked how far the transition between level 0.0 and 7.0 could be pushed away before aliasing appears. In my tests, 4.5 was close to the max.
But what's the scale between the two? I assume the goal is to keep the angular diameter of pixels about constant. Pixel widths varies according to 1/d, but their height decreases faster because the surface also appears more and more tilted (from camera point of view).
I spare you …
> adjust TilemapTextureArray mipmap levels to remove most aliasing

- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
Implementation of a horse mount (or dismount when already on a horse/cart) for G key. This required some changes to the `TransportManager` to make sure transportation change conditions are kept in sync via a public API. `ToggleMount()` can easily mount or dismount a horse if conditions are met.
I can optionally get rid of the G key shortcut, if wanted.
NOTE:
Call to `ToggleMount()` works even inside of buildings or dungeons. This behaviour was kept intentionally to allow mods to use mounts even inside interiors. Of course, the front-end logic defaults to classic behaviour and only allows you to toggle mount in the exterior.
Introduced an option in the Enhancements section called `HorseMountShortcut`.
> Refactor TransportManager

- Assets/Shaders/DaggerfallTilemapTextureArray.shader
Hopefully I fixed the seams problem. The trick was to make ddx and ddy derive a function that varies similarly to UV * texturesize, but without its discontinuities: the function at the origin of UV value, but before tile index/tile UV coords mapping (I called it unwrappedUV in the code).
(it seems there has been a long story of trying similar stuff, so I hope I'm not hitting the same shaders bug as everyone else...)
> Tilemap ddx ddy mipmap

- Assets/Scripts/Game/TalkManager.cs
Matched to classic: NPCs whose faction is "People of" or "Court of" current region retain their original social group even if they use their parent region faction data to interract with the player.
This fixes the bug mentioned by @petchema here: https://forums.dfworkshop.net/viewtopic.php?f=24&p=25816#p25816
> Retain commoners social group

- Assets/Scripts/Game/Automap.cs
- markers are now correctly restored on dungeon exit and reentering
- markers are now correctly removed when exiting dungeons (no left-over artifacts from other dungeons)
I am sorry for this stupid oversights on my side
If it is possible to create new test builds with this fix that would be awesome ;)
> fixed bugs with user note markers and teleporter markers:

- Assets/Scripts/Internal/PlayerGPS.cs
solves bug report mentioned in https://forums.dfworkshop.net/viewtopic.php?f=24&t=2227
moved player house name handling into function GetBuildingDiscoveryData
so all residence name resolving is done in this function now
> fixed bug with named residence not being resolved correctly on info click

- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/Scripts/Game/UserInterface/SpellIconCollection.cs
Spell icon packs can be imported from mods when files are added to a folder name **SpellIcons**. During mod building, directory of selected files are matched and results, if any, are automatically added to `SpellIcons` array of `Contributes` property inside mod manifest file.
This process allows to provide icon packs (and possibly other assets in the future) in the same way for both mods and loose files, doing all the work at build-time rather than run-time where it could affect performance.
This is an example of a result manifest file.
```json
{
"ModTitle": "Example Spell Icons pack",
"ModVersion": "",
"ModAuthor": "",
"ContactInfo": "",
"DFUnity_Version": "0.8",
"ModDescription": "Adds a spell icons pack.",
"GUID": "2f923d7b-b8e5-4db6-a535-6655896b87fc",
"Files": [ …
```
> Import spell icon packs from mods

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
use AudioSource's minDistance to play distant ambient sounds at correct volume
- Simplified thunder sound: instead of enforcing source direction using a coroutine, put the sound source much further and compensate with high minDistance.
- Sounds are not always located within minDistance, so there's some volume randomization that wasn't there before; That can be adjusted if you feel that volume so too often too low;
- Increase ambient AudioSource's 3D spread, so that the hear opposite to the sound source gets more input; Specially in dungeons, to simulate environment reverberation and increase perceived volume.
This is a minimal patch, for example only one ambient sound can be played at any moment (not that PlayOneShot cannot be used several times simultaneously on an AudioSource, but all …
> Ambient sounds spatialization

- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
Enumerated saves were not updated when a new savegame was created. This made QuickLoad not working immediately after using QuickSave for the first time (QuickLoad worked, however, when restarting DFU).
> Update enumerated saves when a new savegame is created

- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
Much easier to pop off the stack before pushing any subsequent windows. This fixes the issues I had with teleport item for archaeologists mod.
Also includes a fix so TG & BD membership to only occur if the joining quest is successful.
> Fix for closing windows when using magic items

- Assets/Shaders/DaggerfallTilemapTextureArray.shader
Seems still almost aliasing free according to visual tests.
Implementing mipmap bias by hand, does standard Texture.mipmapBias apply to custom surface shaders? And if so, where should it be set?
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&t=37&p=26322#p26322
> apply a -0.5 mipmap bias to DaggerfallTilemapTextureArray shader

- Assets/Scripts/Game/FPSWeapon.cs
Repeat wrapmode causes lines to be visible on borders.
Using mirror instead of clamp to support left handed (mirrored) weapons.
> Fix weapon image pixel bleeding

- Assets/Scripts/Terrain/StreamingWorld.cs
After some fast travel, player position could only be adjusted upward; When terrain was very steep downward it could result in fall damage (and death). 
(Maybe there's a use case I'm not aware of for this behavior?)
Make adjustment unconditional; Height formula adjusted to (slightly higher) PlayerMotor.FixStanding formula.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2307
> Fast travel to ground level, always

- Assets/Scripts/Editor/TextureArrayWizard.cs
- Assets/Scripts/Editor/TextureArrayWizard.cs.meta
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/TextureReader.cs
Terrain texture arrays can now also be created inside the Unity Editor and
provided via mods as assets. This brings the following benefits:
* Minor improvements for memory management and initialization times. The individual source
textures don't need to exist at runtime, only the final texture array.
* Failure due to resolution, format or mipmaps mismatches are not possible at
runtime. A texture array is only rejected if slice count is incorrect.
* Runtime creation of texture arrays requires CopyTexture support or Read/Write flag
(with increased memory usage). Texture arrays shipped as assets works on any platform
that support this feature alone.
The disadvantage is the introduction of an additional step in mod creation
workflow. For this reason is introduced as an optional feature.
This …
> Import Texture Arrays as assets

- Assets/Shaders/DaggerfallTilemapTextureArray.shader
(patch on top of #1350 )
Trying (unsuccessfully) to fix seams problem, I did lot of small cleanups on shader code:
- Remove commented code (that's what versioning is for);
- Added TEXCOORDn annotations on Input
- used UNITY_SAMPLE_TEX2DARRAY_SAMPLER_LOD to share SamplerState between albedo and normal texture lookups
- added inline annotation to GetMipLevel (but I suppose the compiler must have guessed that much already)
- replaced fmod(x, 1.0) with frac(x)
- replaced tile rotation branching with matrices. I could have replaced matrix product and vector addition with just a matrix product, but I would have to promote matrix to float3x3 because OpenGL ES 2.0 doesn't support non-square matrices:
static float3x3 rotations[4] = {
float3x3(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0), …
> DaggerfallTilemapTextureArray.shader cleanups

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Patch on top of #1341 and #1342 
When opening the inventory by keypress near dungeon exit in no DungeonExitWagonPrompt mode, do not only allow access to the wagon but also auto-select it.
This makes this mode actually more convenient than prompt mode.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=12&t=2098&start=10#p26151
> Faster noprompt wagon access

- Assets/Scripts/Internal/DaggerfallInterior.cs
This is not exactly as classic but as close as I can get without reverse engineering why they appear is desert FGs but no where else.
I think this is close enough now having spent a few hours testing various buildings in classic.
> Restrict building interior loot piles to TG, DB and pubs

- Assets/Scripts/API/BiogFileMCP.cs
- Assets/Scripts/Utility/MacroHelper.cs
Macro %bn is used only for Nightblade biography history. It expands to a random name using player character race and a random gender.
But as the occupation of the corresponding individual is given by the %q8 macro which expands to a neutral or (mostly) masculine noun (priest, wizard, sorceror, revolutionary, anarchist, warlord, robber baron, assassin), I chose to differ from classic and force the gender to male.
I also fixed MacroHelper.GetNameBank to match classic so it now returns a Khajiit name for Khajiits and an Imperial name for Argonians.
> Handle %bn (biography name) macro expansion

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBookReaderWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Internal/DaggerfallBookshelf.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Utility/AssetInjection/BookReplacement.cs
- Assets/Scripts/Utility/TextProvider.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
Preliminary support for import of custom books for bookshelves. 
1. A book file is positioned inside _StreamingAssets\Books_. For example `StreamingAssets\Books\example-book.TXT`.
2. A map table is positioned inside _StreamingAssets\Books\Mapping_. For example:
```json
[
{
"Name": "example-book",
"Title": "An Example Book"
}
]
```
This table has two purposes: distinguish classic books replacements from additional custom books (could also have done this with a separate folder) and announces book titles before importing the actual resources. Custom subfolders can potentially be supported in the future.
3.  Each book is associated to a numeric id (only valid for the session) starting from 112 and added to **bookIDNameMapping** in ItemHelper.
1. Add files as explained above.
2. Edit …
> Experimental support for custom books

- Assets/Scripts/Game/EnablePlayerTorch.cs
It has been reported that my lazy flickering guttering effect used to warn players (using player based torches) that a light source is running low on fuel is a potentially very serious epilepsy trigger. We must not release an alpha with that code, I would be pretty mortified if someone had a seizure because of it.
I've been less lazy now (but still pretty lazy) and implemented a very simple cosine based effect. Looks pretty decent actually for 1 extra variable and 2 lines of code!
Hopefully this will be fine, I will await feedback from the reporter, it's definitely not a fast stobe like flickery effect anymore anyway!
> URGENT FOR ALPHA BUILD: Improve guttering effect on player torch

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
Improve the way NPCs react to player questions.
I decided to give Streetwise and Etiquette more weight by setting reaction modifiers related to NPC social groups. For example, talking bluntly to a Noble or Scholar will now give a penalty, while doing the same with a Commoner or a member of the Underworld (Thieves Guild or Assassin) will give a bonus. Of course, using Etiquette through a polite tone will trigger the exact opposite. Merchants, as a sort of middle class, will be unaffected by this change. I gave them a default modifier of +5 when using both skills which makes them behave the same as before as I also changed skill check result: failing will give a penalty of -10 while succeeding will give +5.
I also lowered the required value to get the best NPC reaction, though it's still …
> NPC reactions enhancement

- Assets/StreamingAssets/Quests/N0B00Y16.txt
- Assets/StreamingAssets/Quests/O0B00Y01.txt
S.07 failed to fire, wasn't recognizing the condition. One-line fix. Quest has another problem regarding failure line: if you talk to the merchant without opening the chest, you'll never get a success message afterward. Have tried to fix that problem and can't.
> Fix N0B00Y16 "open chest"

- Assets/Scripts/Utility/MacroHelper.cs
Only used in Thieves Guild quest O0B00Y01. Return the name of current region ruler.
Edit: actually it's also used in some non quest rumors.
> Handle %nrn macro expansion

- Assets/Scripts/Terrain/StreamingWorld.cs
Replacement for PR #1359 
It adds a "grounded" boolean parameter tto RepositionPlayer() to force new position to be on the ground; That parameter is used when the player is relocated to a StartMarker using a cardinal direction, which include fast travel case but should always be a safe thing to do.
I'll keep testing it, but I'm releasing the PR so that more people can test it.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2307
> make sure you're grounded after fast travel

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
Without that patch, looping sounds (crickets, rain) stay at the same volume until they're stopped.
(Effect sounds are less problematic because they don't last as long).
This adjust looping sounds immediately; Volume is adjusted with each frame, just like music in DaggerfallSongPlayer. A more elegant solution could involve AudioMixers...
Forums: https://forums.dfworkshop.net/viewtopic.php?f=14&t=1333&p=28652#p28648
> Immediately adjust looping sounds volume

- Assets/StreamingAssets/Tables/QuestList-Classic.txt
Wrongly converted when quest dispensing for guilds was changed to match classic. Coven quests are all implemented as non-member since covens cannot be joined, and that means rank cannot be used. Switching back to reputation.
> Fix Witches coven quests

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Internal/DaggerfallStaticDoors.cs
DaggerfallStaticDoors.FindClosestDoorToPlayer() was returning true if all doors were filtered out by requiredDoorType.
When this happened, doorPosOut would still have its default value of playerPos, making DaggerfallInventoryWindow believe that indeed a door was found close to the player.
This only happens in some dungeons. The issue was first seen in a stream, in the Citadel of Hawking, Daggerfall:
https://www.twitch.tv/videos/461269349?t=01h50m27s
> FindClosestDoorToPlayer() to return false if all doors are filtered out

- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Internal/PlayerGPS.cs
First of all: PLEASE help me to test this out before merging - I tested quite a bit and it seems to work ok, but the devil does not sleep ;)
now regarding the changes:
reworked the building discovery system a bit - no fear - nothing too heavy.
just tried to split stuff a bit better between functions:
- DiscoverBuilding is now the only function that really changes discovery state (except one small exception about player house name which I plan to fix as well)
- GetDiscoveredBuilding only uses this data and does not compute any building names on its own (except player house name)
- GetBuildingDiscoveryData gets initial building information from current location (no building name expansion like quest-named residences, no thieves guild name, etc.) - this function is not used directly by other …
> building discovery rework

- Assets/Scripts/Game/Automap.cs
(https://github.com/Interkarma/daggerfall-unity/issues/1398)
also contains a small fix to a potential problem with teleporter markers - also remaining active in scene incorrectly
code clean up: added SetActivationStateOfMapObjects function which is now used instead of duplicate code
> bug fix for issue #1398

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
When initiating fast travel from notebook, update travel map title so that region name shows up correctly.
Screenshot of the problem:
> update region name from notebook fast travel

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/DaggerfallUIMessages.cs
Having to go see a potion maker makes potions brewing very cumbersome, if not useless.
Players that don't mind bending classic rules can use that command to brew potions from any place.
(Requested by Shinino on Discord)
> add console command to open the potion maker

- Assets/Scripts/Game/WeaponManager.cs
Fix for bug https://forums.dfworkshop.net/viewtopic.php?f=24&t=2219
I stepped through it with a debugger and the splash for arrows against enemies was being spawned at 0,0,0.
So I copied the NPC arrow hitting logic and now it works again.
> Fix arrow blood splash position

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
I tested the behaviour in classic and it seems that fast travel for characters with `Damage from Sunlight` disadvantage behave just like fast travel for vampires (in terms of arrival).
> Fix fast travel for characters with Damage from Sunlight disadvantage

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
However, keep selecting the WAGON (instead of nothing) when opening the inventory explicitly near a dungeon entrance when DungeonExitWagonPrompt is off.
This is a trade-off @ajrb and I want to try concerning proximity wagon access,
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&t=2490
> always select EQUIP when opening inventory explicitly

- Assets/Scripts/Game/Questing/QuestMCP.cs
Handle `DaggerfallWorkshop.Game.Questing.Quest.LastPlaceReferenced` returning null.
> 1383 Fix crash with %di getting direction without location.

- Assets/Scripts/Game/Questing/Person.cs
Fixes messages like `Some weird-acting =contact_ in __contact_, %di of here.`
__contact_ would be filled by Person but not added as Quest.LastPlaceReferenced, which %di uses.
> 1383 Add quest location reference from Person

- Assets/Scripts/Game/TalkManager.cs
fix for answer rumors (answers to tell me about topic) being incorrectly added to "any news" rumors
this issue leaded to some quests being easier to solve than intended (or in worst case trivial to solve)
tested with non-member mages guild quest with missing book (N0C00Y10)
answer rumors (given as answers to "tell me about" topics) defined in the quest source in the line a quest resource is defined, usually after "anyInfo" with the command "rumors"
answer rumors should not be confused with "any news" rumors (can be populated with RumorsDuringQuest and RumorMill quest action)
answer rumors must not appear as answer to "any news" questions.
usually "any news" answers are the less informative ones, resource related anyInfo and rumors are more specific but anyInfo are meant to be correct and …
> fix for answer rumors (answers to tell me about topic) being incorrectly added to "any news" rumors

- Assets/Scripts/Game/Questing/Actions/HaveItem.cs
- Assets/StreamingAssets/Quests/N0B00Y16.txt
Fix for (among others probably) #1369 
`have _item_ set _state_` is only supposed to _enable_ `_state_`, not disable it.
As per 
https://en.uesp.net/wiki/Daggerfall:Quest_pseudo-codes#Pseudo-code_Type_0x46_.2F_70_.28PC_has_Items.29_.5B5_sub-records.5D
and 
https://www.dfworkshop.net/static_files/questing-source-docs.html#usingitems
> 1369 have item should not clear target

- Assets/Scripts/Terrain/StreamingWorld.cs
Third time the charm?
Tested:
- fast traveling to town
- going in and out of buildings (including out of elevated door)
- going in and out of dungeons
- going to and from ship
- teleported by mages guild service
- expelled from town by court
- "location" command
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2521
> don't ground player when onboarding ship

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
When clicking on WAGON button from inside a dungeon when you had no wagon it was not logical to display a message you couldn't access it because you were to far from an entrance.
So, check if you have a wagon first, whether it's reachable second.
Also, add a wagon ownership test that was missing in proximity access since #1343 or even earlier
ownership | in dungeon | proximity |  
-- | -- | -- | --
F | F |   | wagon button not selected, « You don’t own a wagon »
F | F |   | --
F | T | F | wagon button not selected, « You don’t own a wagon »
F | T | T | wagon button not selected, « You don’t own a wagon »
T | F |   | wagon button not selected, but selectable
T | F |   | --
T | T | F | wagon button not selected, « The exit is too far away »
T | T | T | wagon button autoselected (#1416)
> Swap wagon access tests
