Interkarma/daggerfall-unity

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
Fix NPC reactions issues mentioned on the forums, especially here: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2410&start=10#p29493
This restores random seed based on current NPC guid so each NPC in the same town will now react differently as this was already the case before PR #1370.
I also lowered the difficulty level required to get a successfull answer when asking for people location with low personality characters, balancing this change by also lowering the bonus given to find a location (+5 instead of +10). Still, it's much more difficult than classic to find people, where we nearly always get a successful answer even with a very low personality, because of an incorrectly applied modifier (classic seems to always apply +10, regardless of the kind of question).
As with my …
> Fix NPC talk reactions

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
I get annoyed when resting in a guild for npcs to arrive and have to exit and reenter the building for them to show up. Added a check when rest dialog is dismissed.
> Update npc presence when rest dialog dismissed

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/Utility/SceneControl.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
`-window-mode exclusive` arg wasn't working, so I added it as a proper option.
> Add exclusive fullscreen checkbox to advanced video options

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/TalkManager.cs
Sheogorath should not be activated like a normal NPC, neither in information nor any other mode. As this is also the case for all static NPCs attached to "ShowText" or "ShowTextWithInput" action, I just moved the already available check from TalkManager to PlayerActivate and included "ShowText" action flag into it.
In information mode, this matches classic behavior where we never get any display name for this kind of NPC.
In other modes (steal, grab and talk), this fixes an exception which popups for Sheogorath due to the fact both his instances have an invalid faction ID.
Fix #1456
> Fix issues when activating Sheogorath

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
It was only being set when window was setup, and once set the anim was either there or not for the rest of the session.
See: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2610
> Fix for coin anim on inventory window

- Assets/Scripts/Game/Questing/Person.cs
Testcase: quest K0C00Y04 has 2 Npcs in Group_7
Story and timer seem to indicate these have to be local and the quest itself doesn't place them anywhere.
PR makes not only -3 and -4 local, but also -5 and lower. (-8 is individual ans is already always local)
Original report: https://forums.dfworkshop.net/viewtopic.php?f=29&t=2331
> Make more npc types local residents.

- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Questing/Item.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=25&t=1098&start=30#p28634
Implements subclasses for magic items (class 4) in quests.
Testcase:
`startquest S0000501`
That quest uses 
`Item _reward1_ item class 4 subclass 26`
which should generate a random "Unrestrainable" item as \_reward1\_
> Allow magic item subclass definition in quests

- Assets/StreamingAssets/Quests/M0B00Y16.txt
\_S.09\_ = there is no villager to escort.
\_victim\_ = there is a villager to escort.
\_yes\_ = you agreed to escort the villager.
\_S.13\_ = you completed the villager escort.
\_success\_ indicates you killed the giant and returned to the questgiver.
So the quest was ending when you killed the giant, returned to the questgiver, agreed to escort the villager but did not complete the escort yet.
Source: https://forums.dfworkshop.net/viewtopic.php?f=25&t=2557
> Don't end quest when not done with escorting villager.

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
Minimal code changes approach to prevent vampires burning up in prison.
A larger change would be to tie make the court window count as IsPlayerInside, but since the court window explicitly transitions to exterior and the player inside/outside is tightly coupled with the transitions I decided to go another route.
Source: https://www.reddit.com/r/daggerfallunity/comments/cwcsrb/is_going_to_prison_supposed_to_kill_vampires/
https://forums.dfworkshop.net/viewtopic.php?f=24&t=2605
> Prevent vampire sun damage in prison.

- Assets/StreamingAssets/Quests/A0C10Y05.txt
Fix for part of the issues reported at https://forums.dfworkshop.net/viewtopic.php?f=29&t=2134
It was another execution order issue in the template generated quest.
In classic the click on the priest would be cleared again unless the betrothed was also clicked, thus preventing the whole "give pc gold, etc" from executing.
> Only succeed the quest when both priest and betrothed have been clicked.

- Assets/Shaders/DaggerfallTilemapTextureArray.shader
It does not fix shadows issues or anything else, but still that's a noticeable improvement for people that have to run DFU on that hardware.
That looks like a very inexpensive workaround (most likely lost in the noise), and it seems to work fine on my regular hardware (from mathematical standpoint it also feels right to use rounding instead of floor() to make sure int -> float -> int conversions are robust), so maybe it can be added directly into the standard shader?
Otherwise, say if the risk of regression is deemed too high, it could be added to a variant of the shader, so it could be enabled at runtime; But I don't know how to do such things...
Tested on Intel HD-3000 by Siva Machina on Discord;
Tested on nVidia GTX-960 by myself (for lack of regression)
Forums: …
> workaround for "water everywhere" texture issue on low-end hardware

- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
3 modifications:
- wait for the weapon smith MessageBox to be closed before opening the inventory;
- make sure an item is picked from the list of proposed items (and, say, not from the wagon) before closing the inventory;
- close all transient windows before closing the inventory.
Use case for the latter: the player selects to EQUIP some item he cannot equip (forbidden material, for example). EquipItem() opens a MessageBox to tell it's not possible, chooseOne closes to top window which is the MessageBox, and the inventory stays open.
Another implementation would be to set a flag, and close the inventory in Update() when all transients have been closed by the player. The benefit is that the player would see that the item couldn't be equipped.
> Harden received armor

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Picking up previously dropped quest items would not unset the dropped state because they come from Loot, not Dropped.
- Moving quest Items to Loot piles or Merchants would not set the dropped state.
- Picking up quest items without AllowDrop would not unset the dropped state.
- Bitwise or in stead of logical or could cause null reference.
Test quest:
```
- Test quest for dropping and picking up quest items
Quest: __TEST001
QRC:
QBN:
Place _house_ local house2
Item _treasure_ portrait
place item _treasure_ at _house_
_pickedup_ task:
clicked item _treasure_
clear _dropped_
_dropped_ task:
dropped _treasure_ at _house_
clear _pickedup_
```
> Quest item dropping fixes

- Assets/Scripts/Utility/RMBLayout.cs
Found while reverse engineering FALL.EXE to understand map buildings to blocks building mapping process.
Classic uses this exact same runtime patch for some Order of the Raven buildings. These can be found  in Dwynnen or Whitewold for example, and aren't colored in blue on the map.
This is really hacky stuff but it works!
> Implement classic tweak regarding some Order of the Raven buildings

- Assets/Prefabs/Player/PlayerAdvanced.prefab
- Assets/Prefabs/Player/PlayerStandalone.prefab
- Assets/Scripts/Game/Player/AcrobatMotor.cs
- Assets/Scripts/Game/PlayerHealth.cs
Tested using classic Daggerfall, falling from different platforms of Scourg Barrow and Daggerfall Castle.
I repeated some of the measures with a different encumbrance, with a totally different character (68 HP instead of 400 HP) and saw no difference in damage, so I assume the formula is only based on height. 
I got the exact same results with DOSBox's CPU cycles at 50k or 60k, but slightly less at 30k, so it's probably somewhat framerate dependant. Results below and patch match 50k and 60k cpu cycles measures, mainly because I tested the 30k cpu cycles at the last moment.
Threshold seems to be about 5 height units (no fall damage from the falling off the bottom of a crenel above Daggerfall Castle main entrance to the platform in front of the entrance, but small damage is falling slightly …
> fall damage adjustments

- Assets/StreamingAssets/Quests/S0000009.txt
Messages out-of-order bug fixed.
See https://en.uesp.net/wiki/Daggerfall:Elysana%27s_Betrayal#Bugs
and https://forums.dfworkshop.net/viewtopic.php?f=29&t=2192
Also fixed typo from classic.
Renamed some variables along the way to make working with the quest easier.
> Fix classic bug and clean up readability

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Allows the direct stat mods to be able to be used outside the effect bundle system. Without this fix any application of direct stat mod value will accumulate until the player has at least 1 effect bundle applied.
I looked at the prototype vampire class VampiricFortifyEffect and copied it's way of adjusting stats. Unfortunately it didn't work without this fix since the direct stat array is not cleared unless the entity has a bundle associated.
See https://github.com/ajrb/dfunity-mods/blob/encumbrance/RoleplayRealism/Scripts/_startupMod.cs and look at the EncumbranceEffects_OnNewMagicRound() method at the bottom. 
@Interkarma I separated this from the other mod support changes in case this is problematic. I can't see any issues. I did consider creating an effect bundle but since the effect …
> Adjust direct stat, skill and reaction mod mechanism

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Only occurred the first time inventory used if not in a dungeon.
I also simplified the code for wagon access because I simply could not follow it with my tired old brain. I literally spent over an hour getting confused so I had to change the logic for my own sanity. Sorry Pango, my brain gets confused easily sometimes. I think it behaves the same unless I missed something in testing. Could you check you're happy with it please?
> Fix bug where no action mode selected first time inventory accessed

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Fix for first time inventory opens (again, in dungeons near exits thsi time)
Fix for clicking on loot containers near an exit
> Fix inv behaviour near exit

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs
In classic Daggerfall, if you cast Recall by mistake you have no way to cancel it and have to choose between losing your anchor or teleporting right away. This usually ends up in a game reload.
I suggest to allow to cancel it, unless there's some drawback for allowing that.
Magicka refund would be even more generous, but being able to cancel Recall is what really matters...
Forums: https://forums.dfworkshop.net/viewtopic.php?f=23&t=2690
> allow to cancel Recall spell (QoL)

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Fix for #1505 
Crosshair would stay at same position when moving the map below it with the on-screen arrows.
> Update crosshair on travelmap

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/EnemyMotor.cs
Restored point-blank range in which enemies don't use ranged attacks but made it 6m rather than the original 9m.
Also changed the random checks which were using classic random for non-deterministic purposes.
> Enemies shooting point-blank

- Assets/Scripts/Internal/DaggerfallInterior.cs
Interior were using raw block data, not block data processed through RMBLayout.GetLocationBuildingData.
This fixes this issue I discovered after entering the Order of the Raven building in Whitewold after the patch I made for it in PR #1489.
> Fix interiors to use correct block data

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
In the case a rumor involves two factions, previous exclusions of generic factions made in PR #1479 were valid only for the first one. Now, same filters also applies to the second faction.
Also added a check to ensure both factions are not the same, so a faction cannot be its own enemy anymore: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2676#p31098
> Rumor mill fixes

- Assets/Scripts/Utility/MacroHelper.cs
- Assets/StreamingAssets/Factions/FACTION.TXT
In rumors involving a new ruler, when the old one was mentioned, he used the same name. Fixed this by matching classic: random old name uses the HIWORD part of the ruler name seed while new name uses the LOWORD.
FACTION.TXT was tweaked so the following factions always have the same ruler (as intended) and are therefore excluded from "new ruler chance":
Anticlere: Lady Doryanna Flyte
Isle of Balfiera: Medora
Lainlyn: Baron Shrike
Orsinium: Gortwog
> Fix old ruler name being identical to new one

- Assets/Scripts/Game/Automap.cs
Wide dungeons such as Scourg Barrow and the Mantellan Crux were rendering incorrectly on the micro map when modules were offset by more than 3 down or to the right.  This simply moves the origin to give them more room.
> Fix micro map rendering incorrectly in large dungeons

- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
Add ability to register custom item usage handlers for vanilla items.
Allow ship availiability to be defined by mods.
Will be used by next version of R&R modpack for bandage usage and only allowing ships to be boarded in port towns.
> Mod support for item usage and ship availiablity

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Seems to confuse some people, that input some amount, close the window and expect the transaction to have happened.
Another solution would be to open a dialog box to input transaction amounts; But it doesn't match classic screens.
> prevent clicking on EXIT while banking amount input in progress

- Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
Previously, Thieves Guild or Dark Brotherhood instances were never garbage collected because `PlayerGPS` and `StreamingWorld` kept strong references to them through events `OnEnterLocationRect` and `OnAvailableLocationGameObject`. This, because unsubscribing to these events took place in both class destructors, so, to summarize, it never happened.
This resulted in the following behavior: if you loaded a savegame with a character who was a member of any of these guilds, then loaded another savegame from another character who wasn't, you would still discover the guild hideouts using the automap.
Unfortunately, any game saved prior to this fix may still have the guilds available on the automap, this because all discovered buildings are saved.
> Fix some circular dependencies so TG and DB are proplerly GC'ed

- Assets/Scripts/Game/PlayerActivate.cs
Actually don't display the message if player is a member of the guild, as classic does. I wasn't able to test the case where player is not a member as in DFU, it seems Thieves Guild and Dark Brotherhood hideouts are always locked in this case.
Edit. @ajrb confirmed that contrary to what classic does, DFU behavior is to always lock Thieves Guild and Dark Brotherhood hideouts when player is not a guild member, so I simplified the check.
> Don't display a message when entering a TG or DB

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
Enable testing of paperdoll images as requested by #1543.
Adds all types of equippable items for the current character gender/race, but doesn't add variants.
Also extended dumpblock command to be able to dump dungeon blocks, and added a dumplocation command to dump location records.
> Add all equippable items command

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Guilds/IGuild.cs
- Assets/Scripts/Game/Guilds/IGuild.cs.meta
- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
- Assets/Scripts/Game/Guilds/Temple.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Internal/DaggerfallBookshelf.cs
* **Extract IGuild interface and use it instead of Guild abstract class** - This will allow mods to be more easily created with guild implementations that deviate from default vanilla guild behaviour. Note there are still some constraints, like 9 rank based etc.
* **Allow vanilla guilds to be overridden** - by registering a new implementation extended from core or completely new implementations.
* **Move save/new event unregistering into guild classes** - This is so that GuildManager.ClearMembershipData() does not call Leave() to unregister the guild events. This is because the clear method is for clearing memberships while loading etc (happens twice) and is not for when the player is actually leaving the guild. If mods add behaviour for leaving, it should not be initiated when just …
> Enable guild modding

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
Forum topic: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2681
This is one approach to fixing the reported issue.
It seems to work fine on the saves I have, but this definitely needs thorough testing for side-effects.
> Prevent game load from restoring players breath underwater

- Assets/Scripts/Game/Questing/Person.cs
- Assets/StreamingAssets/Quests/R0C10Y21.txt
- Assets/StreamingAssets/Quests/R0C20Y22.txt
Allow Daedra to be used as named NPC as per https://www.dfworkshop.net/static_files/questing-source-docs.html#permanentnpc
Also fix 2 broken quests that were using "named" to align an npc with a provice, which prevented them from loading.
> Quest person factions fix

- Assets/Scripts/Game/Player/FrictionMotor.cs
- Assets/Scripts/Game/PlayerMotor.cs
- smooth follower could be reset very often at high FPS because speed threshold was computed based on framerate instead of fixed updates
- unstick handling could trigger during movements tangential to the (world) origin
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2435&p=31737#p31728
> player smoother movements

- Assets/Scripts/Terrain/StreamingWorld.cs
- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Change 3d asset replacement for nature flats to only replace when terrain distance is <=1 for performance. At larger terrain distances, the standard DFU billboard system is still used since it's highly efficient and billboards are more than sufficient at this distance.
The nature flats used with standard DFU billboarding can still be replaced with high-res/different images.
- Update natures on terrains moving in/out of dist 1.
- Only do extra updates once any nature mesh replacement has been found.
- Ensure nature mesh replacement doesn't change nature placement. (bugfix)
> Change nature 3d asset replacement to limit performance hit

- Assets/Scripts/Game/AmbientEffectsPlayer.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Diseases/LycanthropyInfection.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Diseases/VampirismInfection.cs
- Assets/Scripts/Game/PlayerMouseLook.cs
- Assets/Scripts/Game/Questing/Actions/PlayVideo.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
- Assets/Scripts/Internal/DaggerfallSongPlayer.cs
- stop digitalized music (only MIDI synthesis was muted);
- stop ambient loop sounds
- videos played by quests can only be interrupted by Escape key. This should prevent mouse clicks from accidentally closing the video.
- implement HideCursor. This requires some cooperation with PlayerMouseLook that constantly updates mouse cursor visibility. I'm not sure how to best interact with it though
> make sure videos play under best conditions

- Assets/Scripts/Game/Automap.cs
My previous PR fixed the micromap for some dungeons but not all.  This increases the size of the micromap so that dungeon blocks won't run off the end of the texture.
> Fix micromap size

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
It seems to no longer work correctly with recent Unity, it's becoming a way for players to shoot themselves in the foot, so drop it altogether.
Are there anything to remove beside camera.renderingPath tweak?
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2183
> remove LegacyDeferred setting

- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/RMBLayout.cs
A clean commit with all changes to the existing core system
-3D props can now be rotated in X and Z. Default is set to 0 so it doesn't affect vanilla Assets
-Ladders will only be set to interactive if they are set uo as objectType 3 (propModel), all vanilla ladders are set up this way
-When replacing buildings, always use the original NameSeed, LocationID and Sector values
> Interior replacement core changes

- Assets/Scripts/API/Save/CharacterRecord.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/LycanthropyEffect.cs
Add the missing bonus to Jumping skill for werewolf or wereboar characters. I also fixed the UESP page in the meantime, which lacked this information (https://en.uesp.net/wiki/Daggerfall:Lycanthropy#Advantages).
> Boost Jumping for lycanthrope characters

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
raise transition event on teleporting out of dungeons so it can be handled by Persistent Dungeons mod.
/!\ It seems to work, but I won't pretend I understand all what's going  on.
Forums:
https://forums.dfworkshop.net/viewtopic.php?f=27&t=1667&p=29398#p29398
> raise event on teleporting out of dungeons

- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/TalkManagerMCP.cs
Fix the the first question greeting which was not updated when changing talking tone and also match classic behavior in using specific greeting names for NPCs (friend, mate, bud...) when NPC reaction is negative, see below:
Before:
After:
> Fix PC greeting text for the first question

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/API/DFLocation.cs
- Assets/Scripts/API/DFRegion.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
- Assets/Scripts/Utility/RDBLayout.cs
This extends the world data replacement system to handle:
- Adding new locations
- Changing existing locations
- Adding new dungeon blocks
- Changing existing dungeon blocks
- Updates to world data dump commands
Indexes are automatically assigned to any new locations or blocks added, and the system hooks into the content file readers to seamlessly layer new or altered world data into the DFU engine. New locations and blocks are fully integrated with all the Daggerfall game systems and should be able to be targets for quests, which I need to be able to exclude somehow in the future, and locations appear on the travel map and can be fast travelled to.
I will be documenting how to use this system on the forums over the coming days.
> Override world data for locations and dungeons

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsTypes.cs
- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
Adds support for live changes to mod settings. Mods that whish to implement this feature need to set property `Mod.LoadSettingsCallback` when they are started.
The value is a callback that receives an instance of `ModSettings` and `ModSettingsChange`, the latter being an holder for informations on the change event. Specifically, mods can use `bool ModSettingsChange.HasChanged(string section, string key)` to retrieve if a specific setting has changed.
For the time being, this feature is provided experimentally with a console command that opens a UI window.
Here's a simple example where the callback is assigned and immediately used for first time init where all settings are "changed". From now on, this method is also called automatically when settings are changed by player in game.
```cs …
```
> Support live changes to mod settings

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/UIWindowFactory.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
Instantiate persistent windows only when needed and allow re-instantiation. Allows persistent windows to be replaced.
Made members protected on rest and pause windows during testing. All windows will require protections to be modified, but I suggest we do them as required. I certainly don't want to do them all en masse.
Fix loading new locations from dfmod's. Have to wait until mod manager is initialised before checking for new locations and filling cache
Move mod manager singleton creation.
> Fixes for the upcoming build

- Assets/Scripts/Game/Questing/Message.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Utility/MacroHelper.cs
- Assets/StreamingAssets/Quests/K0C01Y00.txt
Correct macro %qdt expansion so each quest log entry now has its own time as in classic. Before that, it always resolved to quest start time.
Also fix quest K0C01Y00 message 1017 which always used the current time.
Note that this doesn't break current savegames as I added a check to ensure `LogEntry.dateTime` is not `null`. Else, it resolves to quest start time as before this fix.
> Fix %qdt macro expansion

- Assets/Scripts/Utility/RMBLayout.cs
This change meant that replacement buildings e.g. new guilds could take a guild hall entry out of the pool, messing up the matching algorithm.
This does mean that replacement classic guild buildings probably won't work without futher changes, but this fixes an issue where classic guilds are broken with the Archaeologists mod in DFU 0.10.8 - 0.10.10
> Revert change from PR#1557 to building matching

- Assets/Scripts/Game/TalkManager.cs
fix for bug described here: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2994
info:
the line removed was the culprit causing the bug described, it was necessary before the discovery rework but is no longer needed (since named residences get correctly undiscovered once quest is handed in (I checked this) and when I reworked discovery system last time I changed it so that it deletes the discovery list of orphaned entries on load and save (function PlayerGPS.RemoveUnnamedResidencesFromDiscoveryData) - so no need to handle orphaned entries here
> fix for bug: "opening quest log can clear marked residences from map"

- Assets/Scripts/Utility/AssetInjection/VideoReplacement.cs
.mp4 format is not supported by VideoPlayer on Linux:
https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html
Fix for #1550
> use .webm video format on Linux

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
LoadingScreen uses player.IsPlaying to poll when a video is finished
playing, but the video may have been cleared
NullReferenceException: Object reference not set to an instance of an
object
at
DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallVidPlayerWindow.get_IsPlaying
() [0x00000] in <filename unknown>:0
at LoadingScreen.LoadingScreen+<DoDeathScreen>c__Iterator1.MoveNext ()
[0x00000] in <filename unknown>:0
at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator,
IntPtr returnValueAddress) [0x00000] in <filename unknown>:0
> fix a NullReferenceException in DaggerfallVidPlayerWindow.IsPlaying

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
Also, I rewrote CheckRent() because it took me a while to understand that **-1** was a magic value for remainingHoursRented. The logic should be unchanged.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3043
> fix negative rented room time

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Utility/RMBLayout.cs
When altering named buildings, set factionId to zero and the building data pool items (from location) will be used as normal. Set factionId to >0 and pool items will not be used as it will be assumed this is a new named building.
This was the best way I could think of to fix the issues raised here https://forums.dfworkshop.net/viewtopic.php?f=5&p=34619#p34608
While also retaining the fix made by reverting in #1591 
@Interkarma I changed the pool items from a struct to a class so a ref is passed back and the pool item usage can be marked as unused if the replacement data is a new named building with a non zero faction id. Can you confirm this wont screw something else up? I couldn't see any potential issues with it.
> Fix issues with replacement buildings

- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
Some extry doors are raised and cause issues when entered while on a horse since the controller height is larger so the raycast finds the streaming terrain somehow (I think) and the player is then moved under the floor by PlayerEnterExit.SetStanding()
This fix changes that method to always use the standing controller height rather than the dynamic value.
Reproduce the bug by entering the palace at Issaqumbaa  in Abibon-Gora while riding. Before this fix you fall though the world.
> Fix a bug when entering certain buildings riding a horse

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
It was previously possible to make small changes to SaveGameWindow, like custom backgrounds and colors.
This is now made unnecessary by new UIWindowFactory which allows much more advanced customization to more than one window, so this feature is now obsolete and will be removed with a future update.
> Early customization of SaveGameWindow is now obsolete

- Assets/Scripts/Game/PlayerMotor.cs
Prevents trying to rappel down on horse or cart, for example.
Instead you'll just fall as per Newton's law; Should horses be unwilling to fall instead?
It seems falling off walls on horse is the way of classic too https://www.youtube.com/watch?v=1qco1jJmKu0
Also, is it the right place to check for transport mode?
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2997
> skip climbing/rappel mode checks when not on foot

- Assets/Scripts/Game/SongManager.cs
Use OnTransitionDungeonInterior to update song based on dungeon.
I don't expect we'll switch to full event-driven SongManager immediately, as song selection depends on many factors...
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3059
> make sure dungeons's SongManager updates song with each dungeon

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
The player must click on the alternatives he wants, instead of clicking on any alternative to toggle it.
Classic mode had a benefit though, you could test the effect of an alternative on cost and travel time without moving the mouse. So I moved the toggling behavior to the mouse wheel.
> more standard fasttravel options selection

- Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
It can be difficult to assess by how much the difficulty dagger went up or down after adding an advantage or a disadvantage, specially since panels are being displayed on top of the dagger while it changes.
This adds a subtle animation that makes the previous position of the dagger fade away for a second.
It also gives a nice trail as you tweak your HPs per level
> Make previous position of difficulty dagger slowly fade away

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsTypes.cs
- Assets/Scripts/Game/UserInterface/TextBox.cs
Fixes two issues that only happen in some locales (like french) that do not use the dot as floating point separator:
- Join correctly writes lists of values with InvariantCulture, but TrySplit does not, leading to parse errors:
Failed to split values from 0.65,1.05
System.FormatException: Unknown char: .
at System.Double.Parse (System.String s, NumberStyles style,
IFormatProvider provider) [0x00000] in <filename unknown>:0
at System.Single.Parse (System.String s, IFormatProvider provider)
[0x00000] in <filename unknown>:0
at System.Convert.ToSingle (System.String value, IFormatProvider
provider) [0x00000] in <filename unknown>:0
at System.String.System.IConvertible.ToSingle (IFormatProvider
provider) [0x00000] in <filename unknown>:0
at System.Convert.ToType (System.Object value, …
> fix: localized floating numbers handling

- Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainEffect.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
The reset doesn't work correctly yet in this PR. Need Interkarma to take a look because I don't understand the effect system well enough to know why calling EndIncumbentEffect<DrainStrength>() for instance doesn't seem to work.
> Add reset of drained stats to free temple healing

- Assets/Scripts/Terrain/TerrainHelper.cs
Sink nature flats slightly into ground as slope increases to hide floaty trees on sloped ground a bit. Sinks the flats proportional to angle of ground, with a max of 50/70 = 0.714 unity units on y axis.
Based on a suggestion from discord. Ratio seemed a good balance between no floating and buried sprites. Could be tuned more.
> Sink nature flats slightly into ground on slopes

- Assets/Scripts/External/Func.cs
- Assets/Scripts/External/Func.cs.meta
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
All formulas now are stored in a single dictionary and casted to appropriate type when retrieved. Also converted named delegates to generic `System.Func`, which allows to always use the exact signature without making compromises, and enforced load order.
```cs
FormulaHelper.RegisterOverride<Func<int, int, int>>(mod, "CalculatePlayerLevel", (startingLevelUpSkillsSum, currentLevelUpSkillsSum) =>
{
return (int)Mathf.Floor((currentLevelUpSkillsSum - startingLevelUpSkillsSum + 28) / 15);
});
```
> Improved support for formula overriding

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
- Assets/StreamingAssets/Text/DaggerfallUI.txt
When playing on slower systems I've found myself wondering if the click registered after I selected "Load" in the Load Game window.  This gives the user simple visual feedback to assure them that the game is loading.
> Show loading text before loading game

- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/StreamingAssets/Quests/S0000005.txt
Main quest questor NPCs were never flagged as questors, so they never said their post success or post failure greetings to the player.
Also fix quest S0000005 where Aubk-i post success and post failure greetings were inverted. And removed the word "dead" from post failure greeting as neither her husband nor her husband's grandmother are dead.
Edit: I'm not a native English speaker, but it seems to me that "The %ra that refused visit my husband's grandmother" should be changed to "The %ra who refused to visit my husband's grandmother". Could someone confirm?
> Set main quest NPCs as questors

- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/TalkManager.cs
This assigns correct factions to NPCs inside buildings, both to get the list of NPCs having work and to get a proper reaction when talking to such people. This also fixes the reaction value of all NPCs, including mobile ones.
Before, when talking to any NPC, his/her reaction value was always computed using the current region faction reputation. This corrects it by using the NPC faction or its parent one in case he's a member of a sub-faction (this matches what classic does).
Also, since I almost entirely decompiled classic talk system in C code, I saw how classic original code is a real mess in this case. For example, when talking to an NPC, its top parent faction of kind "Group", "Province" or "Temple" is used to get his reaction value. But then, the original NPC faction is also used to …
> Fix NPCs factions and talk reactions

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/StreamingAssets/Text/MainMenu.txt
A warning popup is shown if a mod is enabled and specifies a required game version that is higher than running build. It is possible to dismiss popup and launch the game anyway.
> Show warning for incompatible mods when game is launched

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
Can cause confusing with no benefits
> prevent 3d map from being rotated upside-down

- Assets/Scripts/Editor/SetupMobilePersonEditor.cs
- Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/MobilePersonMotor.cs
- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Game/Utility/PopulationManager.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
Allows mods to provide a gameobject that replaces mobile person prefab. An abstract component class is used to interact with the game, specifically to handle actual npc assignment and animation state.
This is a work in progress born from #1520
A basic example that replaces billboards with cubes:
```cs
using UnityEngine;
using DaggerfallWorkshop;
using DaggerfallWorkshop.Game.Entity;
using DaggerfallWorkshop.Game.Utility.ModSupport;
namespace MobilePersonCubeMod
{
[ImportedComponent]
public class MobilePersonCube : MobilePersonAsset
{
MeshRenderer meshRenderer;
private void Awake()
{
meshRenderer = GetComponent<MeshRenderer>();
}
public override bool IsIdle
{
get; set;
}
public override void SetPerson(Races race, Genders gender, int personVariant, bool isGuard)
{
Vector3 size = GetSize(); …
```
> Support providers of mobile person graphics

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/StreamingAssets/Text/ModSystem.txt
Allows mods to define other mods as dependencies to enforce a minimum version to be installed and/or to be positioned above in the load order. Dependencies are also used for the creation of an automatic load order.
```json
"Dependencies": [
{
"Name": "dungeonexit",
"IsOptional": false,
"IsPeer": false,
"Version": "1.0.2"
}
]
```
> Add support for mod dependencies

- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
A warning box is shown inside Mod Builder window if running on any version of Unity Editor which is not the supported one. It's still possible to ignore it and create mod anyway.
> Show warning if mod is created on unsupported Editor version

- Assets/Scripts/API/Save/SaveGames.cs
Pretty sure this fixes the issue reported here: https://forums.dfworkshop.net/viewtopic.php?f=5&p=36523
Have not fully tested all discovery imports, but seemed to work okay with some classic saves I tried.
> Only iterate for location discovery within bounds of both arrays

- Assets/Scripts/Game/Questing/Parser.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
This is what I considered doing when I originally implementing the quest lists option, but I was concerned about altering the quest parsing stuff so instead I decided to do full parse of every quest and have a 'please wait' message instead.
Since this is the root cause of the bugs we've seen with this feature, I've gone back to my original idea and added a boolean param that allows a partial quest parse to be requested. This doesn't parse the QRC or QBN sections, so the quest object returned is not startable.
This should fix #1536 and also speed up the list preparation. I've left the please wait message in there for now. It could be removed as it's quick enough with this change, but I would like to know that having this partial parse is acceptable by @Interkarma first. Also it's is nice …
> Implement option to partially parse a quest

- Assets/Scripts/Game/MagicAndEffects/Effects/Alteration/Climbing.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FreeAction.cs
Attachment: classic save with custom spells using all effects
Only other difference is missing effects (Shield, Dispell, Comprehend languages)
[SAVE4.zip](https://github.com/Interkarma/daggerfall-unity/files/3963960/SAVE4.zip)
> fix classic load by swapping free action and climbing effects

- Assets/Scripts/Game/WeaponManager.cs
Add clinging sound when you hit walls with a weapon
Limitations: 
- uses Parry6, I would have preferred a totally distinctive sound instead.
- works for all static objects, so hitting wooden furniture does a clinging sound too, even if one could expect the same sound as doors bashing.
- On the other hand non-static objects like elevators do no sound. I could have checked if the gameObject has a DaggerfallMesh component instead, but I don't know if that would have been okay
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&t=3172
> Weapon sounds when hitting walls

- Assets/Scripts/Internal/DaggerfallActionDoor.cs
(Splitting #1645 in two separate PRs)
Sometimes enemies hide behind or "inside" opened doors, and player weapons miss them because they're bashing the door instead.
While trying to add door bashing sound in this case, I checked classic Daggerfall behavior and noticed that it does bash-closing of the door (usually; sometimes it gets confused and bash-opens already opened doors), and that attracts enemies attention just like bash-opening.
> bash-closing doors

- Assets/Scripts/Game/UserInterface/TextBox.cs
In some locales, numeric keys normally require shifting to get digits.
Bypass this requirement for numeric inputs.
Added difficulty: on french keyboard, the 6 key is the shifted dash (-) key, so there's an ambiguity for relative numbers. So I restricted this to NATURAL numeric inputs.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3192
> For numeric input, accept numeric keys even without shifting

- Assets/Scripts/Game/PlayerEnterExit.cs
Fix list of houses for sale not available when loading the game inside a bank: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3034
> Don't suppress world when inside a building

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
that's a consequence of search running in two passes: finding locations whose name best match the given string, then filter the list to only keep already revealed locations. And also the list produced by the first pass having a finite size.
They're screens upon screens of locations matching "Ruins..." (or "Ruins of..." for that matter) in the Wrothgarian Mountains, so only a subset of the names are kept by the first pass; And since the revealed dungeon name is not in the intermediate list (by pure bad luck), the second pass doesn't keep any names.
Simplest fix is just to increase the size of the intermediate list. The first pass creates the list using a priority queue, so it should stay very fast.
Other possibilities include swapping the two passes (search among the name of the locations …
> find revealed locations by a very common substring

- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
Reading the list of existing save slots only happens when opening save window interface; So if quicksave is used first, it will see an empty list of slots and overwrite save0.
Fixed by reading folders once at initialization, alternative would be to check if it needs to be done in several places (QuickSave, HasQuickSave, QuickLoad, at least)
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3303
> fix quicksave overwriting save0 if used first

- Assets/Scripts/Utility/GameObjectHelper.cs
In addition to using the max of width and depth as door thickness, swap Y and Z if Y size is less than Z size.
It seems to work fine (more testing welcome though), but I suspect the logic is not perfectly correct; I suspect Y and Z actually need to be swapped for grounded doors because you're actually entering by its top. As if door dimensions were considered _after_ rotations instead of before; They're really its X, Y and Z sizes, and not local width, height and depth. Or something like that. 
(and that could explain why width and depth can switch roles, probably depending on door orientation).
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=566
> fix static doors collider size

- Assets/Scripts/Game/UserInterfaceWindows/UIWindowFactory.cs
I was looking for a method to return the type of window that is currently up.   I created GetType in UIWindowFactory to achieve this functionality.
An example of use would be 
var manager = (UserInterfaceManager)sender;
if (UIWindowFactory.GetType(manager.TopWindow.GetType()) == UIWindowType.Trade) {
…
thanks 
a
> Allow to get UIWindowType enum value from type

- Assets/Scripts/Game/WeaponManager.cs
Seems to help hitting enemies at very close range
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&t=3172
> exclude player from weapon hit checks

- Assets/Scripts/Game/Player/HeadBobber.cs
One very small adjustment I wanted to make was the fact that the headbobbing animation, if enabled, would continue to play even if the player is in the air. I found it more noticeable if you are jumping while riding on a horse, and the camera still continues to shake. This simple added condition to check for if the player is grounded or not should fix this issue.
> Stop headbobbing animation while player is not grounded

- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/Player/HangingMotor.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
- Assets/Scripts/Game/PlayerFootsteps.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Game/TransportManager.cs
FIx for #1588, and then some (like lowering player's noise volume when sneaking).
Note: 
playerMotor.speed is determined by both world conditions and player's input. While it's only required during FixedUpdate() for modifying movement(*), player's input can change with each Update() so that input must be recorded separately.
*. Except in LevitateMotor, that can adjust movement with each frame. If we care, we could update speed with each Update() too.
> Speedchanger refinements

- Assets/Scripts/API/BaseImageFile.cs
- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/TextureReader.cs
Lower the contrast of Fire god chamber fire walls, and slow down the animation, so it gets less aggressive on the eyes.
> Less stroboscopic fire walls

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Utility/DaggerfallDateTime.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=3309
0.10.17 - Vampire fast travel DFU hangs CUREVAM if target dungeon not present in region
The dungeon had nothing to do with it.
It was the fast travel going back 40 minutes in time. That made the unsigned integer calculation for how many minutes had passed return a huge number. (136 years) which triggered creating the vampire cure quest 591 times, which quickly runs out of random dungeons to assign.
> Prevent backward timetravel issues.

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenHeld.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
I used @petchema 's findings here: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2584&start=40
I tried using the "%" operator on the current game second but that was giving me race condition issues. I opted to use randomness since it wouldn't need to use the current game time. If introducing randomness to the mix doesn't feel right then I could rework the magic round loop.
Still need to find out how much to degrade on equip.
> Degrade equipped "when held" magic items over time

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Resources/defaults.ini.txt
- Assets/Scripts/DaggerfallUnityStructs.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/SettingsManager.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Added experimental setting "AssetCacheThreshold". If different than zero, this is the time in minutes from last access for which a texture can be stored in cache. During fast travels textures that exceed this value are removed to allow Unity to unload them if unused.
> Allow long unused textures to be unloaded

- Assets/Scripts/Game/Entities/EnemyEntity.cs
to prevent capturing multiple souls when killing an enemy by multiple damage sources.
Related form thread: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3187
> Disable soultrap after capturing soul

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/LycanthropyEffect.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/VampirismEffect.cs
- Assets/Scripts/Game/Questing/Item.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Game/Questing/QuestResource.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallDaedraSummonedWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Move creation of topics in the talkmanager from quest parsing to quest starting.
This allows parsing of quests without having to clean up the talkmanager afterwards.
See https://forums.dfworkshop.net/viewtopic.php?f=23&t=2995
> Refactor quest system dependencies

- Assets/Scripts/API/BiogFile.cs
If the list of effects is null the game will permanently lock up. So I simply added a check to see if the list is null and if so return the "ApplyEffects" function.
> Null check for list of effects when applying in the biog file

- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/TalkManager.cs
This fixes issue #1688  which is related to my previous PR #1583.
Because main quest questors are added using the `add _NPC_ as questor` command, they are not always the last clicked NPCs, so we can't rely on this data to select quest related post success and post failure greetings. Instead, we can use faction IDs since all main quest questors are individual NPCs, having a unique faction ID. However to do that, we must also keep the `Person.isQuestor` flag as true, but this should not have any consequences since the `drop _NPC_ as questor` command effectively clears the NPC from the quest list of questors.
> Fix main quest questors issues

- Assets/Scripts/API/BiogFile.cs
Addresses the bug described here: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2220
The %ra macro, which uses the PlayerEntity's BirthRaceTemplate, is used while generating player backstory. Since BirthRaceTemplate is not set until after the player exits the new game wizard, %ra expands into the default race name i.e. Breton.
Setting the race template before generating backstory gives the macro helper the info it needs.
> Set player race before generating backstory

- Assets/StreamingAssets/Quests/S0000009.txt
Clear _clickedElysana_ until the _giveLetter_ timer has expired. This prevents the quest prompt from popping up as soon as the _giveLetter_ timer expires when you clicked Elysana at any time after the quest started.
Forum post: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3368
> Add clearclick to S0000009

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
Logically the cap should only need to be applied when the MaxMagicka changes.
This is the same logic used for health and fatigue.
This fixes forum bug https://forums.dfworkshop.net/viewtopic.php?f=24&t=3075
This reverts commit e1df2c3c2bd72c08f0b8f9d5b7c5b413cbad9eb0
> Changing the magicka in the get method causes bugs during load.

- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
This adjustment is both a quality of life improvement as well as a small bugfix.
Before this commit was made, if you click the "Use" button and then click an article of clothing, it will change its appearance. However, if you click an article of clothing that has a magical effect, it will not only change its variant but it will also incidentally cast the magic effect as well. This means it's only possible to change a magic clothing's appearance without casting only if you equip it and click it on the paper doll.
I made a nice little workaround and improvement to this by making it so if you right-click on the paper doll, or on the "local" and "remote" item panels, it will change its variant without casting a magic effect, and without having to click the "Use" button.
> Right-clicking clothing in inventory window changes its clothing variant

- Assets/Scripts/Game/PlayerFootsteps.cs
- Assets/Scripts/Game/PlayerMotor.cs
If a player is walking on shallow water, the PlayerMotor won't recognize it as a water tile and will make the PlayerFootsteps play regular grass terrain footstep noises. In my commit, I added additional index tiles that are corner pieces between ground and water to make splash noises, without actually being submerged in the water and set to "swimming."
I also added stone paths (indices 46, 47, 55) to use the dungeon tile floor noise, which I think fits nicely.
> Improved outdoor footstep tile noises with shallow water and stone paths

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
Use nearClipPlane to "peel" dungeon layers as you get closer.
This should makes the 2D automap more useful, and closer to classic behavior
> use nearClipPlane in 2D dungeon automap

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
Disable hotkey sequences when controls with overridesHotkeySequences flag have the focus
Part of fix for issue #1707
> Allow controls to override hotkey sequences

- Assets/Scripts/Game/Questing/Actions/PickOneOf.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
No optimisation attempt, QuestMachine.ParseQuest can be called several times during the same frame and is not in a hot path so I'm using System.Random as randomness source.
Generating a list of quests feels just as fast as before.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3399
https://forums.dfworkshop.net/viewtopic.php?f=27&t=924&p=39061#p39056
> force UnityEngine.Random reseeding when parsing quests

- Assets/Scripts/Game/UserInterface/HUDEscortingNPCFaces.cs
In some cases faces creation involve some randomness (say, for children), so FaceDetails structural equality could mismatch.
Also disable face panels until placed, so they don't show up in screen top left corner for a frame.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3430
> Remove escorting faces more reliably

- Assets/Scripts/Game/EnemyDeath.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/StreamingAssets/Tables/QuestList-Classic.txt
- Introduced delegates for player starting equipment and spell assignment. (Moved them to be called after items from biog questions are added to player, so mods can adjust)
- Introduced delegate for assigning enemy starting equipment.
- Added a new formula that is called when loot items are generated for loot piles. This is for mods and LootRealism will use it to have found armor, weapons, and books be in a random condition.
You can see an example of usage here: https://github.com/ajrb/dfunity-mods/blob/startingStuff/LootRealism/Scripts/LootRealismMod.cs
> Allow mods to override allocating player starting equipment and spells, enemy equipment, and modify found items

- Assets/Scripts/Game/PlayerFootsteps.cs
- Assets/Scripts/Game/PlayerMotor.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
- Static geometry (such as buildings) now also make the hard dungeon footstep noise instead of the grassy terrain noise
- Improved detection for what tile the player is on by extending the raycasting distance
- Fixed an issue where sometimes jumping would make a grass noise, and also improved jumping by playing the tile's footstep noise upon landing
When I was designing the functionality for the landing noise, it also happened to get triggered when the player would load a save, or move into/out of an interior location, because the player would be floating in the air before being repositioned on the ground. To remedy this, I created a _StreamingWorld.IsRepositioning_ bool property that checks if the player is currently being repositioned so it can ignore that footstep noise.
> Additional fixes and improvements for footstep noises

- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/RMBLayout.cs
Tried to use a fsSerializer post-processor but couldn't as the DFBlock is a struct and that means there's no way to adjust the values because the obj is passed by value.
This enables world data override files to continue to work without every single model requiring 3 new float values to be added.
> Ensure that the scaling vectors are not initialised with zeros. URGENT FIX!

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
Sometimes, when encountering an idle mobile, it look like it's facing you until you slightly move around.
The problem is that the choice of mobile orientation is based on cases using only strict inequalities, so boundary values did not match any case and orientation was left at its initial value of 0.
I replaced everything with formula, that could be extended more easily to any number of orientations.
> fix rare mobile orientation blind spot

- Assets/Scripts/Game/DaggerfallMissile.cs
Both arrows and spell missiles gameObjects didn't inherit SpellMissiles layer from their parent, so they would collide with one another.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=23&t=3459
> prevent collisions between all missiles

- Assets/Shaders/DaggerfallTilemap.shader
Same as #1484 but in DaggerfallTilemap.shader
No regression found on my hardware with EnableTextureArrays = False, but ideally it should be tested with hardware that require that setting...
Forums https://forums.dfworkshop.net/viewtopic.php?f=5&t=3456
> Same as #1484 with EnableTextureArrays = False

- Assets/Scripts/Game/PlayerActivate.cs
WeaponManager uses camera position and direction, just do the same.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3454
There may be more to the problem discussed in the forums than this bug, but it's a start.
> Don't assume player is standing in PlayerActivate raycast

- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/WeaponManager.cs
One can't simply call WeaponDamage() again with a fallback raycast hit if no enemy was struck during a first call of WeaponDamage() with a spherecast, because environment damage may be done twice.
So the major refacto is to split WeaponDamage() into environment damage (WeaponEnvDamage) and enemy damage (WeaponDamage).
I also used that refacto to simplify missiles damage.
> MeleeDamage raycast fallback

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/Items/ItemEquipTable.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
This allows weapon switching between a melee and a bow without having to access the inventory. Think... sling the bow over shoulder and draw a blade. Introduces a switching delay for all weapon switches which is half the average weapon equip delay of the two weapons.
Playing a character who uses a mix of ranged and melee is a pain, and it seems reasonable to me for this to be a balanced tweak of the Daggerfall weapon system. If you would rather it goes in a mod, then I'll do that, but I feel it's a nice enough change for a core enhancement.
> Add enhancement setting to use bows in left hand

- Assets/Scripts/Game/Questing/Actions/CreateFoe.cs
- Assets/Scripts/Game/Utility/FoeSpawner.cs
Previous algorithm to spawn foes freely would first find a direction slightly outside of player's field of view, check if there's any obstacle in that direction, and if so find a spawning point along the normal of collision point.
Using that normal helps finding a clear location (it should be at least clear from the obstacle just hit, but further tests are still needed), however it changes the direction of the spawning point, moving it away from field of view borders; Either inward (making the foe suddenly appear in front of the player) or outward (not as bad).
Also the code checks the distance of the hit point, not spawning point, making it possible for spawns to happen at a much lower distance than minDistance constraint.
Stream: https://www.twitch.tv/videos/556821863?t=27m40s …
> [RFC] More discreet create foe place freely 

- Assets/Scripts/Game/EnemyMotor.cs
This PR does not change the current doorway finding algorithm, that looks good, but tweaks 2 parameters so far:
- limit the height of the capsulecast used to find doorways to 1.75, to match the hack used to allow tall enemies to get thru doors. Without this, tall enemies could technically get thru doors, yet are very reluctant to do so;
- lower capsulecast distance from 1 to 0.8. Long casts was making it hard for enemies to find door openings coming from the sides. Now it's a bit better.
> AI improve doorways finding

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
https://imgur.com/a/tdHhoRw
I felt like the setup wizard could use a small version label for users to notice which .exe they're opening. It's especially useful in case if a user uses multiple versions for mod compatibility, or if they're transitioning from one version to another and accidentally left the older version pinned to their taskbar, start menu, or on their desktop as a shortcut.
> Added version label to setup wizard

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Was skipping clothes with 0 variants in template.
Was not able to create the 2 different boots.
This is also reverting a change made by Allofich on14/8/2017 (4c81a7f) restricting the variants for chain+plate boots to just one. This may be as classic, but I suspect it's a bug that DFU can happily correct. Anyone disagree?
> Fix add_all_equip command

- Assets/Scripts/Game/Automap.cs
When some gameObject without MeshRenderer is found in a dungeon block, shader of remaining gameObjects is left to Standard shader in the automap.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3476
> Fix automap partial blocks wrong shaders

- Assets/Scripts/Game/Items/ItemBuilder.cs
I've just realised that the fix here for the enchantmentPoints is not getting used in the game. That's probably why it was not noticed up until now.
@Interkarma when you implemented item enchanting you created formula methods (GetItemEnchantmentPower etc) to calculate this from the base points value in the template instead of using the value calculated by Allofich code in ItemBuilder. I'm not sure if this was because of the bug that this PR fixes, or because you were not aware of its existance.
Having it in the item means it is easier for a custom item implementation to alter the points in a different way, which is useful in at least one case but not necessarily a reason to switch if there are good reasons not to.
Either way I think one or the other of these 2 implementation of …
> Fixes discrepancies in item stats from classic

- Assets/StreamingAssets/Quests/N0B10Y03.txt
… when the _oneday_ timer expires without having stolen the guarded item.
Forum post: https://forums.dfworkshop.net/posting.php?mode=reply&f=24&t=3422#pr40022
> Prevent the "end quest" action from firing twice

- Assets/Scripts/Utility/ClimateSwaps.cs
- Assets/Scripts/Utility/TextureReader.cs
Noticed by KoW / @HybOj
Took me a while to understand that emission was wrong for some records because of IsExteriorWindow(). That predicate sure is not pretty.
> make frost daedra emissive, like in classic

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallDaedraSummonedWindow.cs
Should convey that the player is supposed to type something, while having a minimal impact on visuals.
I put the cursor near the bottom right corner of the screen because I didn't manage to fully grasp the UI coordinates system, but it looks okay (and could be improved later).
> Add a blinking cursor to daedra quest Y/N question

- Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleUI.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/Serialization/PrintScreenManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
Besides the map windows, if the player had previously opened a window and then changed the keybind for it, the window would not refresh the toggle button and would stick to the old keybinding. This was also true for the console window as well. I fixed it by refreshing the bindings in `OnPush()` and `ToggleConsole()` for the windows and console, respectively.
Also, in preparation for the secondary keybind window, I've made the pause window utilize a rebindable toggle like all of the other windows. Previously, it relied on a hardcoded `KeyCode.Escape` and `DaggerfallPopupWindow`'s default 'exitKey' to leave the window without actually using `InputManager.Actions.Escape`. Also, when making this change, I noticed that if the toggled key was held down for too long after exiting the window, …
> Fixes + improvements for opening/closing UI windows and console

- Assets/Scripts/Game/WeaponManager.cs
The way bows are accessed for the formula differs from melee so it was using the weapon in right hand for damage calc.
> Fix left handed bow damage and condition lowering 

- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
`ModManager.TryGetAsset()` now doesn't return null if the first asset found can't be loaded but it keep seeking for a valid result instead.
This fixes an issue where a texture could be retrieved properly if a mod contains both texture and xml configuration file (with the same name), while it failed if it contains only the xml file because our internal code only considers the filename (unlike Unity API that also checks type).
`Mod.LoadAsset()` returns null without logging errors if asset is not found, which is consistent with Unity API (i.e. `Resources.Load()`).
> Improved robustness of ModManager.TryGetAsset()

- Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
Added support for serialization of prefabs inside a mod with custom components defined by other mods.
How to use component from mod A for a prefab in mod B:
- [ImportedComponent](https://github.com/Interkarma/daggerfall-unity/blob/27e3e4668890b28cb26355a98e4bca08053805ec/Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs#L31) attribute must be placed on the component class definition in mod A.
- Component from mod A must be added to prefab included with mod B using the "Add Component" button from prefab inspector, like any other component. This means that component class type must be available in Editor when the mod is built. Raw .cs or .dll files are enough, is not needed to have the entire mod source code.
- Mod A must be defined as a …
> ImportedComponentAttribute now supports dependencies

- Assets/Game/Addons/ModSupport/ModTypes.cs
- ProjectSettings/TagManager.asset
Mods can request layers and release them using `ModReservedLayer`.
[Requested on forums.](https://forums.dfworkshop.net/viewtopic.php?f=23&p=41393#p41393)
Example:
```cs
var reservedLayer = ModReservedLayer.Request();
if (reservedLayer == null)
{
Debug.LogError("Failed to get layer");
return;
}
var go = GameObject.Instantiate(mod.GetAsset<GameObject>("Cube"));
go.layer = reservedLayer.Layer;
// ---
Physics.IgnoreLayerCollision(reservedLayer.Layer, LayerMask.NameToLayer("Enemies"), false); 
// ---
reservedLayer.Dispose()
```
> Mod reserved layers

- Assets/Scripts/Game/Player/FrictionMotor.cs
Previous unstick handling used a SphereCast to check whether the player could be teleported forward across some geometry issue.
However the fact that the player controller shape is a capsule instead of a sphere could lead to an erroneous teleportation inside obstacles (shop banners, graveyard gate,...)
Just replacing one shape with another is not sufficient, because hte fact that a controller shaped capsule couldn't move forward is exactly why the player was stuck in the first place. To be safe, what should be checked is whether a capsule could freely follow a path to the place we want to teleport the player to.
Simplest path after the straight line is a step (go up, forward, then down), that's what this PR does.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3291
> Safer unstick handling using Physics.CapsuleCast()s

- Assets/Scripts/Internal/DaggerfallStaticDoors.cs
I case they're several static door hits, give higher priority to dungeon exit
Alternate implementation would be to add static doors deduplication in RemoveOverlappingDoors(), but I'm not sure it's worth the extra complexity.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3390
> Fix dungeon exit and other static door overlap

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Players can never have anything that will be sellable, but this gives mods the chance to flesh out or repurpose furniture stores if they want to.
See https://forums.dfworkshop.net/viewtopic.php?f=5&t=3550
> Add furniture category which are present, just rare

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
- Assets/Scripts/Game/Items/ItemBuilder.cs
- Assets/Scripts/Game/Items/ItemEquipTable.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Utility/ImageReader.cs
Builds on the rudimentary support I added for the locator device 2 years ago. I have attempted to implement this with as light a touch on the codebase as possible.
Now uses the item templates file and defines a template index which for custom items is used for the group index as well.
Regarding paperdoll items, Weapons and armor are fully functional and tested. Clothing may need a bit more work which I will look at soon but I wanted to get this on the list of PRs so people can start to review the changes. Corresponding changes can be found in my Archs mod and Loot Realism on this branch: https://github.com/ajrb/dfunity-mods/tree/moderateWeaponMaterials
Loot realism now adds 2 new weapons: Archers Axe and Light Flail, and also a new lighter set of mail armor allowing players who can't wear …
> Enable custom items to be added by mods

- Assets/Scripts/Game/Player/FrictionMotor.cs
Reset unstick handling frame counter when not trying to go forward or backward. This should make it harder to trigger unsticking when moving by short bursts or using a mix of moves that doesn't make you progress forward or backward
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3537
Also possibly
https://github.com/Interkarma/daggerfall-unity/pull/1759#issuecomment-602054807
> [RFC] Reset unstick handling when idle

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/RDBLayout.cs
These changes extend the custom model activation registration to include flats which was previously not possible. Any flat with a custom activation assigned will have a collider added to it's GameObject to allow for raycasting to succeed. Also, models with custom activations are excluded from the combinedMesh during dungeon assembly.
This allows modders to create custom activations for any model / flat they choose and enables them to implement things like resting at campfires, dungeon beds, etc. 
I have created a custom test dungeon (just a simple room) with a classic model (broomstick cabinet) and flat (campfire) as well as a replacement for both cases (a scarecrow flat is substituted for a white cube and the empty bookshelf is replaced with a bookshelf model I quickly made). Upon …
> Custom flat / model activation

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Advanced Controls Window:
https://i.imgur.com/rVtBFgf.png
Button to access it:
https://i.imgur.com/IuxBN6A.png
Alas, it is here. The advanced controls window contains keybinds for non-classic controls, which are pausing, toggling the console, screenshotting, quicksaving, and quickloading. It can be opened from where the 'MOUSE' button was, which is now an overlaid green button called "ADVANCED".
Like the main control window, it will detect duplicates and highlight them as red. However, _you will still be able to exit out of the advanced controls window_, so that way you can find which keybind you're conflicting with in the main window, but you won't be allowed click 'continue' in the main controls window until it's resolved.
Also, for ease of access, I've also added some settings from the …
> Added Advanced controls window

- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs.meta
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Added a component that holds a list of archives and records and uses them to assign materials when the prefab is instantiated at runtime. Materials are automatically applied on Awake but can also be manually reapplied.
It allows to "reference" a classic Daggerfall material from a prefab provided by a mod.
Mod authors can use this component to provide a list of archive-record tuples associated to a material index. This is a better alternative than including classic textures with the mod because it doesn't require texture duplicates for each mod and has full support for texture replacement with load order. 
The reason to specify material index (instead of using array order) is to allow the use of classic materials along with custom ones. As a convenience i added an entry in the context menu …
> Support for runtime materials

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
The console command 'startquest' will now say "Added quest {quest display name}" if it is a valid ID and "Quest ID '{id}' could not be found" otherwise.
It used to only return "Finished", which seemed ambiguous if it meant I finished that quest or if it got completed it for me. It also didn't say if the player used a valid quest id or not.
> Improved output of 'startquest' command

- Assets/Scripts/Game/WeaponManager.cs
Seems to be what classic does according to my observations.
This is the simplest implementation, No weapon drawn sound is played when you're finished climbing.
> Prevent the use of weapon while climbing

- Assets/Scripts/Game/SongManager.cs
I was looking at #1539 and while I can't seem to reproduce the issue, I minimized GC allocation of SongManager in hopes that it might help with the sound issue. It reduced the GCAlloc from 284 B to 0 B.
Calling struct.Equals(object o) by default will "call Object.Equals(Object) on each field of the current instance and obj and returns true if all fields are equal."
https://docs.microsoft.com/en-us/dotnet/api/system.valuetype.equals?view=netframework-4.8#System_ValueType_Equals_System_Object_
Let me know if this fix was useful.
> Reduce GC alloc of SongManager

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/StreamingAssets/Text/SpellmakerUI.txt
A drawback of adding keyboard shortcuts to form buttons is that sometimes people trigger actions by inadvertedly pressing game keys.
Most common I've seen is W (forward) key pressed in inventory. Either selects the wagon or displays a message if the player has no wagon, it's relatively harmless.
Another a more annoying I'm starting to see is people pressing S (backward) key in the spellbook, reordering their spellbook.
This patch adds a confirmation before spellbook sorting.
Alternatively, the player could be asked what sort order to use.
> Require confirmation before spellbook sorting

- Assets/Game/Addons/ModSupport/Mod.cs
If a mod loads an asset, unloads it and then requests it again, the invalid asset is removed from cache to allow it to be loaded again. Previously, the load operation would have failed.
Mods should not unload cached assets (of course additons to the API can be proposed  if actually needed) but this should handle the issue more graciously for the player.
> Remove invalid assets from cache

- Assets/Scripts/Game/UserInterface/UserInterfaceWindow.cs
- Assets/Scripts/Internal/DaggerfallGC.cs
- Assets/Scripts/Internal/DaggerfallGC.cs.meta
- Assets/Scripts/Terrain/StreamingWorld.cs
Daggerfall Unity needs to explicitly call Resources.UnloadUnusedAssets() because it barely uses SceneManager.LoadScene() which is the way games usually indirectly call it.
This is currently done in two places, including while closing UI windows, a path taken often enough during normal gameplay to prevent unused assets to pile up too much.
However this can be a lengthy operation that blocks the whole environment as it calls GC.Collect() internally, and can make sound skip which can be pretty annoying once you noticed it (issue #1539).
This patch makes sure the call to UnloadUnusedAssets() does not happen more than once every 3 minutes, a tradeoff sufficient to make that issue much less noticeable, yet should prevent unused assets to stay around forever.
It should be noted that, while not …
> Do not call Resources.UnloadUnusedAssets() more than once every 3 mins

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
My most sincere apologies, I accidentally merged changes from custom-dialog-buttons into custom-flat-model-activation. While the changes don't interfere with DFU's normal operation, after consulting @ajrb who thankfully spotted this, I decided to remove them for now until they are properly implemented.
> Removed accidentally merged changes from custom-dialog-buttons.

- Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/Scripts/DaggerfallUnity.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
#1671 introduced removal from cache of materials that have not been accessed for a fixed time. This is now extended to mod cache in order to improve memory management for unique assets used by mods.
Timestamp of last access is updated when an asset is requested with `GetAsset()`. As a compromise, assets loaded with `LoadAllAssetsFromBundle()` or `LoadAllAssetsFromBundleAsync()` are not removed before they are actually retrieved.
> Remove unused assets from mod cache

- Assets/Scripts/Game/UserInterface/DaggerfallShortcut.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/StreamingAssets/Text/DialogShortcuts.txt
Working with the controller PR with the added advanced controls window, if someone were to rebind the pause button to the controller, then replayed the game without the controller, then they would be stuck and unable to change their keybinds without modifying Keybinds.txt.
This PR adds a hardcoded Shift-Escape keybind allowing the player to access the DaggerfallPauseOptionsWindow in case if they fall into this situation.
> Added backup escape key method (Shift-Escape)

- Assets/Scripts/Game/Player/HeadBobber.cs
- Assets/Scripts/Game/PlayerMouseLook.cs
While in cursor mode the player can't adjust his/her view direction with the mouse, but if head bobbing is on it will change view direction, making the view roll over as the player walks around.
This leads to embarrassing moments, because whether the mouse cursor is displayed or not becomes totally secondary to the player when (s)he starts looking at his/her feet, then the landscape upside-down, then the sky, and repeat. People get utterly confused, and the obvious conclusion is usually "the game bugged out", and fixed by restarting it.
I'm not sure whether cursor mode should be totally disabled until fully implemented, but at bare minimum the interaction between cursor mode and head bobbing has to be handled somehow; That's what this PR does.
Forums: …
> Disable head bobbing while in cursor mode

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
(This is pertaining to having `ClickToAttack` disabled)
As of right now, the `WeaponAttackThreshold` is shared with both the mouse and the joystick. For gameplay experience, this threshold isn't really needed for a joystick since it does not move like a mouse, and makes it harder to attack. If the `WeaponAttackThreshold` is set very low (<0.001), the player can hold their joystick in one direction and the game will automatically constantly swing the weapon, giving an unfair advantage over the mouse.
This change removes the WeaponAttackThreshold from being calculated if the player is using a controller (via `InputManager.Instance.UsingController`), but also prevents automatic swinging by having the player let go of the joystick (or moving it close to the middle) in order to swing again.
> Improvements to joystick attack swinging

- Assets/Scripts/Game/TransportManager.cs
Holding space while jumping makes an unpleasing clipped horse noise. This fix delays the stopping of the audio by 0.2 seconds, just enough to get at least one gallop noise in when colliding with the ground. It's not perfect, and sometimes it might fail to make a sound, but I think it's a step up from what it currently is at the moment.
(Also, I think my VSCode editor is automatically normalizing the line endings and I'm having trouble finding another editor that won't do this, sorry about that)
> Fix horse gallop sound clipping when repeatedly jumping

- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/StreamingAssets/Text/ModSystem.txt
- All dependency issues are shown on message box with a scrollbar if needed.
- Prompt to auto sort mods is shown only if at least one issue can be solved by sorting.
> Improve handling of mod dependency issues

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/Button.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPlayerHistoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTeleportPopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallWitchesCovenPopupWindow.cs
This is a fix for the issue discussed in #1783:
Keyboard events can leak from game to UI or from UI to game:
- to prevent leaks from UI to game, UI controls can be triggered on KeyUp, so that the key is released before the game takes control back. However if the player releases game keys after opening the UI, that can activate UI buttons ("W" in inventory, "S" in spellbook,...);
- to prevent leaks from game to UI, UI controls can be triggered on KeyDown, so that keys have to be pressed again inside the UI to have an effect. However this means keys can still be pressed after the UI closed, leaking key events into the game.
It should be clear now that those two situations are symetric, and that none fixes all problems. UI controls need to be able to handle KeyDown and KeyUp explicitly.
With …
> Add genuine keyboard event handlers to UI controls

- Assets/Scripts/Game/WeaponManager.cs
Added functionality where pressing "Ready Weapon" when having a spell ready to cast will cancel it as an alternate way to abort a spell. The weapon will be unsheathed regardless if it was previously or not.
> Added ability to abort spell via Ready Weapon action

- Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs
- Assets/Scripts/Game/Serialization/PrintScreenManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
They all used to use Input.GetKeyX, which would cause an exception if a user were to bind a an axis button to one of them. Also, the console controller did not properly update its binding - it would have to be opened with the old keybind first, then closed with the new keybind to update the change.
I made all of them InputManager.Instance.GetKeyX, as well as made the console listen for OnSavedKeyBinds to update its own keybind.
> Fix GetKey usage for pausing, screenshots, and console

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
Pressing the middle mouse button will toggle autorun mode, which defaults to sprinting forward without holding any keys. While in autorun mode, the run key also becomes togglable, so you can resort to simply pressing the run key once to toggle it between autowalking and autorunning.
Pressing the Autorun key again, or just moving backwards, will cancel it.
I rearranged the order of the advanced control keybinds so similar actions are grouped on top of each other.
> Added Autorun action and keybind

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenHeld.cs
The behavior was reverse engineered on DF forums by Numidium and Elenwel and confirmed by my own reverse engineering, see here: https://forums.dfworkshop.net/viewtopic.php?f=23&t=3621
Since @Allofich did most of the job some time ago, there was very little to do there.
The only difference from classic is that DFU takes all item "Cast when held" effect costs to lower the item condition, where classic takes only the last one.
> Cast when held item condition lowering

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
I reverse-engineered classic function regarding daedra summoning. And as often, I noticed it somewhat contradicts the information found on the UESP. In particular, there is not such thing in classic code as a 95% maximum chance of summoning a dadrea (it's always a roll between 1 and 100), where the "5 % chance" left would be the chance for Sheogorath to replace the daedra.
In classic, it is as follows:
Sheogorath has a 5% chance of replacing the daedra (15% under thunderstorms), so he gets a dedicated roll for that, even with The Glenmoril Witches who usually summon Hircine (this is intentional).
Then, and only after Sheogorath has replaced or not the daedra to summon, the summoning chance is computed and the summoning success or failure roll is done.
I modified DFU's code accordingly.
> Fix daedra summoning to match classic behavior

- Assets/Scripts/Game/Entities/PlayerEntity.cs
This fixes a classic issue where Montalion vampires are given the Free Action spell, which is completely useless for vampires since they are all immune to paralysis.
Instead, it gives them Recall, as was originally intended, since we can read from from "Vampires of the Iliac Bay":
_Montalion alone have the gift for teleportation, but the other eight have powers of their own._
This classic bug was originally mentionted by DelphiSnake: http://slushpool.dfworkshop.net/BUGS.html
> Set Montalion spell to Recall

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Round all inputs into multiples of a gold piece weight then use an integer division.
This works fine with classic weights, because beside gold pieces, all weights are multiple of "classic unit" (250g), which is also a multiple of gold piece weight.
Simplest alternative to #1830
> fix ComputeCanHoldAmount() rounding errors locally

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
Make region maps more accessible to color blinds by adding an outline to location pixels.
It actually makes it easier to point at locations, so it could be seen as a general improvement.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&p=43718#p43717
The implementation uses Panels for the outlines, works well but may be too hackish?
Also, ir probably needs to be made an option or have a keyboard toggle.
> [RFC] Travel map dot outlines

- Assets/Scripts/Terrain/StreamingWorld.cs
see this forum-thread where the bug was reported:https://forums.dfworkshop.net/viewtopic.php?f=4&t=3391&start=10)
the reason was that StreamingWorld class can reuse terrain array elements when needed - it marks no longer needed terrains as "Pooled" and keeps them in memory until memory is needed for new terrains. If pc turns around and travels back the "Pooled" terrains can get reused. If the "Pooled" terrain  was a location map pixel buildings get destroyed as soon as terrain becomes "Pooled" - so this change enforces that buildings of reused "Pooled" terrains which contain a location are loaded again.
> fix for missing buildings bug (when doing round-trips between locations)

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/MainMenu.txt
- Added "joystick deadzone" setting, a value between 0 and 1.0 (0-100%) that is the minimum percentage of joystick movement required to be recognized by the game. This should help with joysticks that have issues such as drifting or are too sensitive and generate small amounts of movement that get captured in other ways.
- Added "Enable Controller" setting to the setup wizard that can disable the controller in realtime, and will have to be re-enabled by the use of a mouse.
- Improvements to the cursor flickering and clicking bug. _(**Note**: If you do not have the flickering issue and want to test this, just keep a joystick moved in one direction with one hand and move your mouse with the other.)_ The flickering is caused by a constant tug-of-war between the cursor going into "mouse mode" …
> Controller fixes, improvements and additional settings related to cursor issue

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Previously, if the player is currently resting, and they stop it prematurely via the 'Stop' GUI button, the toggle window key, or the escape key, the hours they slept for would not actually be accounted to raise skills, and neither would there be a popup saying "you wake up" or "you are healed" when done so.
This PR resolves this issue by isolating all exits to `EndRest()` when the player stopped while resting, or `CloseWindow()` if the player was on the selection menu. I also made a small change where if you choose to rest "until fully healed", but end it prematurely, the message will say "You wake up" instead of "You are healed", since the player wouldn't be fully healed.
> Properly end resting when stopped prematurely

- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
[[Forum post](https://forums.dfworkshop.net/viewtopic.php?f=22&p=44732&sid=3c2b933a14b59a211a0b54c797f6cb4d#p44732)]
[[Images](https://imgur.com/a/sDN4tUb)]
SaveData.txt will now serialize information about mods used at the time of saving - `fileName`, `title`, `guid`, `version` and `loadPriority`. While this serialized information is mainly used for displaying mod incompatibilities when a player loads or quickloads a save, they can also be useful for mod creators to warn players about particular versions or incompatibilities with mods in their own way as well.
Loading a game will compare the saved `ModInfo_v1[]` in SaveData.txt by the currently enabled and loaded-in mods against its GUID. If it cannot find the a mod with the same GUID, then it will say "Mod is either not loaded or has …
> Prompt warnings for modlist mismatches in saves

- Assets/Scripts/Game/SetupDemoEnemy.cs
- Assets/Shaders/GhostShader.shader
- Assets/Shaders/GhostShader.shader.meta
- Assets/Shaders/RequiredShaderVariants.shadervariants
Use semi-transparent shader for ghosts and wraiths. This works quite well with modded textures, but SetSoectral() is lacking for
classic textures (not extracting emissive map for the eyes, nor extracting all the details of the original textures)
modded (DREAM):
> WIP: ghosts and wraiths shader

- Assets/Scripts/API/BaseImageFile.cs
I do like the version of ghosts and wraiths in master, it's really close to classic in term of look and stealthiness, with just more details up close with some lighting. This PR is just an alternative that I find interesting.
It make ghosts and wraiths highlights slightly emissive (more focused on highlights than just a constant emissive value). Shouldn't make much difference under bright light, including classic high ambient light conditions.
In dark places however, it gives a hint of the baddies, as if they were slightly phosphorescent
> [RFC] make ghosts and wraiths highlights slightly emissive

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
[[Image](https://imgur.com/a/XouZv5R)]
Added the Joystick Controls Window, which allows players to:
- Enable/disable the controller in realtime, like the startup wizard
- Rebind their joystick axes, in case of controller or OS differences. It can also be used for preference, like using the D-pad for movement instead
- Invert axes, both horizontally and vertically. The "Invert Mouse" setting in the Advanced Controls Window can also coincide with the vertical camera axis, so it has been renamed to "Invert Look-Y".
- Rebind left- and right-click keybinds
- Adjust look sensitivity, cursor sensitivity, maximum movement threshold, and deadzone. Deadzone can only be set up to 0.9, as 1.0 is near impossible to reach consistently with most controllers
Except for the Enable Controller setting, all …
> Added Joystick Controls Window

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Allows modders to register conditions and messages for preventing or interrupting a rest via `GameManager` with `RegisterPreventRestCondition`. The conditions can also be unregistered as well with `UnregisterPreventRestCondition`.
> Mod support for custom resting prevention

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Switches the guild memberships when player is a vampire, switching back when cured. Nothing else is changed, no reputations or TG/DB initiation processes. I implemented it differently from classic, instead of switching round two data structures I simply access the appropriate one. Trying to minimise the dependencies here and not rely on vampirism triggering the swap.
Classic imports should work too, but I don't have any classic vampire saves so unable to test this. Could someone else test that it works correctly please?
Also fixed a bug with finding region factions.
> Implement vampire guild membership switching

- Assets/Scripts/Game/InputManager.cs
The `previousAxisRaw` dictionary could be set multiple times per frame, causing issues with GetKey methods if called sequentially:
```
if(InputManager.Instance.GetKeyUp((KeyCode)(5015))) //true
Debug.Log(InputManager.Instance.GetKeyUp((KeyCode)(5015))); //false, should still be 'true'
```
This was found in the inability to close the automap window when binded to an axis button (e.g., D-pad, shoulder buttons) by #1810. This PR fixes the issue by queuing the previous input into a list, that will be merged and cleared once per frame in the Update method.
> Fix proper refreshing of recorded previous axis input once per frame

- Assets/Scripts/API/Save/GuildMembershipRecord.cs
- Assets/Scripts/API/Save/SaveTree.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
This fixes #1849 properly, by importing old guild membership records. @Interkarma I removed your exception handling code since it shouldn't be required anymore. However if you prefer that it remains, I will put it back.
@ajrb, could you review the changes as well? I provided a classic save with a character cured from vampirism in #1849, having a single old guild record (Kynareth at novice rank). I had to modify GuildMembership.RestoreMembershipData to avoid an importation bug where this old guild membership was overwriting the actual player membership in Kynareth at patriarch rank.
> Fix import of classic old guild records

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Special/VampirismEffect.cs
- Assets/StreamingAssets/Text/ClassicEffects.txt
(I did you try factorizing code with plain vampirism. Could probably be done using something similar to  #1847 but for fast travel?)
Forums: https://forums.dfworkshop.net/viewtopic.php?f=31&t=3710
> prevent initating fast travel during day with damage-from-sunlight disadvantage

- Assets/Scripts/Game/UserInterface/Panel.cs
- Assets/Scripts/Game/UserInterface/VerticalProgress.cs
Simplest fix: fix parchment tearing by rounding coordinates where textures must meet
> fix parchment tearing

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
- Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
- Assets/Scripts/Utility/MacroHelper.cs
So here'a another of my messy grab bags of trivial changes. I am happy to merge myself unless anyone has a concern with any of this. Nothing controversial I think.
- Allow tavern window extension by mods, this is for Ralzars Calories mod so he can modify the tavern food & drink menu action.
- Allow travel map and popup extension by mods, for a new auto travel mod I'm making.
- Change horse animation to use unscaled time so it doesn't go mad at higher time acceleration - since it's in the players face, it doesn't look good.
- Expose the location type display name mapping from macros to public use.
> Relax permissions to allow window extension by mods

- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
A few improvements for the mod builder. These are the most significative changes:
- Do not allow to add an asset which is not saved on disk and would result in the inability to build mod. This can happen if asset is selected from scene hierarchy. A modal window with an error message explains to select assets from project window instead.
- Show a progress bar with information on current step. Most of the time is spent on API calls but is better than just showing an apparently stuck window.
- Prefabs and C# files need to be copied to temp location for edits before being added to assetbundle (rename to .txt and serialization of custom components). The import process is now performed only when all assets have been copied. Time spent on this step of building process is reduced from almost …
> Improve mod builder

- Assets/Scripts/Game/EnemyMotor.cs
This is basically an improvement over #1733.
In #1733 is conservatively lowered pathfinding probe distance from 1 to 0.8f. After more testing, lowering this distance further improves AI performance.
The first thing to notice, is that because probing is done using a CapsureCast with half the player's capsule radius, everything in probing geometry is proportional to player's capsule radius.
Second, if you consider the cast of following a flat surface (typically a wall), there's some relation between the ratio of probe length to capsule radius and the angle of incidence of probing: sin a = r / 2l
Very low incidence will make it hard to find doorways, very high would probably slow down progression along the wall, and a = 45° <=> l = r / sqrt(2) seems to give good results. The only other …
> Improve doorways pathfinding (again)

- Assets/Scripts/Game/EnemyMotor.cs
When enemy casters can see their target but are right behind some obstacle (say low obstacles like tables, fountains,...), the SphereCast used to check whether they're free to cast can miss the obstacle and allow them to cast, potentially damaging themselves (in classic lich style). An easily reproducible example of such behavior can be triggered in Orsinium entrance hall, if you agro the orc shaman but keep tables in his way.
Starting SphereCast from some position behind the caster could be a workaround, but since its radius is usually larger than caster's capsule radius, it's not very satisfactory (you don't start the SphereCast from inside a "known empty space"; The right offset would also depend on enemy capsule radius).
So instead I prepend the SphereCast test with a SphereCheck at …
> Prevent point blank spellcasting into low obstacles

- Assets/Scripts/Game/ControlsConfigManager.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
[[Images](https://imgur.com/a/7wrMblw)]
Adds support for secondary keybinds, which can be accessed via a small toggle button at the top right of the controls window. By default, they are unpopulated, although later in the future I will create ControllerConfigs that will have loadout configurations specific to the controller type and OS.
Any cross-unary conflicts will be highlighted as blue (to help colorblind people distinguish it from yellow or red/"dark yellow"), and the player cannot "Continue" until resolving them, but can switch between primary and secondary. Any internal (red) conflicts made, and they cannot switch between primary and secondary until that gets resolved first.
To not bloat the controls window and avoid static code, I made a ControlsConfigManager that sets aside much …
> Added support for secondary keybindings

- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/Scripts/Utility/MacroHelper.cs
This fixes %god macro expansion to match classic, see the issue reported by @JayH2971 here: https://forums.dfworkshop.net/viewtopic.php?f=31&p=45914#p45914. I fixed only `QuestMCP.God()` here, but the method could have been used globally.
While doing so, I moved an array extracted from FALL.EXE to `MapsFile` since it is also used in classic for the %god macro.
@ajrb
> Fix %god macro to match classic behavior

- Assets/Scripts/Game/MobilePersonMotor.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
Fixes some regressions:
- Unity 2019 doesn't allow to destroy or reparent gameobjects that are part of prefab instances. When a mod provides an override, the default gameobject is only deactivated instead.
- Custom providers of MobilePersonAsset that use colliders need to define a layermask to support functionality that checks for geometry in the way of npc path (regression introduced some time ago with `MobilePersonMotor.IsDirectionClear()`).
> Upgrade support for providers of mobile person graphics

- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Internal/PlayerGPS.cs
Quest faction macro wasn't expanded correctly when referring to another NPC than the questor. Again, the issue was reported by our quest expert @JayH2971: https://forums.dfworkshop.net/viewtopic.php?f=31&t=2109 :)
I also fixed factions IDs of vampire involved in quests since I noticed they were wrong while I was checking my fix against quest `R0C60Y24`, which uses `==vampire_` in the same way quest `P0B10L08 ` uses `==daedra_`.
> Fix quest faction macro expansion

- Assets/Scripts/API/BiogFileMCP.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
Based on classic reverse-engineering:
- %imp is only used to get a random name for the Emperor's son from a list of names extracted from FALL.EXE.
- %mn and %fn (male name and female name) are used in biographies and in a Noble quest to get a random full name, not first name.
- %mn2 and %fn2 do exactly the same, differing only from the above by using a different random seed.
> Fix %imp, %mn and %fn

- Assets/StreamingAssets/Factions/FACTION.TXT
- Assets/StreamingAssets/Factions/FACTION.TXT.meta
This fixes a lot of errors in FACTION.TXT. My fix is built on top of DelphiSnake's one, which was itself built on top of PLRDLF's fix. To check the list of DelphiSnake's changes: http://slushpool.dfworkshop.net/fact-changes.txt
What I also changed:
- Lady Bridwell is now properly listed under the Daggerfall faction: doing quests for her will now also raise reputation with Daggerfall.
- The Knights of the Hawk are now properly listed under Antiphyllos: this fixes an issue in-game were a member of this order could't rent a room for free in the region taverns.
- King of Worms now appears on top of The Necromancers, as every other guild leader.
- King of Worms and The Necromancers race set to -1 (just for the sake of consistency, since this field is not used at all in classic nor in DFU).
- …
> FACTION.TXT fixes

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/Entities/RaceTemplate.cs
- Assets/Scripts/Game/Questing/Person.cs
- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/TalkManagerMCP.cs
This actually fixes a bug from classic to make NPCs use the correct oath from their respective races.
Oaths are declared by NPC race according to the race index used in FACTION.TXT. Unfortunately, classic never uses this faction race ID but, instead, uses the hardcoded index race of each region, which is not the same. In classic, this results in all NPCs from High Rock saying Nord oaths, while all NPCs in Hammerfell will say Khajiit oaths.
Instead, DFU uses the faction race ID to return the correct oath.
So now, when talking to Morgiah when she doesn't like you, be aware:
@deepfighter, finally, FACTION.TXT race ID has found its intended use :)
> Use faction race ID for oath

- Assets/Scripts/Game/Automap.cs
- Assets/Shaders/DaggerfallAutomap.shader
Looks better than expected, given how simple is the shader modification.
The MR can be squashed, I attempted another approach first on this branch that doesn't need to stay around...
> Add water to dungeon automap

- Assets/Scripts/Game/Questing/Actions/RunQuest.cs
- Assets/Scripts/Game/Questing/Actions/RunQuest.cs.meta
- Assets/Scripts/Game/Questing/QuestMachine.cs
Added an action that allows to start a quest and wait for it to end, setting task for success or failure. This is the syntax:
```
run quest QUESTNAME then _success_ or _failure_
```
and this is a simple test example:
```
Quest: __DEMORUN
QRC:
QBN:
Clock _clock_ 5
start timer _clock_
_clock_ task:
give pc nothing
end quest
```
```
Quest: __DEMORUNMAIN
QRC:
QBN:
Clock _clock_ 5
start timer _clock_
_clock_ task:
run quest __DEMORUN then _success_ or _failure_
_success_ task:
give pc nothing
end quest
_failure_ task:
end quest
```
The purpose of this action is to track progress in a chain of quests (and/or reusable subquests) with a more modern approach compared to global variables, at least when a single success flag is enough. Success state is scoped to the instance of the quest that …
> Add run quest action

- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Read/Write Enabled flag must be set by mod author if texture is to be edited at runtime (for example to cut a button out of window image).
> Log warning if texture is not readable but needs to be

- Assets/Game/Addons/ModSupport/Editor/CompilerWindow.cs
- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
- Assets/Game/Addons/ModSupport/Editor/ModAssemblyBuilder.cs
- Assets/Game/Addons/ModSupport/Editor/ModAssemblyBuilder.cs.meta
- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Add option to Mod Builder to pre-compile C# scripts to a .dll file and add it to asset bundle as a binary asset.
> Support for precompiled mods (experimental)

- Assets/Scripts/Game/MagicAndEffects/Effects/Diseases/DiseaseEffect.cs
- Assets/Scripts/Game/PlayerActivate.cs
Currently, only "Attempted Breaking and Entering" is supported. This allows for the potential upgrade of the crime to full Breaking and Entering when you successfully break into the location. The check for Attempted Breaking and Entering is a Dice100.SuccessRoll(10). I did the same for Breaking and Entering (10% chance "someone saw you" breaking into the location). Guards are currently not being called for Breaking and Entering
Should guards ever be called for Breaking & Entering? I figure if this is implemented, being charged with Breaking and Entering in classic DFU is going to be a fairly edge case (probably: guards got summoned for Attempted B&E, you broke in, went back outside, and the guards arrested you).
Also, made IsDiseasePermanent() public instead of protected and added …
> More Disease info, can be charged with Breaking and Entering

- Assets/Scripts/Game/ControlsConfigManager.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
Added ability to right-click a keybind button which prompts if the player if they would like to set it to 'None'. This is useful for secondary keybinds where someone might accidentally bind the wrong button or no longer would like to use it. As of right now, they  would have to find an unused key to bind to it or set it to None in the Keybinds.txt file, but actually having an in-place removal would help with this issue.
One problem I encountered was the fact that DFU always assumed the primary keybinds (`InputManager.actionKeyDict`) to be non-`None` since there wasn't any need for them to be in the first place. This made finding secondary KeyCode equivalents based off of the primary KeyCode a problem if it was set to `None`, since there can always be duplicate `None`s. So I created an …
> Keybind right-click removals

- Assets/Scripts/Game/InputManager.cs
After having unstick handling removed, there no longer needs to be an arbitrary float value in place that prevented it from going off. Additionally, the `JoystickMovementThreshold` (the ceiling value for maximum movement via joystick) is now used to scale with the distance of the joystick. So if the `JoystickMovementThreshold` is 0.5 and the user moved their joystick at 20% distance from the center, their force would be 0.2 / 0.5 = 40%. Compare this method to having 49% distance as 49% force, but 50% distance = 100% force.
> Update joystick minimum force and acceleration

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs
- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Game/Serialization/PrintScreenManager.cs
- Assets/Scripts/Game/Serialization/SaveLoadManager.cs
- Assets/Scripts/GenerateDiagLog.cs
- Assets/Scripts/SettingsManager.cs
Added a commented-out preprocessor definition under `SettingsManager` called `SEPARATE_DEV_PERSISTENT_PATH`, which allows development under the Unity editor to use a separate data directory called "DaggerfallUnity.devenv", which is alongside the default path. This is useful for separating recreational saves and settings from the development side for organization, and to prevent wiping of settings not yet implemented in the stable release.
I grepped and replaced all instances of `Application.persistentDataPath` with `DaggerfallUnity.Settings.PersistentDataPath`.
> Preprocessor definiton for separate development persistent path

- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Game/StaticNPC.cs
- Assets/Scripts/Game/TalkManager.cs
Static NPC race is now stored in its own dedicated field. If not available from faction data, fallback to race of current region.
This also fixes an issue reported by @petchema in #1902 where Aubki-i was using %oth in a quest before being assigned as questor. The previous workaround was a fallback to race of current region. Now, Aubk-i will properly use the Redguard pool of oathes.
> Set the race of static NPCs

- Assets/Scripts/Game/PlayerEnterExit.cs
It can mess with non-modal UI's like those used by Tedious Travel etc.
I think this works well, but I would be interested in other devs opinions before this one gets merged. Motivated by holiday message boxes messing up the travel UI of my upcoming Travel Options mod when they pop up at the wrong time.
> Don't show holiday text message unless HUD is top window

- Assets/StreamingAssets/Quests/L0B30Y03.txt
- Assets/StreamingAssets/Quests/N0B20Y05.txt
- Assets/StreamingAssets/Quests/P0B00L06.txt
- Assets/StreamingAssets/Quests/R0C10Y04.txt
- Assets/StreamingAssets/Quests/R0C4XY23.txt
Fixes done to quest texts only, to avoid any potentially breaking change.
> Replace mispelled "sorceror" with "sorcerer" in quests

- Assets/Scripts/Game/HotkeySequence.cs
- Assets/Scripts/Game/InputManager.cs
Small oversight when designing secondary keybinds allowed `GetMouse` methods and `HotkeySequences` to look for the secondary equivalents of a specific key when it wasn't supposed to. Created a default parameter for GetKey methods to look for the secondary by default, but set them to false instead for the `HotkeySequence` methods, and used the `GetSingleKey` methods for the `GetMouse` methods.
> Ignore secondary binding equivalents for GetMouse methods and HotkeySequences

- Assets/Scripts/Game/InputManager.cs
It seems that it was intended to have both Shifts and Alts be able to work Run and Sneak but when written at the time, there wasn't any support for secondary bindings, thus the "right" versions of the keys accidentally overrode the "left" versions in the default bindings.
I think it's better to just default them to the "left" versions since they are closer to WASD, but leave it up to the player if they want to include the "right" versions in their secondary bindings.
I also fixed some space formatting issues made by earlier PRs.
> Change default bindings of Run and Sneak to Left Shift and Left Alt, respectively

- Assets/Scripts/Game/HotkeySequence.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
The `toggle_close` hotkey sequences under the Automap windows must look for the secondary bindings so that way the menus can be toggled off with either button. Otherwise, by default `HotkeySequence`s will not.
> (Regression fix) Allow some hotkey sequences to look for secondary bindings

- Assets/Scripts/Game/ControlsConfigManager.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
https://imgur.com/a/rBGxQzS
- Changed the display of KeyCodes without altering the strings that are serialized in Keybinds.txt. Non-alphabetic keys are displayed as their true character, except for numbers. Joystick buttons are displayed as "Joy BX" and Joystick axis buttons are displayed as "JoyX BY".
- When in non-SDF rendering, it will display certain KeyCode strings in a Daggerfall DOS-inspired format (barring some such as "SPCEBAR", mouse buttons like "M 1" and "M 2", etc.)
- If the KeyCode string is too long (in preparation for custom combo codes), the label text will display `...` and you can hover over it to see its full name. The tooltip gets updated/disappears if a smaller-length KeyCode string is binded. If you would like to test this, change the …
> Improved keybind label text and tooltips

- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/RDBLayout.cs
When providing a replacement for _DaggerfallActionDoor_ prefab,  `DaggerfallActionDoor` component must be added by mod author. If component is missing an error message is now logged.
> Add check for DaggerfallActionDoor on door prefab

- Assets/Game/Addons/ModSupport/ModManager.cs
Title is a mandatory property of ModInfo manifest file. An empty or null title causes several issues so mods without a valid title are now ignored logging an error.
> Discard virtual mods without a valid title

- Assets/Scripts/Game/ControlsConfigManager.cs
- When right-clicking a button with hidden text ("..."), the remove assignment will actually display the Keybind and not "..."
- Message box wraps text
- Regex-spaced out the Action name
> Small fix and improvements to remove assignment message box

- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
- Remove characters limit to use all the available space with SDF font rendering.
- Use different text color for enabled/disabled mods.
- Use different background color for show description button if mod doesn't have a description.
> Minor improvements to mod loader UI

- Assets/Scripts/Game/ControlsConfigManager.cs
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterface/Button.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
Introduces a way for players to bind a combination to a single action in the controls window, e.g. "LeftShift + K", "RightControl + K", "K + V", "[ + /", "Joy3B0 + JoyB2".
Since KeyCodes are 32-bit integers, the max length of the KeyCode enum is around 300, and the axis KeyCodes are less than 16-bits long, I managed to store two KeyCodes into one as *15* bits each. (I chose 15 instead of 16 so the most significant bit isn't 1 and becomes a negative number.) You can create a combo by using `GetComboCode(key1, key2)`.
When binding in the controls window, it will make sure that:
- There is no duplicate combo (e.g. two "LeftShift + K"s)
- The modifier is not used independently in any other binding (e.g "LeftShift + K" and "LeftShift")
- The modifier is not used as a key (e.g. "LeftShift + K" …
> Bindable KeyCode combinations

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
For bindable combo keycodes to work properly when closing a window that has a binding using Shift/Ctrl/Alt.
> Change Automap toggle to GetKey method

- Assets/Scripts/Game/UserInterface/Panel.cs
Using the Unity profiler, I found that using a foreach loop of a BaseScreenComponentCollection class allocates memory when getting the Enumerator, and Panel.Draw() is called every frame using that loop. The setup wizard alone took 0.7 KB before under DaggerfallUI.OnGUI(), now it is 0.
> Remove GC in drawing Panels

- Assets/Scripts/Game/EnemySenses.cs
Current pursuit algorithm in EnemySenses compute how much time will be needed to reach the current position of the target, then computes by how much the target will have moved by then. This is only an approximation, because it does both the hypothesis that the target won't move and that it will move. The fastest the target, the less accurate it gets.
One can exploit that inaccuracy by rushing at enemies, that will turn their back, pursuing a position behind them. Hence current algorithm has an additional test to detect that condition, but it doesn't seem to work perfectly, the exploit still exists.
Accurate approach is to compute at what moment the target will be on a sphere centered at pursuer position, growing at its interception speed each second; Or, in 4 dimensions (x, y, z, t), …
> More accurate pursuit formula

- Assets/StreamingAssets/Quests/R0C20Y07.txt
- Assets/StreamingAssets/Quests/R0C20Y22.txt
Clocks with
- both timerValue0 = timerValue1 = 0 and
- neither flag & 1 or flag & 16
Will have a final clockTimeInSeconds of 0, not overridden by a travel time.
(source https://www.twitch.tv/videos/741689738?t=4h16m16s )
Until Clock implementation is changed, a workaround for those cases is to modify flag to have either flag & 1 or flag & 16.
Fortunately, there's only 2 such instances.
> fix Clocks that would return 0 days

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
Addresses the bug discussed here: https://forums.dfworkshop.net/viewtopic.php?f=31&t=3923
Bonuses and phobias are now applied to player AND enemy armed/unarmed attacks.
Note: This will break any mods that override GetBonusOrPenaltyByEnemyType
> Apply bonuses and phobias to all attacks

- Assets/Scripts/Game/Items/ItemCollection.cs
This has been around for a while undetected. Just added some code that uses this and was scratching my head for a while... hope this can go into .26 but not a big issue if not.
> Fix SearchItems method when no template index specified

- Assets/Scripts/Utility/MacroHelper.cs
See bug report https://forums.dfworkshop.net/viewtopic.php?f=31&t=4117
I changed the localization table for internal strings to add:
temple = temple
but it doesn't seem to have got picked up in the commit and I don't know what to do.
> Ensure shrines are handled correctly

- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/Serialization/SerializableStateManager.cs
- Assets/Scripts/Game/Utility/PopulationManager.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/RDBLayout.cs
Hooking into enemy / npc spawning isn't super doable currently, making modding a bit tough. This makes modifying enemies itself a lot harder than it should be! Adding spawn events is a major way to make this easier.
All cases I could find correctly trigger these events - dungeon enemies, quest spawns, sleeping encounters, etc.
> Enemy + Mobile NPC Spawn Events

- Assets/Scripts/Game/Player/PlayerHeightChanger.cs
The sneak action either uses ActionStarted when in toggled mode, or HasAction when not. To keep a consistency for all physical actions, I believe the crouch action should be changed to "ActionStarted" as well.
> Change crouch action to "key-down" (ActionStarted)

- Assets/Scripts/Game/TransportManager.cs
- reset flag so that new coroutines can be started
- And rename stoppedRidingAudio as pendingStopRidingAudio to better convey
its purpose.
Fixes a regression introduced in 0.10.23
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4191
> fix horse/cart sound stopping (regression in 0.10.23)

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/Utility/StartGameBehaviour.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
- ProjectSettings/ProjectSettings.asset
Some people seem to be annoyed by runInBackground being false now.
It's hard to tell what value satisfies the most people, however I suspect it's when runInBackground is enabled, and only a minority really prefers it to be disabled.
So, making it a hidden setting (.ini only), defaulting to true.
Original issue:
https://github.com/Interkarma/daggerfall-unity/issues/1942
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4236
> make runInBackground a setting

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBaseWindow.cs
I'm writing a mod for displaying tooltip information in the world and some of these methods need to be public in order to retrieve all of the information about it. Also publicized `ChangeInteractionMode` and `Pickpocket` as they would probably be useful for future mods.
`NativePanel` would be useful as a public property to get information about certain information about windows and adding components to them without overriding the class itself.
> Publicize parts of PlayerActivate and NativePanel for mod support

- Assets/Scripts/Game/Automap.cs
Adjust dungeon micro map resolution to dungeon size.
Fixes issues with some dungeons like The Ruins of Moorford Manor, Daggerfall.
This is an alternative to #1958
> Autoadjust micromap size

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
This is for issue #1962.
This PR essentially would replace the utility of `PlayerEntity.IsLoitering` and `PlayerEntity.IsResting`, but may be kept for mod compatibility reasons. I also have no problem with removing them if requested. :)
I publicized the `RestModes` enum and kept it in `DaggerfallRestWindow`, but I can move it elsewhere to `DaggerfallUnityEnums` if mod compatibility is also not an issue.
> Publicize CurrentRestMode

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/DaggerfallUnityEnums.cs
- Assets/StreamingAssets/Factions/FACTION.TXT
- Assets/StreamingAssets/Tables/Quests-Factions.txt
Fix Bhoriane county mispelled as Bhoraine in FACTION.TXT, which resulted in similar mistakes in DFU source files.
Discussion here: https://forums.dfworkshop.net/posting.php?mode=reply&f=5&t=4294.
> Correct Bhoriane spelling everywhere

- Assets/Scripts/Game/EnablePlayerTorch.cs
Currently uses a message box which stops the player in their tracks.
> Use HUD text for light source depletion message

- Assets/Localization/StringTables/Internal_RSC_en.asset
- Assets/Scripts/Utility/MacroHelper.cs
This PR is a first attempt at correcting TEXT.RSC errors. The following ones were fixed:
- All directions given by NPCs should be fixed. No more _The best way to go The Green Hedgehog is southwest of here_. Now, the NPC will properly answer _The best way is to go southwest of here_. I tried to correct all of these historical mistakes, but a review would be greatly appreciated.
- Knightly order descriptions are now using proper guild names. No more Knights of the Dragon described as Order of the Dragon. Also, the Knights of the Hawk are properly assigned to Antiphyllos.
- Replaced the non-existent %pc macro (even in classic) with %fpc.
- Fixed the "Freshly burried dead" issue reported here: http://forums.dfworkshop.net/viewtopic.php?f=12&t=2692&sid=892c8fc88eac4bc46f06d9cdcf49eb78
- …
> Fix several mistakes in Text.rsc

- Assets/Scripts/Game/InputManager.cs
To remove code duplication and prevent binding inconsistencies in the future, this PR combined both functions by using a boolean parameter called `autofill` that will determine whether to forcefully reset the bindings or simply fill in what is missing.
> Combine SetupDefaults and ResetDefaults as one method

- Assets/Scripts/Game/TalkManager.cs
Fix greetings when talking to unique NPCs affiliated to guilds, like Karethys or Popudax.
Fix #1973
> Fix guild greetings for unique NPCs

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/WeaponManager.cs
Note: Changes the signatures of CalculateAttackDamage and CalculateBackstabChance delegates.
It seemed weird to pass around a frame record number that's tied to current enemies animation.
> Prevent backstabbing daedra seducers during transformations

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/SongManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
Adds a new checkbox to advanced settings under audio. If checked, the game will use the FM version of the soundtrack if an OPL3 soundfont is in use or custom music files that replace FM songs are loaded.
It works well with @petchema's mod here: https://www.nexusmods.com/daggerfallunity/mods/79/
The OPL3 soundfont found here: https://musical-artifacts.com/artifacts/15 doesn't make the songs sound quite the same as they do in classic, unfortunately. It's theoretically possible to mimic Classic's OPL3 soundtrack with a proper soundfont in conjunction with this PR, however.
> Create a setting to choose the FM soundtrack

- Assets/Scripts/Utility/AssetInjection/Components/ObjectPositioner.cs
- Assets/Scripts/Utility/AssetInjection/Components/WallPropPositioner.cs
By default  a mesh renderer is seeked on gameobject to get bounds. Renderer field can be assigned from the inspector to override this behaviour and use a different renderer. For example this is useful when a lod group is used and root gameobject doesn't have a mesh renderer attached.
> Allow custom Renderer for ObjectPositioner

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
Immediately apply volume changes in launcher.
Play door effect to check sound volume.
I had to create a temporary GameObject to get a separate
DaggerfallAudioSource. Not sure how I feel about that.
> Immediately apply volume changes in launcher

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallStaticDoors.cs
- Assets/Scripts/Utility/RMBLayout.cs
Guards now spawn at the ground-level door in taverns and residences. The door farthest from the building's origin is chosen to prevent guards entering from the building's courtyard.
Note that guards can still spawn in an unreachable place in disconnected interiors. This PR does not cover that issue.
> Handle interior guard spawns for taverns and houses

- Assets/Scripts/API/DFBlock.cs
This solves an issue I discovered and reported which causes all doors inside the overridden block to use model 9000.
Fixes #1989
> Made DoorModelIndex public

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
If you encumbrance is maxed out, picking maps will work but be followed by a "can't carry any more" message that was stacked below by the call to CanCarryAmount().
This doesn't happen with arrows because their effective weight is 0.
Extend this to maps, which is the simplest fix.
> Fix spurious "can't carry any more" when picking maps

- Assets/Scripts/Internal/DaggerfallSky.cs
I observed that one straight north and south of classic skybox with Distant Terrain, but I suppose it's not caused by it; However if I reload the save with another terrain generator my position is changed and the seam disappears.
[SAVE475.zip](https://github.com/Interkarma/daggerfall-unity/files/5720252/SAVE475.zip)
> more skybox seam fixes

- Assets/Scripts/Game/SongManager.cs
Makes sure they're 15 dungeon FM songs, like the 15 dungeon GM songs, so that songs stay in sync.
In classic Daggerfall configured for SoundBlaster 16,  
- fm_dngn1 plays in The Convocation of Elona, Daggerfall
- 15fm plays in The Ruins of Copperhart Orchard, Daggerfall
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4401
> Fix dungeon FM songs (related to #1953)

- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
This makes no change to vanilla DFU, but allows mods to allow sprint riding. This will fix the Roleplay & Realism mod exhanced riding sprint function to be faster rather than slower as it currently is.
I can take a different approach if this change is a problem.
> Return to using baseSpeed if riding

- Assets/Scripts/Game/SongManager.cs
Fix the bug reported on the forums: http://forums.dfworkshop.net/viewtopic.php?f=5&t=4446&sid=1f23cb27abe1fc66bb5e39698055c153. This is similar to what classic does.
I also removed a temple song as there should be only 8 of them, corresponding to the 8 deities.
> Ensure that both Mages Guild songs can be played

- Assets/Scripts/API/BiogFileMCP.cs
- Assets/Scripts/Game/Questing/QuestMCP.cs
- Assets/Scripts/Game/TalkManagerMCP.cs
- Assets/Scripts/Utility/MacroDataSource.cs
- Assets/Scripts/Utility/MacroHelper.cs
Fix an issue reported on the forums regarding the %fn macro: http://forums.dfworkshop.net/viewtopic.php?f=31&t=4447&sid=26748510f65c64d9c1d3237b74cb59cb
This issue can be seen on character biography when creating a Warrior. The same bug also affects the %mn macro when creating a Knight.
There is also one affected noble quest using both macros, R0C11Y28, where names on the autopsy report are always changing without this fix.
I also took the time to refactor the `MacroHelper.Name` method as its current state was not satisfying.
> Fix some naming macros

- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
Dungeon models can also be used outside of a dungeon, so default material should always be applied even if "Use Dungeon Texture Table" option is enabled.
> Fix part of #1990

- Assets/Scripts/DaggerfallUnity.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Terrain/TerrainNature.cs
- Assets/Scripts/Terrain/TerrainNature.cs.meta
This allows new nature layout algorithms to be used by mods in the same way terrain height samples and textures can be replaced.
Example usage:
` DaggerfallUnity.Instance.TerrainNature = new BasicRoadsNature();
`
> Refactor nature layout to it's own class and interface

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Custom assets are tipically only seeked in the Game scene. Cursor is a special case because is also needed in the Startup scene, so there was an issue where a mod providing the cursor, initially enabled, was disabled resulting in a missing cursor, as well as an issue where a custom cursor was provided by a disabled mod.
Cursor is now also seeked on game launch to ensure changes to mod configuration during setup (i.e mod enabled or disabled) are applied.
> Refresh cursor on game start

- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
I am working on a Thief overhaul mod and to make any headway I need the ability to override the stealth check.
As far as I can see, only EnemySenses.cs checks this, so I have made a PR that moves this calculation to FormulaHelper, making it possible for mods to easily change how stealth is checked.
> Move Stealth skillcheck to FormulaHelper

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Terrain/TerrainNature.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
Turns out that live builds can sometimes update locations in a different order leaving the last location set to someplace other than current which breaks building variants for first entry.
Also added some docs for the terrain nature interface.
> Ensure that the last location is set to current loc when entering a building.

- Assets/Scripts/Game/MobilePersonNPC.cs
There is a bearded Nord who's face data goes unused. This changes the value from 264 to 168 to restore the NPC's proper face to the game. I will also need this for my VIO mod in the future.
> Unused Face Data for Male Nord

- Assets/Scripts/Game/Questing/Actions/PayMoney.cs
This action was added for my R&R quest Mountain Rumors. With the latest quest machine changes I needed pay money to be able to limit to just real gold pieces. SHould be backwards compatible with saves, and it worked for me.
> Update paymoney quest action to allow only gold to be accepted if desired

- Assets/Localization/StringTables/Internal_RSC_en.asset
Fix a bug reported on the forums: http://forums.dfworkshop.net/viewtopic.php?f=5&p=52162&sid=a9eea9ca6a9b8d58b2ded2b973db6856
I choosed to use %pcn (player's full name) here rather than %pcf (player's first name), as it seems more appropriate for a hostile reaction.
I also took this occasion to add some missing apostrophes.
> Fix %pcn macro written as %pfn and add missing apostrophes

- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
- Assets/Scripts/Utility/RMBLayout.cs
Missed this before because I was doing a guild and they don't use a seed for the name. Have already updated documentation accordingly here https://forums.dfworkshop.net/viewtopic.php?p=32886#p32886
> Add NameSeed to building overrides

- Assets/Scripts/Game/Automap.cs
While building the dungeon's Automap, the script's CreateDungeonGeometryForAutomap function disables the CombineRDB option to create individual models in the map instead of a combined model. After generating these models, it then re-enables this option. The problem is that if the user has disabled this option through the Unity Editor, this script re-enables it after generating the automap, forcing the user to re-disable it every time they load or enter a dungeon.
This commit adds a check to the setting manipulation so that at the end of automap generation, the CombineRDB option will only be re-enabled if it was originally enabled at the start of generation.
> Automap: Check CombineRDB state before resetting

- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
[[0.11.0] All On/Off buttons in mod management don't update mod name "ghosting"](https://forums.dfworkshop.net/viewtopic.php?f=31&t=4556)
> Fix mods window all on/off text color

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
Fixed misnamed formula overrides for CalculateFatigueRecoveryRate and CalculateSpellPointsRecoveryRate
Every other formula in that file has an override named after the function name. These two seem to be a copy-paste error. The function signature is not even consistent, so it wouldn't work as intentional design.
> Fixed misnamed formula overrides

- Assets/Scripts/Game/Questing/QuestListsManager.cs
This is for the Witch Coven guild that is not joinable, and leaves all non-member quests with 0 rank/rep defined in the quest list still able to be given to players with negative rep.
> Allow non-member quests to have rep requirements

- Assets/Scripts/Internal/DaggerfallDungeon.cs
- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
RuntimeMaterials previously didn't take the game's RandomDungeonTextures setting into account when it decided to apply climate variations to dungeon models. This meant that dungeon models using RuntimeMaterials looked noticeably different next to vanilla models. This PR integrates the same logic that DaggerfallDungeon uses to decide what textures vanilla models use. 
The texture assignment abilities of RuntimeMaterials now ~almost~ matches that of the vanilla logic. The only thing I still need to sort out is that when the RandomDungeonTextures setting was set to "Random", I found a dungeon (Castle Buckington - Ilessan Hills in this case) where the vanilla models were using textures from the "Swamp" climate set whereas RuntimeMaterials used the "Temperate" set. Edit: This no longer …
> RuntimeMaterial: Take RandomDungeonTextures setting into account

- Assets/Scripts/Game/Automap.cs
This does two things:
1. Makes the UpdateMeshRendererDungeonState() function be called on all components of all children of the current transform model instead of only the first component in it's root. This fixes an issue where already discovered models on the dungeon map are not revealed after loading a save game if an OBJ file has been used to replace the model.
2. Solves an issue where the SaveStateAutomapDungeon function doesn't properly save the discovery state of OBJ models because it only checked the MeshRenderer component attached to the model's root and not those attached to children.
This PR is identical to #2002, just with all of my changes moved to a new branch. This PR fixes #1995.
> Automap: Add support for the discovery state of OBJ models to be saved and loaded

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
Previously, GameObjectHelper ran the SetDungeon function in DaggerfallDungeon before returning it's results. Since PlayerEnterExit uses the value of this returned result to fill it's Dungeon variable, this meant that there was a short period where Dungeon was equal to Null even though the DaggerfallDungeon object existed. This moves the SetDungeon function so that it runs after the Dungeon variable is filled.
I encountered this problem while working on PR #2026 where I couldn't retrieve the value of the dungeon's ID because Dungeon was still Null while the ApplyMaterials function in RuntimeMaterials was running.
> PlayerEnterExit: Reduce delay filling Dungeon variable

- Assets/Scripts/Game/Automap.cs
- Assets/Scripts/Game/AutomapModel.cs
- Assets/Scripts/Game/AutomapModel.cs.meta
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/RDBLayout.cs
This moves the contents of the InjectMeshAndMaterialProperties and UpdateMaterialsOfMeshRenderer functions into the AutomapModel script. This script is attached to every model that is used to construct the Automap. Then, instead of the Automap script iterating through the Automap tree to run these function on every model it finds, it raises an event that causes each model to run it's copy of the AutomapModel script functions.
I also made one or two optimisations to the existing code, resulting in a 55-60% reduction in the time it takes. Here are some numbers I got for the time taken for the InjectMeshAndMaterialProperties loop/event to run on loading or entering these locations on my desktop PC. For some reason, the function appears to run twice for dungeons and once for castles. I …
> Automap: Move Mesh and Material update to separate script

- Assets/Scripts/Game/Automap.cs
- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
I noticed some issues with the way dungeon Automap models are created which caused them to use the wrong texture tables when creating their materials. Both the vanilla models and RuntimeMaterials had this problem.
For the vanilla models, the script was passing a null reference for the texture table, causing the CreateBaseGameObject method to just use the default table. For RuntimeMaterials, the script was getting the texture table from an event that never fired.
It has been reported in the forum [here](https://forums.dfworkshop.net/viewtopic.php?f=31&t=4412).
If merged, this PR will fix the second problem mentioned in issue #1990.
@TheLacus - Maybe you should review the RuntimeMaterials portion of this PR?
Edit: Merging this PR will fix #1990 as this is the last part of that issue that …
> Fix issues where dungeon Automap models are created using the wrong texture table

- Assets/Scripts/Terrain/DaggerfallTerrain.cs
- Assets/Scripts/Utility/ViewportChanger.cs
This fixes three of the warnings that appear in the editor every time scripts are re-compiled by:
- Adding "new" keyword to ViewportChanger's Camera variable.
- Deleting line in DaggerfallTerrain that sets materialType as materialTemplate is now set directly.
The warnings related to WWW being obsolete are still present because, [as I discovered](https://forums.dfworkshop.net/viewtopic.php?p=52520#p52520), UnityWebRequest is not a straight drop-in replacement for DFU's current code.
> Fixed some editor warnings

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/WeaponManager.cs
Hi all,
I saw this as a bug, but it may have been intentional. If so, please reject this PR.
I noticed that the click to attack never selects Thrust forward. It turns out that the random selection doesn't have thrust as an option. I changed it to now include upRight (enum #3 instead of starting with Left Enum #4).
I did have to change FPSWeapon as OnAttackDirection was only looking for Up instead of also looking for UpLeft and UpRight.
Thanks
a
> Added Forward Thrust as an option

- Assets/Scripts/Game/Player/AcrobatMotor.cs
Make horse jumping capability independant of player's capability, so you can always jump over hedges with the horse.
I used a jumpSpeedMultiplier value higher than strict minimum so horse doesn't "stumble" as much on hedges (unless you have perfect timing); But best value is debatable.
Forums: https://forums.dfworkshop.net/viewtopic.php?p=51147#p51147
> Constant horse jumping capability

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
Inserts a new middle-click keybind accessible through the Joystick controls window, defaulted to `JoystickButton2`. Added in part by #2032 but would also benefit existing in the first place for mods that might make use of the middle mouse button.
Set the UI controls to protected so they can be accessible to subclasses created by mods.
> Add joystick middle-click keybind and set Joystick UI controls to protected

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
If the player accidentally moves their movement or camera axis in a cutscene sequence, it will recognize it as a button press in the direction it went and skip the video, since it was looking for "any key down". Similarly, a player might accidentally bind either axis while the control window is waiting for a key press (especially when trying to bind the controller buttons commonly known as L3 and R3, where you press down on the joysticks.) Those axis buttons are not needed for any practical reason since they are already in use for moving the character and camera.
These changes will simply ignore those detected axis buttons if they are a part of the movement or camera axes. I also added two new boolean property getters `AnyKey(Down/Up)IgnoreAxisBinds` and four new public `KeyCode` methods …
> Prevent detecting accidental axis button "presses" from movement and camera axes

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/HotkeySequence.cs
- Assets/Scripts/Game/Serialization/PrintScreenManager.cs
- Assets/Scripts/Game/UserInterface/Panel.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
Hi all,
This PR is in response to a bug report from agris in Inventory Filter; the bug report can be found at https://forums.dfworkshop.net/viewtopic.php?f=27&t=3224&start=30
the approach used to resolve the issue was proposed by @petchema at https://forums.dfworkshop.net/viewtopic.php?f=23&t=4612
This approach is to change the data type of HotKeySequenceProcessed from a bool to an enum in order to support a third state: Disabled
If a window control has focus and is set to overrideHotKeys then HotKeySequenceProcessed = disabled.
If not, then if hotKeysequence recognized, HotKeySequenceProcessed = Handled
otherwise, HotKeySequenceProcessed = NotFound
@petchema, If you wouldn't mind taking a quick peek at the code, I would really appreciate it.  It seems to be working, but I just want to …
> Change HotKeySequenceProcessed From Bool To Enum

- Assets/Scripts/Game/Questing/Place.cs
It happens occasionally and breaks the rest of one of the Archs guild quests Jay wrote when it does occur.
Rather hard to reproduce as it's based on random number selecting the current location.
> Prevent player location being selected for remote place

- Assets/Scripts/Game/DaggerfallUI.cs
I found an issue in the code that I had submitted in PR # 2056.
In DaggerfallUI, I check for uiManager.TopWindow.FocusControl not to be null but I just hit a situation where uiManager.TopWindow was null so this failed on nullException.
I added a check for TopWindow as well now to correct that issue.
Sorry for this, the issue.
Thanks 
A
> I found a bug in the code that I had submitted as part of PR 2056.

- Assets/StreamingAssets/Quests/A0C00Y06.txt
- Assets/StreamingAssets/Quests/A0C00Y10.txt
- Assets/StreamingAssets/Quests/A0C00Y12.txt
- Assets/StreamingAssets/Quests/A0C00Y14.txt
- Assets/StreamingAssets/Quests/A0C01Y09.txt
- Assets/StreamingAssets/Quests/C0C00Y11.txt
- Assets/StreamingAssets/Quests/M0B20Y02.txt
- Assets/StreamingAssets/Quests/M0C00Y12.txt
- Assets/StreamingAssets/Quests/M0C00Y13.txt
- Assets/StreamingAssets/Quests/M0C00Y14.txt
- Assets/StreamingAssets/Quests/N0B10Y01.txt
- Assets/StreamingAssets/Quests/N0B10Y03.txt
- Assets/StreamingAssets/Quests/N0B20Y02.txt
- Assets/StreamingAssets/Quests/N0B21Y14.txt
- Assets/StreamingAssets/Quests/N0C00Y10.txt
- Assets/StreamingAssets/Quests/N0C00Y11.txt
- Assets/StreamingAssets/Quests/N0C00Y13.txt
- Assets/StreamingAssets/Quests/P0A01L00.txt
- Assets/StreamingAssets/Quests/P0B00L06.txt
- Assets/StreamingAssets/Quests/P0B10L07.txt
- Assets/StreamingAssets/Quests/Q0C00Y04.txt
- Assets/StreamingAssets/Quests/Q0C00Y06.txt
- Assets/StreamingAssets/Quests/R0C10Y18.txt
- Assets/StreamingAssets/Quests/R0C11Y03.txt
- Assets/StreamingAssets/Quests/R0C11Y16.txt
- Assets/StreamingAssets/Quests/R0C11Y27.txt
- Assets/StreamingAssets/Quests/R0C20Y07.txt
- Assets/StreamingAssets/Quests/R0C20Y22.txt
- Assets/StreamingAssets/Quests/S0000001.txt
- Assets/StreamingAssets/Quests/Y0C00Y00.txt
In some quests the text of the journal entry starts directly after the variable _%qdt:_. 
I changed those entries and reformatted them, so that now all the text is on a new line, which is the preferred way, as seen in all the other instances.
(btw. first pull request (ever)! :))
> Fixed date lines in journal entries of quests

- Assets/Scripts/API/BiogFileMCP.cs
Verified with:
1. Launch the original Daggerfall game
2. Create a new character
3. Make a Dark Elf Healer
4. Proceed to gameplay
5. Enter Character Sheet (F5), click History
6. Proceed to background history
7. See "_Your father was the healer for a very small village deep in the mountains of Morrowind._"
DFU currently says "rolling hills of Morrowind".
All the other races have been verified and were already correct.
> Fixed %hpw being inconsistent with DF classic for Dunmer characters.

- Assets/Scripts/API/BookFile.cs
- Assets/Scripts/Utility/AssetInjection/BookReplacement.cs
On a few occassions, I've loaded a save only to get the HUD overlaying a black screen. The game still appeared to be running but the game didn't seem to react to my inputs. I couldn't open the main menu either and had to kill the game. On this occasion, I caught this happening in the editor which reported an `EndOfStreamException` in the line `header.PageOffsets[i] = reader.ReadUInt32()`. As a result, I added a try-catch check to gracefully handle this exception in future for any part of the BookFile's BinaryReader code.
> BookFile: Added try-catch check to BinaryReader portion

- Assets/Scripts/Game/EnablePlayerTorch.cs
Every frame, if the game is not paused, the torch checks if more than 20 seconds has elapsed since the last tick, and if so, reduces condition. This check is based on real time­. Therefore, if a tick occurs and the player pauses immediately for at least 20 seconds, once they come back to gameplay, the torch will burn again immediately. No game mechanic should progress while the game is paused.
This implementation instead uses a time buffer that increases in time only while the game is not paused (and the torch is active of course). One potential issue is that the timer does not reset when unequipping the torch, but it might be a good thing, since it prevents "exploits" based on unequipping the torch every 19 seconds.
> Fixed torch burning ticks progressing while the game is paused

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs
- Replace ingredients with an ItemCollection of cloned ingredients, not shared with either player's inventory or wagon.
- Add/Remove ingredients to the cauldron using ItemCollection methods
- When the cauldron is mixed, find and remove ingredients from player's inventory first, and wagon as a fallback.
This is a more extensive rewrite than take 1, so I don't exclude bugs.
> fix potion maker's stackCounts (take 2, alternative to #2011)

- Assets/Scripts/Game/UserInterface/ItemListScroller.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
See page 53 of the original Daggerfall manual. Variant changing was added to right clicks, this is now on middle mouse click.
As discussed here: https://forums.dfworkshop.net/viewtopic.php?p=52256#p52256
@Interkarma This is a candidate change which you can veto if you wish. 
Note that it may break mods that override inventory or trade UI windows until they are updated.
@petchema Would you mind casting your eye for detail over this one and test it to see if I missed any interactions.
> Implement right clicks as described in Daggerfall manual

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs
Caster level is a core feature of Daggerfall spell effects. The 3 ways effects change in effectiveness is in their duration, their cast chance, and their magnitude. All three properties scale based on caster level, and this is the main way a spell gets better as the player progresses (aside from casting cost). The SpellMaker interface deals with caster levels, and a spell's information will also feature this level scaling.
Therefore, a mod that wants to modify existing or add new spell effects to the game will also most likely deal in terms of caster level. Currently, the caster level is always equal to the entity's level. But what if mods wanted to change that?
In my research, I've found one mod that tries to change the caster level: Unleveled Spells …
> Adding a FormulaHelper hook "CalculateCasterLevel"

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallEffectSettingsEditorWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellMakerWindow.cs
This pull request is for overriding CalculateTotalEffectCosts, CalculateEffectCosts, ApplyTargetCostMultiplier. Since C#'s `System.Func` does not handle `out` parameters, I've replaced the gold cost and spell point cost out parameters with a single return type containing both values, a struct inside `FormulaHelper` called `SpellCost`. I thought it would be preferable to having a generic `Tuple<int, int>`. Tell me if there's a better place to put this structure.
The branch has no impact on gameplay, but allows mods to change how spell effect costs are calculated. 
Example: https://github.com/KABoissonneault/DFU-BalancedSpellCosts/blob/main/Scripts/BalancedSpellCostsMod.cs#L41
This mod keeps the same overall formula, but removes the truncating in the "Per-level" cost calculate and in the …
> Adding formula overrides for spell effect cost formulas

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
If a spell has multiple effects, the entity effect manager will remove its bundle when the last effect expires, rather than when all effects expire.
To reproduce:
1. Create a spell with at least two effects. Make the first effect last at least 2 rounds, and make the last effect last 1 round (instant counts as 1)
2. Cast spell
3. Wait 1 round
4. See spell being immediately removed, even though the first effect still had another round
The bug still occurs even if the first effect has 10+ rounds remaining.
I'm not sure if this is a classic issue, but even if it is, it's worth fixing in my opinion. The bug can be worked around by having the longest effect be the last in the list.
> Fixed spells with multiple effects ending too early

- Assets/Scripts/API/BiogFile.cs
- Assets/Scripts/Game/Player/CharacterDocument.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharBiography.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
- Assets/StreamingAssets/BIOGs/readme.txt
I felt like investigating the biography and History system in Daggerfall, and noticed that it wouldn't be too hard for DFU to give mods the ability to introduce alternative biographies for character.
With these changes, after choosing a class (ex: Mage aka 0), the game looks for all files that match BIOG00T([0-9]+).txt in the BIOG source folder. If multiple files are found, one is selected at random (note: could be extended later to offer a list to choose from).
In addition, an extension was added to the BIOG file format. Before the first question, if a line starts with #, the rest of the line will be interpreted as a string id, and will be used for the backstory. With a custom ITextProvider, mods can make use of unused string values to provide new backstory text.
For example, if a mod …
> Added the ability for mods to add new Biography templates

- Assets/Scripts/Game/PlayerEnterExit.cs
- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
This fixes a bug in PR #2053 where Runtime Materials only detected that it was being created for a dungeon's or castle's interior if attached to a Base Game Object and not if attached to anything else that is inside a dungeon, such as Action Doors. This meant that modded secret doors received the wrong textures. The script will now correctly detect a dungeon/castle interior creation if attached to other objects.
To test this PR, you can download my mod [Unofficial Block Location and Model fixes](https://www.nexusmods.com/daggerfallunity/mods/100?tab=files) then load the attached save game. Without this PR, the secret door in front of you will have the wrong texture. With this PR, the texture will be correct.
[Secret door test.zip](https://github.com/Interkarma/daggerfall-unity/files/620979 …
> Bugfix for PR 2053

- Assets/Scripts/Utility/BuildingNames.cs
After having reverse engineered DF classic function expanding the %ef macro, I decided to submit a patch which will change DFU behavior from classic. If this gets merged, all Hammerfell shops will use Redguard names instead of Breton ones. As an example,"Perynak's General Pawnshop" in Sentinel would become "Maevrn's General Pawnshop".
The explanation, using the comment I put in fix:
```
In classic, the function expanding the %ef macro uses a global variable containing the current
region race. However, this variable is never updated when the character travels
and remains at 0. This explains why the Breton name bank is always used for shops.
This global variable is probably a leftover from Daggerfall early development as,
with the exception of %lp, which presents a similar issue and always …
```
> Fix classic bug related to %ef macro

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Every operation in Setup had "protected" access in case a derived class felt like overriding it entirely, except for SelectActionMode and the "toggleClosedBinding" part, which require private access. Added "protected" to SelectActionMode, and exposed the toggleClosedBinding operation as a protected method
- Added a virtual to "UpdateItemInfoPanel(item)" in case a derived window wants to change how an item's info is displayed without changing all the other functions
- Added a virtual to PaperDoll_OnMouseMove since the other "OnMouseMove" functions had it (I actually need this for my mod)
> Added more "protected" and "virtual" in DaggerfallInventoryWindow

- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/RDBLayout.cs
When I moved the InjectMeshAndMaterialProperties and UpdateMaterialsOfMeshRenderer functions into a separate script, the intention was for each of these scripts to do the same thing as the previous code. However, PR #2051 has a regression in it where this script is only added to vanilla models generated from Arch3D.bsa and is not applied to mod added models. This PR fixes this so that mod added models will now also receive the script and have the Automap shader and textures applied.
At the same time, I also removed some comments I accidentally left in RDBLayout in one of my other PRs. Unfortunately, Unity does not allow manipulating a Game Object's Transform from anything except the main thread.
> Fix regression in PR 2051

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
Unfortunately System.Func doesn't allow for passing by ref so returning the array allows new loot to be added by mods.
> Allow mods to add as well as modify loot items

- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/CreateItem.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/Game/WeaponManager.cs
- don't stack conjured arrows with different TTLs;
- shoot conjured arrows first, starting with the ones with lowest TTL;
- change color of arrow counter to tell whether you're about to shoot a conjured or real arrow;
- prevent looting conjured arrows (currently they're converted to real arrows in enemies inventory).
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4629
> Fix several issues with conjured arrows

- Assets/Scripts/Internal/DaggerfallActionDoor.cs
Some doors in Castle Wayrest do not show their "warning" messages on first click because their actions are flagged MultiTrigger and only Door and Direct flags were handled in DaggerfallActionDoor.Open().
However, I noticed that some MultiTrigger doors (like the large double doors of Castle Wayrest, no need to search very far) are flagged as having some DoorText yet have no text to display, so if I just add MultiTrigger to the handled cases, those doors suddenly require 2 clicks to open.
So, I also added an action.Index > 0 check to try to make sure the DoorText flag is legit (I assume there's no text with index TYPE_11_TEXT_INDEX aka 8600?)
Fixes issue #1974
> Fix Castle Wayrest backroom door messages not showing up (issue #1974)

- Assets/Scripts/Game/FPSSpellCasting.cs
I received a [comment ](https://forums.dfworkshop.net/viewtopic.php?p=53906#p53906)on my Readied Spellcasting Hands mod to fix the offset for the Large HUD. When I went to investigate, I found out that the FPSSpellCasting class does not have the offset fix, either. While it seems unnoticeable because of how fast the animation is, it would probably be noticed if someone was using my mod with the fix but not DFU. The readied hands would be offset properly, but then the casting animation would suddenly move them downwards.
This PR resolves that issue by adding the offset logic like in FPSWeapon. It also will be affected by the "LargeHUDUndockedOffsetWeapon" option in the settings.ini, which I think is okay since hands and weapons are viewed in a similar vein.
> Add Large HUD offset logic to FPSSpellCasting like in FPSWeapon

- Assets/Scripts/Game/Entities/PlayerEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Game/Player/PersistentFactionData.cs
- Assets/Scripts/Game/TalkManager.cs
Change made after having reverse engineered classic Daggerfall function used to check if an NPC is able to answer a question or not. NPCs will now use an array of modifiers corresponding to their social class and to the kind of question they are asked in order to get the roll to beat to check if they are able to answer or not.
This change also makes NPC keep their previous knowledge after closing the chat window, as in classic.
> Change NPC knowledge in Talk Manager to match classic

- Assets/Scripts/Game/TalkManagerMCP.cs
This PR fixes this:
The %mn macro is not used in conversations but I added it for the sake of consistency. Note that the random seed for an NPC is not fixed for now so what I do in `MaleName` to differentiate the male name random seed from the female name one is uselesss until PR #2085 is merged.
> Add %mn and %fn macros support to TalkManagerMCP

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Items/LootTables.cs
There's currently many ways to modify what loot is found in enemy loot piles, and the loot piles found in dungeons and interiors.
When mods register custom items in a given category, it can replace the default loot of that category. 
Mods can replace the default loot tables found in LootTables.
Mods can use the "ModifyFoundLootItems" formula, now fixed for 0.11.3
Mods can also register to the EnemyDeath.OnEnemyDeath event handler and modify the entity's items just before it creates the loot pile.
For some situations, all these solutions have issues.
First, the loot tables in LootTables and the "ModifyFoundLootItems" formula can only be changed by one mod. If multiple mods take this approach, they will conflict.
Second, registering items in a category used by loot tables does not work if …
> Added two event handlers for loot spawning

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
- Assets/Scripts/Game/PlayerMotor.cs
Developers can now hook into and update player walk and run speed using the player speed changer. This is done by sequentially adding the change values to a dictionary and tying them to a UID out string property. The developer stores the UID out so they can remove/manipulate their speed changes at a later time in code execution.
**Currently we have these public properties:**
- Bool walkSpeedOverride: turns on and off using walk modifier list to change player movement speed. Does not clear list, merely ignores it.
- Bool runSpeedOverride: turns on and off using run modifier list to change player movement speed. Does not clear list, merely ignores it.
- Bool updateWalkSpeed: turn true to recompute the walk speed; will flip false once done on next frame.
- Bool updateRunSpeed: turn true to …
> SpeedChanger Updates

- Assets/Scripts/Game/Player/VitalsChangeDetector.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
Fix for issue #2096
Vital indicators logic is already split in two parts:
- update methods deal with the inertia/convergence usual behavior;
- events can force an immediate adjustment of indicators to current value
This PR add an event triggered right after the large HUD is toggled, and then subscribe to that event to force an immediate update of the indicators.
> Resynchronize vital indicators after toggling large HUD

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Utility/AssetInjection/Components/CustomDoor.cs
- Assets/Scripts/Utility/RMBLayout.cs
My changes here add two additional functions to the CustomDoor script:
- You can specify what DoorType the doors created by this script will be in the Editor's Inspector, giving a modder the ability to override the DoorType set by analysing the textures.
- ~~You can add multiple BoxColliders to the model and allow more than one of them to be treated as a door by this script.~~ Edit: Original code already did this.
I've marked this as a draft to get the opinions of the DFU devs and see if this is something you are willing to add to the base game. Especially @TheLacus since this was originally his work.
> Extra features for the CustomDoor script

- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
The previous fix (PR #1987) was removed in commit https://github.com/Interkarma/daggerfall-unity/commit/721522c0d032b8d23c510f38867fb6bb82694e6b from PR #2084 
@l3lessed: Unless there's a good reason not to I'd like to put my fix back so the galloping in my mod continues to work.
> Re-fix riding sprint in mods

- Assets/Scripts/Utility/MacroHelper.cs
It should have been this way when I committed it in 2017. Is now the same as pg3 since the hers plural was removed. Leaving both methods in, but added comment to make it clear they now function the same.
> Fix typo in DFU macro %pg1

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs
- Assets/Scripts/Game/WeaponManager.cs
Sometimes quest items and enchanted items deserve to not be used as standard items:
- (subreddit below) arrow quest item should not be picked as missile;
- enchanted ingredients should not be used to mix potions (regression in my refactoring of potion maker);
- I assume quest spell books could exist, and should be given a normal one as needed;
- I assume quest lanterns could exist, and should be excluded;
- I assume no quest or enchanted wagon/horse, sounds silly;
- I didn't consider quest or enchanted currency either. Currencies are hard enough (and a bit of a mess already), and also currencies are a good example of commodity so I don't think quest or enchanted money would make a great feature.
I also considered using a predicate parameter instead of flags to filter the result of …
> Quest and enchanted items exclusions

- Assets/Scripts/API/BiogFile.cs
- Assets/Scripts/API/DFCareer.cs
- Assets/Scripts/Game/Entities/DaggerfallSkills.cs
- Assets/Scripts/Game/UserInterface/SkillsRollout.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharAddBonusSkills.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharSummary.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
I noticed the original TES2 shows the Biography skill bonuses during the "Add Bonus Skills" and "Summary" phase of character creation. The bonuses themselves are bugged in TES2, but the ones you see during creation are the ones you get when you start the game.
So, I did this for consistency
> Fix: Show biography skill bonuses during character creation

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Utility/FallbackTextProvider.cs
- Assets/Scripts/Utility/FallbackTextProvider.cs.meta
- Assets/Scripts/Utility/TextProvider.cs
Mods may add new benefits to skills. For example, my [Skilled Spells](https://www.nexusmods.com/daggerfallunity/mods/186) mod bases the caster level for a magical effect on the skill associated with the effect.
This is currently hard to communicate to the player, without telling them to just enter console commands. 
I found that having a mod replacing the entire character sheet window just to change the skills dialog was too prone to conflicts, so I took another approach.
The skill summary code in DaggerfallCharacterSheetWindow.cs was simplified - without changing how it looks - and moved to TextProvider, in a new GetSkillSummary method. The text provider only has to handle the "starting position" for the tokens due to the Misc skills window's two columns. Otherwise, it can show whatever …
> Modding the character sheet's Skills dialog

- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/BuildingDirectory.cs
- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/TalkManager.cs
- Assets/Scripts/Game/Utility/CityNavigation.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLocation.cs
- Assets/Scripts/Terrain/StreamingWorld.cs
- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Utility/RMBLayout.cs
While working on new PRs, I noticed again that `RMBLayout.GetLocationBuildingData` takes a long time for big cities when a replacement mod such as _Taverns Redone_ is used (around 1.5s for Daggerfall city on my computer, using a stopwatch). Furthermore, the method is called at least three times when loading a savegame. The more problematic issue is that it is also called in several places like when opening the talking window or selecting a random place for a quest.
Some time ago, I made a first attempt at fixing this issue in PR #1541, however, it was not satisfactory and since I didn't have time to work on it anymore, I closed it.
For this new attempt, I decided to cache RMB blocks as a static field in RMBLayout itself, with a size of 12 locations at most. This works quite well, reduces …
> Cache RMB blocks

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Includes an event for when the persistent windows have been instantiated so mods can easily register to listen to the UI window event. It's possible other events for other persistent windows would be useful, and the same technique can be used for them. However I am not going to try to divine what they are.
Using this from a mod looks like this:
```
DaggerfallUI.Instance.OnInstantiatePersistentWindowInstances += OnInstantiatePersistentWindowInstances_TestItemHover;
static void OnInstantiatePersistentWindowInstances_TestItemHover()
{
DaggerfallUI.Instance.InventoryWindow.OnItemHover += TestItemHover;
}
static void TestItemHover(DaggerfallUnityItem item, DaggerfallInventoryWindow.ItemHoverLocation loc)
{
Debug.LogFormat("Hovered {0}  uid:(1)", item.ItemName, item.UID);
}
```
> Add OnItemHover to inventory window for mods

- Assets/Scripts/API/DFLocation.cs
- Assets/Scripts/Game/Questing/Actions/Climate.cs
- Assets/Scripts/Game/Questing/Actions/Climate.cs.meta
- Assets/Scripts/Game/Questing/Actions/PcAt.cs
- Assets/Scripts/Game/Questing/Actions/Season.cs
- Assets/Scripts/Game/Questing/Actions/Season.cs.meta
- Assets/Scripts/Game/Questing/Actions/TrainPc.cs
- Assets/Scripts/Game/Questing/Actions/TrainPc.cs.meta
- Assets/Scripts/Game/Questing/Actions/Weather.cs
- Assets/Scripts/Game/Questing/Actions/Weather.cs.meta
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/StreamingAssets/Tables/Quests-Places.txt
Added "weather", "season", and "climate" quest trigger conditions, and "train pc" quest action.
I was originally going to keep this as a mod since I made them for a modder, but after he shared his results, other people said they wanted those quest actions too, so might as well share it here.
The syntaxes are:
- weather sunny|cloudy|overcast|fog|rain|thunder|snow
- season fall|summer|spring|winter
- climate desert|desert2|mountain|mountainwoods|rainforest|ocean|swamp|subtropical|woodlands|hauntedwoodlands
- climate base desert|mountain|temperate|swamp
- train pc <skillName>
Note: "train pc" uses the same formula as the default training window, except it's free. It works like quest rewards, and therefore works after ending the quest (with the quest end message).
@rossipaolo Are you the one …
> Added "weather", "season", and "climate" quest trigger conditions

- Assets/Scripts/Utility/DaggerfallDateTime.cs
- Assets/Scripts/Utility/MacroHelper.cs
- %day: Current day of the month as number
- %dayn: Name of the day of the week, in TES terminology (ex: Morndas)
- %days: Current day of the month as number, with suffix (ex: 1rst, 2nd, ..., 30th)
- %mon: Month as number
- %monn: Month as name, in TES terminology (ex: Hearthfire)
- %year: Year as number (ex: 405, not 3E405)
- %min: Current minute on the clock
- %hour: Current hour on the clock (24 hour mode)
- %sign: Sign of the current month. These aren't lore in TES2, but they're a staple of the series right after that, and it was already in the code...
- %sea: Current season name
Fixed an issue which prevented sequences of characters like "%day/%mon/%year" from properly expanding as 3 separate macros.
Before fix:
After fix:
These macros were requested by a quest modder. I think they …
> Added new time-related text macros

- Assets/Scripts/Game/LevitateMotor.cs
Also fix forward taking priority over backward, and right taking priority over left when pressing both controls simultaneously
> Prevent levitating and swimming diagonally from being 40% faster

- Assets/StreamingAssets/Quests/U0C00Y00.txt
Excuse the gloom.
Fixes #2099. I couldn't figure out how to make a short and long timer, so I just set one to start after the other. Could be better but it's functional. Quest works from covens. Removes text box 1013 since it tries to reference Beothiah but that isn't possible in DF or DFU. Tidies text box 1014.
> U0C00Y00 Fix

- Assets/Scripts/Game/Automap.cs
I have noticed that if you load a save that was made inside a dungeon after installing a modified dungeon block override that adds new models, you can get an `ArgumentOutOfRangeException` if the dungeon you are in uses any of those overrides. This exception also causes other issues. The most serious I've noticed is that if you try to load the same save again after getting that exception, another exception is triggered and the game loads to a black screen.
I believe that the cause of this is that after creating the dungeon's automap models, the game iterates through each model in the block's automap and checks it's status against the save game's `AutomapData.txt`. The problem is that if the block has had new models added to it, the game will try to load an entry in the TXT file that …
> Fixed ArgumentOutOfRangeException on loading game with new dungeon models

- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Internal/PlayerGPS.cs
Fix a regression introduced in #2100 and fix a historical issue that could happen when fast travelling to a location with the same name as the current one (for example, from Ashford Manor, Anticlere to Ashford Manor, Dwynnen).
> Fix automap update not triggering on some occasions

- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/Automap.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Internal/DaggerfallDungeon.cs
Instead of discarding one block as DFU does, classic simply moves one of the block south of the other.
> Use classic hack to fix Orsinium overlapping blocks

- Assets/Scripts/API/BlocksFile.cs
This fixes the following blocks:
N0000071.RDB: connect the lower western dead-end to the rest of the block, can be checked in Ruins of Kinghouse Grange, Glenpoint
W0000009.RDB: move the exit to another corner (classic applies another but less clean trick), can be checked in The Tower of Hearthhouse, Wrothgarian Mountains
W0000018.RDB: connect the upper rooms together and fix a wrong door model, can be checked in the The Roost of Grumerus, Wayrest
W0000020.RDB: connect the lower western dead-end to the rest of the block, can also be checked in The Roost of Grumerus, Wayrest
Supersedes #2125 and #2126
> Add a runtime method to fix invalid RDB blocks

- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Terrain/TerrainTexturing.cs
This does change the interface, but almost all implementation extend from the default and will inherit the new method. I will assist any that I've missed.
> Allow water tile conversion to be handled by terrain texture mods

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/TalkManager.cs
Keep the line breaks from rumors for display on town bulletinboards; It's not guaranteed to be perfectly formatted, but is better than current concatenated text on one line. It's also most likely a step in the right direction for text adjustment to display width, since it preserves text as text tokens.
By the way I had a hard time testing to PR, I found few towns with rumors
> Preserve rumors line breaks on bulletin boards

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
Formula is redundant now there are EnemyEntity and LootTables OnLootSpawned events, and it was never really a formula anyway.
Follows up PR #2087
> Remove ModifyFoundLootItems formula

- Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
- Assets/Scripts/Utility/RMBLayout.cs
Also don't cache at all when running in unity editor in the same way the world data caching is disabled in editor. This allows mod developers to see their world data changes without needing to restart the game. The downside to this is to debug issues with the cache the directive needs to be modified.
> Clear location cache if world data variant is set

- Assets/Scripts/Game/Entities/EnemyEntity.cs
`careerIndex` is `18` for the City watch, but `MobileTypes.Knight_CityWatch` is `146`.
See https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/Entities/EnemyEntity.cs#L186
> Fixed guards accidentally not being above the player level

- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/RMBLayout.cs
This allows wold data building overrides to have exterior flats without needing to override the entire RMB. In classic data there only appears to be editor flats define, but have filtered these out as they're not used by any DFU systems.
> Layout building exterior flats

- Assets/Scripts/API/FlatsFile.cs
- Assets/Scripts/Game/StaticNPC.cs
Fix a game data related bug by using FLATS.CFG information to set exterior NPCs gender (mostly, if not only, witches). The issue was reported by @Ralzar81 [on the forum](http://forums.dfworkshop.net/viewtopic.php?f=5&t=4914&sid=d6db9aca862954531d2f267f04f01ff0).
> Use FLATS.CFG to set gender of exterior NPCs

- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Internal/MobilePersonBillboard.cs
This allows mods to use the assigned face to change the look of the mobile to match.
@rossipaolo If you want I will add backwards compatibility, but I haven't because I'm pretty sure no one has released a mod yet that uses the MobilePersonAsset override so it would feel like adding cruft for no reason. 
(BTW Kamers villager mod VIO overrides the PopulationManager as far as I can see)
> Pass face record id into mobile person asset

- Assets/Scripts/Internal/DaggerfallBillboard.cs
Mostly important for one shot animations. Is there anywhere else than may have the increment before the first frame?
As reported here: https://forums.dfworkshop.net/viewtopic.php?f=5&p=55561
> Fix billboard animation so frame 0 is rendered first

- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectBroker.cs
- Assets/Scripts/Game/MagicAndEffects/MagicAndEffectsStructs.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Summary:
- Added a TextAssetReader Merge for SPELLS.STD spell records through a "SpellRecords.json" file, similar to "ItemTemplates.json". 
- Ensured the DaggerfallSpellBookWindow uses the modded standard spells rather than reading SPELLS.STD directly.
So, as part of my magic modding, I started feeling the need to replace the "classic" (aka circinate) spells. Those spells are sold by spell vendors, and are part of potions and enchanted items. As one starts tweaking spell costs for spell effects, they suddenly find the need to tweak those spell bundles too.
I looked into the existing work, and I found only the "custom bundle" in EntityEffectBroker. However, this can only add new spells, and the work seems incomplete (ex: see TODO in CastWhenUsed.EnchantmentPayloadCallback).
I thought the …
> Added a TextAssetReader Merge for SPELLS.STD spell records

- Assets/Scripts/Game/Questing/Place.cs
Fixed an issue where locations "magery" and "fighters" are treated the same as "guildhall" in "pc at any <location>".
I forgot guild halls have a "p3" parameter.
> Fixed "pc at any <location>" guildhall issue

- Assets/Scripts/Game/EnemyMotor.cs
Fixed enemy AIs treating arrows and spell projectiles as obstacles, causing them to shortly initiate a detour every time they get shot at.
I started investigating as part of https://forums.dfworkshop.net/viewtopic.php?f=5&t=4890. As mentioned in the thread, I noticed that the CapsuleCast detects triggers, and therefore arrows were detected but not handled as "not an obstacle" in the EnemyMotor, so the AI treated them as an obstacle. Even if the CapsulaCast didn't detect triggers, spell projectiles are solid, and would be detected as an obstacle anyway.
Pango suggested I use the layer mask, as used for detecting a clear path for shooting. This worked well enough in my tests. 
Here's the save I used for testing. It's just a level 1 Archer at the start of Privateer's Hold. …
> AI pathfinding issues when getting shot at

- Assets/StreamingAssets/Quests/B0B20Y07.txt
- Assets/StreamingAssets/Quests/B0B60Y12.txt
Restore dungeon types from classic that were removed before the fallback was implemented in 2019.
I made these changes originally in 061ca3ee because the quests were failing in major regions that don't have orc strongholds (like Daggerfall) not being able to find a suitable dungeon location. I'd forgotten about this until recently. Restored to classic and tested.
There are some quest candidates for refined dungeon type use that were not like that in classic being produced which will come in a separate PR for consideration. I was only prepared to do these to restore to classic.
> Restore dungeon types from classic

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/ExteriorAutomap.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/SettingsManager.cs
- Assets/StreamingAssets/Text/GameSettings.txt
A player mentioned that they had trouble seeing taverns and shops in the exterior automap, due to red-green color blindness. Nothing else in the game seems to cause any issues.
There's many kinds of color blindness, and various degrees of it, so I thought letting each person tweak colors to their preferences is best. DFU already has a color picker UI used in the Settings.
This PR adds a new Settings tab, and 4 new color settings used by the ExteriorAutomap.
For example, changing the taverns to yellow and brightening the residences looks like this:
Note how the caption at the bottom is updated with the selected colors.
I checked with the colorblind user, and this was much better for them. I hope others will find this useful too.
Side note, but perhaps DFU could use a "restore defaults" …
> Colorblind accessibility settings

- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/UserInterface/ListBox.cs
Small change to prevent using a needless "ToArray()" method when using a non-array[] collection for the 'AddItems' methods. Parameter takes in an IEnumerable instead, which are the superclass of all collections, including regular arrays[], Lists, HashSets, etc. Checking for its length is no longer needed when using a foreach loop after confirming that the collection is not null.
> Use generic IEnumerables for 'AddItems' methods

- Assets/Scripts/Utility/RDBLayout.cs
This will enable custom models for new dungeons to automatically have colliders applied by unity via DFU RDB layout code.
> Add colliders to custom dungeon models added using "COL" in the World Data Editor I'm working on.

- Assets/Scripts/Game/EnemyAttack.cs
- Assets/Scripts/Internal/Base/MobileUnit.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Otherwise mods adding custom mobile units get log spammed with null pointer exceptions. Not sure if this is the best correction but figured I'd take a stab at it.
Was broken by the fix for slow spells commit 47e2c588
> Add frame speed divisor to abstract class

- Assets/StreamingAssets/Quests/M0B11Y18.txt
At current, there is no event more complained of than the Lord K'avar quest. This PR greatly reduces the spawn rate for Lord K'avar's soldiers.
> Greatly reduce Lord Kavar spawns

- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
This corrects an issue where a location override is also loaded and applied as a new location when in a mod package rather than loose files. Bad mistake on my part, but thankfully I found it while developing an update for my guild mod.
----
One other thing I noticed while investigating this issue is that disabling the mod didn't prevent this bug, which made me realise that the use of FindAssets is returning assets from and mod (as I expected) including mods that are disabled - which is not what I expected. I'd not noticed before now also causes my dungeon tester mod to put a location pixel dot on the travel map that has no name and you can't travel to, this is also because my World Data replacement code is finding the new location asset even though the mod is disabled.
@rossipaolo Could …
> Ensure only new locations are picked up from mods

- Assets/Scripts/Utility/ContentReader.cs
As discussed on PR #2173, the EnumerateMaps() is running before the mod settings have been confirmed and thus partially loading new locations regardless of whether a mod containing them is enabled or disabled. (since that state is undefined at that point) New locations have to be included and checked for collisions when the map dictionary is created.
This PR moves the setting up of the map dictionary to happen the first time it needed rather than on construction of the ContentReader. I felt this was less intrusive code change wise, but it could be done differently if you don't like the check method calls.
> Fix a loading issue when EnumerateMaps() is run before mods enable/disable state is set.

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
As part of a greater effort to allow mods to add new enemies to DFU, this PR allows mods to add new "mobile" textures, and use them for MobileEnemy's MaleTexture/FemaleTexture.
On its own, the only use case I see would be for mods to give Class enemies distinct textures. For example, Mage and Healer both use 486/485, and one could be changed to use a new texture id beyond the 512 original Textures. It is my hope that eventually, this will be useful to add new MobileEnemy types too.
Here's an example
I'm not familiar with all the graphics features, but I tried to keep the emission textures working at least. Tell me if I'm forgetting something that's usually supported in mobile textures.
The extent of my testing is just adding a bunch of palette swaps of TEXTURE.486 as PNGs in the Textures …
> Modding new mobile textures

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
- Assets/Localization/StringTables/Internal_Strings Shared Data.asset
- Assets/Localization/StringTables/Internal_Strings_en.asset
#2004 
Implemented starting point for a universal warning sign whenever a player changes a mod's settings while running the game, saying "Note: Some changes may not be applied until you restart the game." right above the save button.
In the future, we can add a flag to each mod setting that will instead prompt the warning when necessary.
> Display warning label for runtime mod settings

- Assets/StreamingAssets/Quests/A0C01Y01.txt
Adds a new spawn mechanism after 11 PM to guarantee that the enemies will spawn during the quest. Spawning "every 10 minutes 1 times with 25% success" still gives a tiny dangling chance that the enemy will fail to spawn for no good reason.
> Adds failsafe spawn to A0C01Y01

- Assets/Scripts/Game/ControlsConfigManager.cs
- Assets/Scripts/Game/InputManager.cs
[Fixes this forum post issue](https://forums.dfworkshop.net/viewtopic.php?f=5&t=4943)
Default bindings now only get set when the default KeyCode is no longer used in either binding page, and that it isn't used as a modifier. This fix also lead me to find another bug where not all modifiers were being found, which has also been resolved.
Also integrated idea from @KABoissonneault to have a list of primary bindings specifically removed by the player. While the primary fix should suffice, this idea will help keep the binding behavior expected.
> Fix default binding accidental overrides

- Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
First fix from [this comment](https://forums.dfworkshop.net/viewtopic.php?p=55752#p55752)
- Manually running and enabling AutoRun will now continue to let the player run
- Prevent enabling Autorun while moving backwards, which causes unexpected behavior where the player is not moving forward, but is in a running state unless if they press the 'Run' button or move backwards again.
> Autorun fixes

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
- Assets/Scripts/Game/TextManager.cs
This is the main part of my efforts to let mods add new enemies to DFU, as discussed here: https://forums.dfworkshop.net/viewtopic.php?f=23&t=4915
This is actually a draft PR, more for raising discussion to see if the solution is appropriate for this point in development.
What this PR does:
- SetupEnemyDemo now recognizes enemy IDs beyond those defined in MobileTypes. For every group of 256 IDs, the first 128 will be EnemyMonster, and the last 128 will be EnemyClass (0-127 Monster, 128-255 Class, 256-383 Monster, 384-511 Class, etc...)
- DaggerfallEntity now has "custom" DFCareer templates, created from mods. This can be used to create new or replace enemy careers for a given enemy ID 
- EnemyEntity will now use that "custom" career template if available, when a DFCareer is needed
- When …
> Modding new enemies

- Assets/Scripts/Game/PlayerActivate.cs
Sorry for breaking the 0 PR pending, but
#2087 was meant to cover all spawned loot, and Ralzar noticed that I missed containers, which are spawned from PlayerActivate.
PlayerActivate generates loot for containers, both for house/shop "private property" crates and shop shelves. Shop shelves do cover modded items in a more automatic manner, but I put the event anyway for consistency.
> Fixed missing "OnLootSpawned" event for house/shop containers

- Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
When I added the code in feb I made a small mistake. Doesn't affect most uses since lastLocationKey is usually the correct one anyway, but needs correcting for future uses.
So not essential for 0.11.5 release, but could go in.
> Fix code mistake in building variant getter

- Assets/Scripts/Game/Questing/Person.cs
Fix two issues related to the placement of quest NPCs:
- Named NPCs (i.e. Individuals and Daedras) are not supposed to be placed by default as they can be present in a quest person list only for reputation change purpose. This is the case, for example, of quest A0C0XY04, where Gortwog is not supposed to be placed anywhere. Furthermore, for quests where an indivudal NPC is supposed to be placed somewhere, this is always done by the `place _person_ at` command.
- When getting a quest from a location where there is no building at all, always choose a remote scope when selecting the place of a quest NPC who has no assigned location scope. This is the case when getting quests from Witch Covens, but it could also happen from a static NPC placed in the wilderness by a mod, for example.
> Fix the placement of quest NPCs

- Assets/Scripts/Game/TalkManager.cs
- Assets/StreamingAssets/Quests/10C00Y00.txt
- Assets/StreamingAssets/Quests/20C00Y00.txt
- Assets/StreamingAssets/Quests/30C00Y00.txt
- Assets/StreamingAssets/Quests/40C00Y00.txt
- Assets/StreamingAssets/Quests/50C00Y00.txt
- Assets/StreamingAssets/Quests/60C00Y00.txt
- Assets/StreamingAssets/Quests/70C00Y00.txt
- Assets/StreamingAssets/Quests/80C0XY00.txt
- Assets/StreamingAssets/Quests/90C00Y00.txt
- Assets/StreamingAssets/Quests/S0000001.txt
- Assets/StreamingAssets/Quests/T0C00Y00.txt
- Assets/StreamingAssets/Quests/U0C00Y00.txt
- Assets/StreamingAssets/Quests/V0C00Y00.txt
- Assets/StreamingAssets/Quests/W0C00Y00.txt
- Assets/StreamingAssets/Quests/X0C00Y00.txt
- Assets/StreamingAssets/Quests/Y0C00Y00.txt
- Assets/StreamingAssets/Quests/Z0C00Y00.txt
Fix all Daedra quests as well as Lhotun's part of the main quest to allow asking about Daedra princes and The Underking. The only exception is Namira who has no dialogue for anyInfo.
Also fixed some artifacts dialogue messages which where incorrectly associated with the `used` command instead of `anyInfo`.
> Allow to ask about individual NPCs in some quests

- Assets/Scripts/Game/Questing/Actions/AddFace.cs
Fixes issue where intended dialog was not displayed when adding an NPC face to player's HUD if player had saved and loaded their game prior to the AddFace action occurring. 
Error in RestoreSaveData method of AddFace.cs led to `sayingID` field remaining at zero value and ignoring the intended message ID.
> Fix dialog not displaying when adding a face

- Assets/Scripts/Game/Questing/Person.cs
Partial fix for #2190, specifically "NPCs who should appear in buildings where they don't."
The Tick method in Person.cs contains logic that attempts to hot-place an NPC at its home location when the player arrives there. While this behavior only occurs once, it did not contain a check to see whether the NPC had already been placed, e.g. by a PlaceNpc action. This had the effect of permitting quantum NPCs that could exist in two places at the same time: both at their placed-at location and at their home location. Once the player visits the NPC's home location, however, the NPC will no longer appear at the placed-at location. These anomalies account for the strange NPC availability noted in the issue.
Test case: Quest A0C00Y16
* _missingperson_ is placed at _hidingplace_ but still has a …
> Fix placed NPCs reverting to home location

- Assets/Scripts/Game/Questing/Place.cs
IsBuildingAssigned method was comparing site's mapId against location's ExteriorData but everywhere else site mapIds are derived from location's MapTableData instead. Change comparison to compare against proper value.
This PR represents another partial fix for #2190 that addresses errors such as:
* incorrect building names causing confusion on automap and in dialog messages
* created NPCs sometimes existing at the same location
* NPCs placed at locations sometimes reusing their home location (e.g. _missingperson_'s home and _hidingplace_ being the same physical location but having different names)
With this fix in place, all locations chosen for quest A0C00Y16 were unique (within scope of quest itself) in 10 separate tests.
> Fix assigned quest places getting re-assigned when setting up places

- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
LastClickedNPC quest resource behavior fixup only occurred when starting quest via popup window. Moving it within StartQuest method of QuestMachine ensures it will take effect for any code path that starts a quest. AssignQuestResourceBehavior method already ignores non-questor NPCs and will only create a single behavior component per NPC so this should be a safe fix globally.
Quest K0C00Y06 hides its questor NPC shortly after quest start. Prior to this fix, this would only occur if starting the quest from a dialog popup. With fix in place, questor now also hides properly when invoking quest via `startquest` console command.
> Fix questor NPC not hiding when using startquest via console

- Assets/StreamingAssets/Quests/K0C00Y06.txt
K0C00Y06 features two symbols with very similar names: _thiefhome_ and _thiefhouse_
_thiefhome_ is the location for the usual suspect _thief_ and where they can be found if not the guilty party.
_thiefhouse_ is the site where the incriminating evidence and/or guilty party can be found.
Rumors related to all other usual suspects use appropriate home symbols (e.g. _priesthome_ for _priest_) so rumors for _thief_ should use _thiefhome_.
The anonymous letter you receive when _thief_ is the culprit should similarly reference _thiefhome_  as all other anonymous letters do for their respective culprits.
This change should help reduce confusion in #2191 since now the only way to learn the location of _thiefhouse_ is through meeting the witness.
> Use _thiefhome_ symbol for rumor mill and anonymous tip

- Assets/Scripts/Game/Questing/Place.cs
In K0C00Y06, the _witness_ NPC is placed at _withouse_ immediately after calling for the guards.
The current implementation of a hot-remove in Place.cs tried to hide the NPC in such an instance but the Tick method of QuestResourceBehavior would un-hide the NPC immediately after. Destroying the NPC's gameobject instead allows for hiding the NPC in a manner that QuestResourceBehavior cannot revert. The NPC will re-instantiate when the player visits its new location.
The only instance in which I can see this causing an issue is if an NPC is placed at an alternate location via `place npc` and then placed back at its original location while the player is still there. If such an instance exists, it should be changed to use `hide npc` and `restore` instead.
> Destroy extant NPC object when placing it somewhere player is not

- Assets/Scripts/Game/Questing/Person.cs
ExpandMacro method in Person relied on GetHomePlace which only ever took into account a person's home place symbol. Switched to using new method GetDialogPlace which will use assigned place first, falling back to home place if needed.
"Where Is" calls TalkManager::GetKeySubjectPersonHint which relies on GetPersonSiteDetails to check for an assigned place symbol, falling back to the person's home place symbol if no assignment exists. With this change, "Tell Me About" now employs similar logic, which works well for queries about questor and quest-related NPCs alike.
My test case was quest K0C00Y06 from #2191 wherein mobile NPCs reported two different locations for _witness_. They now report just one location, the correct one, which updates as the witness is moved from _inn_ to _withouse_.
> Fix "Tell Me About" giving different person locations than "Where Is"

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/StreamingAssets/Text/ModSystem.txt
Minimum fix: adds a warning when a dependency of an enabled mod is not enabled
Forums: https://forums.dfworkshop.net/viewtopic.php?f=22&t=5020
> Check that dependencies of an enabled mod are enabled

- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Fixes an edge case for 2 vanilla items with 0 max condition defined (finger and dead body) - it was causing exceptions when the curse quest that gives the finger when used with a mod that repairs items as it checks all items in player inventory.
> Add divide by zero protection to ConditionPercentage property

- Assets/Scripts/Game/UserInterfaceWindows/CreateCharNameSelect.cs
The original code comment said:
>Disable random name button only for Argonians because their race id
>would give them Imperial names from namegen
but that's only true in games after Daggerfall. In both Arena and Daggerfall, Argonians get latin names, that's just how it works in those games. Imperials don't even exist. Even in Daggerfall Unity, an Argonian character will have named characters with latin names in their background History. 
There's no reason for this arbitrary exclusion in DFU. It's going to be a surprise to veterans of the series, but it's consistent with Daggerfall itself. Worst case, they can name their character Makes-Up-Names themselves.
> Allow Argonians to get random names in character creation

- Assets/Scripts/Game/Entities/PlayerEntity.cs
Corner case seen in a stream, player tried to sleep over some poisoning, but was also close to leveling up.
He died while resting, but had to level up before death scene could start.
> Don't level up if already dead

- Assets/StreamingAssets/Quests/60C00Y00.txt
- Assets/StreamingAssets/Quests/A0C0XY04.txt
- Assets/StreamingAssets/Quests/B0B00Y00.txt
- Assets/StreamingAssets/Quests/B0B10Y04.txt
- Assets/StreamingAssets/Quests/B0B40Y08.txt
- Assets/StreamingAssets/Quests/B0B40Y09.txt
- Assets/StreamingAssets/Quests/B0B60Y12.txt
- Assets/StreamingAssets/Quests/B0B70Y14.txt
- Assets/StreamingAssets/Quests/B0B80Y17.txt
- Assets/StreamingAssets/Quests/B0C00Y06.txt
- Assets/StreamingAssets/Quests/C0B00Y03.txt
- Assets/StreamingAssets/Quests/E0B00Y00.txt
- Assets/StreamingAssets/Quests/L0B10Y03.txt
- Assets/StreamingAssets/Quests/M0B1XY01.txt
- Assets/StreamingAssets/Quests/M0B20Y02.txt
Suggested dungeon type changes for 15 quests according to their context.
For some of them, a dungeon type is implied in dialogue or the quest prompt, yet they use the "_dungeon_" place, which randomly selects a dungeon from every type. This can create the scenario of having to hunt down the leader of an orc band in a crypt, which would make the target the only orc in the dungeon.
I went through every quest that used "_dungeon_" as a place and examined the dialogue to see if it could use a specific dungeon type instead of a random one. Since there's already a fallback mechanic in place, regions that do not have these dungeon types will still parse by choosing a random dungeon instead. At least, a dungeon type that offers a theme and foe spawns more in line with the quests' context could be …
> Classic Quests : Suggested dungeon types changes

- Assets/StreamingAssets/Quests/M0B00Y16.txt
Giant Killing can be a hectic quest, with multiple giants spawning when the first is injured. A player can lose track of the correct target and kill the wrong one with no notification. This commit adds a kill message.
> Adds kill msg M0B00Y16

- Assets/Scripts/Game/Questing/Actions/AddFace.cs
- Assets/StreamingAssets/Quests/A0C00Y16.txt
Matched to classic: the message popup should be displayed before the NPC is actually hidden. Quest _Missing Person Case_ is the only quest where `add _npc_ face saying` is used.
> A0C00Y16: show message popup before hiding NPC

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Lock.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Open.cs
Not really a fix, but it's small enough at least.
In my Unleveled Spells mod, I managed to remove level scaling from all the spells in the game, except for spells featuring the Open and Lock magic effects. My users would appreciate if I could fix this.
You can't replace those effects without inheriting from them and replacing `TriggerOpenEffect` / `TriggerLockEffect`, since the DFU code is hardcoded to search for them specifically, so a DFU code change was necessary.
> Expose and virtualize members in Open and Lock magic effects

- Assets/Scripts/Game/PlayerActivate.cs
UX improvement for issue #2232.
I considered disabling all interactions except doors, "action" (ex: levers), ladders, and custom. Then, I decided that for most other interactions, if you're clicking on them, you probably meant to interact, not cast a spell on them.
Maybe loot markers might be accidentally misclicked in combat, and some may prefer disabling interactions with them while casting spells.
I decided not to, since players might be readying a spell from an auto-recast mod (ex: Hotkey Bar) and deliberately clicking a loot container. 
So, in the end, I only disabled mobiles, since you're most likely intending to fight them. It was already dangerous to talk to villagers with a spell ready since it would go off even when you could successfully interact with them.
> Disable interactions during touch-range spell

- Assets/Scripts/Game/Formulas/FormulaHelper.cs
While doing #2108, I intended to cover all the formulas required to modify how spells work. Technically, I did, but I realized spells go through another `SavingThrow` overload first that just has way more information for mods to use.
Note that I gave the override a name different from the function itself, since the function is overloaded.
> Added missing formula override for FormulaHelper.SavingThrow 

- Assets/Scripts/Terrain/StreamingWorld.cs
Fix StreamingWorld.TrackLooseObject not setting "mapPixelX" and "mapPixelY" in the loose object description if specified to anything other than player position. 
All code in DFU uses `-1` for both the `mapPixelX` and `mapPixelY` arguments, so this issue is only for mods. 
My mod spawns objects on the terrain outside of the player's current map pixel, and needs the StreamingWorld to track them so they're destroyed in the right order in all cases. Without this fix, the moment the player moves from one map pixel to another, `CollectLooseObjects` is called (with `collectAll = false`), and my objects have (0, 0) as the mapPixelX and mapPixelY, so they're considered "out of range", and get destroyed. With this fix, they have the right mapPixelX and mapPixelY that I set, and only get destroyed …
> Fix StreamingWorld.TrackLooseObject "mapPixelX" and "mapPixelY"

- Assets/Scripts/MaterialReader.cs
- Assets/Scripts/Utility/TextureReader.cs
See issue #2230 
It seems lots of this code is older, back from 2019. For example, the Material code only checked loose files, not "all locations" (assets from the dfmod). 
Graphics isn't my area, and I don't know what are the users of these graphics settings. However, I tried to make my changes have no effects on people replacing texture 0 to 511 - there shouldn't be any users for textures outside of these in materials, as it didn't work before this PR.
I'm open to suggestions to make this cleaner.
Hopefully with this, Kamer can complete his mod.
EDIT: yes, this works for him :)
> Enemy corpse custom texture fix

- Assets/Scripts/Game/UserInterfaceWindows/ColorPicker.cs
Made a few changes to the color picker used for mod settings (for example by RealGrass mod):
* Improved scaling (text labels were too small).
* Color is picked (`OnColorPicked` event) only if window is closed with OK button, otherwise is discarded.
* Fixed an issue that caused a color to be selected if the mouse button is still pressed after popup window is opened by clicking a button positioned under the popup.
> Color picker tweaks and fixes

- Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenHeld.cs
This is so travel options can prevent ticking of damage when time accelerated travelling, since fast travel doesn't damage condition.
> Allow cast when held to be overridden and modified by mods.

- Assets/Scripts/Internal/DaggerfallInterior.cs
With #2242, mods can add static NPCs with new textures using world variants.
Pictured: Lady Flyte, in the Anticlere palace
However, there is an issue: they cannot be interacted with like a normal NPC.
`MaterialReader.GetFlatType` only handles textures between 0 and 511, so custom textures will not get detected as a `FlatTypes.NPC`. 
`DaggerfallBillboard.SetMaterial` uses this enum value to know whether to add a collider on it. Therefore, custom textures don't get that collider.
There were a few ways to go about fixing this, but I went, again, with something short that affects as few code as possible. Let me know if you think we could do with something cleaner.
> Fixed custom textures for NPC billboards not having a collider

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Open.cs
- Assets/Scripts/Game/PlayerActivate.cs
I received a report that my "unleveled" Open spell didn't work on exterior doors. Indeed, that check is not made through the Open effect, and cannot be overriden by mods.
I simply moved the code to a virtual function inside `Open`. 
Not a blocker this time, so merge at your own leisure.
> Virtual "Open" effect for exterior doors

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Utility/FloatingOrigin.cs
The "floating origin" system can cause large position offsets for all entities in the scene over a single frame. For this reason, each time it occurs, the player's controllers are notified so that they can offset the fall damage values. But this isn't done for enemies.
In vanilla DFU, exterior enemies don't happen often, and it's usually in situations where the floating origin doesn't cause issues. With mods, it's another story. Many of them try spawning enemies near a fast travel target or a dungeon entrance, which causes all of them to die from fall damage during the transition. You get "A bandit has died." spam, and a whole bunch of corpses instead of the planned encounter.
This change fixes this issue, at the cost of a `FindObjectsOfType` call per floating origin change (which isn't …
> Floating Origin change now also adjusts EnemyMotor's "last grounded" 

- Assets/Scripts/Game/EnemyMotor.cs
The EnemyBasics.Enemies array size is only 62, and the ids of the objects are not sequential in this array (It goes straight from Lamia id: 42 to Mage id: 128).
So just using the id as the array position would only work for enemies with an id of 42 or less. Better to check with Linq on the actual id of the object.
> Fix for switching back to original enemy Team

- Assets/Scripts/Game/Utility/PaperDollRenderer.cs
Add Support For Jewelry Type Items To Be Rendered On Paper-doll If They Have Their Equip Slot Set To The Body, Mod Support.
Forum Post About "Issue": https://forums.dfworkshop.net/viewtopic.php?t=5323
> Add Support For Jewelry Type Items To Be Rendered On Paper-doll If They Have Their Equip Slot Set To The Body, Mod Support.

- Assets/Scripts/Game/Guilds/GuildManager.cs
See https://forums.dfworkshop.net/viewtopic.php?t=5200
Alternative would be to change line 5956 to read "ggroup: -1" but that will only affect new games I think as faction data is saved.
> Prevent shops being treated like FG

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
I think a lot of players miss the presets function for mod settings and I think the button should be made clearer. Here is my proposal. I used the same background colour as the save button since I am terrible at colour selection and I think it looks fine. See picture below for comparison:
> Make preset button in mod settings more obvious

- Assets/Scripts/Game/Items/ItemCollection.cs
- Assets/Scripts/Game/Items/ItemHelper.cs
Update GetGroupIndex to simply return input for new items from mods since groupIndex == templateIndex
This fixes issue #2245 I think.
> Update GetGroupIndex to simply return input for new items from mods

- Assets/Scripts/Game/Questing/Actions/PromptMulti.cs
Don't check an int for zero when it's a valid button value. Checks task object instead.
> Fix bug with promptmulti action

- Assets/Game/Addons/WorldDataEditor/Editor/WorldDataEditor.cs
- Assets/Game/Addons/WorldDataEditor/Editor/WorldDataEditorBuildingHelper.cs
- Assets/Game/Addons/WorldDataEditor/Editor/WorldDataEditorDungeonHelper.cs
- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyBlood.cs
- Assets/Scripts/Game/Serialization/SerializableLootContainer.cs
- Assets/Scripts/Internal/Base/Billboard.cs
- Assets/Scripts/Internal/Base/Billboard.cs.meta
- Assets/Scripts/Internal/Base/MobileUnit.cs
- Assets/Scripts/Internal/DaggerfallBillboard.cs
- Assets/Scripts/Internal/DaggerfallDungeon.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallLocation.cs
- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
- Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
- Assets/Scripts/Utility/GameObjectHelper.cs
- Assets/Scripts/Utility/RDBLayout.cs
- Assets/Scripts/Utility/RMBLayout.cs
This is to allow mods contributing new MobileUnit or Billboard implementations to allow most DFU and other mod logic to continue to work. Billboard is based on the same base class structure as MobileUnit.
@Interkarma Would you like a different name for the base class, maybe AbstractBillboard or BillboardBase? I just followed the pattern already set. Apologies for the blast radius of this one. 
Pretty sure I did the refactoring correctly but could use some review in case I made a mistake somewhere. @KABoissonneault can you please review my work here?
> Extract abstract class from DaggerfallBillboard and move summary struct into MobileUnit base class

- Assets/Scripts/Internal/Base/Billboard.cs
- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
As discussed with IK, the change from `DaggerfallBillboard.BillboardSummary` to `Billboard.BillboardSummary` can cause mods relying on `BillboardSummary` to fail to compile. To mitigate this, I moved the struct to the DaggerfallWorkshop namespace instead.
> PR #2284 mod compilation issue workaround

- Assets/Scripts/API/BlocksFile.cs
This was added to allow named buildings to be altered without affecting the pool matching. Unfortunately I missed this one when I made that change.
> Don't override faction id if the replacement id is zero

- Assets/StreamingAssets/Quests/K0C00Y03.txt
"Smuggling" quest originally gave you a -100 legal repute loss during quest duration, fixed by a +100 gain at quest end. There is some practical use in allowing a person to wipe their legal rep with this, but the danger of failing the quest and keeping the legal rep loss, along with the annoyance of massive Criminal Conspiracy charges, makes for bad questing.
I personally don't agree with having a "reputation wipe" quest, but it could be easily achieved by having a -100 and then +100 swap at the very end of the quest, without burdening the player with it while quest runs. Open to feedback.
> K0C00Y03 reputation change

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsTypes.cs
This enables dynamically changing a colour setting for a mod using the recent menu option to work. The method was allowing any single element not being changed to indicate the colour as a whole had not changed.
> Fix IsValueEqual for ColorKey's

- Assets/Localization/StringTables/Internal_Strings Shared Data.asset
- Assets/Localization/StringTables/Internal_Strings_en.asset
- Assets/Scripts/Game/UserInterfaceWindows/GameEffectsConfigWindow.cs
- Menu could only be escaped by the "Esc" button which a controller is unable to do
- Added a "buttonPanel" to occupy the bottom part, so if settings pages were to scroll, other UI elements would cut off and not interfere with the button
> Add "Done" button to GameEffectsConfigWindow

- Assets/Scripts/Game/UserInterface/TextBox.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
Setting these values to null would create exceptions elsewhere in their respective classes, including in the `set` action for TextBox.Text and TextLabel.Text.
> Prevent setting null values for setting text in TextBox and TextLabel with empty string

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/PlayerMouseLook.cs
Using the Steam Deck and capping the framerate, I noticed that if I set the game to 30 fps, the cursor and controller-look moved half as fast, 15 fps a quarter speed, and 60 the desired speed.
This commit fixes the issue by adding a multiplier with an inverse relationship where if the frames go down, the speed goes up and vice versa.
You can test the different speeds by adding an Awake function and comparing:
```cs
void Awake()
{
Application.targetFrameRate = 30;
}
```
> Make controller cursor and controller-look frame-independent

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceDonation.cs
Donating to a temple while at reputation `0` causes `DivideByZeroException`
> DivideByZeroException: Attempted to divide by zero.
> DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallGuildServiceDonation.DonationMsgBox_OnGotUserInput (DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInputMessageBox sender, System.String input) (at Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServiceDonation.cs:68)
> DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInputMessageBox.ReturnPlayerInputEvent (DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInputMessageBox sender, System.String userInput) (at Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs:270)
> DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInputMessageBox.Update () (at …
> bugfix: DivideByZeroException at DaggerfallGuildServiceDonation.cs:68

- Assets/Scripts/Editor/SaveExplorerWindow.cs
Tiny bugfix. Opening up a new `Daggerfall Tools/Save Explorer` caused a minor case of:
> NullReferenceException: Object reference not set to an instance of an object
> DaggerfallWorkshop.SaveExplorerWindow.IsReady () (at Assets/Scripts/Editor/SaveExplorerWindow.cs:512)
> DaggerfallWorkshop.SaveExplorerWindow.OnGUI () (at Assets/Scripts/Editor/SaveExplorerWindow.cs:72)
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, …
> bugfix: NullReferenceException at SaveExplorerWindow.cs:512

- Assets/Shaders/DaggerfallTilemap.shader
- Assets/Shaders/DaggerfallTilemapTextureArray.shader
Attempt to fix ground seams to appear on some hardware/drivers (AMD, integrated Intel graphics), based on
https://forum.unity.com/threads/tiling-textures-within-an-atlas-by-wrapping-uvs-within-frag-shader-getting-artifacts.535793/
Again, I no longer have access to some hardware to test this issue, so I need feedback from developers with such hardware!
Forums: https://forums.dfworkshop.net/viewtopic.php?t=1464
> Fix ground seams on some hardware/drivers

- Assets/Scripts/Internal/DaggerfallBillboard.cs
I was watching a stream by Cliffworms where he was using the world data editor to place items and I thought it might be helpful to have a bounding circle displayed at the bottom of billboards to make it easier to see how big they are. 
I tried to match the existing code style as closely as possible so hopefully it's not too bad.
> QoL: Draw circle gizmo at the bottom of BillBoards

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharClassQuestions.cs
I tried playing this game on Steam Deck, but I was unable to scroll through questionnaire during character creation (it doesn't react to any input, apart from clicking first visible answer).
I have quickly hacked a solution for this - simulating mouse scroll down event when right stick is being used (though possibly actual scrolling code could have been moved to separate function [so we won't call function with misleading name when using controller input], but I decided to leave it as it is).
Also I made it react to both axes - I have tested this on controller emulator first (because I didn't have any to plug to my dev PC) and it apparently doesn't output proper vertical values. So this version works fine both on Deck and with controller emulator.
> CreateCharClassQuestion: Allow scrolling with controller right stick

- Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
When the custom class creator window appears, the difficulty dagger trail starts at the top left of the screen and fades out. This moves it to the correct position at the start.
> Start difficulty dagger trail in correct place

- Assets/Scripts/Internal/DaggerfallBillboard.cs
It was observed while using the World Data Editor that multiple calls to `SetMaterial` on NPC Billboards causes many Box Colliders to be added.
This probably doesn't occur in gameplay, but I don't think my fix hurts gameplay either, so might as well be more robust here.
> Fixed multiple calls to Billboard.SetMaterial

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
I changed the signature of `DaggerfallCharacterSheetWindow.ShowSkillsDialog()` to `protected virtual` to allow mods such as[ Viewable Skill Progress](https://www.nexusmods.com/daggerfallunity/mods/298) to override it and display a custom popup with the skills.
Right now this mod creates another set of buttons on top of the originals (primary, major, minor, misc skills) to add an extra popup showing the progress of the skills when clicked, because it does not have access to modify the behavior of the original buttons.
After applying this change, I could remove all that duplicated button and click handler code from that mod and display the skill progress together with the levels in a single popup.
Since the original behavior of this method just displays a popup and doesn't change anything …
> Made ShowSkillsDialog() protected virtual to allow overriding by mods

- Assets/Scripts/Game/Guilds/Services.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
his allows standard service handling to be replaced by mods.
Examples:
```
// Override cure service without changing label or shortcut key
Services.RegisterGuildService(GuildServices.CureDisease, CustomCureService);
// Override cure service, changing label
Services.RegisterGuildService((int)GuildServices.CureDisease, CustomCureService, "Custom Cure");
```
> Allow overriding standard guild services

- Assets/Scripts/Game/TextManager.cs
- Assets/Scripts/Utility/FallbackTextProvider.cs
- Assets/Scripts/Utility/TextProvider.cs
Added ability for mods to provider per enemy name through a new TextProvider function. Previously, custom enemies could only be named after their career name.
This removes a TODO I left last year :)
Usage example: 
https://github.com/SquidKamer/DaggerfallBestiaryProject/blob/feat/enemy-name/Scripts/BestiaryTextProvider.cs#L16
For custom enemies, it makes sense to me that mods should be able to reuse the same DFCareer for multiple enemy ids. For example, a mod might have a Goblin Soldier, a Goblin Archer, and a Goblin Skirmisher, all using the same Goblin career. Before this change, however, info-clicking the goblin would always say "You see a Goblin" - you'd need a unique career for each to get their unique name.
This change allows the career reuse.
> Per-enemy name for custom enemies

- Assets/Scripts/Game/EnemyMotor.cs
(could have sworn I'd fixed that in #2163 ...)
Previously, EnemyMotor's "hasBowAttack" check was hardcoded to be true for enemy ids above 129 and not equal to 132.
This is obviously a problem for custom enemies, which use IDs above 129 and not equal to 132. If they don't have ranged attack animations, their mobile crashes.
I changed the logic so that it stays the same for DF class enemies, while allowing the full logic to be accessible to custom enemies.
If an enemy uses neither spells nor bows:
- HasRangedAttack1 is false
If an enemy only casts spells:
- HasRangedAttack1 is true
- HasRangedAttack2 is not true
- CastsMagic is true
If an enemy only shoots bows:
- HasRangedAttack1 is true
- HasRangedAttack2 is not true
- CastsMagic is not true
If an enemy uses both spells and bows:
- …
> Fixed "has bow attack" crash for custom enemy casters

- Packages/manifest.json
- Packages/packages-lock.json
Hi,
This is a small and basic PR. It adds:
- `com.unity.mathematics`
- `com.unity.collections`
- `com.unity.jobs`
- `com.unity.burst`
Hope you approve it.
Adding these 4 packages won't change anything by virtue of just adding them but those can enable some worthwhile performance gains in few areas where the workload can be considerably high. There is probably not a lot of cases like that, but those few still impact the performance & gameplay experience and that is noticeable with older CPUs (my i3-4170 among them).
To give an example, a Burst compilation could make all existing `IJob`s about >=10x faster after adding `BurstCompile` attribute and few changes (removing managed objects and static code references). This won't make a noticeable difference in vanilla release but I saw that a …
> 4 packages to unlock some future performance gains (for either vanilla release or for modders)

- Assets/Scripts/Game/Guilds/GuildManager.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/RDBLayout.cs
- Assets/Scripts/Utility/RMBLayout.cs
For example, mods can add NPCs with unused faction IDs (ex: Lady Doryanna Flyte) to normal city Palaces. Unlike Daggerfall, Sentinel, and Wayrest Palace, the other palaces aren't dungeons, and previously no QuestResourceBehaviour would be allocated to Individual NPCs in RMBs (RDBLayout.AddFlat is what's handling that for vanilla Main Quest NPCs). This changelist adds the QuestResourceBehaviour component for Individuals NPCs in DaggerfallInteriors and RMB exteriors.
Impact:
- Classic NPCs with garbage faction ids corresponding to Individual factions (ex: Lord Kilbar) will now have an extra QuestResourceBehaviour component
Tested with:
- Famous Faces of the Iliac Bay (mod)
- Test quest here: [testface.txt](https://github.com/Interkarma/daggerfall-unity/files/8645740/testface.txt)
- Go to …
> Quest can target Individual Static NPCs outside of dungeons

- Assets/Scripts/Game/Questing/Actions/PayMoney.cs
Issue reported here:
https://old.reddit.com/r/Daggerfall/comments/vjsdkn/disappearing_gold_glitch_unity_a_cohort_of_the/
Quest in question:
https://github.com/JayH2971/dfunity-questpacks/blob/master/QP1/QuestPacks/QP1/Temples/JHTP111.txt
The custom DFU quest action "PayMoney" was missing a call to `SetComplete()`. Therefore, the task would infinitely try to pay the specified amount, rather than only once as expected.
> Fixed "PayMoney" quest action infinite money drain

- Assets/Scripts/Game/MobilePersonMotor.cs
I altered the code to only change one line as suggested in my other PR, which I closed.
Maybe using `public MobilePersonAsset MobileAsset { private get; set; }` would be an alternative without "duplictating" the member. 
Reason for the Change:
`MobilePersonMotor.FindMobilePersonAsset()` instantiates my custom MobilePersonAsset and calls `SetPerson()`. 
My implementations tries to find a 3d model prefab based on the race and gender etc. If it fails it falls back to Billboards.
I do it using this way:
```cs
//Find parent and get billboard child
Transform parent = transform.parent;
GameObject goBillboard = parent.Find("MobilePersonBillboard").gameObject;
MobilePersonBillboard billboard = goBillboard.GetComponent<MobilePersonBillboard>();
//Activate billboard, reset correct asset to the …
```
> Added public property for MobileAsset

- Packages/manifest.json
- Packages/packages-lock.json
The Jetbrains Rider Editor package that DFU currently uses is locked to v1.2.1. This package is not compatible with the current version of Rider, which causes a number of issues. Some of the ones I've noticed are:
- The External Script Editor option is labelled as "Rider.exe" rather than the program's name and version.
- Project files can't be regenerated from the Unity editor.
- Rider complains about missing Unity classes.
- Autocomplete doesn't suggest anything from the Unity API.
I haven't noticed any issues caused by telling the Editor to use the latest version of this package instead of the one recommended for this version of Unity.
> Update Jetbrains Rider Editor package to latest version.

- Assets/Scripts/API/Save/SaveGames.cs
While diagnosing an issue someone was having with my mod, I noticed that the SaveGame class' TrySave method checks for if an exception occurred while importing a Classic save, and reports that the save failed to load if this is the case. 
The problem is that this behaviour gives no indication why the exception occurred. This PR changes this behaviour so that the exception that occurred will be logged to the console and log file.
> Log exceptions that occur when importing a Classic save

- Assets/Game/Addons/WorldDataEditor/Editor/WorldDataEditor.cs
- Assets/Game/Addons/WorldDataEditor/WorldDataEditorObject.cs
- Assets/Scripts/API/DFBlock.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
- Assets/Scripts/Internal/DaggerfallBillboard.cs
- Assets/Scripts/Utility/RDBLayout.cs
It's something @ajrb and I discussed a while ago.
We have a conflicting situation when it comes to the `FactionOrMobileId` field of the `FlatResource` of a Monster marker (archive 199, record 16). 
- classic DF data needs to be masked with `& 0xFF` to get the correct mobile Id
- custom enemies need to support ids bigger than 255
My solution here is to add a bit flag to annotate a marker as "custom" (ie: not from DF data).
Flags usage is a bit hard to find in DFU code, but this is the assumptions I've relied on:
- In DF data, "Monster" marker uses Flags=0 for unspecified gender, Flags=1 for Female, Flags=2 for Male (source: `RDBLayout.AddEnemy`, with `useGenderFlag==true` only for FixedRDB Enemy)
- "Random Monster" marker uses Flags as a seed between 0 and 255 for indexing into the monster …
> Custom enemy support in RDB

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
In mods that spawn enemies with a custom flow (ex: World of Daggerfall), a custom serialization component might be used (ex: for extra, mod-specific data).
Previously, `EntityEffectManager.GetCasterLoadID` explicitly checked for the component `SerializableEnemy`, when it really only needs a component that implements the `ISerializableGameObject`, for the LoadID.
I've loosened the `GetComponent` to work with custom `ISerializableGameObject` types.
I've also added a null check, to avoid the null reference exception in the future.
> Null reference exception when mod enemies cast

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
This is so they don't interfere with text entry on pages > 1. I was trying to add "Mouse3" to a text box on page 2 and it kept switching back to page 1 every time I pressed left shift... was very confused.
happy if someone can suggest better keys.
> Change key binds for left/right page in mod settings

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/Automap.cs
- Assets/Scripts/SettingsManager.cs
Dungeon Micro-Map QoL Option, 7/1/2022.
Originally in relation to this forum thread: https://forums.dfworkshop.net/viewtopic.php?t=5242
This post is mostly related to the above forum thread that I made a good few months back, and finally decided to make a PR for it. I think the difference is fairly clear from the below attached screenshots. I set the option to be disabled by default. Also the purple background is not what occurs in practice, that is just a weird quirk when you try to take a screenshot with "F8" while in the map screen. 
Please do any edits you feel would make this better. I was considering for small possible performance reasons to put the settings check into another for-loop on it's own, but did not want to make the PR look to ugly by doing that, but up to whoever if they …
> Dungeon Micro-Map QoL Option, 7/1/2022

- Assets/Scripts/Game/DaggerfallUI.cs
- Assets/Scripts/Game/FPSCrosshair.cs
- Assets/Scripts/Game/FPSSpellCasting.cs
- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/PlayerCompass.cs
- Assets/Scripts/Game/ShowPlayerDamage.cs
- Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs
- Assets/Scripts/Game/UserInterface/Checkbox.cs
- Assets/Scripts/Game/UserInterface/DaggerfallFont.cs
- Assets/Scripts/Game/UserInterface/DaggerfallVideo.cs
- Assets/Scripts/Game/UserInterface/HUDCompass.cs
- Assets/Scripts/Game/UserInterface/HorizontalSlider.cs
- Assets/Scripts/Game/UserInterface/Panel.cs
- Assets/Scripts/Game/UserInterface/ReflexPicker.cs
- Assets/Scripts/Game/UserInterface/TextCursor.cs
- Assets/Scripts/Game/UserInterface/UserInterfaceRenderTarget.cs
- Assets/Scripts/Game/UserInterface/VerticalProgress.cs
- Assets/Scripts/Game/UserInterface/VerticalScrollBar.cs
- Assets/Scripts/Game/UserInterface/VideoPlayerDrawer.cs
- Assets/Scripts/MaterialReader.cs
- Assets/Shaders/DaggerfallPixelFont.shader
- Assets/Shaders/DaggerfallSDFFont.shader
- Assets/Shaders/DaggerfallUIBlendShader.shader
- Assets/Shaders/DaggerfallUIBlendShader.shader.meta
- Assets/Shaders/DaggerfallUIBlitShader.shader
- Assets/Shaders/DaggerfallUIBlitShader.shader.meta
- Assets/Shaders/RequiredShaderVariants.shadervariants
Implemented DaggerfallUI.DrawTexture to handle separate UI rendering pathways for Mac and PC/Linux.
The PC/Linux pathway is still using GUI.DrawTexture as before. Mac pathway uses Graphics.DrawTexture and font shader customisations to yield correct colour space output.
This should be a low impact change for mods as only internal UI DrawTexture handling involved. Any mods using GUI.DrawTexture or GUI.DrawTextureWithTexCoords should use the equivalent method in DaggerfallUI to render textures in correct colour space on Mac.
Tested with and without DREAM in editor and builds across Mac/PC and working OK, so texture mods should not be impacted by this.
Tagging @ajrb and @KABoissonneault - please quickly test your mods build with the changes in this PR and it doesn't cause any problems you can …
> Fix bright UI rendering on Mac

- Assets/Scripts/Game/PlayerActivate.cs
Simple switch for the building greetings so mods can turn them off, and optionally replace using enter exit events
> Allow building greeting message boxes to be disabled by mods

- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Utility/AssetInjection/Components/NPCModelRotator.cs
- Assets/Scripts/Utility/AssetInjection/Components/NPCModelRotator.cs.meta
Currently only acts on building interior NPC replacements, facing them toward the nearest internal door, preferring visible.
I would like to add this to 0.14.1 builds. It will get further development over time, this is just the first version. Has no effect on anything else, as it's simply a component resource for mod prefabs to use.
> Add model replacement NPC rotation component

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
When multiple calls to `UserInterfaceWindow.CloseWindow()` are made in one frame, it will pop the current window from the UIManager each time and accidentally close other windows below it.
How to reproduce:
1. Bind "Cast Spell" to "Escape"
2. Open Character Sheet Window
3. Click the "Spellbook" button within the Character Sheet Window
4. Press Escape
5. Observe that both windows closed instead of just the spellbook window
It was called twice because the Escape key to exit is already observed in the base class's `DaggerfallPopupWindow.Update()`, and the binding for `Escape` is also observed as the `toggleClosedBinding` in the Spellbook window.
This PR fixes the issue by peeking for an existing message to close the window, which should not appear if it was only called once.
While it would …
> Fix accidentally closing multiple windows at once

- Assets/StreamingAssets/Quests/K0C0XY01.txt
K0C0XY01 is a harpy-slaying quest with several dummied-out items that still appear as dialogue choices. Not only that, the text is strange, like a description rather than dialogue. It makes more sense to remove them from the game, since they contribute nothing at all. The quest is still completable by delivering the leader's harpy feather to the questgiver, like vanilla.
> K0C0XY01 fix

- ProjectSettings/ProjectSettings.asset
This tiny PR enables an incremental garbage collector via `ProjectSetting.asset` file (a single line changed), nothing else.
As we know managed allocations pile-up leading to `GC.Collect` being called sooner or later. In 2018/2019 Unity introduced an incremental GC which is no longer an experimental feature for some time now. Here is an official article announcing it's introduction: https://blog.unity.com/technology/feature-preview-incremental-garbage-collection
`gcIncremental: 0` leads to sudden, very noticeable CPU spikes, freezing the game rendering for few frames. This is how it work now:
`gcIncremental: 1`, spike is spread across few frames, framerate is maintained:
> optimization: lets enable incremental garbage collector

- Assets/Scripts/Game/EnemySenses.cs
Honestly I'm more interested in the custom enemy name support (see #2348), but I figure it's gonna help the localization efforts too.
I did a search for all calls to `.Replace` in the repo, and I think I got all enemy entities covered now.
> Fixed missing call to "TextManager.GetLocalizedEnemyName" in EnemySenses

- ProjectSettings/AudioManager.asset
The Doppler effect implementation in Unity causes odd-sounding, and at times extreme, pitch shifts to occur during play. This is most noticeable to me when I run past an enemy as it plays its bark. It's a matter of preference but I believe it may be best to simply disable it since it was not something present in classic.
> Disable doppler effect

- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Entities/DaggerfallEntity.cs
- Assets/Scripts/Game/MagicAndEffects/Effects/Thaumaturgy/CharmEffect.cs
- Assets/Scripts/Game/SetupDemoEnemy.cs
Replace "id >= 128" logic in DFU with a new helper, `DaggerfallEntity.IsClassEnemyId`, for better consistency in custom enemy support. Remember that for custom enemies, for every multiple of 256, the first 128 ids are monsters, and the last 128 ids are class enemies (this allows infinite extensibility while allowing mods to reserve an id space for themselves).
I made this change at first thinking MuteHumanSounds was an actual user-facing feature that players could turn off, and I wanted custom class enemies to properly support it. But I eventually realized only code can disable it. So that part of the change is not really necessary, I can just remove the sounds from my custom enemies. 
But the CharmEffect fix is useful, so I kept it all. It's not that big
> Fixed "MuteHumanSounds" and "CharmEffect" for custom class enemies

- Assets/Scripts/Game/SetupDemoEnemy.cs
This is caused by an invalid careerIndex to mobileType conversion. For example, custom class enemy 384 would be converted to 512 (384+128), and the save would softlock if enemy id 512 didn't exist.
Sorry for the many PRs in recent weeks, our monster expansion mod is getting close to release, and so we're playtesting it a lot more.
> Fixed saves failing to load custom class enemies

- Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs
When recalling, anchor was not consumed in all code paths
Regression since 239ad207661804c33d02a86ed9aa5e05db9a484e
Forums: https://forums.dfworkshop.net/viewtopic.php?t=5788
> Always consume teleportation anchor when recalling

- Assets/Scripts/Game/MagicAndEffects/Effects/Thaumaturgy/Levitate.cs
- Assets/Scripts/Game/PlayerMotor.cs
Levitation could stop under 2 conditions while NoClip status was still active:
- some levitation spell (on top of levitation caused by NoClip) expired;
- a game was (re)loaded; NoClip status was persistent, but not its associated flying effect.
It is still possible to disable it with "levitation off" in console, in case one absolutely wants NoClip with no levitation.
Another implementation could be to have LevitationMotor::IsLevitating() return playerLevitating || GameManager.Instance.PlayerEntity.NoClipMode if its entity is the player; It could be a little cleaner than spreading PlayerEntity.NoClipMode checks in several places, but a little more expensive at runtime.
> Keep levitating as long as NoClip is active

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/WeaponManager.cs
- Assets/Scripts/Utility/WeaponBasics.cs
Very basic mod support for making it possible through a mod with texture replacements to add unique HUD animation frames for the various different vanilla weapons.
So instead of only being able to replace the entire group of the generic "long-blade" animations that most bladed weapons use, the modder can specify through texture naming if they want to replace the animations for say the Claymore and Katana so they look different from one another on the HUD. Or even adding unique HUD animations for the vanilla weapon artifacts and enchanted magic weapons, etc, 7/19/2022.
> Weapon HUD Animations Mod Support 1, 7/19/2022

- Assets/Scripts/Game/PlayerDeath.cs
Ties classic player death sound to combats vocalization; No combats vocalization <=> classic player death sound.
Rationale:
- players bothered by "non classic" death gasp are more than likely also bothered by combats vocalization;
- on the other hand I see a possible case for players that don't want combats vocalization but like race and gender aware death sounds. Seems pretty niche case though.
> Classic player death sound option

- Assets/Scripts/Utility/RDBLayout.cs
After this change, a mod can register its custom NPC archives by calling `RDBLayout.NPCFlatArchives.Add(textureArchiveID);`. This also opens up the way for custom NPC portraits by adding new FlatData to the FlatsFileReader.FlatsDict. I have tested this already and it works but I can provide the mod for testing if necessary.
Without this change, the billboard's collider is never added since the custom archive can't be identified as an NPC archive and just gets treated as a regular billboard.
Please let me know if anything more is needed
> Using a public list instead of the hardcoded archive IDs allows mods to register custom texture archives that should be treated as NPCs

- Assets/Scripts/Terrain/DefaultTerrainSampler.cs
- Assets/Scripts/Terrain/TerrainHelper.cs
- Assets/Scripts/Terrain/TerrainTexturing.cs
Hi! This PR is part of #2416 saga.
Burst compilation enabled for all existing jobs. That's it, nothing else.
Burst is not a magical wand necessarily. It is powerful when there is a lot of math calculations but it won't fix a memory access-bound code (L2 cache misses).
It sped up these existing jobs by around a factor of 10x and nearly `*halves*` my loading time for exteriors (20-40% reduction)
- before: `5 seconds` total of work (left), after `[BurstCompile]`: `0.4 second` total of work (right)
<p float="center">
</p>
> **I mean... optimization is *never* this easy, so merge while PR is still hot :T**
> [BurstCompile] for all existing jobs

- Assets/Scripts/Game/EnemySounds.cs
- Assets/Scripts/Game/Questing/Foe.cs
Fix for [https://forums.dfworkshop.net/viewtopic.php?t=5847](https://forums.dfworkshop.net/viewtopic.php?t=5847)
I also added an extra custom enemy id fix for Foe quest resources. Once we get quests targeting custom enemies, it would be nice if custom class enemies didn't have monster names.
> Fixed regression where City watch lost its human sounds (HALT)

- Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharRaceSelect.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBaseWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPopupWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
I have rebased #2367 to fix conflicts from upstream and also applied a couple other needed fixes for the pull request.
@argonius2 I assume you want to have credit as well which is why I have kept your commits!
> Add Joystick "Back" Button

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/Game/Player/AcrobatMotor.cs
Update set_jump and set_grav commands to display correct default values in help,
accept float arguments, and accept -1 for "default value".
Note: float argument format is currently localized (eg "4,5" on my system that has french localization).
> Update set_jump and set_grav commands

- Assets/Scripts/Internal/DaggerfallBillboardBatch.cs
Hi! This PR is part of https://github.com/Interkarma/daggerfall-unity/pull/2416 saga.
I refactored #2416 changes to the `DaggerfallBillboardBatch.cs` to make them more conservative, safe and limited to a single file. It delivers less benefits than original, but will serve as a good foundation for future improvements which has been identified so far.
I know you guys have other priorities now so no worries - take your time. I am posting this now while my mind is still familiar with this code.
- `CreateMesh` takes less time from the main thread. Before: about `266 ms` (left), after: about `34 [s]` (right):
<p float="center">
</p>
- `AddItemsAsync` were added to open the door for future decrease in the overhead from the thousands of separate  `AddItem` calls (about an `100 ms`, sometimes …
> DaggerfallBillboardBatch: mesh data creation process multi-threaded

- Assets/Scripts/Internal/DaggerfallBillboardBatch.cs
#2427 re-uploaded for further consideration
> Hi! This PR is part of https://github.com/Interkarma/daggerfall-unity/pull/2416 saga.
> 
> # What
> 
> I refactored #2416 changes to the `DaggerfallBillboardBatch.cs` to make them more conservative, safe and limited to a single file. It delivers less benefits than original, but will serve as a good foundation for future improvements which has been identified so far.
> 
> I know you guys have other priorities now so no worries - take your time. I am posting this now while my mind is still familiar with this code.
> 
> # Results
> 
> - `CreateMesh` takes less time from the main thread. Before: about `266 ms` (left), after: about `34 [s]` (right):
> <p float="center">
>     <img src="https://user-images.githubusercontent.com/3066539/189755528-f406 …
> DaggerfallBillboardBatch: mesh data creation process multi-threaded (take 2)

- Assets/Game/Addons/CSharpCompiler/Compiler.cs
- Assets/Game/Addons/ModSupport/Mod.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
A change in `DaggerfallWorkshop.Game.Utility.Compiler` to help fellow mod developers fix mod compilation errors more easily.
> edit: since [1911297](https://github.com/Interkarma/daggerfall-unity/pull/2432/commits/191129724181daa3a962435e2fcdec9f9d9d265b) this includes minimal changes in `Mod.cs` and `ModManager.cs` so compilation API can pass mod title+version as an optional parameter.
I compiled a mod, ran the game, mod failed to load. Saw this error message:
<p>
</p>
Now I can see this:
<p>
</p>
> improvement: mod compilation error message

- Assets/Scripts/Game/EnemyMotor.cs
Flying enemies hitting ground (recoil, under paralysis,...) were taking fall damage relative to their spawn location, because their lastGroundedY was never updated.
This can be fixed several ways, in this patch I extend lastGroundedY to flying enemies by updating it as long as flyingFalls is false; It could be renamed say lastAltitudeControlY, the last value of Y when the enemy had control over its altitude.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=5874
> Fix flying enemies fall damage

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs
#2437
Set endOnAnyKey to false by default in DaggerfallVidPlayerWindow, but allow spacebar and Escape/back buttons.
> Prevent ending on any key by default for video playback

- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Game/Utility/PopulationManager.cs
One of our mod plans is to expand the selection of mobile NPCs generated in towns.
Currently, the PopulationManager chooses the race of the mobile using the climate settings, then passes it on to `MobilePersonNPC.RandomiseNPC` which takes care of the rest. Other NPC settings like gender, outfit, face, guard, and name are determined internally.
We've previously worked around some of these limitations with `PopulationManager.OnMobileNPCEnable`, but all we can really do is call `RandomiseNPC` a second time with another race (we've put Redguards in Swamp and Subtropical climates, for example). This approach only works for Bretons, Redguards, and Nords, since other races aren't supported.
In addition to the limitations of this approach, this also had the issue of causing two calls to …
> Added a "generator" customization point for PopulationManager

- Assets/Scripts/Game/InputManager.cs
From the discussion of #2428.
Originally I was going to go with a whitelist of keys to be accepted, but since there isn't any formalized controller default buttons yet, I decided instead to create a list of unaccepted keys.
> Exclude modifier keys from being used in AnyKey methods

- Assets/Scripts/Game/Serialization/SerializableGameObject.cs
- Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Serialize PlayerTeleportedInsideDungeon so that dungeon doors can be opened from inside, even if player has saved/reloaded the game.
Problem of doors not always opening from inside after teleport mentioned by Aina the Khajiit on Discord:
https://discord.com/channels/559842137374457876/599345625569689620/1042632093072625845
Strictly speaking she couldn't tell if it stops working for her because of save/reload cycle.
PlayerTeleportedInsideDungeon flag and discussion about this very PR: 
see commit e81b2d7283cbc1d8c9ac56d6ad3d1e06d201af80
> Serialize PlayerTeleportedInsideDungeon

- Assets/StreamingAssets/Quests/K0C00Y06.txt
Typo and reputation fix. During the quest, the player could suffer Criminal Conspiracy charges that lower legal rep even more. A full refresh at the end of the quest is better.
> Update K0C00Y06.txt (A Mix-Up quest)

- Assets/Scripts/Game/InputManager.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
From Pango's [comment](https://github.com/Interkarma/daggerfall-unity/issues/2428#issuecomment-1301489156).
My apologies for not checking this earlier! Since it does break binding things as simple as "Shift" back to sprint for example, I'm not sure if this warrants a hotfix release. I do know as a workaround, you can simply rebind in the Keybinds.txt file.
> Fix 'unaccepted keys' not being allowed for bindings in control settings

- Assets/Scripts/Internal/DaggerfallStaticDoors.cs
> This is small and unimportant PR. You can close it rn if you see it of no worth to the project.
Moves commented out "Debug trigger placement at start" code block from `Start()` and puts it into `OnDrawGizmosSelected()`
I needed to see where the door triggers were... the code was ready written already, so.
Door gizmos shows up when `DaggerfallStaticDoors` instance is selected only, so it wont pollute the screen nor slow down the editor everywhere. `#if UNITY_EDITOR` makes sure this won't ever end up in a build.
> added: `DaggerfallStaticDoors.OnDrawGizmosSelected()` to debug door trigger placements

- Assets/Scripts/Game/Serialization/SerializableStateManager.cs
More precise exception message for `SerializableStateManager.GetStatefulGameObjectType` method
Misleading `Exception: ISerializableGameObject type not implemented for DaggerfallWorkshop.Game.Serialization.SerializablePlayer` appeared while working on #2442
This PR does not resolve the underlying issue but fixes the messaging to clear out confusion first.
A new message is:
```
NotImplementedException: GetStatefulGameObjectType does not know what to do with DaggerfallWorkshop.Game.Serialization.SerializablePlayer
DaggerfallWorkshop.Game.Serialization.SerializableStateManager.GetStatefulGameObjectType (DaggerfallWorkshop.Game.Serialization.ISerializableGameObject sgObj) (at Assets/Scripts/Game/Serialization/SerializableStateManager.cs:495) …
```
> better exception message for `SerializableStateManager.GetStatefulGameObjectType`

- Assets/Scripts/Internal/DaggerfallBillboardBatch.cs
Calls `OnDestroy()` on `PlayModeStateChange.ExitingPlayMode` (editor only).
> I haven't confirmed yet, but DunnyOfPenwick on forums has raised another warning about native collection not being disposed. This one happen when game closes from inside a building directly after load, so should only be a minor problem and not impact gameplay.
> 
> https://forums.dfworkshop.net/viewtopic.php?t=5937
_Originally posted by @Interkarma in https://github.com/Interkarma/daggerfall-unity/issues/2436#issuecomment-1297843900_
Also seen as https://github.com/Interkarma/daggerfall-unity/issues/2455
Exceptions are gone. Builds unaffected.
> `DaggerfallBillboardBatch` fix for an issue #2455

- Assets/Scripts/Game/Entities/PlayerEntity.cs
Modding support.
This may be a useful event for a number of future mods - it's necessary for mine. I made a crime system overhaul the allows the player to accrue multiple counts of a single crime/multiple crimes, and they're all tracked by region.
An event wasn't necessary before, but a breaking change was added in a DFU commit since I last worked on my mods that de-spawns guards when the player's crime is set to "None" (this is probably for the best).
Unfortunately, I relied on setting the player's crime to "None" as soon as a crime was committed, as I kept track of all crimes committed via a dictionary. The reason why it was necessary to set the crime to "None" is because the counts will add up very quickly over Update() calls.
Storing the last time a crime was committed and keeping …
> Raise an event when a crime is committed

- Assets/Scripts/Game/FPSWeapon.cs
- Assets/Scripts/Game/WeaponManager.cs
Had to work through multiple issues.
1. SpecificWeapon needed to be set right before the caching routine so proper cache keys can be referenced.
2. Used a pigeon-hole cache instead of a queue for the right/left hands. The queue couldn't cache for both hands in every case.
3. Modified GetWeaponTextureAtlas to not alter the screen weapon's current custom textures. The caching routine uses this method so I opted to put the newly loaded textures in an output parameter where it can be assigned to customTextures as needed.
I went through the steps to reproduce the bug outlined in https://forums.dfworkshop.net/viewtopic.php?t=5954. I do not have DREAM installed but I have another texture replacer (Diverse Weapons). I was seeing similar issues before while using it but they are now resolved with …
> re-work caching, de-couple gfx change from caching

- Assets/Scripts/Game/DaggerfallMissile.cs
Prevents arrows spawning off-center from player perspective.
**Problem:**
When player aims the bow far enough up or down, arrows spawn noticeably off-center from the camera's perspective.
**Solution:**
Adjust the arrow origin "down" from the camera's perspective instead of moving it down the Y-axis.
> Adjust arrow position relative to camera rotation

- Assets/StreamingAssets/Quests/C0B10Y15.txt
Move the ending of the quest to the end of the quest. This should give S.03 a chance to trigger without being stopped at S.01.
Fixes https://forums.dfworkshop.net/viewtopic.php?t=5679
> [C0B10Y15] The Relic does not give extra reputation

- Assets/StreamingAssets/Quests/S0000008.txt
Removes the requirement to be outside the castle (S.07) before Gothryd will "thank" and reward you for giving him the Totem.
Fix for https://forums.dfworkshop.net/viewtopic.php?t=4845
> Bug when giving the totem to Gothryd

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
`UseItem()` overrides on custom items would only trigger on `LocalItemListScroller_OnItemClick` and `RemoteItemListScroller_OnItemClick`. 
Moving the "own usage handling" to the `UseItem()` method allows overrides to trigger from `AccessoryItemsButton_OnMouseClick` and `PaperDoll_OnMouseClick` as well.
Fix for https://forums.dfworkshop.net/viewtopic.php?t=5936
> Always allow custom items to handle UseItem themselves.

- Assets/Scripts/Game/Questing/QuestMCP.cs
This is a fix for using a %god macro in a quest when inside a Fighters Guild hall in a region where this is considered a temple.
It will pick a random deity name, rather than crashing the quest.
I also fixed the existing random deity name selection, which could pick non-existing factionIds 23, 30, 31, 32 and 34.
> 2430 fix %god macro for fighters guild

- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
Matters for case-sensitive operating systems, like Linux or OS X
Fix for #2491 
I wonder if there could be other similar bugs hiding, because that one was almost silent (unless you keep an eye on the logs)
> Use uppercase ?PAINT.CIF filenames

- Assets/Scripts/Game/Entities/EnemyEntity.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
Added FormulaHelpers for EnemyEntity:
- GetEnemyGroup
- GetLanguageSkill
- GetWeightInClassicUnits
The first is necessary for the functioning of Pacify and Dispel spells effects to work on custom enemies. The second is for the language pacification feature.
The third one, I don't plan on using just yet, but I felt I might as well add it for completion.
> Moved EnemyEntity methods to FormulaHelper for mod override

- Assets/Scripts/Game/StringTableCSVParser.cs
- Assets/Scripts/Game/StringTablePatcher.cs
Problem was discovered after DFU froze (busy-looping) while parsing a CSV with a faulty
1554,"%it, Le Protecteur
(missing closing quotes) line in Text/Internal_MagicItems.csv
Nested star operators - like here, `(a*b*)*` - can take exponential time under the right conditions.
Minimal fix is to replace this pattern with `(a+|b+)*`, assuming a and b share no common prefix.
I did not stop there and removed the intermediate `matches` array by directly parsing key and value columns together in the regex.
Another potential bug fix, `.Trim("\"")` may remove more than the quotes surrounding quoted strings, ex.
"""Approach"" said the King" -> Approach" said the King
so I replaced it with a more explicit removal of surrounding quotes.
> Rewrite of CSV regex parsing to avoid exponential behavior

- Assets/StreamingAssets/Quests/S0000002.txt
- Assets/StreamingAssets/Quests/S0000006.txt
- Assets/StreamingAssets/Quests/S0000007.txt
- Assets/StreamingAssets/Quests/S0000008.txt
- Assets/StreamingAssets/Quests/S0000010.txt
- Assets/StreamingAssets/Quests/S0000015.txt
- Assets/StreamingAssets/Quests/S0000018.txt
- Assets/StreamingAssets/Quests/S0000021.txt
closes #2503
I hope this isn't stepping on anyone's toes, but I was trying to figure out the quest strings system and was looking at these files anyway. This PR simply extracts the corrected Quests.zip file from @Sappho20 to the correct location making the files a PR.
All changes authored by @Sappho20 
(I was trying to fix a duplicated word I noticed where Queen Aubk-i said something about 'king King Gothryd', but I can't find the string in Quests/ and didn't exactly record the text... so I'll have to go back and try to reproduce.)
> Commit spelling errors fixes from #2503

- Assets/Scripts/API/BiogFile.cs
Only happens when:
- not using SDF
- character has been refreshly created (not saved/reloaded)
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6298
> Fix biography spurious questionmarks on empty lines

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Translate the location written on maps used from the inventory (usually maps found in loot).
Tested to translate correctly the dialog box, the notes, and the regional map.
Screenshot before PR:
> Localize "USE"d maps

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
Tested that it works on Linux too, so lift the restriction for Windows and OSX only
> Allow clicking on save thumbnail to open save directory on Linux

- Assets/Resources/defaults.ini.txt
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/Scripts/SettingsManager.cs
Some streamers would prefer not to show PersistentDataPath in the launcher because it reveals their login name.
This PR adds a (not published) setting to hide that path. I called the setting "HideLoginName" to match its true intent, it case it becomes necessary in other places.
(I kept this PR minimal given feature freeze).
> Add an option to hide PersistentDataPath in launcher

- Assets/Scripts/Game/UserInterface/HUDActiveSpells.cs
I've recently learned that spell bundle names are user-facing
There's an existing practice in DF data that spells that shouldn't be sold at the Mages Guild start with ! (ex: `!Lycanthropy`). Having one of these as an active effect is not really possible in classic. With mods, it's desirable to give enemies custom spell bundles without filling up the vendor.
So, this change just removes the ! prefix of spells in the active spells HUD, making the name look less like a debug placeholder
> Remove ! prefix from spell bundles in Active Spells HUD tooltips

- Assets/Scripts/API/BsaFile.cs
- Assets/Scripts/SoundReader.cs
This can be used for custom enemies to pass new sounds in EnemySounds (ex: by providing `1000.mp3` and using `1000` as the attack sound in its Mobile structure). The value is forwarded to `SoundReplacement`, which handles non-standard values just fine.
I added some extra sanitization for negative numbers in BsaFile, because `SoundClips.None` is `-1`, which is often used as a default.
> Allow custom sound indices in SoundReader.GetAudioClip. 

- Assets/Scripts/Utility/GameObjectHelper.cs
Unlike other static NPCs, quest NPCs didn't take custom flat gameobjects into account. So, no custom animation for Vanilla Enhanced, no 3d model.
With the fix:
> Use custom billboard gameobject for quest NPCs

- Assets/StreamingAssets/Quests/S0000502.txt
Players would suffer enemy spawns in Direnni Tower after completing Former Student 2, this will prevent that.
> Spawn fix for Former Student part 2

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
DaggerfallGuildServicePopupWindow.cs line 231 (in the GetMerchantMagicItems function) sets a consistent seed when opening the magic items window. This means there is no randomization when you go to steal an item from the magic shop. This change re-randomizes the seed when you're about to steal so that quickload-stealing is possible from the magic shop as I have to assume it was in vanilla.
> Reset seed to ensure magic item shop theft randomization

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
GetMerchantMagicItems() sets the random seed based on the current day. Any activity reliant on random sequence which occurs after opening the mages item seller will always have the same set of outcomes. Preserve the seed to avoid this.
This is an alternative fix to the one contributed in PR #2529 to limit the effect the change may have on the rest of the codebase. I am pretty sure there would be no ill effects from the other approach, but it's possible and given how close to release of v1.0 I am very cautious.
All credit to @chloelcdev for finding the issue, and contributing a perfectly fine fix.
> Ensure GetMerchantMagicItems preserves seed (alternative to #2529)

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallEffectSettingsEditorWindow.cs
The background panel of the DaggerfallEffectSettingsEditorWindow should be dimmed like in the original DF.
> Dim backgound for DaggerfallEffectSettingsEditorWindow

- Assets/Scripts/Game/DaggerfallMissile.cs
- Assets/Scripts/Game/EnemyMotor.cs
PR #1861 was added to prevent caster enemies from nuking themselves with spells at range in the presence of low obstacles.
A side effect of this PR however, is that daedra lords in the "crossbow room" near the end of Mantellan Crux stopped shooting at the player altogether, making this room much less threatening.
This new PR checks for obstacles a bit in front of the enemies, so they can still cast from behind thin obstacles (rationale: spells start from arm's reach). It's a bit crude, for example it doesn't change from where the spells will be really cast. While some spells get thru, daedra lords sometimes nuke themselves.
> Fix regression caused by #1861

- Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs
PAINT.DAT's #70 paintingRecord alternatives list for %pp2 is empty, raising an exception.
Runtime patch a list for this macro, compatible with painting gfx. In case this paintingRecord is hardcoded to be used for Wayrest Painting, it will also be compatible with the "fog over Cryngaine Fields" event.
It is also possible that classic does not generate text (%pp2 expands to the empty string) instead.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6336
> Fix painting description for paintingRecord #70

- Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
Required for new settings for Travel Options mod in DFU release 1.0
> Allow extension to travel calculator for mods

- Assets/Scripts/Game/Guilds/DarkBrotherhood.cs
- Assets/Scripts/Game/Guilds/ThievesGuild.cs
When revealing a dungeon in DB or TG rank up, the dungeon name is not translated
> Localize %dng macro

- Assets/Scripts/Game/EnemyMotor.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/Entities/EntityConcealmentBehaviour.cs
- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Replaces some method calls in enemy components with delegates so mods can inject additional logic.
Also includes a change to prevent player allies from attacking pacified creatures. (EnemySenses)
Also changes ApplyGravity in EnemyMotor to allow enemies to slowfall.
Also adds option to base enemy spell cost on enemy skills rather than player skills. (EntityEffectManager)
> Enemy component access

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
It's not a secret that text in different languages have different lengths. Hence, we need the ability to move labels. At least through mods. But currently we cannot do that easily, because these fields are private. And instead of quick extension of the dialog class we must re-implement the whole window logic. 
To be able to do something simple like 
```cs
protected override void Setup()
{
base.Setup();
// Setup labels
nameLabel.Position = new Vector2(34, 4);
raceLabel.Position = new Vector2(40, 14);
classLabel.Position = new Vector2(47, 24);
levelLabel.Position = new Vector2(54, 34);
goldLabel.Position = new Vector2(53, 44);
fatigueLabel.Position = new Vector2(42, 54);
healthLabel.Position = new Vector2(48, 64);
encumbranceLabel.Position = new Vector2(68, 74);
}
```
or 
```cs
protected …
```
> Added ability to move text labels.

- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/Scripts/Utility/MacroHelper.cs
Fix for `%cn` macro not expanded in all cases 
Before:
<hr/>
After:
> Fix for buildings names macro expand

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
A user on Discord sent me this error during gameplay.
This error is easy to reproduce.
1. Load any save
2. Use console command `diseaseplayer werewolf` to get Lycanthropy Infection
3. Wait 1 day (ex: travel anywhere), get the dream sequence
4. Wait 2 another day (ex: travel anywhere 2+ days away)
5. See error in logs / console
So, during `EntityEffectManager.DoMagicRound()`, we have this loop
```
foreach (LiveEffectBundle bundle in instancedBundles)
{
// Run effects for this bundle 
bool hasRemainingEffectRounds = false;
foreach (IEntityEffect effect in bundle.liveEffects)
{
// Update effects with remaining rounds, item effects are always ticked
// All other effects with a duration will be ended at zero rounds remaining
hasRemainingEffectRounds = hasRemainingEffectRounds || …
```
> Fix exception thrown during Lycanthropy transition

- Assets/Scripts/Game/Player/ClimbingMotor.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs
Issue at #2560 
Fixed "overrideSkillCheck" not being turned off after being done Climbing. 
overrideSkillCheck is used in the transition from wall to the floor above it, and should only be true during that automatic movement.
Moved "ClearStateOnRestore" to always run on restore, not just when climbing with Advanced.
The second fix is not strictly required, but seems cleaner. No risk of regression, since non-advanced climbing should have no expectation of state if saving/reloading during climbing (it's supposed to drop the moment you let the key go).
> Fix for Advanced Climbing bug #2560

- Assets/Scripts/Utility/RMBLayout.cs
Modders working with RMBs have known for a long time that rescaling 3d objects will break them. Either the scale will be wrong or objects will disappear entirely when scaled. The screenshot below demonstrates this bug with a modded RMB but otherwise unmodded game:
This bug turns out to be caused by a typo in the GetModelScaleVector method, in which obj.ZScale is incorrectly set to obj.YScale on line 76. Correcting this typo fixes the scaling bug:
> Fix typo that breaks 3d object scaling in RMBLayout.cs

- Assets/Scripts/Game/LocalizedBook.cs
- Assets/Scripts/Game/Questing/QuestMachine.cs
Seek localized book files and quest files from mods
Loose files can be packed, and it will make installing new books mods and quest localizations easier and more straightforward.
> Seek localized book files and quest files from mods

- Assets/Scripts/Game/Questing/Place.cs
The `____place_ ` macro was not fully localized.
Before:
After:
The text of the letter that is on screenshot:
```txt
Message:  1011
%pcf,
<ce>
Картографы поручили мне сопровождать вас
в поисках пути в ____place_.
Давайте встретимся в ___place_, чтобы мы могли пойти
вместе. Пунктом назначения будет __home_,
и упражнение должно быть выполнено не позже,
чем через =timer_ дней, чтобы поддержать
вашу репутацию в ассоциации.
<ce>
_qg_
Исследователь, полевой офицер
Ассоциация Картографов
___place_, ____place_
```
> Fix for region macro localization

- Assets/Scripts/Game/StaticNPC.cs
Allows modders to edit static NPC data.
> Add setter for StaticNPC.Data

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Scripts/Internal/PlayerGPS.cs
Fixes #2573 . Most of the details should be on the issue, but in summary:
1. PlayerGPS updates the world info
2. This causes the ContentReader to fill its "MapDict" cache with all the regions
3. Loading a region also loads the WorldDataReplacement location data from mods
Before the fix, this could happen before disabled mods were removed (this occurs in ModManager.Init). Now, PlayerGPS waits for the ModManager to be Initialized before running.
As an aside, for performance reasons, I'd like if ContentReader did not read _all_ the regions on boot, since it slows down when mods try adding thousands of new locations (carademono has a vision, okay). But I'm not ready to change that yet - maybe I'll send cara a custom build to see if simply having independent caches per region works.
But this …
> Fixed PlayerGPS loading ContentReader maps before mods ready

- Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Fixes for #2569. 
I found an issue where archive 288 has 4 frames for record 0, 1, 2, and 4, but 8 frames for record 3. Record 3 is the "back diagonal" sprites (both left and right). Normally, all mobile archives have the same number of frames on each orientation, but the Ancient Lich is an exception. When changing orientation, the `currentFrame` is preserved so that the animation keeps playing from where it was. However, for the Ancient Lich, if you change orientation from the back diagonal while on frame 4, 5, 6, or 7 is playing, the `currentFrame` will now be past the allowed frames for the new orientation (back or side). On unmodded DFU, this reaches into a "Casting spell" frame in `summary.AtlasRect` (because `rectIndex` has enough room to overflow into the next records, rather than …
> Fixed frame overflow in DaggerfallMobileUnit. 

- Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
When using mods that provide lots of texture replacements and new textures, logs are filled with the message "Texture {name} is not readable."
The root of this is a change I made in 2021 in this PR: https://github.com/Interkarma/daggerfall-unity/pull/2160/files#diff-19063ddd0d72895174af2f1e16dd67e9c31329b6c2b66995d076184724e2991dR550
Crucially, for `TextureReplacement.GetMobileBillboardMaterial`, we read textures in three points:
- `LoadFromCacheOrImport`, called when the billboard material is in cache, where `readOnly` was true
- `textureFile.Load`, called when the archive is a DF classic, where `readOnly` was true
- the `TryImportTexture` fallback, added by my above PR, called when the archive is outside DF classic, where `readOnly` was implicitly false
This issue therefore mostly hits …
> Fixed "readOnly" issue with GetMobileBillboardMaterial

- Assets/Scripts/Internal/DaggerfallLocation.cs
Billboards always float in the air, so the bottom touches the ground. In `DaggerfallLocation.ApplyClimateSettings`, we have a procedure to apply climate swap on child billboards, but it fails to account for the change in billboard height.
This issue only affects nature used in RMB "misc block flats". In normal Daggerfall data, nature is in the ground scenery, which applies the climate swap directly in `RMBLayout.AddNatureFlats`, before the billboard's been aligned to base. However, ground scenery is bound to a 16x16 grid and has fixed elevation, so mods prefer to use "misc flats" for better control (like putting a tree on a hill).
This issue was reported by carademono here: https://github.com/Interkarma/daggerfall-unity/pull/2545#issuecomment-1820286381
Without climate swap:
With climate …
> Fixed climate-swap changes in DaggerfallLocation not respecting the billboard's "AlignToBase"

- Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs
A user was having a mismatch in RuntimeMaterials when replacing ground textures according to climate/season/weather.
In this example:
The bright green of the hill clashes with the dark green of the rest of the area. This is because the hill has been made to use archive 302-304, and Woodland Hills uses archive 102-104 for ground.
A concrete climate's ground archive is defined in `MapsFile.GetWorldClimateSettings`, along with its base climate setting. Without the concrete climate, we can get a default ground archive matching the base climate as defined in `ClimateSwaps` logic (either in `ApplyClimate` or `GetGroundArchive`).
In the latter case, we have for the ground:
- Desert = archive 2
- Mountain = archive 102
- Temperate = archive 302
- Swamp = archive 402
With winter variants at x03 …
> Fix for RuntimeMaterials to pick the right ground texture in Woodland Hills

- Assets/Localization/StringTables/Internal_Strings Shared Data.asset
- Assets/Localization/StringTables/Internal_Strings_en.asset
- Assets/Scripts/Game/Items/ItemHelper.cs
- Assets/StreamingAssets/Text/Master Localization CSV Files/Internal_Strings.csv
Potion recipe weight localized
> Potion recipe weight localized

- Assets/Scripts/Game/Questing/Foe.cs
After looking into this issue: https://forums.dfworkshop.net/viewtopic.php?t=6357
Normally, we can store any `int` value in a `MobileTypes` enum, which occurs when using custom enemies with ids not defined in the `enum`. This works as long as we don't rely on features that require a field to be defined, such as serialization to and from string.
I found that in fsSerializer, enum values are serialized as strings, based on the matching enum field name.
In the `Foe.SaveData_v1` struct, we have `foeType` as a `MobileTypes` enum. This shows in the save like this
```
"resourceSpecific": {
"spawnCount": 3,
"foeType": "Knight",
...
},
```
If a field is not defined for this value (ex: custom enemy ids), this gets saved as `"foeType": null`, which will default to 0 when loaded back in (hence the …
> Changed save data in Questing Foe to allow for custom foe ids

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
Original problem: If a game is loaded immediately after casting spell, spellcasting will be locked up.
Setting castInProgress to false when EntityEffectManager.ClearReadySpellHistory() is called.
> Set castInProgress to false when loading game (EntityEffectManager.cs)

- Assets/Editor/.Schemas/ModInfo.schema.json
- Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
Currently you can activate new Quest Pack (quest list) by adding the file to StreamingAssets\QuestPacks\ folder.
In case of packing quests in .dfmod file, you must call `QuestListsManager.RegisterQuestList("MyQuests")`.
It is not possible to ship quests in .dfmod without C# script.
I propose to register them in "Contributes" ModInfo section, the same way as BooksMappings 
Example:
```json
{
"ModTitle": "QuestPack",
"ModVersion": "1.0.0",
"Files": [
"QUEST1.txt",
"QUEST2.txt",
"QUEST3.txt",
"QuestList-MyQuests.txt"
],
"Contributes": {
"QuestLists": [
"MyQuests"
]
}
}
```
> Add ability to declare QuestLists in .dfmod file.

- Assets/Scripts/Game/EnemySenses.cs
In a previous PR I had added code to prevent allies from attacking pacified enemies but forgot to prevent pacified enemies from attacking player allies.
Added check to prevent pacified enemies from attacking player allies.
> Pacified-Enemy-Not-Attack-Allies

- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
Before the change, the logic for whether to cache the result of `WorldDataReplacement.GetDFRegionAdditionalLocationData` was as follows:
```
bool success = false
foreach(asset in loose files)
success = AddLocationToRegion(asset)
foreach(asset in packed mods)
success &= AddLocationToRegion(asset)
...
if(success)
cache result
```
`AddLocationToRegion` pretty much always returns true. Therefore, if we have any loose files, `success` is assigned true in the first loop, and the second loop will do `success = true & true`, and `success` will stay true.
If we do not have any loose files, `success` stays false, and the second loop will do `success = false & true`, making `success` false.
This means setups where a region has new locations in packed mods but not locations in loose files always fail …
> Fixed caching of new WorldData locations

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
This PR fixes the following issue: #2591 (Fast Travel deducts gold even if travel is canceled)
Pretty straight forward. Moved the code to deduct the gold into a separate method, `DaggerfallTravelPopUp.DeductFastTravelGold`. Rather than invoking directly from update, I opted to do so in `DaggerfallTravelPopUp.performFastTravel`, as that method seemed to be where most of the other related changes to `GameManager.Instance.PlayerEntity` state occur. The only concern I have is related to the `DaggerfallTravelPopUp.OnPreFastTravel` and `DaggerfallTravelPopUp.OnPostFastTravel` events. Previously, the gold was deducted prior to either event being fired. In `performFastTravel`, I put it after `OnPreFastTravel`, as that seemed to make the most sense. Looking at the codebase, I did not see any …
> Fast travel gold fix

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
When transitioning from asking about "Where Is? Work" to "Tell Me About", the question at the top of the screen remains about work.
https://github.com/Interkarma/daggerfall-unity/assets/5789925/c38badb1-79e7-4b77-9f92-40d35bdebb7d
The "Where Is?" talk category is preserved when moving to "Tell Me About" so it can be restored when going back to "Where Is?". 
The problem is that `UpdateQuestion` only checks the talk category "Work", not if we're actually in the "Where Is?" talk option.
I fixed this to also check the talk option
> Fixed "work question" sticking while moving from "Where Is?"

- Assets/Game/Addons/RmbBlockEditor/Editor/RmbBlockEditorWindow.cs
- Assets/Game/Addons/RmbBlockEditor/Editor/Utils/PositionUpdater.cs
- Assets/Game/Addons/RmbBlockEditor/Editor/Utils/PositionUpdater.cs.meta
- Assets/Game/Addons/RmbBlockEditor/MiscFlat.cs
Fixed a couple of bugs.
1. Fixed a problem where the position of MiscFlatObjectRecords billboards would be calculated incorrectly, when the billboard is duplicated through the editor.
2. MiscFlatObjectRecords and BlockFlatObjectRecords, BlockPeopleRecords and BlockDoorRecords in Interior and Exterior subrecords need to have unique "position" values. This "position" property is used to identify the objects.
> RMB Block Editor bugfixing

- Assets/Scripts/Game/Player/PersistentFactionData.cs
Missed this back in 2018. If new custom factions are added by mods and they specify parent factions, this needs to be processed by the child linking code FactionFile.RelinkChildren() otherwise it does nothing.
Found this when Cliffworms added a named NPC to Betony - this should be used at the provinces ruler but it wasn't. Will confirm once this has been completely tested. 
Still doesn't help being able to modify existing faction data to, for example, set the ruler value for Betony. Tried some things for that but breakpoints stopped working and I just can't continue today.
> Relink children if any new custom factions with parents were added

- Assets/Scripts/Game/Player/PersistentFactionData.cs
This allows changes of rulers to have appropriate title when %rt macro is used. Without this new rulers must be a Lord which is the default. No one is clamouring for this, but I realised that Cliff's change to add a ruler luckily is okay because it's a Lord but in future this could be useful.
Tested this with a bare bones quest script that prints the %rt macro. Happy to supply this if any reviewers want it.
> Allow faction ruler type to be set by mods

- Assets/Scripts/DaggerfallUnityApplication.cs
Fixed issue caused by #2607.
Before #2607, PersistentDataPath was lazily initialized whenever it was requested. In #2607, I made it get defined on application start. I failed to consider that PersistentDataPath was used in Editor code. Currently, if you open the editor on the latest code, it should throw a null reference exception.
This change turns it back into lazy initialization, so editor code still initializes it.
> Fixed "PersistentDataPath" usage in Editor context

- Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
The warning for changing live settings being inside the panel messes up the careful formatting of the mod settings. I know that for my mods I spend a lot of time getting them looking good.
I also think the message is more obvious not being lost in all of the settings text.
> Move the live change warning outside of the settings panel

- Assets/Scripts/Game/UserInterface/FolderBrowser.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
- Assets/StreamingAssets/Text/MainMenu.txt
Fixes #2487. Steam installs DF in a hidden folder by default on Linux, so it's pretty essential for these users.
I can find a DF installation in AppData just fine :)
> Added checkbox to show hidden folders during Daggerfall setup

- Assets/Scripts/Game/SongManager.cs
Temple music is handled differently from other playlists in SongManager. The selected song is based on the faction of the building (the manager checks for both the "Temple" faction id and the "God" faction id). The songs are as follows:
| God       | Song    |
|-----------|---------|
| Arkay     | Good    |
| Z'en      | Bad     |
| Mara      | Good    |
| Akatosh   | Neutral |
| Julianos  | Bad     |
| Dibella   | Good    |
| Stendarr  | Bad     |
| Kynareth  | Neutral |
I found two errors in how we handle this.
First, we use separate SongPlayer objects for Exterior and Interior. This means that when moving from an Interior to outside, the Interior SongPlayer is not updated until we enter a new interior. Therefore, if we move from one temple to outside to another temple, from the …
> Fixed Temple music errors

- Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
- Assets/Scripts/ActiveGameObjectDatabase.cs
- Assets/Scripts/ActiveGameObjectDatabase.cs.meta
- Assets/Scripts/External/FPSDisplay.cs
- Assets/Scripts/Game/EnemySenses.cs
- Assets/Scripts/Game/GameManager.cs
- Assets/Scripts/Game/MobilePersonNPC.cs
- Assets/Scripts/Game/Questing/Actions/ChangeFoeInfighting.cs
- Assets/Scripts/Game/Questing/Actions/ChangeFoeTeam.cs
- Assets/Scripts/Game/Questing/Quest.cs
- Assets/Scripts/Game/StaticNPC.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Assets/Scripts/Game/Utility/FoeSpawner.cs
- Assets/Scripts/Internal/DaggerfallActionDoor.cs
- Assets/Scripts/Internal/DaggerfallDungeon.cs
- Assets/Scripts/Internal/DaggerfallEnemy.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Internal/DaggerfallRDBBlock.cs
- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/Scripts/Utility/FloatingOrigin.cs
My solution for https://github.com/Interkarma/daggerfall-unity/issues/2355 crashes.
I have personally observed some users struggling with DFU crashes multiple times a day. The callstacks are almost always somewhere in the middle of a specific Unity function: FindObjectsOfType. DFU uses these in many places, often on every frame, for each object in the scene (see EnemySenses).
From the Unity docs: https://docs.unity3d.com/ScriptReference/Object.FindObjectsOfType.html
> Note: This function is very slow. It is not recommended to use this function every frame. In most cases you can use the singleton pattern instead.
And this is precisely what this changelist does.
I have personally never reproduced these crashes. They seem to require extensive gameplay sessions on a very specific mod setup. …
> Added "ActiveGameObjectDatabase" to replace FindObjectsOfType

- Assets/Scripts/Game/PlayerActivate.cs
- Assets/Scripts/Game/WeaponManager.cs
Leverages ActivateStaticDoor when bashing static doors so all door types are handled. Currently, only exterior doors in settlements are handled. This mimics classic behavior with the exception that dungeon exterior doors can be bashed too.
> Fix exceptions when bashing certain doors

- Assets/Resources/ItemTemplates.txt
- Assets/Scripts/API/ItemsFile.cs
- Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
This allows mods to change arrows so that their weight counts towards encumbrance. A mod to do this would consist of a single file ItemTemplates.json with the following entry:
```
{
{
"index": 131,
"hasNoEncumbrance": false
}
}
```
> Move the hardcoding of items that don't encumber into templates

- Assets/Scripts/Game/Items/ItemCollection.cs
Fixes issue #2640.
I think this should go into 1.1 since it's a clear fix of broken functionality and the blast radius is miniscule.
> Fix expiring equipped items not adjusting armorvalues

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModTypes.cs
- Assets/Scripts/Game/Questing/QuestListsManager.cs
QuestListsManager.GetQuest() will check mods for quests as well.
I removed `if (File.Exists(questFile))` check, because `LoadQuest()` function also checks for that, and more importantly, checking mods for quest files included.
Then, if we didn't find any, we proceed as usual.
> Fix for QuestListsManager.GetQuest

- Assets/Game/Addons/ModSupport/ModManager.cs
- Assets/Game/Addons/ModSupport/ModManager.cs.meta
- Assets/Scripts/Game/UserInterface/DaggerfallFont.cs
- I changed `ModManager` load priority, so now it initialized before `DaggerfallUI`.
- Init logic of the `ModManager` was moved from `Start()` to `Awake()`
> Support loading font file from .dfmod

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
This PR fixes the following bug: #2511 (Painting info window scales improperly with higher resolution images). The issue appears to be caused because the messagebox size is being calculated using the texture height, rather than the actual image panel height. 
Before:
After:
> Fixed messagebox painting scaling issue.

- Assets/Scripts/Game/Questing/Person.cs
This PR (hopefully) fixes the following bug: #2510 (0.14.5: "Generic Knightly Order" used as faction in quest dialogue). The update makes `Knightly_Guard` resolve to a random knightly order, which should fix the faction resolution issue in `Q0C20Y02`. Since the knightly orders are already hardcoded in the `DaggerfallWorkshop.Game.Guilds.KnightlyOrder.Orders` `enum`, the `enum` values were used instead of adding another hardcoded set of knightly order ids.
> Fixed Knightly_Guard faction resolve bug.

- Assets/Scripts/Game/UserInterface/ListBox.cs
- Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs
- Assets/Scripts/Game/UserInterface/TextLabel.cs
Fix for MultiFormatTextLabel and ListBox TextLabel wrapping issues spotted in 4:3 mode.
I originally noticed an issue with wrapping TextLabels when constructing a MultiFormatTextLabel while running in 4:3 mode.
Wrapped text would overlap the following line. 
In the TextLabel.CreateNewLabelLayoutWrapped() method, the LocalScale was (1,1), causing some bad line metric calculations.
More recently I noticed the bottom line of the npc conversation window was often not shown in 4:3 mode.
This appears to be the same problem.
This fix calls GetRectangle() on the TextLabel early to establish the correct LocalScale prior to other operations.
> Fix TextLabel metrics in 4:3 mode for MultiFormatTextLabel and ListBox.

- Assets/Scripts/Game/Player/VitalsChangeDetector.cs
- Assets/Scripts/Game/UserInterface/HUDVitals.cs
This PR fixes the following issue: #2593 (Changing Vitals while HUDVitals is not Active)
RCA can be found in my comment on the issue. This was the least hacky fix I could think of without resorting to updating `HUDVitals` every tick from `DaggerfallUI.Update`, or doing more complicated state tracking in `VitalsChangeDetector` to ensure `VitalsChangeDetector.HealthLost` wasn't missed. The latter approach would have been difficult to make generic to cover all of the states that can be missed e.g. `FatigueLost`, `MagickaLost`, etc., and may have involved modifications to referencing code as well.
Instead, I opted to modify `VitalsChangeDetector` to delay updates a single tick after each unpause. This should cover cases like those observed in #2593, where only a single tick passes between …
> Fixed VitalChangeDetector UI synchronization issue.

- Assets/Scripts/API/MapsFile.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/Scripts/Internal/PlayerGPS.cs
So, most of the Daggerfall is Breton lands. But not all. But in quests, we always see the named residences of Bretons. Even in the Redguard lands. We should use Redguard names in Redguard lands.
Original DOS:
PR effect:
Sentinel
Wayrest
> Use Redguard names in Redguard lands for named residences

- Assets/Scripts/Game/Questing/Actions/PcAt.cs
- Assets/Scripts/Game/Questing/Place.cs
- Assets/StreamingAssets/Tables/Quests-Places.txt
In `Quests-Places.txt` records with `p1 == 0` are dungeons but function Place.IsPlayerAtBuildingType() forbids using anything but buildings.
```cs
if (!playerEnterExit.IsPlayerInsideBuilding)
return false;
```
> PcAt : ActionTemplate support dungeons

- Assets/Scripts/Game/TransportManager.cs
- Assets/Scripts/Internal/DaggerfallLoot.cs
- Assets/Scripts/Utility/ImageReader.cs
- Allows custom transportation items to be contributed by mods and actually have a chance to appear in shops.
- Allow new horses to enable the horse transportation option. (this could be done for carts as well if desired, but I don't think people really use this much so won't want to add any new ones)
- Allow custom items to have animated icons in inventory. (bugfix)
> Allow other transportation items to be added by mods

- Assets/Editor/X-DoorBoxCollider.preset
- Assets/Editor/X-DoorBoxCollider.preset.meta
- Assets/Editor/Z-DoorBoxCollider.preset
- Assets/Editor/Z-DoorBoxCollider.preset.meta
- Assets/Scripts/Internal/DaggerfallInterior.cs
- Assets/Scripts/Internal/DaggerfallStaticBuildings.cs
- Assets/Scripts/Utility/AssetInjection/Components/CustomDoor.cs
- Assets/Scripts/Utility/RMBLayout.cs
Improve custom door support for custom models, enabled for building exterior / interior and dungeon exterior doors. CustomDoor now creates its own StaticDoor data same as any DF model StaticDoor, allowing completely new custom models using non-classic model id's to be supported. 
Retained the existing copy mechanism that uses the boxcollider to test for a hit and the copied door data. This copy mechanism has been retained for backwards compatibility, code could be simplified if it were removed. I don't think it's that useful anymore. If any published mods use CustomDoor then they should continue to work identically as long as the copy index was set.
Player placement for both entering and exiting is now correct. The exception is when replacing a classic model with all building doors …
> Improve custom door support for custom models

- Assets/Scripts/API/FactionFile.cs
- Assets/Scripts/Game/Guilds/GuildManager.cs
Try creating guild using variant so that custom guilds can have sub-groups like Temples and Knight Orders do.
Also entended the guild groups enum so we have plenty of guild entries available. Pretty sure this has no detremental effect.
> Enable variant custom guilds

- Assets/Scripts/AudioSynthesis/Synthesis/Synthesizer.MidiControl.cs
Many soundfonts will only provide percussion on patch 0 of bank 128. This fix allows attempting to fall back to the default percussion patch location when a drum patch is unavailable.
See this comment for an example of the common soundfont bank and patch setup for drums: https://github.com/LMMS/lmms/issues/323#issuecomment-40160617
To verify the problem, try loading this OPL3.SF2 soundfont [OPL3.zip](https://github.com/Interkarma/daggerfall-unity/files/14804912/OPL3.zip) with the current release version and notice the percussion during 5strong.mid is missing in the startup screen. When this fix is applied the percussion will work.
> Fix drums in custom soundfonts

- Assets/Scripts/Game/DaggerfallBankManager.cs
The weight of Gold Pieces in the player's inventory is stored in DaggerfallBankManager.cs as a literal value. This change instead indirectly loads it in from the itemTemplates array set in ItemHelper.cs
The intended result is that it thus exposes to mods the weight of gold pieces in the player's inventory, which it does according to my tests. It also appropriately affects certain transfers of gold pieces.
> Replace PC Gold Weight Literal With Loaded Value

- Assets/Scripts/Utility/MacroHelper.cs
Some quest dialog and strings include GSP (gender-specific pronoun) macros (e.g. %g1). However, the macro handler always makes these lower-case, which is improper at the beginning of a sentence, in English at least.
Instead of making GSP macros always capitalized, and unnecessarily deifying characters, it makes more sense to capitalize only the ones at the beginning of a sentence. I found an earlier proposal which suggested code changes to detect when one is used at the beginning of a sentence. However, this detection becomes problematic when accounting for whitespace, unusual punctuation, and other languages whose sentences may end with different symbols.
Therefore, I added new macros which capitalize the first letter of the GSP, which can be placed in quest/string files as needed to …
> Add Contextual Macros for Capitalized Gender-Specific Pronouns

- Assets/Scripts/Game/Questing/Item.cs
This adds a new format for defining items in quest scripts enabling creation of modded items that have classes. The new form is:
`Item _thing_ item class 27 template 512`
The class specified is only used if the templateIndex isn't registered, otherwise it uses the item class.
Also fixed a code error that had not been spotted because it didn't cause any issues until I added this form.
> Quest item resource mod support

- Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
See issue at #2661.
I did a search for `Application.persistentDataPath`, it should be the last one
> Fixed the Mod Loader Interface Window's Extract Text in Portable Inst

- Assets/Scripts/Game/MagicAndEffects/Effects/Special/WabbajackEffect.cs
A new gameObject is actually created for the transmuted enemy, facing north. Keep the orientation of the replaced gameObject instead.
Test: you can give yourself the Wabbajack by typing "addArtifact 6" in the console
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6709&sid=e5aade01a84f5052bc8b32e13e7ee934
> Preserve enemy orientation when hit by the Wabbajack

- Assets/Scripts/Internal/PlayerGPS.cs
- Assets/StreamingAssets/Factions/FACTION.TXT
In FACTION.TXT, you can find 44 factions of the "Court" guild type. Out of these, 43 have the social group Nobility - we have only one exception, the Court of Mournoth.
```
#567
type: 14
name: Court of Mournoth
rep: 0
summon: -1
region: 53
power: 51
face: -1
race: 2
flat: 183 3
flat: 183 9
>>> sgroup: 2
ggroup: 15
flags: 0
minf: 20
maxf: 80
```
As documented at the top of FACTION.TXT, 
```
; The field sgroup should be set to one of the following values:
; COMMONER	0
; MERCHANT	1
; SCHOLAR	2
; NOBILITY	3
; UNDERWORLD	4
```
sgroup of 2 is Scholar.
In DFU's search for the current region's Court, it specified that the faction it's looking *has* to be Nobility. This is an unnecessary restriction, and causes the Scholarly Court of Mournoth to fail to return here, causing an exception to be …
> Fixed error during GetCourtOfCurrentRegion query in Mournoth

- Assets/Scripts/Game/FPSWeapon.cs
Adds an Offset variable that lets other scripts move the FPS Weapon sprite while preserving the original weaponPosition variable, mostly made to support mods that add weapon sway/bob.
[SAMPLE](https://streamable.com/p2o26c) of Offset working with mod (not included)
If nothing tries to change the FPSWeapon Offset, it should behave entirely like usual. I hope. Suggestions for better implementation are always welcome.
> FPS Weapon Movement variable

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
In classic you can use all magic items while silenced, but in Daggerfall Unity you couldn't use magic items at range, because while silence lets you ready magic items, it does not let you release their spells.
Most likely an overlook.
Also, SilenceCheck() can do side effets (display "You are silenced" and reset readied spell), so when used with short-circuited logic operators, order matters and it should be placed late/last.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6725
> Use magic items at range while silenced

- Assets/Scripts/Game/Entities/RaceTemplate.cs
- Assets/Scripts/Game/Formulas/FormulaHelper.cs
FormulaHelper previously applied racial resistances by reading the player's race directly. With this change, the saving throw calculation will be modified by the contents of the player's RaceTemplate.
Addresses the following issue:
https://github.com/Interkarma/daggerfall-unity/issues/2660
> Refactor FormulaHelper to read racial resistances

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
When absorbing magicka from own spells, DFU explicitly ensures that magicka recovered is not larger than the magicka that was used. For this, it needs to track how much magicka was spent for the last spell: lastReadySpellCastingCost
A special case was not correctly handled though: when the last spell came from a magic item, lastReadySpellCastingCost should be set 0 so that next absorption of own spells is not capped.
That worked by luck when the game was just started because lastReadySpellCastingCost was still 0, but broke after first spell casting.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6755
> Fix spell absorption capping

- Assets/Scripts/Game/EnemySenses.cs
Previous code checked that the first obstacle between an enemy and its target was an object tagged "static" to determine if the enemy could hear the target (followed by a distance check).
In some cases that allowed enemies to hear targets when they shouldn't (other static tagged objects along the "line of hearing" not checked), leading to enemies facing walls or still chasing enemies thru walls when you encounter them.
This PR first checks for distance to target (like CanSeeTarget() does), then checks if they're no object tagged static inbetween the enemy and its target.
As an optimization, only objects on layer "Default" are considered, and Physics.RaycastNonAlloc() API is used to lower memory allocations.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=6759
> Fix enemies sometimes hearing thru walls

- Assets/Scripts/Game/UserInterface/DaggerfallShortcut.cs
- Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
- Assets/StreamingAssets/Text/DialogShortcuts.txt
Classic Daggerfall uses plain U key, but since in Daggerfall Unity the class name input field always has focus, that key would add an U character to the class name instead.
Remark: Under Linux, keyboard handling behaves a bit differently in the Unity Editor and in the Standalone Player: standalone player filters out control characters, while the editor does not, adding a "?" in the class name when Control-U is pressed. They could be filtered explicitly:
```diff
diff --git a/Assets/Scripts/Game/UserInterface/TextBox.cs b/Assets/Scripts/Game/UserInterface/TextBox.cs
index 9da458cef..6d660339f 100644
--- a/Assets/Scripts/Game/UserInterface/TextBox.cs +++ b/Assets/Scripts/Game/UserInterface/TextBox.cs @@ -453,6 +453,14 @@ namespace DaggerfallWorkshop.Game.UserInterface
}
}
}
+ …
```
> Control-U during character class creation resets bonus pool

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
When trying to buy from a shop and not having enough gold to pay the negociated price,
In classic Daggerfall:
- displays the same dialog box as usual, with merchant negociated price message, and Yes/No buttons;
- if you click on No, dialog box just closes;
- if you click on Yes, a message box "You don't have enough gold" is displayed
In Daggerfall Unity:
- you get the message box "You don't have enough gold"
So you never learn the negociated price, and how far you are from being able to afford buying what you are interested in.
This PR replaces the "You don't have enough gold" message with the merchant negociated price message.
> Always display negociated prices

- Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
If player is silenced, only readySpell is reset by SilenceCheck(): https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs#L1941
If this happens during spellcasting animation, castInProgress is true, and stays at true after the animation is finished because the first thing PlayerSpellCasting_OnReleaseFrame() checks is whether readySpell is not null:
https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs#L2101
Consequently, player cannot cast spells until (s)he reload a game.
This PR resets castInProgress unconditionally at the beginning of PlayerSpellCasting_OnReleaseFrame(), which is consistent with the animation being over.
Forums: …
> Handle being silenced during casting animation

- Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs
- Assets/Scenes/DaggerfallUnityGame.unity
Saw a streamer struggle twice because he opened the console unintentionally and had no idea how to close it, so closed and restarted the game instead.
Unless there's any inconvenience, I think it would be best to enable by default an already existing feature of the console: allow to close it with the Escape key in addition to the console toggle key.
(some additional fixes required because of bit rot)
> Allow to close console with Escape key

- Assets/Scripts/Game/Guilds/Guild.cs
- Assets/Scripts/Game/Guilds/IGuild.cs
- Assets/Scripts/Game/Guilds/KnightlyOrder.cs
- Assets/Scripts/Game/Guilds/MagesGuild.cs
- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
- Assets/StreamingAssets/Tables/QuestList-Classic.txt
Guild quests can be dispensed by player level as well as rank if minReq is <10 depending on the guild implementation. Proposed alternative to #2678 .
Enabled for Mages Guild and Knightly Orders.
Will add for Witch Coverns if evidence from classic Daggerfall is provided that contradicts https://en.uesp.net/wiki/Daggerfall:Witch_Covens
Only other thought is whether this change should have a way to disable this for players who prefer how DFU 1.0 currently works. Happy to add a setting or ini file property if you think worthwhile, @KABoissonneault & @petchema ?
> Allow guild quests to be dispensed by player level as well as rank

- Assets/StreamingAssets/Quests/A0C01Y01.txt
- Assets/StreamingAssets/Quests/A0C01Y03.txt
- Assets/StreamingAssets/Quests/S0000008.txt
- Assets/StreamingAssets/Quests/S0000016.txt
See bug report here: https://www.reddit.com/gallery/1evrwhg . Handing over a nonexistent totem is a separate problem, and will require a more complicated fix. Not as urgent.
> Removes totem delivery to foes during "Who Gets the Totem"

- Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Allows mods to change the endPos of DaggerfallTravelPopUp.
[Video](https://streamable.com/o0a2f8) of proof-of-concept fast travel encounter mod I was working on. If it decides to roll an encounter, it will change the destination of the travel in the DaggerfallTravelPopUp.OnPreFastTravel event. Nothing fancy. This threw me for a loop because it pretty much worked flawlessly as a virtual mod and only caused an error when building the DFMOD.
> Removed the "protected internal" keywords from the DaggerfallTravelPopUp.EndPos setter.

- Assets/Scripts/API/BlocksFile.cs
- Assets/Scripts/Utility/AssetInjection/WorldDataReplacement.cs
This allows building overrides to only replace the automap data for the relevant area of the RMB for the specific building. This effectively enables merging of overridden map data. The picture below shows the town map, first is with the building override data being used (current functionality), second is without the building override (the modified RMB map data taken from Beautiful Cities), and the third is with functionality added by this PR where the building override only overwrites the part it needs to.
You can see it overwrites some of the nearby buildings, but after adjusting the amount of area it looks very good. (note Beautiful Cities map data doesn't include the random objects and flats that can be displayed using the red grid icon)
The unused value of '30' is used to signify no …
> Mergable building override automap data (take 2)

- Assets/Scripts/Utility/ImageReader.cs
Removing the `frameCount` check made some custom inventory items with custom textures appear as material silver. Reverting the change fixes this bug.
> Revert ImageReader frameCount check
