Interkarma/daggerfall-unity

Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedWorldTerrain.cs, Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs, Game/Addons/ReflectionsMod/Scripts/MirrorReflection.cs, Game/Addons/ReflectionsMod/Scripts/UpdateReflectionTextures.cs, Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
MirrorReflection.cs: eliminated GameObject.Find() invocations inside OnWillRenderObject() and doing them instead in Start() function
UpdateReflectionTextures.cs: new function for obtaining sea reflection render texture and ground level reflection render texture added (getSeaReflectionRenderTexture() and getGroundReflectionRenderTexture())
IncreasedTerrainDistance.cs: sea reflections activated and new function for obtaining sea reflection render texture (getSeaReflectionRenderTexture()) from ReflectionsMod's UpdateReflectionTextures script used, SetupGameObjects() is invoked OnAwake() so that cameras are created there - so MirrorReflection script of ReflectionsMod can find cameras in its Start() function
InjectReflectiveMaterialProperty.cs: eliminated GameObject.Find() invocations inside …
=> implemented changes due to feedback from interkarma

Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Scripts/Game/GameManager.cs
Added simple generic methods to GameManager for finding gameobjects & components
Expanded the properties in GameManager using these new generic methods
Added GetProperties() to GameManager, which sets all of the GameManager's properties
Updated Set_Weather console command to change weather via WeatherManager
=> Changes to GameManager & SetWeather console command

Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Scripts/Game/GameManager.cs
Reverts Interkarma/daggerfall-unity#7
=> Revert f6a13bdf57759360aa9812b02770e42fc6ddf5e5

Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Scripts/Game/GameManager.cs
Reverts Interkarma/daggerfall-unity#8
=> Revert 2c8f3b8e3ab04406335f6b55d2e7fc3f468146d0

Scripts/Game/DaggerfallUI.cs, Scripts/Game/UserInterface/TextBox.cs, Scripts/Game/UserInterface/UserInterfaceManager.cs, Scripts/Game/UserInterface/UserInterfaceWindow.cs, Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs, Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs.meta, Scripts/Internal/DaggerfallAction.cs, Scripts/SettingsManager.cs
Action types 11 & 12, UI changes to support them, and a small change to SettingsManager that will create a new settings.ini file from fallback.ini if settings.ini isn't found in the data directory.
=> Work in progress

Scripts/GenerateDiagLog.cs
updated log creator to include system info.
=> Added system info properties to better log hardware

Scripts/Game/UserInterface/ListBox.cs
Added a new method to ListBox to swap text labels
=> Added a Method to ListBox to swap 2 text labels in the list by index

Game/Addons/UnityConsole/Console/Scripts/Commands/LoadCommand.cs, Scripts/VersionInfo.cs
=> Fixed using statement in LoadCommand.cs.

Scripts/Game/DaggerfallUI.cs, Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
DaggerfallUI changes:
ProcessMessages() won't push travel map window when player inside
DaggerfallTravelMapWindow:
1. Fixed Region overlay not updating player region after travel
2. Esc no longer closes travel window
3. Added color array for location pixels & lookup function; location pixel colors now correct
4. Can now click to travel to location or travel by find button
5. At button now works in both region and main map window.
7. Red flashing crosshair texture now created from both At & find buttons (in region map view).
8. Cybadies is now working
=> travel map update

Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Adds properties & fixes some mouse related issues with DaggerfallTravelMap
=> Travel map

Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs, Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs, Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs.meta
Replaces old teleport functions in DaggerfallTravelMap w/ travel options pop-up window
=> Travel map 

Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
=> Travel map update adding ability to switch to different regions

Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs
reflections should work now after fast traveling again
=> [ReflectionsMod]

Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedWorldTerrain.cs, Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Game/Addons/ReflectionsMod/Scripts/UpdateReflectionTextures.cs
fixed NullReferenceException in IncreasedTerrainDistance mod when ReflectionsMod is not activated
added some missing checks for mod activation state
fixed a bug in ImprovedWorldTerrain script and increased elevation amplification of map pixels without locations
=> fixed NullReferenceException in IncreasedTerrainDistance mod and other fixes

Scripts/Game/DaggerfallAutomap.cs
geometry now correctly loads when starting in privateer's hold
=> automap - fixed bug when player died and a new game is started

Game/Addons/UnityConsole/Console/Scripts/ConsoleController.cs, Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Scripts/External/FPSDisplay.cs, Scripts/External/FPSDisplay.cs.meta, Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Added a FPS counter that can be enabled w/ the tdbg console command.
Added a new console command to trigger action objects.
Bug fix for texture creation in DaggerfallTravelMapWindow.
=> Changes to DefaultCommands & bug fix for TravelMap

Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedWorldTerrain.cs, Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Scripts/Game/DaggerfallAutomap.cs, Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
right-mouse drag&drop rotates now the camera around model (with left/right around the rotation axis, with up/down on the camera YZ-plane)
fine-tuned some control speeds
=> automap - improved controls

Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
alternative background (single-color) can be selected with hotkeys, F5-F8, F4 is default
rendering mode hotkeys are now F2-F4, F1 is reserved for help window
=> Automap - switch automap background with hotkeys F4-F8

Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedTerrainSampler.cs, Game/Addons/IncreasedTerrainDistanceMod/Scripts/ImprovedWorldTerrain.cs, Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Game/Addons/IncreasedTerrainDistanceMod/Shaders/DaggerfallBillboardBatchFaded.shader, Game/Addons/IncreasedTerrainDistanceMod/Shaders/DaggerfallBillboardBatchFaded.shader.meta, Game/Addons/IncreasedTerrainDistanceMod/Shaders/DaggerfallIncreasedTerrainTilemap.shader, Game/Addons/IncreasedTerrainDistanceMod/Shaders/FarTerrainCommon.cginc, Game/Addons/IncreasedTerrainDistanceMod/Shaders/FarTerrainCommon.cginc.meta, Game/Addons/IncreasedTerrainDistanceMod/Shaders/TransitionRingTilemap.shader, Game/Addons/IncreasedTerrainDistanceMod/Shaders/TransitionRingTilemap.shader.meta, Scripts/Terrain/DaggerfallTerrain.cs, Scripts/Terrain/StreamingWorld.cs
please test it and give me some feedback about it ;)
would suggest setting TerrainDistance in StreamingWorld script to 2 for a more fair performance comparison with the "old" implementation.
If your computer is strong enough run with TerrainDistance 3...
TerrainScale can be upped to 1.6 or even more if you want to see the blending more often in action ;)
=> FarTerrain - terrain transition ring

Scripts/Game/GameManager.cs, Scripts/Game/StateManager.cs, Scripts/Game/Utility/SceneControl.cs
Changes to SceneControl, GameManager & StateManager
=> Runtime compiler

Assets/Scripts/Game/DaggerfallAutomap.cs
if you find the time please wire it up with the save system so we can test it.
the last n dungeons are now remembered
the number of dungeons memorized can be set via function setNumberOfDungeonMemorized(n)
0...vanilla behavior (no dungeons are remembered after leaving them)
1...the dungeon visited last is remembered after leaving it
n...the n last visited dungeons are remembered after leaving them
default is 1 - but if you like the vanilla behavior better you can change this to 0.
as discussed on the forums - would be nice to have a ini value (e.g. numberOfDungeonMemorized) where one can set the extended behavior
=> Automap work in progress

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs
not as good as a dedicated help page but still an improvement and a start
=> automap - tooltips are now displayed on mouse over automap buttons

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Scripts/DaggerfallUnityEnums.cs, Assets/Scripts/Editor/DaggerfallUnityEditor.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Removed recent Tags / Layers changes as they are no longer needed.
ModManager changed to check SettingsManager.LypyL_ModSystem bool at start.
=> Removed Tags / Layers update & ModManager now checks LypyL_ModSystem bool

Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Assets/Game/Addons/ReflectionsMod/Scripts/MirrorReflection.cs
reverting is super bad - broke all of my branches completely. had to manually do all recent changes since revert on a clean master . maybe we find a better workflow - or is it intended to make it impossible to work on on any existing branch?
=> removed UnityEditor statement and redo recent changes

Assets/Game/Addons/IncreasedTerrainDistanceMod/Shaders/DaggerfallIncreasedTerrainTilemap.shader, Assets/Game/Addons/IncreasedTerrainDistanceMod/Shaders/FarTerrainCommon.cginc, Assets/Game/Addons/IncreasedTerrainDistanceMod/Shaders/TransitionRingTilemap.shader, Assets/Game/Addons/ReflectionsMod/Scripts/InjectReflectiveMaterialProperty.cs, Assets/Game/Addons/ReflectionsMod/Scripts/UpdateReflectionTextures.cs
FarTerrain - changed shaders to Standard shader instead of Lambert 
ReflectionsMod - fixed interior reflections
=> FarTerrain and ReflectionsMod improvements/fixes

Assets/Scripts/Game/DaggerfallAutomap.cs
automap now correctly opens up again ;)
=> automap - fix for automap - removed interior light rig handling code

Assets/Game/Addons/ReflectionsMod/Shaders/CreateLookupReflectionTextureCoordinates.shader, Assets/Game/Addons/ReflectionsMod/Shaders/CreateLookupReflectionTextureIndex.shader, Assets/Game/Addons/ReflectionsMod/Shaders/FloorMaterialWithReflections.shader
should now hopefully get through cloud build also ;)
=> ReflectionsMod - deferred planar reflection shaders now DX9-compatible

Assets/Game/Addons/ReflectionsMod/Shaders/CreateLookupReflectionTextureIndex.shader, Assets/Game/Addons/ReflectionsMod/Shaders/FloorMaterialWithReflections.shader
incorrect use of shader pragma shader_feature replaced with multi_compile
hopefully might fix the glossmap issue
=> ReflectionsMod - shader pragma multi_compile replaces shader_feature

Assets/Scripts/SoundClips.cs
This identifies various sound clips. Several of them are from Arena. There are probably some other sounds that are also from Arena that I haven't identified yet.
Also the gold pieces sound was marked as ambient metal jangling but I'm pretty sure it is the normal gold pieces sound. There's a separate ambient version.
Also there was "arrowhit1" and "arrowhit2," but arrowhit1 is the sound for shooting an arrow.
=> Identify various sound clips

Assets/Scripts/SoundClips.cs
More sounds identified, mostly monster sounds from Arena.
I also labeled a couple Daggerfall sounds, namely the body collapse sound when you kill an enemy, and the player death sound.
=> Identify more sound effects

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
I finally figured out how to get buttons showing at buttonTextDistance (4 pixels) below the text in message boxes.
All that is left right now as far as positioning things is the misc skills. Interkarma do you have any advice about how that should be done?
=> Position buttons to be correct distance below text

Assets/Scripts/Game/Items/ItemHelper.cs
Just a few minor changes to make the starting clothing match with Daggerfall.
=> Changes to starting clothing to match Daggerfall

Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Game/WeaponManager.cs, Assets/Scripts/Utility/WeaponBasics.cs
=> Basic bow combat implemented

Assets/Resources/PotionRecipes.txt, Assets/Scripts/API/ItemsFile.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionRecipeWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements the potion recipe viewer so that the user can click "INFO" in the inventory window and read their potion recipes.
=> Potion recipe viewer

Assets/Scripts/Game/DaggerfallAutomap.cs, Assets/Scripts/Game/DaggerfallExteriorAutomap.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/StateManager.cs, Assets/Scripts/Game/WeatherManager.cs
Plus some cleanup (from default Rider IDE suggestions)
=> Save and load weather

Assets/Scripts/Game/DaggerfallAutomap.cs, Assets/Scripts/Game/DaggerfallExteriorAutomap.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/StateManager.cs, Assets/Scripts/Game/WeatherManager.cs
=> Save weather

Assets/StreamingAssets/Addons.meta
Looks like the Addons folder was removed a while ago
=> Remove old meta file

Assets/Scripts/DFTextureReplacement.cs, Assets/Scripts/MaterialReader.cs
Enable import of normal maps along with custom textures.
=> Mesh and Texture replacement - Add support for normal maps

Assets/Game/Addons/EnhancedSky/Scripts/Editor/SkyManagerEditor.cs, Assets/Game/Addons/EnhancedSky/Scripts/EnhancedSkyConsoleCommands.cs, Assets/Game/Addons/EnhancedSky/Scripts/SkyManager.cs, Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Resources/WeatherTable.json, Assets/Resources/WeatherTable.json.meta, Assets/Scripts/API/MapsFile.cs, Assets/Scripts/Game/PlayerWeather.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/SongManager.cs, Assets/Scripts/Game/Weather.meta, Assets/Scripts/Game/Weather/Weather.cs, Assets/Scripts/Game/Weather/Weather.cs.meta, Assets/Scripts/Game/WeatherManager.cs, Assets/Scripts/Utility/ClimateSwaps.cs, Assets/Scripts/Utility/Tuple.cs, Assets/Scripts/Utility/Tuple.cs.meta
Weather is loaded from a JSON table based on the table in Chronicles (pg.49).
Currently weather is determined randomly. This is a bit jarring, however. It's possible to go from snowing to sunny with no transition. Marking it as a TODO to handle smoother/believable weather transitions.
Also added fog to the possible weather states.
=> Use weather table from Daggerfall Chronicles

Assets/Scripts/DFMeshReplacement.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RMBLayout.cs
Replace billboards with custom prefabs in dungeons/outdoor
=> Mesh and Texture replacement - Add Flat --> 3d Model replacement in RDB/RMB

Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Game/WeaponManager.cs
- Adds the formulas for weapon damage
- Adds helper methods to get modifiers for swing direction and weapon material
- Adds weapon damage range to the weapon object
=> add calculations for weapon damage

Assets/Scripts/Game/WeaponManager.cs
Imitates classic Daggerfall behavior. Also removed a debug comment I accidentally left in.
=> Don't play sound or hit effect for 0 damage hits

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/Scripts/Game/WeaponManager.cs
I had completely overlooked the existence of the formula helper before. I moved the previous work on damage and rest calculations to it.
There are some organizational things here I'm not sure about, like which formulas should go into the "player" region and which the "basic" region, or whether it is a good idea to use the player entity as a parameter for damage calculation.
=> Move damage and healing rate formulas to helper

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RMBLayout.cs
I started looking into Lypyl awesome work on mods support to see if i
can get a real-time import of meshes using assetbundles. This is very
WIP and it uses only a single mod package, but it does its job for now.
=> Mesh and Texture replacement - Preliminary support for AssetBundles

Assets/Scripts/Internal/DaggerfallBillboard.cs, Assets/Scripts/MaterialReader.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
* Set optional custom size of billboards
*  Cleanup
=> Mesh and Texture replacement - more on textures

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModTypes.cs, Assets/StreamingAssets/Mods.meta, Assets/StreamingAssets/Mods/.gitignore
Changes to the mod system, including:
1. Custom components on prefabs that implement the idfmod_Serializable interface will have serialized data saved in the asset bundle
2. Prefabs can now be setup w/ the serialized file mentioned previously during setup
3. ModManager can now save / load mod settings (specifically enabled bool & load priority settings) to json so the user doesn't have to set these manually every time.
=> Mod System update

Assets/Scripts/Utility/AssetInjection/FaceWall.cs, Assets/Scripts/Utility/AssetInjection/FaceWall.cs.meta
A script for objects that are hanged to walls, like wall torches. 
Let me know if i should place it somewhere else.
rotation:
http://i.imgur.com/HJWWzGT.png
alignToWall:
http://i.imgur.com/DBQPwwD.png
=> Mesh and Texture replacement - billboard-->model rotation

Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Import textures for first person weapons, different for each kind of metal.
=> Mesh and Texture replacement - Weapons

Assets/Game/Addons/IncreasedTerrainDistanceMod/Scripts/IncreasedTerrainDistance.cs, Assets/Game/Addons/ModSupport/Mod.cs
Removes all references to the Enhanced Sky mod from the IncreasedTerrainDistance, and a bug fix for the Mod class
=> Changes to Nystul's IncreasedTerrainDistance

Assets/Scripts/SoundReader.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs.meta
Import custom .wav audioclips from _StreamingAssets/Sound_.
=> Sound replacement

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/MeshReader.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RMBLayout.cs
* Code organization
* Removed legacy method
=> Mesh, Texture and Sound Replacement - Minor changes

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
overhauled & simplified the rendering process
Added zoom functionality
Replaced filter & arrow button handler functions
=> Changes to the DaggerfallTravelMapWindow

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/DaggerfallBankManager.cs.meta, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Bank data is now read from classic saves, and saved & loaded in Daggerfall Unity saves. Existing saves will still work like normal.
Basic functionality for the Bank window UI is implemented.
Added console command showbankwindow
=> Adding Bank Manager and Bank UI Window

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Questing/Actions/ClearTask.cs, Assets/Scripts/Game/Questing/Actions/ClearTask.cs.meta, Assets/Scripts/Game/Questing/Actions/LogMessage.cs, Assets/Scripts/Game/Questing/Actions/LogMessage.cs.meta, Assets/Scripts/Game/Questing/Actions/PlaySound.cs, Assets/Scripts/Game/Questing/Actions/PlaySound.cs.meta, Assets/Scripts/Game/Questing/QuestMachine.cs
Adds the following actions:
PlaySound
LogMessage
ClearTask
and the startquest console command
=> Adding quest actions & startquest console commands

Assets/Scripts/Game/Questing/Actions/PickRandomTask.cs, Assets/Scripts/Game/Questing/Actions/PickRandomTask.cs.meta, Assets/Scripts/Game/Questing/Actions/PlaySound.cs, Assets/Scripts/Game/Questing/Parser.cs, Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/Questing/QuestMachine.cs
ClearTask - updated pattern
Parser - updated ParseQrc to work with quest log entry Qrc records
Quest - fixed bug that caused GetLogMessages() to only return 1 message
QuestMachine - Added GetAllQuestLogMessages()
=> Adding PickRandomTask quest action & changes to quest system

Assets/Scripts/Game/Questing/Actions/RemoveLogMessage.cs, Assets/Scripts/Game/Questing/Actions/RemoveLogMessage.cs.meta, Assets/Scripts/Game/Questing/Actions/StartClock.cs, Assets/Scripts/Game/Questing/Actions/StartClock.cs.meta, Assets/Scripts/Game/Questing/Actions/StopClock.cs, Assets/Scripts/Game/Questing/Actions/StopClock.cs.meta, Assets/Scripts/Game/Questing/Clock.cs, Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/Questing/QuestMachine.cs
Clock - stubbed StartClock and StopClock methods
Quest - added GetClock method
=> Adding StopClock, StartClock, and remove LogMessage

Assets/Scripts/Game/UserInterface/FacePicker.cs, Assets/Scripts/Game/UserInterface/HUDCompass.cs, Assets/Scripts/Game/UserInterface/HUDCrosshair.cs, Assets/Scripts/Internal/DaggerfallMobileUnit.cs, Assets/Scripts/Internal/DaggerfallSongPlayer.cs, Assets/Scripts/MaterialReader.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/AssetInjection/XMLManager.cs
* Import .wav files for songsplayer. This means players can place correctly-named digital music files inside the sound folder and these will be played in the game without any technical knowledge required.
* Import MetalGloss textures and read Metallic/Smoothing parameters from xml.
* Improvements on TextureReplacement and XMLManager classes.
=> Various improvements on graphical and sound modding.

Assets/Scripts/Game/DaggerfallExteriorAutomap.cs
excellent work of yours interkarma! just had to plug it in.
=> exterior automap - building names integration

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/AssetInjection/XMLManager.cs, Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RMBLayout.cs
* Changes in mesh replacement
* Get UV for billboards
* use ogg for songs
=> Improvements in modding support

Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
* (ModSettings window) Fixed bad alignment when the last object on the left column is a section and not a key.
* Added a method which allow mods to easily import textures from any path on disk.
=> Improvements for mods

Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Scripts/Game/UserInterface/FacePicker.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallListPickerWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/TextureReader.cs
* Import models from mods instead of single assetbundles. This makes it easier to create, update and remove models packs.
* Fix some problems with panels and higher resolution textures.
* Settings button inside the ModLoaderWindow was wrongly  shown when there were no mods.
=> Mods: improvements

Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs
Get mod from title instead of current index
=> ModSettings: fix button behaviour

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModTypes.cs
It now remembers & automatically opens the last mod, as well as remembers the build directory so it only has to be set once
Adds visual seperators to make it easier to read
=> Updates the Mod creator window to make it more user friendly.

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
This makes it easier to see the visual limits in the UI.
=> Brighter background for adv settings scrollbars

Assets/Scripts/Game/UserInterface/HUDCompass.cs, Assets/Scripts/Game/UserInterface/HUDCrosshair.cs, Assets/Scripts/Internal/DaggerfallBillboard.cs, Assets/Scripts/Internal/DaggerfallLocation.cs, Assets/Scripts/Internal/DaggerfallMobileUnit.cs, Assets/Scripts/MaterialReader.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/AssetInjection/XMLManager.cs, Assets/Scripts/Utility/GameObjectHelper.cs
* save billboards material in cache for now, will get back to work on batch and atlas for the next build
* other minor improvements
=> TextureReplacement: Improvements

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Game/Addons/ModSupport/ModTypes.cs
Added a simple message sending method to mod manager to allow mods to pass data
Further improvements to the mod builder window
Changed mod settings to look for mod title internally, and use the directory the mod file is in rather than the main mod path
Added GUID to ModInfo / Mod so modders
=> Updates to mod system

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs, Assets/Scripts/SettingsManager.cs
added advanced settings option for setting shadow resolution mode (modes are: low, medium, high, very high)
default mode is now medium resolution which should improve performance a lot for many systems
=> added advanced settings option for setting shadow resolution mode

Assets/Scripts/Game/Questing/Actions/ClockAction.cs, Assets/Scripts/Game/Questing/Actions/ClockAction.cs.meta, Assets/Scripts/Game/Questing/Actions/StartClock.cs, Assets/Scripts/Game/Questing/Actions/StopClock.cs, Assets/Scripts/Game/Questing/Clock.cs, Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/Questing/Task.cs, Assets/StreamingAssets/Quests/__DEMO06.txt, Assets/StreamingAssets/Quests/__DEMO06.txt.meta
Added ClockAction class which is created by the Clock resource directly.  The basics of the clock resource are now working (see __Demo06 quest for example), though the flags & random range still need to be implemented.
=> Clock Resource & condition

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
* Settings presets
* Do not close the window after reset
=> ModSettings: presets

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBookReaderWindow.cs
Adds book opening and page turning sounds.
Unrelated to this PR, there is an error in the console when turning book pages, although the page turning seems to work fine.
=> Add book sounds

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Kind of pointless, but I added the "You have no spells in your spellbook." message so something happens when you click use on your spellbook. I also moved a few text IDs to the top of the file, which is where I've seen them in other files.
=> Add "no spells in your spellbook" message

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Utility/AssetInjection/SoundReplacement.cs
There are a number of incorrect calls to `string.Format`.
=> Fix string.Format usage

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/PlayerMouseLook.cs
A simple fix for http://forums.dfworkshop.net/viewtopic.php?f=24&t=325. Any reason to not just set the player's view horizontal like this?
=> Make player look straight when leaving dungeons

Assets/Scripts/Game/Entities/EntityEnums.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/WeaponManager.cs
Tallies weapon skill uses. I've managed to figure out a simple function in FALL.EXE used for tallying skills, and I added in calls to tally weapon usage. I also added in enums for skills based on their ordering in FALL.EXE.
=> Tally weapon skill uses

Assets/Scripts/Utility/AssetInjection/FaceWall.cs
* Rotate the GameObject to align it to non-straight dungeon walls
* Additionally to bring near the go if is distant from the wall, now it
also move it away if it's clipping in it.
=> Improvements to FaceWall

Assets/Scripts/Game/Formulas/FormulaHelper.cs
Remove a couple unneeded checks I added to the healing formulas. I was tired and thought I was protecting against dividing by zero :).
=> Remove unneeded checks

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Looks like I shouldn't have changed the thing. I didn't test my changes in the last PR on starting a new character. This PR should fix it.
=> Fix player dying on starting new game

Assets/Scripts/Game/Entities/PlayerEntity.cs
Small simplifying of the last PR.
=> Simplify previous fix

Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
* Added support for tuples in ModSettings and ModSettingsWindow.
* Do not write to disk automatically when a preset is applied, let the
user Save or Cancel all changes.
* Minor changes to colors: use a brighter blue for section titles.
=> ModSettings: Tuples, improvements on Cancel button

Assets/Scripts/API/Save/SaveVars.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs
=> Restore some settings from classic saves

Assets/Scripts/API/Save/CharacterRecord.cs, Assets/Scripts/Game/Entities/EntityEnums.cs, Assets/Scripts/Game/Items/ItemBuilder.cs
This imports a couple more things from classic saves:
1. Race for player to return to after they have become a vampire, werewolf or wereboar.
2. Hit points to gain on leveling up
Also corrected the race enums to match classic (they were off by 1) and added in vampire, werewolf and wereboar.
=> Import some more information from classic saves

Assets/Scripts/API/Save/CharacterRecord.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/CharacterDocument.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterface/StatsRollout.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements player leveling. As far as I know everything that should be implemented is implemented. Unity saves will at some point need to store the sum of starting skills used in calculating levels. For now this value is estimated based on the current level.
=> Implement player leveling

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
Places settings in a list of panels instead of a single one, in order to
support more than 38 keys.
A button and the keyboard Tab key can be used to switch among pages.
=> ModSettings: support multiple pages

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
added exterior automap caption line (guilds, shops, taverns) to background image
=> added exterior automap caption line (guilds, shops, taverns)

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModTypes.cs, Assets/Scripts/API/Arch3dFile.cs, Assets/Scripts/API/DFMesh.cs, Assets/Scripts/API/DFRegion.cs, Assets/Scripts/Game/Items/ItemEnums.cs
This corrects all the spelling mistakes I saw in the code, not including comments.
By the way, Interkarma, if you use Visual Studio, you might want to try it's Code Analysis tool. It helped me find these spelling mistakes and it also pointed me to the incorrect uses of string.Format for my earlier PR. It can give a ton of suggestions if you apply all the rule sets, and I'm sure that are many false positives or suggestions that are against the coding style you want to use, but it may be worthwhile to take a look at if you feel like it.
=> Correct spelling mistakes

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPopupWindow.cs
I suppose with this fix the issues in https://github.com/Interkarma/daggerfall-unity/pull/322 could result in you getting stuck in the character sheet window... I haven't been able to reproduce those yet, though.
=> Don't allow leaving with ESC during level-up

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
For http://forums.dfworkshop.net/viewtopic.php?f=24&t=529&p=5281#p5281.
=> Fix 0-hour rest/loiter taking an hour

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Reverts Interkarma/daggerfall-unity#333
=> Revert "Fix 0-hour rest/loiter taking an hour"

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Let's try this again.
I also noticed that the stupid healing rate when resting is acting up again, or maybe I didn't fix it correctly the last time. I'm only healing 1 point with a character who should heal more. I'll take a look at that next.
=> Fix 0-hour rest and loiter taking 1 hour

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Implemented rapid healing (none, in light, in darkness, always) and cleaned up the earlier health recovery formula. This is checked against classic and should be correct.
=> Implement rapid healing

Assets/Scripts/Editor/SaveExplorerWindow.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs
Fixes problem mentioned in https://github.com/Interkarma/daggerfall-unity/pull/338.
=> Fix items in classic saves not being equipped

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RMBLayout.cs
* Added name as discussed
* Resource-import only on dev builds, import only from mods on released game.
* Optimization on method call to avoid repeating some code. Basically  some minor changes to integrate more default and custom import.
=> MeshReplacement: name, optimization

Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/WeaponManager.cs
This puts in the basic weapon damage calculations for the player. The weapon type, material and strength modifier are all that are considered so far.
I plan to keep adding bits to this as I figure out the formulas, but first of all here are the basics.
=> Implement weapon damage calculations

Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs, Assets/Scripts/Utility/RDBLayout.cs
I moved my code in AddFlat() and hid the quest part under an if, so action and sound are applied in the same way for vanilla and custom. Let me know if you have other preferences.
=> Action component for flat->3d object

Assets/Scripts/API/DFCareer.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
More work on damage modifiers. The damage modifier stuff should be almost done.
=> Add more damage modifiers

Assets/Scripts/API/ClassFile.cs, Assets/Scripts/API/DFCareer.cs, Assets/Scripts/API/Save/CharacterRecord.cs, Assets/Scripts/Editor/DaggerfallCareerViewerWindow.cs, Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/CharacterDocument.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Implement armor values for player shields.
Use correct value for monster level and relabel old one as number of
hit point die rolls for monsters.
Read armor values from classic as signed bytes.
=> More work on combat calculations

Assets/Scripts/Game/Player/CharacterDocument.cs
100 is the player character armor value for no armor equipped.
=> Initialize new character armor values to 100

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs, Assets/Scripts/Utility/AssetInjection/CustomVideoPlayer.cs
Instantiate video player as BaseScreenComponent instead of GameObject
=> CustomVideoPlayer: use DaggerfallUI

Assets/Scripts/Utility/AssetInjection/DayNight.cs, Assets/Scripts/Utility/AssetInjection/DayNight.cs.meta
If you want a test model to try, [this is a town lamp](https://drive.google.com/open?id=0B_JvVNlSG3cRWHpzZ0txaUF6NDA).
=> Add day time logic for imported models

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
The basics of pickpocketing are implemented here. More work needs to be done on it, but first of all I want to be sure you're OK with the ray tracing checks. It's using a mix of a "motor" for mobile NPCs and a "DaggerfallEntityBehaviour" for mobile enemies, but it works.
The most notable problem at the moment is that many of the messages when you don't find any gold on the target are too long and run off the screen. Looks like the text formatting still needs some work.
Also shortened the lockpicking formulas.
=> Implement pickpocketing

Assets/Scripts/DaggerfallUnityStructs.cs, Assets/Scripts/Game/EnemyDeath.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Internal/DaggerfallLoot.cs, Assets/Scripts/Utility/EnemyBasics.cs, Assets/Scripts/Utility/GameObjectHelper.cs, Assets/Scripts/Utility/RDBLayout.cs
Adds maps to loot from enemies and in dungeons the same as classic, and sets loot by dungeon type as in classic
=> Add maps to loot and set loot by dungeon type

Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/API/CfaFile.cs, Assets/Scripts/DaggerfallUnityEnums.cs, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/DaggerfallUIMessages.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/PlayerFootsteps.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/TransportManager.cs, Assets/Scripts/Game/TransportManager.cs.meta, Assets/Scripts/Game/UserInterface/UserInterfaceManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs, Assets/Scripts/Utility/ImageReader.cs
- Transport popup menu added. 
- Options enabled depending on having horse or cart in inventory.
- Horse and cart transport modes change height and speed. (cart and horse are the same to minimise changes to PlayerMotor class)
- Allow jumping since it makes sense that a horse can jump. (should be disabled for cart when PlayerMotor is rewritten)
- Play sounds for movement (clip-clop) and random neighing. (every 2-30secs)
- Transport state is correctly saved & loaded. (not imported from classic saves)
- Automatically dismount when entering buildings or dungeons.
- Fixed palette bug in CfaFile.
=> Added transport menu and horse riding.

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
fix for incorrectly shown border on travelmap (world map) -
border is only shown in region map now
=> fix for incorrectly shown border on travelmap (world map)

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/DaggerfallUIMessages.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMDS.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMDS.cs.meta, Assets/Scripts/Game/Questing/Person.cs, Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/Questing/QuestMDS.cs, Assets/Scripts/Game/Questing/QuestMDS.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs, Assets/Scripts/Utility/MacroDataSource.cs, Assets/Scripts/Utility/MacroDataSource.cs.meta, Assets/Scripts/Utility/MacroHelper.cs, Assets/Scripts/Utility/MacroHelper.cs.meta, Assets/Scripts/Utility/QuestMacroHelper.cs, Assets/StreamingAssets/Quests/M0B00Y16.txt
Please let me know what you think of this. If you like it I will finish it and tidy it up and submit again.
Info status popup complete. (press 'I')
Weapon info almost complete.
Armour info partially complete.
Quest macros handled.
=> Prototype macro handling system

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
Items are better subdivided in sections
=> AdvancedSettingsWindow: reorganization of settings position

Assets/Scripts/Editor/SetupMobilePersonEditor.cs, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/MobilePersonMotor.cs, Assets/Scripts/Game/MobilePersonNPC.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterface/HorizontalSlider.cs, Assets/Scripts/Game/UserInterface/ListBox.cs, Assets/Scripts/Game/UserInterface/TextLabel.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs, Assets/Scripts/Game/Utility/PopulationManager.cs, Assets/Scripts/Internal/MobilePersonBillboard.cs, Assets/Scripts/Utility/ImageProcessing.cs
I create this pull request now since important parts of the basic window functionality are working and I already touched a lot of files - so I want to do several "smaller" pull-request (in fact the are not that small) instead of one huge in the end...
things changed in other files than DaggerfallTalkWindow that are worth mentioning:
- MobilyPersonNPC now holds all npc data and its data is propagated to/consumed by MobilePersonMotor and MobilePersonBillboard class
- Found and fixed a bug in HorizontalSlider class preventing correct slider operation in many cases
- extended Listbox (and its dependency) TextLabel class to support labels starting from a character other than the first (if it is not clear what I mean check out talk window list box on the left - it can be scrolled to left/right …
=> talk window - first stage of implementation

Assets/Scripts/Internal/MobilePersonBillboard.cs, Assets/Scripts/Utility/RMBLayout.cs
* Support mobile npcs (4096 atlas like vegetation)
* Removed old checks in RMB I forgot to remove before
=> TextureReplacement: Mobile NPCs

Assets/Resources/ItemTemplates.txt, Assets/Scripts/API/Save/ContainerRecord.cs, Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/Items/ItemEnums.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInputMessageBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Utility/MacroHelper.cs
Inventory, carry, wagon, gold.
Added message for gold too heavy from bank over classic.
Fixed skeletons key artifact popups.
=> Implement weight and encumbrance

Assets/Scripts/API/Save/CharacterRecord.cs, Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/CharacterDocument.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Implements ineffective weapon materials, as well as a little reorganizing. Later we will probably want to use the weapon damage code for AI attacking the player or each other, too.
=> Implement ineffective weapon materials

Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Caused by me changing Allofich's code while he was still working on it I think.
Needs Allofich to confirm I fixed this correctly, but basically removed the bit I added and was duplicated by his work.
=> Fix merge conflict with shield armour values

Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Player/CharacterDocument.cs, Assets/Scripts/Game/UserInterface/PaperDoll.cs
Well that was surprisingly easy... which is a first for any of the DFU tasks I've set myself.
Note I moved a couple of the values a little to improve on classic. Spent much more time on the positioning than the code!! lol
=> Add armour values to paperdoll

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Tiny little tweak I made last night - just had to give it a test before submitting
=> Boots & shoes count as leather armour

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Cost calculation is rubbish
Fixed broken skills popup
=> Basic repair - instant

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Utility/MacroHelper.cs
Implemented choice of accessing wagon when exiting dungeon.
=> Disallow wagon access in dungeons

Assets/Scripts/Game/MobilePersonNPC.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterface/TextLabel.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
namebank for mobile npc's names are now derived from climateSettings
"where is" topic list added (news and placeholders for organizations)
bug in textlabel class fixed
some question and answer pairs implemented
first version of greeting messages implemented
re-selection of same topic category will no longer create a new question
=> Talkwindow - improvements and fixes

Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
=> Handle building name macro & fix quest item stack combination

Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
1) try to import ID_ClimateSeason or ID_Desert.
2) try to import generic ID (interiors etc.)
=> MeshReplacement: support for climate/season variants

Assets/Scripts/Editor/TextRecordViewerWindow.cs, Assets/Scripts/Editor/TextRecordViewerWindow.cs.meta, Assets/Scripts/Game/DaggerfallExteriorAutomap.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterface/TextLabel.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs, Assets/Scripts/Utility/MacroHelper.cs
new things:
text record viewer in unity editor (to have an easy way to show text records)
dialog macro expansion started
location hints implemented (direction and map reveal) - currently chances are hardcoded and not like in vanilla since this has to be found out, furthermore npcs always use the same hardcoded "mood" set for answers
=> Talkwindow - location hints and revealing

Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/PersistentFactionData.cs
Implemented mostly. There's still a little bit to figure out, perhaps related to adjusting regional power.
I've tried to keep there from being a noticeable pause when the function has to process for a lot of days. I think it's OK but Interkarma, can you test doing a long fast travel and see if there is a noticeable pause for your computer? If there is maybe the function can be streamlined further.
=> Implement daily price adjustments

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/Questing/Components/SpecialNPCClickBehaviour.cs, Assets/Scripts/Game/StaticNPC.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
currently only a few portraits are in (e.g. quest giver of fighters guild of daggerfall)
portraits are matched to billboards texture archive and record index
for currently unknown combinations (almost all static npcs) the portrait image with the text "oops! ..." is chosen to make it easily recognizable that the mapping needs to be done for this npc's billboard
=> Talkwindow - implementation of talking to static npcs started

Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
* Avoid NullReferenceException on block/city viewer in editor
(ModManager is not present); import models from resources while in
editor instead.
* Print an error instead of throwing an exception when a
material is not assigned; do not print an error if maintexture is not
present (transparency etc.)
* Assign filtermode using sharedmaterials.
=> MeshReplacement: tweaks

Assets/Scripts/API/FlatsFile.cs, Assets/Scripts/API/FlatsFile.cs.meta, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/Questing/Components/SpecialNPCClickBehaviour.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Utility/ContentReader.cs
in PlayerActivate.cs: put the hit test for quest npcs first and added return - so no need to check for attached script
changed SpecialNPCClickBehaviour.cs as suggested
added FlatsFile.cs class (flats file reader for file FLATS.CFG) and uses this information to derive correct common static npc resolving
=> progress and fixes for talk functionality

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Also ensured the info is cleared each time inventory accessed. Seems the on start event is not getting called.
=> Make iventory info panel enabled by default

Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellMerchantWindow.cs
Also fixed broken message & don't display for arrows
=> Fix info panel scroll reaction

Assets/Scripts/Game/UserInterface/TextLabel.cs
fixed Textlabel size when TextScale is used (set background color and see correct textlabel size now)
there is a new Property HorizontalTextAlignment now which can be used to align text inside the textlabel
=> fixed Textlabel size when TextScale is used, horizontal text alignment

Assets/Scripts/Game/UserInterface/ListBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
Reduced font size to get space for more settings. @ajrb 
@Nystul-the-Magician 
Had to add a property to ListBox because label is not publicly accesible.
=> SettingsWindow: visual improvements

Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Items/ItemEquipTable.cs, Assets/Scripts/Game/UserInterface/ItemListScroller.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
- Items can now be colour highlighted in enhanced mode
- Fixed broken acrtions when info panel disabled
Thanks for pointing out that last one. I forgot to test that.
=> Fixes for inventory window

Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs, Assets/Scripts/Game/UserInterface/TextLabel.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
sry hazelnut for screwing up things - hope this works now good enough
LineHeight in MultiFormatTextLabel fixed
=> fixes to TextLabel and MultiFormatTextLabel - infopanel values updated

Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs, Assets/Scripts/Game/UserInterface/TextLabel.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
fixes to MultiFormatTextLabel (no unintended extra-line spacing is added anymore)
improvements for text scaling issues with small (one-lined) text
=> fixes to MultiFormatTextLabel and TextLabel regarding TextScaling and Formatting

Assets/Scripts/Terrain/TerrainHelper.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Instantiate trees from mods on streaming world. It needs some good optimization and i've yet to get the correct positions, but we're almost there.
=> MeshReplacement: Early implementation of StreamingWorld trees

Assets/Scripts/Terrain/TerrainHelper.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
It's still a bit off, don't know if due to terrain resolution or something i can fix.
=> Trees: fixes and tweaks

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
- Can now identify things at mages guild. (Allofich, can you check the new formula please?)
- Can now purchase random items from magic items seller in mages guild. (Allofich, please check I used formulas correctly)
- Items to be purchased have a yellow highlight.
- All mage guild & fighters guild npcs have popups now.
- Two temple npcs have popups.
- Quest popup will be assimilated at some point. (once Gav is happy)
=> Guild services - initial implementation (identification)

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/Items/LootTables.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Fix race bug with createRandomClothing
- Fix weight handling when purchasing
- Correct equip behaviour when purchasing
- Fix for material weight calculation. (Was causing Dwarven and Ebony weapons and armour to weigh nothing)
=> Purchase UI refinements & some bugfixes

Assets/Scripts/Game/EnemyDeath.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/UserInterface/ItemListScroller.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Ensured that quest items are still highlighted correctly if magic.
Assumed quest items can never be purchased.
=> Implement animated magic swirls and purchasable item coins 

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
See discussion in https://github.com/Interkarma/daggerfall-unity/pull/498
=> Fix wrong shift direction for material check

Assets/Scripts/API/DFLocation.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
=> Match identify cost formula to classic

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
- Training offered by mages and fighters trainers.
- Fixes for when players have no wagon.
- Fix for showing str increase effect on encumbrance when leveling.
=> Initial implementation of training plus couple of fixes.

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Also fixes for
- Library booksellers
- Sale of religious items
- Black background on exit dungeon message
=> Development of guild training

Assets/Scripts/API/Save/ContainerRecord.cs
Fixes http://forums.dfworkshop.net/viewtopic.php?f=24&t=371.
=> Fix classic save items being wrongly put in wagon

Assets/Scripts/Terrain/StreamingWorld.cs
=> Add wandering NPCs to temple settlements

Assets/Game/Addons/ModSupport/ModSettings/Editor/ModSettingsConfigurationEditor.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsConfiguration.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsKey.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs
* Create presets from inspector. Properties are cloned from main config file for creation and changes sync.
* MultipleChoice and Color support for inspector config.
=> Modsettings config

Assets/Scripts/Internal/DaggerfallMesh.cs
Should give correct dungeon door textures.
=> Apply climate swap to dungeon door textures

Assets/Scripts/Internal/DaggerfallAction.cs
Skips over some incorrect door messages in Wayrest dungeon.
=> Skip incorrect door messages in Wayrest dungeon

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Scripts/Game/UserInterface/HorizontalSlider.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
* Moved common code for slider TextLabel indicator inside HorizontalSlider class. By default it acts as a scrollbar but it can be set to be used as numeric slider or multiplechoices slider.
* Improved graphics in ModSettingsWindow.
* Minor fixes for mod settings.
=> Modsettings: graphic improvements, fixes

Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Fixes http://forums.dfworkshop.net/viewtopic.php?f=24&t=753.
=> Fix spellbook having magic swirl

Assets/Scripts/Utility/MacroHelper.cs
Used in holiday text and perhaps elsewhere.
=> Implement %t macro

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/SettingsManager.cs
Addresses request in http://forums.dfworkshop.net/viewtopic.php?f=4&p=9231&sid=a0d0a83058d2068e130a0061395aacb0#p9231.
Possible values are:
0 - Don't show material (like classic). Default.
1 - Show for non-leather and chain materials 
2 - Same as 1 but show chain
3 - Show all
=> Optionally show material for helms/shields

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
* Merged tooltips modes in a slider.
* Added inventoryinfopanel and enhanceditemlists.
=> SettingsWindow: inventory settings

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs
As showed on forums, settings are grouped in tabs or pages. You can move to the next one with the tab key or selecting a title in top bar.
=> SettingsWindow: support for multiple pages

Assets/Scripts/API/Save/SaveVars.cs, Assets/Scripts/Game/AmbientEffectsPlayer.cs, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/FakeLevitate.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/PlayerFootsteps.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs, Assets/Scripts/Game/UserInterface/HUDVitals.cs, Assets/Scripts/Game/UserInterface/VerticalProgress.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs, Assets/Scripts/SoundClips.cs, Assets/Scripts/Utility/GameObjectHelper.cs, Assets/Scripts/Utility/RDBLayout.cs
New water stuff.
- Sounds for walking in shallow water, swimming in deeper water, underwater ambient sound
- Swim movement, borrowing the FakeLevitate class, since levitation and swimming movement are pretty much the same thing in Daggerfall. Swim speed based off of classic formula.
- Swim fatigue and skill tallying, matching classic.
- "You cannot sleep now." message if you try to rest while swimming.
=> Water movement, sounds

Assets/Scripts/Game/Questing/Actions/DialogLink.cs, Assets/Scripts/Game/Questing/Actions/RumorMill.cs, Assets/Scripts/Game/Questing/Actions/RumorMill.cs.meta, Assets/Scripts/Game/Questing/Item.cs, Assets/Scripts/Game/Questing/Person.cs, Assets/Scripts/Game/Questing/Place.cs, Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/Questing/QuestMachine.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/TalkManager.cs
started rumor mill implementation, still very early work in progress
"rumor mill" quest action added
fixes and bugfixes
=> Talkwindow - started rumor mill implementation

Assets/Scripts/Game/EnemyDeath.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/Serialization/SerializableLootContainer.cs, Assets/Scripts/Internal/DaggerfallLoot.cs, Assets/Scripts/Utility/GameObjectHelper.cs, Assets/Scripts/Utility/RDBLayout.cs
Creates potions randomly from the 20 varieties, like in classic, with correct names and values. Also works with potions imported from classic.
=> Potion generation and enemy inventory changes

Assets/Scripts/Game/Questing/Quest.cs, Assets/Scripts/Game/TalkManager.cs
implemented questor post quest messages
furthermore multi-line textrecord for quest progress rumors are working correctly now
=> TalkWindow - implemented questor post quest messages

Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
You can't actually ask about them, but the list is populated now.
=> Add regional building talk options

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsReader.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs, Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs.meta
* Import presets from mod and disk with check on target version
* Create and update new presets on disk
=> PresetPicker window

Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/EnemySounds.cs, Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/PlayerFootsteps.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Game/WeaponManager.cs
Here's the basics of enemy ranged attacks. The timings and ranges used in the AI decisions should be the same or close to classic.
This still needs work but the basics are in and I think it's already functional enough for testing or playing around.
=> Implement basics of enemy ranged attacks

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTeleportPopUp.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTeleportPopUp.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
A nice simple UI addition to ease myself back in gently. Can be used by everyone for now, until guilds are implemented.
=> Implement Teleportation service

Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Utility/MacroHelper.cs
Hello everyone. I thought I'd take a crack at implementing the faction talk on the "Tell me about..." list. I made sure to list the factions in the order that they appear in vanilla. It doesn't yet handle cases in which the NPC doesn't know about/doesn't want to discuss the topic but this should help lay the groundwork for the dialogue system.
=> Implement dialogue for getting faction info

Assets/Scripts/Game/EnemyMotor.cs
This lets aquatic creatures move around freely while in dungeon water.
Classic has odd behavior where aquatic creatures only move horizontally. (I think they might be able to move vertically by slight amounts, not sure) I think creatures being able to move around freely like the player is the expected behavior, though.
There's one known issue. If you lead an aquatic creature to a (not overly steep) slope leading out of the water, it will follow you and get stuck above the water, unable to move. I think this happens because even when it's near the water surface it can still move horizontally, and when it does this the sloping floor pushes it up out of the water.
It's probably a pretty rare case, so if there's a cheap and simple solution for it, that would be good. Similarly we need to stop …
=> Allow aquatic creatures to swim around in water

Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/EnemySenses.cs
This implements enemy turning, modeled after classic.
In master branch right now enemies don't have to turn, they instantly move in the direction they want to move. With this PR they turn and then move.
=> Implement enemy turning

Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Internal/DaggerfallLoot.cs
Since you're making a final 0.4 build in next day or so, I though the shelf stocking should be refined to be vaguely sensible so I threw together a quick algorithm to tide it over until Allofich implements the real one from classic. (@Allofich didn't want to pressure ya mate)
Should probly have done this from the start, was me being lazy.
=> Refine temporary shop shelf stocking to be more sensible for next build

Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Internal/DaggerfallInterior.cs
Now shops are working you need to be able to buy and sell horses and carts
Removed free horse and cart for new characters as well as books and ingredients, they will have to earn and sell for money now
=> Allow purchase and selling of horse and cart

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Internal/DaggerfallLoot.cs
Also has minor cleanup to store shelf stock code.
=> Implement classic stock for private property

Assets/Prefabs/Scene/DaggerfallActionDoor [Interior].prefab, Assets/Scenes/DaggerfallUnityGame.unity, Assets/Scripts/Game/DaggerfallAutomap.cs, Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/Questing/Actions/CreateFoe.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableActionDoor.cs, Assets/Scripts/Game/Serialization/SerializableActionObject.cs, Assets/Scripts/Game/Serialization/SerializableEnemy.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializableLootContainer.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/Serialization/SerializableStateManager.cs, Assets/Scripts/Game/Serialization/SerializableStateManager.cs.meta, Assets/Scripts/Game/TransportManager.cs, Assets/Scripts/Game/UserInterface/BaseScreenComponent.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs, Assets/Scripts/Internal/DaggerfallDungeon.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Internal/DaggerfallLoot.cs, Assets/Scripts/Internal/PlayerGPS.cs, Assets/Scripts/Terrain/StreamingWorld.cs, Assets/Scripts/Utility/GameObjectHelper.cs
This is just for you to test where I am at since probably can't do any more for a day or so. 
Looks like I will need to merge Allofich's PR once you have accepted it into master and then create a new PR for this work. I synchronised my fork before changing the shelf stocking code... but still got caught out! lol  Is no problem at all, but will be best if I do the merging I think.
=> Scene cache implementation to handle stateful game objects

Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
=> Ship purchasing

Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializableLootContainer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Internal/DaggerfallLoot.cs, Assets/Scripts/Internal/DaggerfallLootDataTables.cs, Assets/Scripts/Utility/GameObjectHelper.cs, Assets/Scripts/Utility/RDBLayout.cs
Inventory destination icon:
Left click = next icon
Right click = prev icon
Middle click = next archive of icons
=> Implement customisation of dropped icons, and display loot container billboard textures in inventory window 

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/Serialization/SerializableStateManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/MacroDataSource.cs, Assets/Scripts/Utility/MacroHelper.cs
It works really nicely, hope I've not missed anything.
Hope you don't mind using the serialization object to store these things in player entity. Nothing needs transforming.
=> Tavern room rental system fully implemented

Assets/Scripts/Internal/PlayerGPS.cs
Fixes the resting issue in tavern/lodge/inn locations
=> Fix tavern locations to be towns

Assets/Scripts/Game/BuildingDirectory.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/BuildingNames.cs, Assets/Scripts/Utility/MacroHelper.cs
includes palace naming for the big 3 with dungeons
also moved strings for future localisation
=> Holiday macros %nt and %lp

Assets/Scripts/Game/FakeLevitate.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
This implements climbing. It's a mix of stuff I was able to figure out from classic (skill-checking formulas) and trial and error to get something that worked decently. I'm sure this still needs work but I think it's working well enough as a first iteration.
=> Implement climbing

Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Also moved strings for later localisation
=> Save breath and last ate into savedata

Assets/Scripts/Game/Items/LootTables.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/RDBLayout.cs
=> Add treasure marker containers

Assets/Scripts/Game/UserInterface/ItemListScroller.cs, Assets/Scripts/Internal/DaggerfallInterior.cs
Also fixed inventory info panel not getting updated when moving items around
=> Add model 41026 to shop shelves list

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Game/WeaponManager.cs, Assets/Scripts/Internal/DaggerfallInterior.cs
Also reinstated tally crime guild calls and disabled the function instead.. much easier to enable in one place later.
=> Shop & building schedules

Assets/Scripts/Game/EnemySenses.cs, Assets/Scripts/Game/Entities/DaggerfallSkills.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Utility/MacroHelper.cs
Can train language skills up to intelligence stat level
Increased skill tally on success to 3
Added BCHG tag to changes from classic
=> Improve usability of language skills

Assets/Scripts/Game/BuildingDirectory.cs, Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/Questing/Place.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Internal/DaggerfallInterior.cs
Also enabled mesh replacement, but still needs testing by a moddy person.
Added location name into savefile in case people forget where they bought houses.
=> House selling and lighting 3d models

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/StreamingAssets/Tables/Temp-MagesGuild.txt
Also a correct for dupe TG training skill
=> Added mage guild quests to table, mostly commented out

Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/TalkManagerMCP.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs, Assets/Scripts/Utility/MacroDataSource.cs, Assets/Scripts/Utility/MacroHelper.cs, Assets/StreamingAssets/Tables/Temp-Merchants.txt, Assets/StreamingAssets/Tables/Temp-Merchants.txt.meta, Assets/StreamingAssets/Tables/Temp-Nobility.txt, Assets/StreamingAssets/Tables/Temp-Nobility.txt.meta
NPCs can now give answers about "work." Added a generic window for quest offering that can be shared among all the NPC social groups whenever questing for those groups is implemented.
I added a merchant quest table with one quest that seems to work. A table for nobility is included as an example of extending functionality of the new questing window but those quests are not handled as of yet.
=> Add ability to get "work" from merchants

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs
Sorry about the multiple commits - I updated my fork after pushing the fix to it which causes Github to do this. I'm avoiding this most of the time now, but I forgot this morning.
=> Clear rented rooms for new games

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/UserInterface/HUDCrosshair.cs, Assets/Scripts/Game/UserInterface/PaperDoll.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallVidPlayerWindow.cs, Assets/Scripts/Utility/AssetInjection/CustomVideoPlayer.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs, Assets/Scripts/Utility/AssetInjection/VideoReplacement.cs, Assets/Scripts/Utility/ImageReader.cs, Assets/Scripts/Utility/TextureReader.cs
* Import movies from loose files
* Import Img, Cif and Rci files from mods. I had to merge seeking and import in a single method to avoid iterating mods and locations twice, but i don't think we lost much.
=> Asset injection: Improvements for movies and images

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/SettingsManager.cs
Added a few settings which where not exposed on GUI
InteractionModeIcon was not present in SaveSettings(), i assumed this wasn't intended but let me know :)
=> Settings window: "Theme" settings

Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs
I merged SetMerchantQuestors into GetBuildingList and made it part of its loop. Also updated TalkToStaticNPC so it checks to see if the NPC is a potential questor.
=> Minimize repetition in work dialogue code

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/Effects/MagicEffects.meta, Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/Entities/DaggerfallDisease.cs, Assets/Scripts/Game/Entities/DaggerfallDisease.cs.meta, Assets/Scripts/Game/Entities/EntityEnums.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Ready for Allofich to do the formula when he has time.
=> Disease foundations

Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
@ajrb Here is the PR we discussed. Interkarma, could you let ajrb take a look before merging? I didn't change much of what he had implemented.
I also added some todos for various bits to add into the damage code.
=> Match disease infliction by enemy type to classic

Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Guilds/QuestTablesManager.cs, Assets/Scripts/Game/Guilds/QuestTablesManager.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Utility/Table.cs, Assets/StreamingAssets/Tables/Quests-Classic.txt, Assets/StreamingAssets/Tables/Quests-Classic.txt.meta
Just Fighters and Mages so far.
=> Initial version of manging quest tables

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Guilds/Temple.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Utility/MacroHelper.cs
Cure is very skeleton for now, Allofich and I will flesh out soon.
=> Add donation and cure disease guild services

Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/EnemySenses.cs
At some point I seem to have accidentally made it so that all enemies hold their ground at range, not just those with ranged attacks. This fixes it.
=> Fix enemies without ranged attacks not pursuing

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Implemented climbing fatigue penalty, which I forgot to do before.
Show warning for traveling with diseases when they are past incubation. I had mistakenly thought they only showed during incubation.
=> Misc fixes

Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
* Use new generic methods from ModManager
* Expose trees settings to mods with callbacks
=> MeshReplacement: Improvements to trees, refactoring

Assets/Scripts/Game/BuildingDirectory.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Guilds/DarkBrotherhood.cs, Assets/Scripts/Game/Guilds/DarkBrotherhood.cs.meta, Assets/Scripts/Game/Guilds/GuildManager.cs, Assets/Scripts/Game/Guilds/KnightlyOrder.cs, Assets/Scripts/Game/Guilds/ThievesGuild.cs, Assets/Scripts/Game/Guilds/ThievesGuild.cs.meta, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/Questing/Person.cs, Assets/Scripts/Game/Questing/Place.cs, Assets/Scripts/Game/Questing/QuestListsManager.cs, Assets/Scripts/Game/Questing/QuestMachine.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Internal/PlayerGPS.cs, Assets/Scripts/Utility/MacroDataSource.cs, Assets/Scripts/Utility/MacroHelper.cs, Assets/Scripts/Utility/Table.cs, Assets/StreamingAssets/Quests/L0A01L00.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
3 days ago I thought I would knock out the remaining two guilds that evening... yeah, there was a lot of extra stuff to do than I expected so that didn't happen. 
Here it is now though - all types of quests except for daedra are now availiable in game!
=>  Add TG + DB, make non-member quests availiable when rep less than 0 

Assets/HeadBobber.cs, Assets/HeadBobber.cs.meta, Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs
This implements Head Bobbing and the ability to toggle and save the setting.
=> Head bobbing

Assets/Scripts/Game/Questing/Person.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs, Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/StreamingAssets/Quests/B0B50Y11.txt, Assets/StreamingAssets/Quests/B0B70Y16.txt, Assets/StreamingAssets/Quests/C0B10Y05.txt, Assets/StreamingAssets/Quests/C0B10Y07.txt, Assets/StreamingAssets/Quests/C0C00Y13.txt, Assets/StreamingAssets/Quests/F0B00Y00.txt, Assets/StreamingAssets/Quests/I0B00Y00.txt, Assets/StreamingAssets/Quests/L0B00Y01.txt, Assets/StreamingAssets/Quests/L0B10Y03.txt, Assets/StreamingAssets/Quests/N0B00Y09.txt, Assets/StreamingAssets/Quests/O0A0AL00.txt, Assets/StreamingAssets/Quests/O0B00Y01.txt, Assets/StreamingAssets/Quests/O0B00Y12.txt, Assets/StreamingAssets/Quests/O0B10Y00.txt, Assets/StreamingAssets/Quests/O0B20Y02.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Have gone through all guild quests and removed all changes Jay_H made to work around unimplemented quest system features. These will all start working once those features are finished.
Still a few work arounds in the TG + DB joining quests to allow players to join for now.
Updated all notes in quest list, and removed all the errors that were caused by testing using command line instead of a questor.
Fix commoner assigned quests by finding people of region faction id and allowing faction id 0 on static npc.
=> Fix quests

Assets/Scripts/API/Save/SaveVars.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/PersistentFactionData.cs
Changes to faction power are disabled until power can be raised in some way.
=> Progress on conditions

Assets/Scripts/API/Save/ContainerRecord.cs, Assets/Scripts/API/Save/SaveTree.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs
Added back wagon check to ContainerRecord.
Revised some comments.
=> Minor fixups for classic record reading

Assets/Scripts/MaterialReader.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Import materials from mods with load order.
=> TextureReplacement: Import materials from mods

Assets/Croucher.cs, Assets/Croucher.cs.meta, Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/PlayerMotor.cs
Hey Interkarma.  Here is smooth croucher code, I have tested the code and haven't seen the player get stuck in any doorways, and it works well with HeadBobber and CameraRecoil.
This code makes the player smoothly (and quickly) crouches or stands up.  There is also a function that uses a Spherecast to check if the player has room to stand up.  If the player tries standing up when there's no room, the code waits until the player has moved out of the area and then stands him up.
When crouching, the code first lowers the camera, then crouches the playerController.  When standing, the opposite order happens.
Most of the code is in croucher.cs.   PlayerMotor is mostly untouched, I kept in mind what you said about PlayerMotor being due for a rewrite.  I felt that maybe if I reallocated crouching …
=> Croucherfullbackup

Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
Fix for [bug with imported textures](http://forums.dfworkshop.net/viewtopic.php?f=24&t=966).
=> TextureReplacement: fix regression for loose files

Assets/Scenes/DaggerfallUnityGame.unity, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/SongManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Utility/MacroHelper.cs
Note that there seems to be an issue with the MIDI playback in DF Unity and the song used for the court screen (Song_11) where the instrument at the beginning of the song doesn't play. At first I thought the song wasn't playing at all but you wait a few seconds you'll hear music.
=> Progress court screen

Assets/Scripts/Game/Serialization/SerializablePlayer.cs
Pretty stupid mistake on my part. :(
=> Fix loading saves outside losing guild membership data

Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModTypes.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs
Added interface which allows mods to store and retrieve custom data inside save folder.
Data package is automatically de/serialized as json like core save data.
=> ModSystem: Allow mods to take part of game load/save logic

Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
questor of current quest is added to list of persons in "where is"->"person" section of talk window
answers not implemented right now
fix: quest related talk topics now get correctly removed if quest is neglected
=> Talkwindow implementation: questor is added to talk options + fix

Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/MobilePersonMotor.cs, Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/ClimbingMotor.cs.meta, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/Utility/PopulationManager.cs
Like the other two PRs, this one Isolates climbing motor commands.
=> Climbing motor

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Alteration/Paralyze.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/ContinuousDamageFatigue.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/ContinuousDamageHealth.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/ContinuousDamageSpellPoints.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainAgility.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainEndurance.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainIntelligence.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainLuck.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainPersonality.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainSpeed.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainStrength.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Destruction/DrainWillpower.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Illusion/ChameleonTrue.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/HealStrength.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/Regenerate.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Thaumaturgy/Levitate.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs
It will spit out correct costs once offsetGold values are corrected. That is planned for the next pull request.
=> Spell costs code refinement

Assets/Scripts/Game/DaggerfallExteriorAutomap.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs, Assets/StreamingAssets/Text/ConversationText.txt
info clicking won't reveal quest place resources that are available for chat but were not revealed by npc
player now must get them revealed to show on the map
=> %hnr "Ma'am" instead of "Madam", work/merchant quest offers accept closes npc submenu

Assets/Scripts/API/Save/CharacterRecord.cs
Just information, no functionality. It might be useful since you're building out effects.
=> Document and read classic effect flags

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Player/AcrobatMotor.cs, Assets/Scripts/Game/Player/AcrobatMotor.cs.meta, Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/FrictionMotor.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Terrain/StreamingWorld.cs, Assets/Scripts/Utility/FloatingOrigin.cs
Migrates code that deals with Jumping, Falling, falling damage, and gravity to a class called AcrobatMotor.  Significantly reduces size of PlayerMotor.  No problems while testing it on my end.
=> Acrobatic motor

Assets/StreamingAssets/Tables/QuestList-Classic.txt
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>
=> Fix quests repute

Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/FrictionMotor.cs, Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/Player/PlayerGroundMotor.cs, Assets/Scripts/Game/Player/PlayerGroundMotor.cs.meta, Assets/Scripts/Game/Player/PlayerHeightChanger.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Utility/FloatingOrigin.cs
Migrates code responsible for enabling input to move the player along the ground to PlayerGroundMotor. Also migrates the code enabling moving platforms to move the player to the same new class. 
Migrates a couple Height variables unused by PlayerMotor to PlayerHeightChanger.
Sorts PlayerMotor into Regions.
Adjusts access modifiers of classes I've created and adds XML documentation to several methods.
=> Player motor changes

Assets/Scripts/Game/Guilds/DarkBrotherhood.cs, Assets/Scripts/Game/Guilds/FightersGuild.cs, Assets/Scripts/Game/Guilds/Guild.cs, Assets/Scripts/Game/Guilds/GuildManager.cs, Assets/Scripts/Game/Guilds/KnightlyOrder.cs, Assets/Scripts/Game/Guilds/MagesGuild.cs, Assets/Scripts/Game/Guilds/Temple.cs, Assets/Scripts/Game/Guilds/ThievesGuild.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
* Add guildjoin and guildrank commands for guild testing
* Remove temp testing features from guilds (i.e. no free resting and rank changes only every 28 days)
* Use faction id enum where appropriate
* Fix gdd macro for donations when not temple member
=>  Add guildjoin and guildrank commands for guild testing 

Assets/Scripts/Game/Player/AcrobatMotor.cs, Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/Player/PlayerHeightChanger.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerMotor.cs
So, with these changes, I'm reasonably sure I'm done with PlayerMotor.  At least on a massive scale.
=> Player motor

Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyAgility.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyAgility.cs.meta, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyEndurance.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyEndurance.cs.meta, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyLuck.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyLuck.cs.meta, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyPersonality.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifyPersonality.cs.meta, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifySpeed.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Restoration/FortifySpeed.cs.meta
Implements the remaining 5 fortify effects, first 3 originally authored by @Interkarma, Last 5 continued by the same example set by him.  This one was actually pretty easy, just compare what you did and continue the pattern. Tested and verified spells are available now in spellmaker.
=> Finish Fortify Effects

Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs, Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/Player/PlayerGroundMotor.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs
This is the final part of @MeteoricDragon's PlayerMotor refactor. This not only makes the base motor class much smaller and neater, it separates all movement-related logic into their own class so the function of each is clearer and easier to maintain.
Thank you for your work on this @MeteoricDragon. It will make any future changes to the motor class much easier to manage.
=> Merging player-motor

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
Another piddly little change from me. Still here guys o/
lol
=> Enable scrollwheel on journal

Assets/StreamingAssets/Quests/A0C00Y00.txt, Assets/StreamingAssets/Quests/A0C01Y13.txt, Assets/StreamingAssets/Quests/M0B21Y19.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
This PR fixes gender-related discrepancies between QRC and QBN blocks and updates quests status.
=> Quests: minor fixes

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Guilds/Guild.cs, Assets/Scripts/Game/Guilds/GuildManager.cs
Bug was memberships adding to existing when loading classic saves.
=> Refactor classic guild membership import and fix bug

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs
Needs to be reviewed and given green light by Nystul before merge.
=> Fix for commoner quest handout closing HUD

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Player/PersistentFactionData.cs
New overridable formula:
CalculateAttackDamage
CalculateSuccessfulHit
CalculateStruckBodyPart
CalculateBackstabChance
CalculateBackstabDamage
=> Refactor CalculateAttackDamage and make more formula overridable

Assets/Scripts/API/DFLocation.cs, Assets/Scripts/API/MapsFile.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Reverts Interkarma/daggerfall-unity#794.
Breaks key locations such as Direnni Tower.
=> Revert "Merging mapsfile to master"

Assets/Scripts/API/DFLocation.cs, Assets/Scripts/API/MapsFile.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Continued from https://github.com/Interkarma/daggerfall-unity/pull/792
=> Fix .RMB name resolving

Assets/Scripts/Terrain/StreamingWorld.cs
This event is raised when location gameobject is created, after location components are added.
=> StreamingWorld: Add event OnUpdateLocationGameobject

Assets/StreamingAssets/Tables/QuestList-Classic.txt
Missing required quest actions for normal completion.
=> Comment out failed quest

Assets/Scripts/Utility/AssetInjection/DayNight.cs
Just some deprecated parameters.
=> DayNight: upgrade ColorUsage attribute

Assets/Scripts/Game/UserInterface/StatsRollout.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharClassSelect.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/CreateCharReputationWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharReputationWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs.meta, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Not much functionality here, just setting up the navigation and background for the custom class creator. This is mainly to stake my claim, as it were, on this feature since it's what I'm focusing on currently. Others are welcome to add to it, of course.
I commented out the "Custom" option on the class select since there's no functionality on the window as of yet. You can test it out by uncommenting line 62 of CreateCharClassSelect.cs.
=> Setup initial class creation window

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/ItemBuilder.cs
This PR calculates and assigns gold values to magic items in loot. Values should match classic.
This was kind of complicated because it also involved reversing the formula for how spell costs are calculated.
A problem here Interkarma is that I saw you already have code in place for calculating spell costs.
I looked at using your existing function but it didn't seem that it was going to be straightforward to do so, as it is built into your system and the data representations you are using for spells. Sorry I didn't do it that way but I didn't know how to convert over when the only data I had was a SPELLS.STD index (that's the only data specified by spell enchantments on items). Also I wanted to figure out how classic was doing things.
The stuff I added is self-contained and won't interfere …
=> Implement magic item gold value calculation

Assets/Scripts/Game/UserInterface/StatsRollout.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharReputationWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Sorry for the third PR in a row. There were a couple of things that were trivial to implement so I added them for the sake of completeness.
=> Implement class creator help button and add click sounds

Assets/Scripts/API/RumorFile.cs, Assets/Scripts/API/RumorFile.cs.meta, Assets/Scripts/API/Save/SaveGames.cs
No functionality yet, just reads `RUMOR.DAT` when importing a classic save and stores the data in a list of rumors.
=> Read classic rumor data

Assets/Scripts/Game/Player/HeadBobber.cs
Now swimming will bob the player down slowly then up real quick to simulate a breast stroke keeping the player afloat.  Achieved by repurposing the landing bob code to make the player bob when landing on ground or swimming, at different speeds.
=> Swimming Head Bob

Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
Includes the special advantage/disadvantage UI issue, max HP not carrying over, and spell points always being zero. Also fixes oversight in classic that allows more than 1 spell point multiplier.
=> Class creator bug fixes

Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/UnderwaterFog.cs
Simple change to allow modders to change the color of the underwater fog
=> Exposed waterFogColor with get: set: public variable

Assets/Scripts/Game/LevitateMotor.cs, Assets/Scripts/Game/Player/AcrobatMotor.cs, Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/Player/PlayerGroundMotor.cs, Assets/Scripts/Game/Player/PlayerHeightChanger.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerMotor.cs
The last commit in this PR has lots of experimental changes to the climbing system.  The others are the groundwork for a new climbing system mostly.
Things to try with this code:  
- Climbing outdoor buildings.
- Climbing dungeon walls.
- Climbing dungeon walls while aimed at doors. Curious results.
- Climbing onto dry land from water.
- Climbing starting from underwater if feeling adventurous.
=> Swimming climb up

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs
As far as I know this should be it for reflexes.
=> Finish implementing reflexes

Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/PlayerHeightChanger.cs
A few fixes to climbing and swimming
=> Swim crouch climb

Assets/Resources/FLATS.CFG.txt
=> fixed wrong npc portraits in daggerfall, wayrest and sentinel castle

Assets/Scripts/Game/TalkManager.cs
fix for merchants "I am a member of unknown-guild" bug
(see https://forums.dfworkshop.net/viewtopic.php?f=24&t=1240)
=> fix for merchants "I am a member of unknown-guild" bug

Assets/Scripts/Game/Guilds/Temple.cs, Assets/Scripts/Game/PlayerActivate.cs
=> Fix issues with guild NPCs that have no/bad building faction data

Assets/Scripts/Game/Entities/PlayerEntity.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1255.
=> Fix legal reputation persisting into older saves

Assets/Scripts/API/PaintFile.cs, Assets/Scripts/API/PaintFile.cs.meta, Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterface/MultiFormatTextLabel.cs, Assets/Scripts/Utility/ContentReader.cs, Assets/Scripts/Utility/MacroDataSource.cs, Assets/Scripts/Utility/MacroHelper.cs, Assets/Scripts/Utility/TextProvider.cs
Painting titles match classic.
Artist names don't match classic. 
Image not displayed yet.
=> Initial version of painting info construction

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/StreamingAssets/Text/GameSettings.txt
Gameplay settings window was overflowing so i moved some settings to their own page. Took the occasion to add audio settings. There are some other settings from ini to add, but first i wanted to make sure this quick fix is in the next build.
=> Update game settings window

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/StreamingAssets/Text/GameSettings.txt
This continues from #877.
Removed a duplicate key and added new light options as well as freescaling, which was missing.
Ps: @Interkarma do you get notifications for new messages in closed PRs? Just wanted to make sure you received my last post :)
=> Update game settings window / 2

Assets/Scripts/Utility/RDBLayout.cs, Assets/Scripts/Utility/RandomEncounters.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1263. Also I must have accidentally added a few extra enemies onto the cemetery list earlier that aren't in there in classic.
=> Fix IndexOutOfRangeException

Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs
Quick refactor of climbing speed to PlayerSpeedChanger
=> Climbing speed refactor

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Poisons.meta, Assets/Scripts/Game/MagicAndEffects/Effects/Poisons/PoisonEffect.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Poisons/PoisonEffect.cs.meta, Assets/Scripts/Game/MagicAndEffects/EntityEffect.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectBroker.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectBundle.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs, Assets/Scripts/Game/MagicAndEffects/MagicAndEffectsEnums.cs
I will progress this feature set soon.
=> Merging in-progress PoisonEffect branch to master

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs, Assets/StreamingAssets/Text/MainMenu.txt
As discussed on https://github.com/Interkarma/daggerfall-unity/pull/877#issuecomment-421826527. Tell me what you think :)
=> Overhaul main menu

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySetupGameWizard.cs
Reduced size of title added in #901.
=> Main menu: reduce title size

Assets/Scripts/Game/Automap.cs, Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Nystul should check this and give his blessing before is merged, but I'm pretty sure this is correct.
=> Fix quest giver greeting context for guilds + new mod hooks

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
It was a simple fix. I changed some stuff around when adding the player backstory and neglected the poor custom class.
=> Fix new custom class bug

Assets/Scripts/Game/Serialization/SaveLoadManager.cs
@numidium Hope you don't mind me fixing this, I just happened to spot it while I was testing that new characters were initialised with mages guild as enemy of achaeologists.
=> Fix not deleting bio save file when deleting a save

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPlayerHistoryWindow.cs
=> Fixes bio text not reloading when loading a new game

Assets/Scripts/Game/Formulas/FormulaHelper.cs
Noticed that these were reversed.
=> Fix reversed tolerance flags

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
This should finish giving the History button parity with classic.
=> Show message box with special adv/disadv on history button click

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Also fixed bug where identify spell initiated a trade
=> Fix bug preventing items being shown for repair & identify

Assets/Scripts/Game/Utility/StartGameBehaviour.cs
Implements the classic starting spell lists.
=> Give player starting spells

Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/EnemyMotor.cs
Must have accidentally removed this earlier.
=> AI enemy fixes

Assets/Scripts/Game/Guilds/DarkBrotherhood.cs, Assets/Scripts/Game/Guilds/FightersGuild.cs, Assets/Scripts/Game/Guilds/Guild.cs, Assets/Scripts/Game/Guilds/GuildManager.cs, Assets/Scripts/Game/Guilds/KnightlyOrder.cs, Assets/Scripts/Game/Guilds/MagesGuild.cs, Assets/Scripts/Game/Guilds/NonMemberGuild.cs, Assets/Scripts/Game/Guilds/Services.cs, Assets/Scripts/Game/Guilds/Temple.cs, Assets/Scripts/Game/Guilds/ThievesGuild.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/Items/ItemCollection.cs, Assets/Scripts/Game/Items/ItemEnums.cs, Assets/Scripts/Game/Items/ItemEquipTable.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/Items/LootTables.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Internal/DaggerfallLoot.cs
Moving on in sequential order, this is cleanup on:
`Scripts/Game/Guilds`
`Scripts/Game/Items`
Use implicit array initializers
Merge nested if statements
Add end of file newlines
Fix variable shadowing
Add readonly keyword where appropriate
Clean up spacing, remove whitespace
Omit redundant comparison
Make sure foreach iteration is on expected type
Remove unused parameter in ReceiveHouse()
Remove unused using statements
Add missing `<summary>` tag
Change !(A == B) to (A != B)
Revise comments
Fix incorrect function summary params
Remove redundant variable assignment
Remove redundant textAsset to textAsset casts
=> File cleanup

Assets/Scripts/API/MapsFile.cs, Assets/Scripts/Utility/BuildingNames.cs, Assets/Scripts/Utility/MacroHelper.cs
Removed the duplicate title generation method.
=> Fix shop titles with %rt macro

Assets/Scripts/Game/FPSWeapon.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterface/LeftRightSpinner.cs, Assets/Scripts/Game/UserInterface/StatsRollout.cs, Assets/Scripts/Game/UserInterface/UpDownSpinner.cs, Assets/Scripts/Game/UserInterface/UserInterfaceManager.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
Fixed special handling of temple buildings - now can join Akatosh Chantry again by visiting Order of the Hour.
Added name change function to character sheet. Seems to work just fine with save system - just as I thought it would.
=> Fixed temples, added name change function to char sheet, Fixed spinners

Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Totally forgot about those!
https://forums.dfworkshop.net/viewtopic.php?f=28&t=1274&start=10#p16257
=> Don't stack enchanted ingredients

Assets/Scripts/Game/MagicAndEffects/Effects/Thaumaturgy/PacifyEffect.cs
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1363
=> Fix wrong text for Pacify effect

Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1410
=> Fix travel cost being negative sometimes

Assets/Scripts/Game/Items/ItemEnums.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1407.
=> Fix enum that messed up index order

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/TransportManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs, Assets/Scripts/Game/Utility/TravelTimeCalculator.cs
See https://forums.dfworkshop.net/viewtopic.php?f=28&t=1409
=> Fix travel from ship to use boarding location

Assets/Scripts/API/BiogFile.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1365.
=> Fix parsing of character background questions

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Had to make a separate branch for this due to mismatching sync with main repo
=> Fix caching of ship exteriors when fast travelling

Assets/Game/Addons/ModSupport/ModSettings/ModSettingsWindow.cs, Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs, Assets/StreamingAssets/Text/ModSystem.txt
Changed the preset picker window to follow a more consistent style and be more comfortable to use.
=> Improvements to PresetPicker

Assets/Prefabs/Scene/DaggerfallLootContainer [Game Serializable].prefab, Assets/Prefabs/Scene/DaggerfallLootContainer [Game].prefab, Assets/Scripts/Game/DaggerfallMissile.cs, Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/EnemySenses.cs
AI stops at ledges (unless they are very shallow) and does LOS check from around eye level.
=> AI: Don't walk off ledges, LOS check from eye level

Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs, Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
This implements behavior from classic for the class creator.
=> Disallow player from adding conflicting advantages and disadvantages

Assets/Scripts/Game/Player/VitalsChangeDetector.cs
@MeteoricDragon You should probably check this change and test that you're happy with the fix. Bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=1479
=> Fix for level up bug in enhanced vitals indicators

Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettings.cs, Assets/Game/Addons/ModSupport/ModSettings/PresetPicker.cs
This is for master (0.5). Then i'm going to push another PR for 0.6 to remove support for obsolete features, such as ini settings.
=> Mod Settings cleanup and documentation

Assets/Scripts/Game/EnemyMotor.cs
Fixes getting stuck at base of stairs
Fixes walking backwards off of ledges
I couldn't get AI to stop while walking against a wall as you mentioned Interkarma, but it should be fixed, too.
=> Fix issues with AI fall detection

Assets/Scripts/Game/Player/CameraRecoiler.cs, Assets/Scripts/Game/Player/CharacterDocument.cs, Assets/Scripts/Game/Player/HeadBobber.cs, Assets/Scripts/Game/Player/PersistentFactionData.cs, Assets/Scripts/Game/Player/PersistentGlobalVars.cs, Assets/Scripts/Game/Player/PlayerGroundMotor.cs, Assets/Scripts/Game/Player/PlayerHeightChanger.cs, Assets/Scripts/Game/Player/PlayerNotebook.cs, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/Player/VitalsChangeDetector.cs
Covers Scripts/Game/Player, except for the files there being modified by 
https://github.com/Interkarma/daggerfall-unity/pull/976.
Remove unused using statements
Add end-of-file new lines
Tidy up whitespace
Inline returned variables
Add missing comment headers to beginning of files
Simplify boolean expressions
Comment out unused variables
Use readonly keyword
Use const keyword
Remove empty Update functions
=> More cleanup

Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/EnemyMotor.cs
Unlike the light cleanup I'm giving in the other PRs, this is a heavy clean of EnemyMotor.cs.
The reason is that I've been and continue to be experimenting with Enemy AI. The code is messy in parts, which gives me trouble when trying to implement new things. This is to set up EnemyMotor as a cleaner base for continued work.
Changes:
- Whitespace, formatting tidied
- Code duplication removed
- Better comments, renamed variables/functions to be more accurately descriptions
- Fix shadowed variables
- General solution for switching between standing and moving animations instead of trying to catch each individual case. Problem of enemies sliding around while appearing to be in the idle animation is fixed (maybe not 100%, but definitely better)
- For enhanced combat mode, don't stop while …
=> Clean up EnemyMotor

Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
Some improvements for the ImportedComponentAttribute introduced with #1021.
This introduces support for storing references to assets or other prefabs. Basically, it saves the name of the asset, then seek it from the mod when the prefab is loaded.
A remaining limitation is that a component field can't store a reference to a component from another prefab. References to components on the same prefab can also fail depending on serialization order, due to how Component instances are created. I don't think this is a big issue because you would normally use GetComponent() instead of storing it from the editor, anyway. What's important is that the actual instance is correctly recreated, then references can be easily retrieved from Start().
Something else to keep in mind is that FullSerializer …
=> Improvements for ImportedComponentAttribute 

Assets/Scripts/Game/AmbientEffectsPlayer.cs
Water sound now played 3D at a point on the water surface
Ambient sounds played 3D around the player
The water sound was already fake 3D but I had put a TODO for making it actual 3D.
The ambient sounds seem to have been 2D on purpose but I think 3D sounds better. It comes from a random direction around the player now. Let me know if you like it or you want them to stay 2D.
Cleanup:
Merge nested if statements
Remove redundant yield break
Remove unneeded variable for classic update loop
Use const keyword
Remove unused variable assignments
Add contributors
Add end-of-file newline
=> Ambient sound cleanup and made sounds 3D

Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs
Addresses issue described here:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1535
=> Apply proficiency flags to custom classes

Assets/Scripts/Internal/DaggerfallAction.cs
Partway fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1545.
This fixes 2) and fixes 1) as far as only putting "casterOnly" spells on the player.
To complete the fix, we need to shoot non-casterOnly spells at the player from the triggering object, at the strength of the player's level. Interkarma I think you would know better how to do that. Would you like to finish out this fix by implementing that?
For 2), in classic a counter gets set to 1000 when triggering a spell trigger, then it is lowered by an amount on each trigger. After getting <= 0 the spell fires again. I think the amount may vary by FPS. I matched the amount so that the banner in Scourg Barrow triggers every 22 clicks, which is what I was getting in testing classic.
Attaching a video of Direnni Tower trap …
=> Make triggered spells closer to classic

Assets/Scripts/Game/TransportManager.cs
Bug introduced by 60d083e
See https://forums.dfworkshop.net/viewtopic.php?f=27&t=1293&p=17954#p17954
=> Fix spurious horse sound in TediousTravel mod

Assets/Game/Addons/UnityConsole/Console/Scripts/ConsoleUI.cs
Bug report:
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1544
=> Limits console output string from growing too large for TextMesh

Assets/Scripts/Game/DaggerfallMissile.cs
Generally fixes the remaining issue for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1235 of the arrows shot at extreme angles not looking like they come from the right spot. If you look completely up or down (probably very rare) it's still slightly off, but I think maybe that's an issue/limitation of the main camera or something as that is what I am using for positioning the arrow spawn now (rather than the player location).
Arrows do hit at extreme angles so that part of the bug report is not an issue, and I think it can be closed.
Also did a light cleanup of DaggerfallMissile.cs.
Add contributor
Add end of file newline
Fix variable shadowing
Remove whitespace
Remove unneeded boolean
Fix arrows to look correct when shot by player
=> DaggerfallMissile cleanup, fix arrow spawn

Assets/Scripts/SettingsManager.cs
Bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=1339
=> Persist EnableModernConversationStyleInTalkWindow setting

Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
https://forums.dfworkshop.net/viewtopic.php?f=24&p=17866#p17866
=> Adds travel map settings to save state & sets travel map settings from load data

Assets/Scripts/Internal/DaggerfallBillboardBatch.cs
Fixes afternoon billboards shadows, could it be that simple?
Bug report https://forums.dfworkshop.net/viewtopic.php?f=24&t=653
=> fix afternoon billboards shadows

Assets/Scripts/API/BookFile.cs, Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/Scripts/Game/Items/ItemBuilder.cs
Also added book replacement check to the item MCP for author. I considered moving this check inside BookFile class so it didn't need to be done in every place the class is used, but there may be a good reason this wasn't done so I chose to leave it alone.
=> Calculate book values like classic

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/Scripts/Utility/GameObjectHelper.cs
Also adds ability to ignore an allocated room for resting in bed clicked on.
See https://forums.dfworkshop.net/viewtopic.php?f=22&t=1581 for more discussion.
=> Add ability to add activations to models by registering custom actions

Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs
Fixes issue raised in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1578
=> Fix trying to find undiscovered locations from notebook

Assets/Scripts/Game/Items/ItemBuilder.cs
See https://forums.dfworkshop.net/viewtopic.php?f=24&t=1532
=> Fix for arrows with material set when it should not be

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBookReaderWindow.cs
=> add mousewheel support to books

Assets/Scripts/Game/FPSWeapon.cs
* Mirror texture rect when required.
* Use texture key instead of string for dictionary.
=> TextureReplacement: Improvements for FPSWeapon

Assets/Resources/Post-Processing.asset, Assets/Scenes/DaggerfallUnityGame.unity, Assets/Scripts/Game/WeatherManager.cs
- WeatherManager class uses different fog settings for different weather types now (fog mode, density, etc. stored per weather type now)
- "set_weather 3" now works again
=> fixed fog settings (WeatherManager class related)

Assets/Scripts/Game/UserInterfaceWindows/CreateCharRaceSelect.cs
AudioSource don't handle asynchronous loading of modded sounds
https://forums.dfworkshop.net/viewtopic.php?f=14&p=18441#p18441
=> Use DaggerfallAudioSource during race choice

Assets/Resources/Post-Processing.asset, Assets/Scenes/DaggerfallUnityGame.unity, Assets/Scripts/Game/WeatherManager.cs
introduced bool excludeSkybox to FogSettings struct
dfunity vanilla skybox should now work for all weather types
=> hopefully fixes the issues with vanilla skybox for other weather types than sunny

Assets/Scripts/Game/PlayerEnterExit.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1630.
=> Stop pending holiday text if location changes

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs, Assets/StreamingAssets/Text/ClassicEffects.txt
Fixes: https://forums.dfworkshop.net/viewtopic.php?f=28&p=18606
=> Fix casting spells with no spellbook

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/DaggerfallUIMessages.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs, Assets/Scripts/Game/UserInterface/ListBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs.meta
Using standard list picker window rather than implementing the small list from the old banner UI mode. I think this is better, and less work since it's reusing the existing component. We can revisit if there are many who want the UI as classic for this.
=> Add use magic items list picker

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
If my understanding of the RaceTemplate class is correct then this should include bonuses from being a vampire or lycanthrope.
=> Add racial bonuses to character history popup

Assets/Scripts/Game/EnemySounds.cs, Assets/Scripts/Game/Entities/DaggerfallEntityBehaviour.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/WeaponManager.cs
Fix for https://forums.dfworkshop.net/viewtopic.php?f=24&t=1637
=> Guard improvements

Assets/Scripts/Game/SetupDemoEnemy.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=329.
I just got this through trial and error, but it doesn't seem to cause any problems.
=> Adjust large colliders to fit through doors

Assets/Game/Addons/ModSupport/Mod.cs, Assets/Game/Addons/ModSupport/ModLoaderInterfaceWindow.cs, Assets/Game/Addons/ModSupport/ModTypes.cs
Changing alignment from center to left for the mod list as requested on the forum.  
Also marks idfmod_serializable & SetupPrefabHelper() as obsolete so they can be removed in the future.
=> Changes alignment for mod list & add Obsolete attribute

Assets/Scripts/Game/TalkManager.cs
Addresses issue discussed in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1500&start=10
Adds a random number (0-15 inclusive) to the reaction rating so that not all NPCs will refuse to give info if the base reaction number is below zero.
=> Make NPC reaction rolls semi-random

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1654&sid=0f15b83fe6a93233f16a469d58675e9e
=> Fix going to prison for 0-day sentences

Assets/Scripts/Game/ExteriorAutomap.cs
described in https://forums.dfworkshop.net/viewtopic.php?f=24&p=19244#p19244)
=> fix for issue with classic savegame import and exterior automap

Assets/Scripts/Game/UserInterface/SpellIconCollection.cs
See discussion for  #1139.
I also disabled mipmaps, is this ok?
=> Use correct format for ICON00I0.IMG when compression is enabled

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Learned some Unity, nothing fancy
=> refacto: simplify control keys check in stack splitting

Assets/Scripts/Game/EnemySenses.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1714&sid=93d4628dc960c2d72d6fa9689c231a6a.
Thanks Hazelnut and Pango for noticing it.
=> Fix prev. target overriding non-hostile mode

Assets/Scripts/Terrain/TerrainHelper.cs, Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
Only a tiny improvement but still worthwhile since it iterates a large number of times.
Also tidied the checks code in mesh replacement.
=> Optimise LayoutNatureBillboards loop

Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
* Fixed an issue where serialized data was unnecessarily created for prefab children.
* Added a null check for parent components when children need to be deserialized.
=> Fixes for ImportedComponentAttribute

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
@petchema Sorry I didn't like the changes you made, so this PR is the way I would like to change it instead and supercedes #1174. I hope you don't mind, I mean no disrespect - your contributions are very valuable.
Anyway, you definitely demonstrated that I'm bloody awful at getting around to stuff I don't personally care about... :embarrassed: I honestly had meant to get around to this.. at some point before the heat death of the universe.
Anyway I've tested at 320x200 and up, but your feedback is welcome.
=> Make journal notebook dialog boxes more compact (supercedes #1174)

Assets/Scripts/Internal/DaggerfallSky.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?p=19983#p19983
The root issue seems to be that transform.eulerAngles.y can become slightly negative (not by much, I've seen up to -0,000563718).
=> Fix sky blind spot

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1756
=> Prevent wagon access from inside dungeons during identification

Assets/Scripts/Game/Items/ItemHelper.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1738
=> don't make sure the player has a spellbook

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/GameManager.cs
Allows for fast travel, sleeping,... when only pacified NPCs are around
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1752
=> do not always count pacified NPCs toward enemies

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
@Interkarma @Lypyl are you ok with this change? I moved the region overlay to its own panel to draw it above the map texture at any resolution. I think we will also need to allow high resolution overlays but the default one should be available as a fallback. It might even look fine as is with texture filter. Should i link it to `Settings.GUIFilterMode`?
=> TextureReplacement: Support for TRAV0I00.IMG

Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUseMagicItemWindow.cs, Assets/StreamingAssets/Text/SpellmakerUI.txt
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1755
=> don't freeze when you have no usable magic item

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Utility/AssetInjection/Components/CustomDoor.cs, Assets/Scripts/Utility/AssetInjection/Components/CustomDoor.cs.meta, Assets/Scripts/Utility/RMBLayout.cs
A pretty basic implementation, but should allow people interested in this field to experiment a bit with towns modding.
=> Initial implementation of custom doors for buildings

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs, Assets/Scripts/Utility/AssetInjection/TextureReplacement.cs
=> TextureReplacement: Support for FMAPXXXX.IMG

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallListPickerWindow.cs
Addresses the bug described in https://forums.dfworkshop.net/viewtopic.php?f=24&t=1792
=> Adjust listbox row count for small font

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Players not familiar with the concept can be very confused
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&p=21119#p21119
=> warn the player when paid with a letter of credit

Assets/Scripts/Game/UserInterface/PopupText.cs
Make popup text scroll up smoothly instead of line by line; The text stays easily readable while being removed from screen.
=> popup text smooth scrolling

Assets/Scripts/Game/UserInterfaceWindows/CreateCharSpecialAdvantageWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallListPickerWindow.cs
Per @petchema 's suggestion, using handy constructor parameters that I previously didn't notice.
=> Use cleaner solution to list picker item count issue

Assets/Scripts/Game/EnemyMotor.cs
Adds strafing to enhanced combat AI. I've tried to keep it somewhat subtle, so that it will look good and not too game-like. Used in both melee and ranged combat.
Also, this addresses an issue with enemies turning their back to their opponent too much in combat due to trying to path around an obstacle when backing up. Although it looked kind of good like they were "running away" after being backed against a wall it happened a bit too much and would only be appropriate for a weaker or more cowardly combatant, not for all cases. They can now get out of this situation by strafing, which allows them to keep facing their opponent.
=> Implement strafing for enhanced combat AI

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Resets the class creator to its original state when restarting character creation. Prevents bugs associated with persisting class creator window.
=> Re-instantiate class creator when starting over

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
Put all the logic to display information about current spell (or nothing if none can be selected) to UpdateSelection()
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1860
=> spellbook cleanup

Assets/StreamingAssets/Quests/A0C00Y17.txt
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1856
=> fix typo in A0C00Y17 quest

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1856&p=21577
=> fix shoplifting messages keys

Assets/Scripts/Game/PlayerEnterExit.cs
I used **LogException()** which is quite handy when testing from the editor.
=> Log exception thrown when failing with "nothing of value" message

Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
Very low AdvancementMultiplier in particular is game breaking
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1882
=> check that the advancing dagger is not too high or too low

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
.x vs .y buglet
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1855
=> fix "floating" house labels when free scale is enabled

Assets/Scripts/Game/GameManager.cs
Fixes https://forums.dfworkshop.net/viewtopic.php?f=24&t=1913&sid=e75c962cc2258a847352de0187e7caf1
=> Make classic update false when game is paused

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Entities/EnemyEntity.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/SoulTrap.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs, Assets/Scripts/Game/UserInterface/ItemListScroller.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Implements the Oghma Infinium. It was harder than I expected because there were bugs to chase down to get the correct texture and inventory behavior. (Being assigned by the data in MAGIC.DEF to the books group was interfering with these things).
I noticed problems with the leveling screen. I think they are the result of a recent commit.
https://github.com/Interkarma/daggerfall-unity/commit/b0f6f52bd3c7d99ff7e6873e18807f6c3f29be11#r32858800
Use `addArtifact 5` at the console for easy testing.
=> Implement Oghma Infinium and Azura's Star

Assets/StreamingAssets/Quests/_TUTOR__.txt
=> remove a missed reference to old interface icons

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
Addresses oversight pointed out in
https://github.com/Interkarma/daggerfall-unity/commit/12fda4e458b838b7d7bb0583169875ee6e2d00f9#r32910451
=> Use oghmaBonusPool

Assets/Scripts/Game/SetupDemoEnemy.cs
https://forums.dfworkshop.net/viewtopic.php?f=24&t=1425
Should prevent both rats walking on each other and player walking over them.
=> Prevent rats being walked upon

Assets/Scripts/Game/UserInterface/HUDVitals.cs
Fixes a bug when the effect of some healing was still animated at the time of resetting (say, you where trying to heal yourself when you got slain and reloaded a game).
Also, cleanups
PositionIndicators() side effects are unlikely to change from one Update() to the next, is it worth optimizing?
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=1880#p22163
=> set *BarGain vital indicators in SynchronizeImmediately

Assets/Scripts/Game/Utility/PopulationManager.cs
distanceToPlayer was updated too late, for recycled npcs that can make a lot of difference!
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1997
=> fix mobile town NPCs spawning in front of player

Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/GameManager.cs
@petchema brought this to my attention. Looks like I put an OR where an AND should have been.
=> Fix typo in AreEnemiesNearby

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Allow to sell horses and wagons.
If you have items in your wagon, one arbitrary wagon cannot be sold.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=23&t=697
=> Sell horses and wagons

Assets/Scripts/Game/MagicAndEffects/Effects/Mysticism/Teleport.cs, Assets/Scripts/Game/PlayerEnterExit.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs
Everything's in the title, when teleporting into a dungeon from some
other place, import dungeon enemies (and loot).
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=1661
=> import enemies and loot on teleport in dungeon

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
**Background**
There's a base time for each item, proportional to the amount of damage it took. Then the time for the longest item to repair is increased by half the time taken by all the others (rationale, I assume, is that
while working on other items, work on this item is slowed down by half. On the other hand all other items are worked on in parallel, mmh). Anyway, it gives some incentive to repair several items at once, yet it's not totally for free.
Now what happens if you add items when some repairs are already ongoing? 
Implementation in DFU just reevaluates everything together; So old repair times may adjust if you add items to the mix (I've checked that classic does that too), and in the end you get the same times as if you put everything to repair at once, so it seems it's not …
=> fix negative repair times when removing other repaired items

Assets/Scripts/Game/EnemyAttack.cs, Assets/Scripts/Game/EnemyMotor.cs, Assets/Scripts/Game/WeaponManager.cs
-Cleanup-
Use auto properties
Divide long Move() function into smaller functions
Add/correct comments, renaming
-Fixes, improvements-
Allow backup for out-of-pitch target to move smoothly
Allow knock-back for paralyzed enemies
Knocked-back flyers will drop while being knocked back
Use direction, not movement, consistently with obstacle-check functions
Refined obstacle and fall detection
Smaller radius used when checking for arrow shot. Will shoot over tables
now.
Account for controller changing height when colliding with objects by
storing original height
Stop flyers from flying near floor during combat
Flyers/swimmers/levitating enemies check up and down when detouring
=> Cleanup and fixes for EnemyMotor

Assets/Scripts/Game/DaggerfallBankManager.cs
Loans were due immediately
Bug was not obvious because displayed due date does not show the year
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2072
=> loans to be repaid one year later

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs, Assets/Scripts/Internal/DaggerfallBookshelf.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
=> Fix unhandled map items

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Addresses issues described in https://forums.dfworkshop.net/viewtopic.php?f=24&t=2075 and https://forums.dfworkshop.net/viewtopic.php?f=24&t=2051.
=> Fix navigation in character creator

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs, Assets/Scripts/Utility/MacroHelper.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Note: will not be correct if CalculatePlayerLevel() formula is changed by mods.
=> Add level progress dialog

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Special/MasqueOfClavicusEffect.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Special/MasqueOfClavicusEffect.cs.meta, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/TalkManager.cs
I made the reputation boost +20.  Please let me know if this should be higher for gameplay purposes or if there is a value that is more Classic-accurate.
=> Implement Masque of Clavicus effect

Assets/Scripts/Game/UserInterface/Panel.cs, Assets/Scripts/Game/UserInterface/ScreenComponentCollection.cs
This allows foreach(var component in components) to properly infer the type.
=> Implement IEnumerable<BaseScreenComponent>

Assets/Scripts/Utility/MacroHelper.cs
Gender generated when expanding %n in quests was not kept. Fixed it by using DFRandom.
=> Fix macro %n gender generation in quests

Assets/Scripts/Game/ExteriorAutomap.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs
fixed this in exterior automap code - against my initial intuition it turned out to be the right place to make those changes
=>  fixed town map positioning (player marker positioning) for custom 1x1 locations

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Forums;
https://forums.dfworkshop.net/viewtopic.php?f=12&t=2098&p=26161#p26161
=> Fix dungeon exit wagon access upon first inventory use

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
While removing items from my wagon:
NullReferenceException: Object reference not set to an instance of an object
at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow.RemoteItemListScroller_OnItemClick (DaggerfallWorkshop.Game.Items.DaggerfallUnityItem item) [0x00000] in <filename unknown>:0 
at DaggerfallWorkshop.Game.UserInterface.ItemListScroller.ItemButton_OnMouseClick (DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent sender, Vector2 position) [0x00000] in <filename unknown>:0 
at (wrapper delegate-invoke) DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent/OnMouseClickHandler:invoke_void__this___BaseScreenComponent_Vector2 (DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent,UnityEngine.Vector2)
at …
=> More null checks

Assets/Scripts/Game/Utility/DaggerfallDistance.cs
Prefix and suffix costs were totally dissymmetric if the match was a prefix or suffix of a word; Make those computations more symmetric, just taking into account costs of prefix/suffix letters and full words.
Also, overall make prefixing and suffixing cheaper relative to letter edits, so that the search behave slightly more like a substring search.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=7&p=26334#p26333
=> DaggerfallDistance fix and small adjustments

Assets/Scripts/SettingsManager.cs
Changes to AssetInjection option from game UI weren't correctly saved to ini file.
=> Fix AssetInjection setting save

Assets/Scripts/Game/UserInterfaceWindows/CreateCharNameSelect.cs
Enable Khajiit names to be randomly generated. However, #1361 should be tested and merged before this PR or Khajiit will be given default Breton names.
=> Enable Khajiit random name generation on character creation.

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Guilds/Services.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
As discussed here:L
https://forums.dfworkshop.net/viewtopic.php?f=23&t=2336&p=27331#p27331
=> Fix for non-temple guild greeting messages & provide reference to calling window to custom services

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs, Assets/StreamingAssets/Text/GameSettings.txt
Addresses issue #1377 
Should be checked for DB and for Temple of Arkay by bug author @Hellmasker10.
=> Implement soulgem selling service

Assets/Scripts/Game/Questing/Place.cs, Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Internal/DaggerfallDungeon.cs
Fix %loc expansion failures as reported here: https://forums.dfworkshop.net/viewtopic.php?f=5&p=27843#p27843
I also filtered NPC names in topics so you shouldn't be able to ask people anymore about themselves both in "Where is people" and "Tell me about" question categories. The filter is a little ugly at the moment but at least it's working.
=> Fix %loc macro expansion in castles

Assets/Scripts/Game/Automap.cs, Assets/Scripts/Game/ExteriorAutomap.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
changed schema in DaggerfallUI.txt to
schema: *key,$text
added quotes for all strings in the file
=> migrated remaining text in automap and exterior automap to text data base

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/Scripts/SettingsManager.cs, Assets/StreamingAssets/Text/GameSettings.txt
Also refined layout a little, moved both repair options to be adjacent and made layout more balanced
=>  Add loiter limit setting

Assets/Scripts/Game/UserInterfaceWindows/CreateCharSummary.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartNewGameWizard.cs
Allow last minute character modifications in the summary screen (last character creation screen):
- Name
- Face
- Rebalance status bonus points
- Rebalance skills bonus points
- Reflexes
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2459
=> allow character modifications in summary screen

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2499
=> don't display find button on world map upon first use

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs
Allow paintings to sell in pawn shops
Remove single ingredients from wagon as well
=> Bugfixes#2

Assets/Scripts/Game/UserInterfaceWindows/CreateCharCustomClass.cs
=> visually clamp difficulty dagger to gauge

Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
So players can easily keep track of where their owned properties are.
=> Add journal message when getting a house

Assets/Scripts/Game/Items/DaggerfallUnityItemMCP.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
=> Show the author as unknown for broken/missing books.

Assets/Scripts/Utility/RDBLayout.cs
Tested and confirmed to solve issue #1421
=> Add "CAV" to ActionDoor check for hidden cave doors

Assets/StreamingAssets/Quests/_TUTOR__.txt
Not as good as having macros to use current keybindings instead, but I didn't manage to implement that.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=4&t=429&p=27238#p27238
=> adjust changed default keybindings in tutorial

Assets/Scripts/Game/Guilds/KnightlyOrder.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Forums:
https://www.reddit.com/r/daggerfallunity/comments/cuvbks/bug_knights_of_dragon_clicked_receive_armor_didnt/
Game save for testing:
[SAVE361.zip](https://github.com/Interkarma/daggerfall-unity/files/3537545/SAVE361.zip)
=> only acknowledge received armor after one is picked

Assets/Prefabs/Player/PlayerAdvanced.prefab, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerMotor.cs, Assets/Scripts/Game/TransportManager.cs
I plan to adjust the horse sounds too as they're currently far too loud but I currently can't figure out why they're being set by unity... posted a cry for help on the forums.
=> Make cart move at correct slower speed

Assets/Scripts/Game/Entities/PlayerEntity.cs
Filter some factions which should not be included in rumor mill. Fix https://forums.dfworkshop.net/viewtopic.php?f=5&t=2629
=> Remove some factions from rumor mill

Assets/StreamingAssets/Quests/B0C00Y05.txt
Fix for https://forums.dfworkshop.net/viewtopic.php?f=29&t=2411&start=10
=> Don't end quest before revealing location if needed.

Assets/StreamingAssets/Quests/A0C00Y00.txt, Assets/StreamingAssets/Quests/C0B3XY09.txt, Assets/StreamingAssets/Quests/N0B10Y03.txt
Fixed unsupported usages of "until" idiom where a condition should unset a variable.
See https://forums.dfworkshop.net/viewtopic.php?f=29&t=2628#p30745 for background.
=> Fixed unsupported usage of "until" idiom

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs
A little cosmetic change. This does not match classic but guilds are not stores...
=> A closed guild now display "Guild is closed." message.

Assets/Scripts/Game/MagicAndEffects/Effects/Special/LycanthropyEffect.cs
I set it to reduce max health by 24 points per day, please adjust to taste ;)
I also added removal of the max health limit when feeding or being cured.
=> Fixes for #1374 and lack of max health restore on cure and feed.

Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/PlayerMouseLook.cs, Assets/Scripts/Game/TransportManager.cs
- Allow can-run delegate to be contributed
- Allow pitch limiting for mouse look
- Allow default horse graphics to be disabled
=> Add mod facilities for horse riding mods

Assets/Scripts/Game/Formulas/FormulaHelper.cs
Another contributor pointed this out to me.  Honestly not sure what possessed me to write something this awful.
=> Refactor ugly if statement

Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Utility/AssetInjection/TextAssetReader.cs
Support changes to ItemTemplates data, requested by @ajrb.
=> Import contributes to ItemTemplates from mods

Assets/Scripts/Game/BuildingDirectory.cs, Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs, Assets/Scripts/Internal/PlayerGPS.cs
Doesn't match classic exactly.
Fixed house ownership to work with new discovery system, at present if players buy a house it's not shown on the map.
=> Expand houses offered for sale

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
Malacath quest name was wrong as mentioned on the forums: https://forums.dfworkshop.net/viewtopic.php?f=25&t=2684
=> Fix Malacath quest name

Assets/StreamingAssets/Text/GameSettings.txt
Fix some random typos I noticed in the game settings. I'm new to github, please make sure that I'm editing the right file and didn't break anything.
=> Fix typos in game settings

Assets/Scripts/Game/PlayerMouseLook.cs
Refinement of pitch limit setting for enhanced horseriding implementation.
=> Ensure that player pitch is within limits

Assets/StreamingAssets/Quests/A0C00Y16.txt
_yes_ was started by _S.22_ but being unset again by its when task
=> Fix for A0C00Y16

Assets/Scripts/Game/TalkManagerMCP.cs
While very rare, %g3 is also used when asking for work.
=> Expand %g3 macro when asking for work

Assets/Scripts/Game/TransportManager.cs
Needed for next version of enhanced horse riding to allow hi-res graphics
=> Expose horse animations frame index for mods

Assets/Scripts/Game/UserInterface/HUDActiveSpells.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=23&t=2869
=> Remove black background behind HUD active spells

Assets/Scripts/Game/EnemySenses.cs, Assets/StreamingAssets/Quests/K0C00Y05.txt, Assets/StreamingAssets/Quests/K0C00Y06.txt, Assets/StreamingAssets/Quests/S0000012.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Sorry, this PR has some junk (2a7c0c5 and 74eb689) based on my master branch and I don't know how to wipe them out. This is intended to only comment out k0c00y06 in QuestList-Classic. If I've done it badly you can reject it.
=> Disables k0c00y06

Assets/Scripts/Game/EnemySenses.cs
Requires a custom quest mod, which is not implemented in DFU core, to take advantage
=> Adds possibility of quest NPC infighting

Assets/Scripts/Game/TalkManager.cs
(fixes issue https://forums.dfworkshop.net/viewtopic.php?f=24&t=2730)
=> fix for incorrect residence name resolving for quest person resources

Assets/Scripts/Game/UserInterface/HUDQuestDebugger.cs
And that's all this does.
It does not increase the label limits, it just doesn't show any labels above the limit.
Fix for https://forums.dfworkshop.net/viewtopic.php?f=25&t=2780
=> Guard against array index out of bounds.

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallGuildServicePopupWindow.cs
Also prevent loading quests twice.
https://forums.dfworkshop.net/viewtopic.php?f=5&t=2790&sid=46b0dbc40ac30f112d73be0fefb16002
=> Fix mismatch between questPool and questPicker.ListBox.

Assets/Scripts/Game/PlayerActivate.cs
Added an interface which can be used to subscribe to custom player activations for any object. I'm personally going to use it for my harvesting mod where i need to detect when a crop is picked.
=> Add IPlayerActivable interface for custom activations

Assets/Scripts/Game/Questing/QuestListsManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestOfferWindow.cs, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Applied M (male) to all quests with "group Questor male" in quest list
Should fix #1542 to match classic. Needs some checking by ferital.
=> Add gender filtering for social quests

Assets/Scripts/Game/Questing/Actions/CreateFoe.cs
Forums:
https://forums.dfworkshop.net/viewtopic.php?f=25&t=2556&p=32825#p32825
=> Do not delay quest create foe by one spawnInterval

Assets/Scripts/Game/Guilds/FightersGuild.cs, Assets/Scripts/Game/Guilds/Guild.cs, Assets/Scripts/Game/Guilds/IGuild.cs, Assets/Scripts/Game/Questing/Item.cs, Assets/Scripts/Game/Questing/Parser.cs, Assets/Scripts/Game/Questing/QuestListsManager.cs, Assets/Scripts/Game/Questing/QuestMachine.cs
Fix gold rewards for guild quests, following TODO notes with faith they are correct. 
Ensure faction id is availiable for gold calc and implement Fighters Guild benefit of increased rewards
=> Fix gold rewards

Assets/StreamingAssets/Quests/R0C11Y26.txt, Assets/StreamingAssets/Quests/R0C11Y28.txt
Fixes https://www.reddit.com/r/Daggerfall/comments/dje4ki/got_an_unremovable_200_kg_dead_body_in_my/
=> Prevents holding on to dead body in two R quests

Assets/Scripts/Game/TalkManager.cs
No more potential questors in  "House for sale" when asking NPCs for available work.
=> Remove house for sales from the list of questors locations

Assets/Resources/PotionRecipes.txt
Fixes a stray typo missed in earlier pull request
=> fix minor typo

Assets/Scripts/Game/Guilds/GuildManager.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Thaumaturgy/Identify.cs, Assets/Scripts/Game/Questing/Item.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Fix identify spell trade window construction call
Fix ship purchase popup window (fixes #1579)
Fix gold rewards for non-guild NPCs with faction ids - hopefully this will fix the 1gp bug, but I don't have a save to test this with
=> Fixes for DFU 0.10.8

Assets/Scripts/Game/Questing/QuestResource.cs
The "named" version of anyInfo is not used in any current quests but if we support it it should work correctly.
=> Small copy/paste mistake fix.

Assets/Scripts/Game/MagicAndEffects/Effects/Special/MasqueOfClavicusEffect.cs
Thanks to @df-ferital for reverse-engineering the formula.
=> Use correct formula for Masque of Clavicus

Assets/Scripts/Game/Questing/Item.cs
Please someone check this before it goes out in a build. Ta.
Sorry for taking so long @Interkarma.
=> Fix 1gp reward bug, properly this time!

Assets/StreamingAssets/Quests/C0C00Y10.txt
=> Quest fix Nov 2019

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs
Just a little update to the add_all_equip command
=> Add ability to spawn all magic weapons for testing mods

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/UserInterface/HUDActiveSpells.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/SettingsManager.cs, Assets/StreamingAssets/Text/GameSettings.txt
Allow to select between different (de)buff icons layouts
=> (de)buff icons sizes and positions

Assets/Scripts/Game/UserInterface/FacePicker.cs
Reuse code from EscortingNPCFacePanel
=> fix facepicker aspect ratio

Assets/Scripts/Game/PlayerFootsteps.cs, Assets/Scripts/Game/WeatherManager.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3108
=> don't change footstep sounds during winter under snow-free climates

Assets/StreamingAssets/Quests/K0C30Y03.txt, Assets/StreamingAssets/Quests/S0000009.txt
They display as (Unicode) garbage
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3095
=> remove TAB characters from quest messages

Assets/Scripts/Game/EnemyDeath.cs, Assets/Scripts/Internal/AudioSourceExtensionMethods.cs, Assets/Scripts/Internal/DaggerfallAudioSource.cs
Add volume setting and asynchronous loading
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3078
=> wrap AudioSource.PlayClipAtPoint

Assets/Scripts/Game/SetupDemoEnemy.cs
In frame 0 wings are in high position, assume body is the lower half
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2898
=> prevent flying enemies from flying too low

Assets/Scripts/API/MapsFile.cs, Assets/Scripts/API/PakFile.cs
This supports the ability to add new locations to the world data.
See https://forums.dfworkshop.net/viewtopic.php?f=22&t=3011 for more discussion.
=> Add ability for mods to update the politic and climate for map pixels

Assets/StreamingAssets/Quests/A0C00Y00.txt, Assets/StreamingAssets/Quests/A0C00Y06.txt, Assets/StreamingAssets/Quests/A0C00Y07.txt, Assets/StreamingAssets/Quests/A0C00Y08.txt, Assets/StreamingAssets/Quests/A0C00Y10.txt, Assets/StreamingAssets/Quests/A0C00Y11.txt, Assets/StreamingAssets/Quests/A0C00Y12.txt, Assets/StreamingAssets/Quests/A0C00Y14.txt, Assets/StreamingAssets/Quests/A0C00Y15.txt, Assets/StreamingAssets/Quests/A0C00Y16.txt, Assets/StreamingAssets/Quests/A0C00Y17.txt, Assets/StreamingAssets/Quests/A0C01Y01.txt, Assets/StreamingAssets/Quests/A0C01Y03.txt, Assets/StreamingAssets/Quests/A0C01Y06.txt, Assets/StreamingAssets/Quests/A0C01Y09.txt, Assets/StreamingAssets/Quests/A0C01Y13.txt, Assets/StreamingAssets/Quests/A0C0XY04.txt, Assets/StreamingAssets/Quests/A0C10Y02.txt, Assets/StreamingAssets/Quests/A0C10Y05.txt, Assets/StreamingAssets/Quests/A0C41Y18.txt, Assets/StreamingAssets/Text/ClassicEffects.txt
Notes:
-lots of missing commas or apostrophes that are technically necessary, and many commas where a period should be. Proper punctuation helps readability.
-about 10% of the time, two spaces followed a period. This inconsistency has been removed in favor of one space everywhere. The two-space thing is an old style with monospaced typewriters that has fallen out of favor in modern text.
-ellipses did not have consistent spacing
-there is an awkward lack of contractions, but only in a few instances does it sound so bad that I thought it warranted a change. "It is you!" is one example.
-there are a few macro fixes of %g2 and %g3 being swapped
-I am a strong writer and have a BA in English. Please discuss or post links to grammar articles if you think there is an error here.
=> Commoner Quests:  errors and inconsistencies in punctuation, grammar, spelling, spacing

Assets/Scripts/External/FPSDisplay.cs
Forums: https://www.reddit.com/r/daggerfallunity/comments/ec7vsy/i_think_i_found_a_bug/
=> Fix FPS display (tdbg) when game is paused

Assets/Scripts/Game/Serialization/SerializableStateManager.cs, Assets/Scripts/Terrain/StreamingWorld.cs
This was quite a mission doing this. See thread here for my journey: https://forums.dfworkshop.net/viewtopic.php?f=20&t=3213
The fix I made to StreamingWorld.InitPlayerTerrain() may break other stuff. I'm really not sure about it so would be good to have opinions from others.
=> Corpse cleanup for player owned places

Assets/StreamingAssets/Quests/B0B71Y03.txt, Assets/StreamingAssets/Quests/C0B00Y01.txt, Assets/StreamingAssets/Quests/C0B3XY09.txt, Assets/StreamingAssets/Quests/N0B11Y18.txt, Assets/StreamingAssets/Quests/O0B10Y05.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Much of this is enabling working quests and fixing the Questlist, which I left in a brutal state.
=> Classic quest fixes, Dec 2019

Assets/Scripts/Game/StaticNPC.cs
See https://forums.dfworkshop.net/viewtopic.php?f=5&t=3048
=> Add location index to ensure nameseed is unique

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Also move all text into table file
=> Shorten labels for rename and delete to fit using non-SDF fonts

Assets/StreamingAssets/Quests/S0000018.txt
Makes reading the letter a 50% chance of reading one line
=> <---> separator bug in S00000018

Assets/Scripts/Game/Player/ClimbingMotor.cs
See https://forums.dfworkshop.net/viewtopic.php?f=5&t=3235
=> Fix the addition of initial climbing skill check

Assets/Scripts/Internal/DaggerfallStaticDoors.cs, Assets/Scripts/Utility/GameObjectHelper.cs
Improvement over 5b1d37a4b992f61cad1d2400fbca2ca0f218f312
It needs more testing, are there examples of cases that required the fix above?
Forums: https://forums.dfworkshop.net/viewtopic.php?f=27&p=37823#p37823
=> adjust door thickness

Assets/StreamingAssets/Quests/Q0C0XY02.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
All witch quests tested and working
=> Year-end quest fixes

Assets/Scripts/Utility/TextureReader.cs
Had to replace test on isEmissive with resultEmissive l.285 because we can have one but not the other, I'm not sure it's to be expected.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2917
=> complete all archives containing emissive textures, not only lights

Assets/Scripts/Utility/TextureReader.cs
Fix for forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3289
=> emissive maps: support more lights

Assets/Scripts/Game/UserInterfaceWindows/CreateCharClassQuestions.cs
Addresses the issue discussed in https://forums.dfworkshop.net/viewtopic.php?f=24&t=3316
=> Use correct indices for animations

Assets/Scripts/Game/EnemyMotor.cs
While hard to reproduce, I've seen thieves bleed from a fall, so I assume fall damage exists for enemies too.
It's even harder to know what formula is used (beside decompilation maybe), for I've used the exact same formula as for player fall damage.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3353#p39126
=> enemies fall damage

Assets/StreamingAssets/Quests/$CUREWER.txt
Region in letter would change when player moved. Now it'll be the region where letter is received only.
=> Fixes region update in $CUREWER

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMessageBox.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=12&t=3332
=> [RFC] DFUMessageBox.clickAnywhereToClose using any button but swing weapon one

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Is there a way to embed a line return in a message instead of having to use several messages to match classic text formatting?
=> adjust max loiter time message to setting

Assets/Scripts/Internal/DaggerfallMobileUnit.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=2961
=> fix spell casting female spellsword size

Assets/Scripts/Game/MobilePersonMotor.cs
Use raycast as an additional check to localWeight == 0
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=792
=> prevent mobile NPCs from entering stairs

Assets/Scripts/Game/AmbientEffectsPlayer.cs
Around cemeteries, classic plays creepy bird calls infrequently (once per minute on average), and howlings even less often (about 1/4th of the time).
During the day it happens on top of normal bird calls, so it's another layer of ambient sounds.
=> Cemetery ambient sounds

Assets/StreamingAssets/Quests/C0B00Y02.txt, Assets/StreamingAssets/Quests/K0C00Y04.txt, Assets/StreamingAssets/Quests/R0C30Y25.txt, Assets/StreamingAssets/Quests/R0C4XY23.txt, Assets/StreamingAssets/Quests/R0C60Y24.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
C0B00Y02 was complex enough to merit a whole variable/structure rewrite. Only a few quests remaining now: A0C00Y16, K0C00Y06, M0B11Y18, N0B11Y18, and S0000007.
=> Classic quest fixes, Mid-Feb 2020

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/Serialization/SerializablePlayer.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs
See https://forums.dfworkshop.net/viewtopic.php?f=24&t=2649
=> Fix covens offering different Daedra summons in the same day

Assets/Scripts/Game/Formulas/FormulaHelper.cs
Noticed this bug while looking though the code. Affects orcs and centaurs. No wonder they always felt so weak.
=> Fix equipped monster enemies always using hand to hand

Assets/Scripts/Utility/RMBLayout.cs
See https://forums.dfworkshop.net/viewtopic.php?f=24&t=3417
Only seems to be an issue when two identical blocks are next to each other in west-east direction.
=> Copy building array in block before modifying it

Assets/Scripts/Game/MagicAndEffects/EntityEffectBroker.cs
Just propagating the already passed flag to potion indexing method, pretty sure that it was just an oversight but it should be verified before merging.
=> Need to allow replacement of potion recipes for mods

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Previous PR was closed when I tried to squash my commits.
=> Change protection levels for inventory menu for modability

Assets/Scripts/Game/PlayerFootsteps.cs
Fixed from petchema's review #1718.
=> Fix water footstep playing while jumping over water

Assets/Scripts/Utility/MacroHelper.cs
Warm Ashes mod has used it I think.
=> Implement %ln macro as it was seen on stream as unhandled

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallControlsWindow.cs
(I already have the secondary keybind window finished, but I'm breaking into smaller PRs)
- Rewrote CheckDuplicates() to use a shared static helper method called GetDuplicates(), which will be used by the secondary keybind window. 
- All keybinds are shared in a static dictionary of unsaved keybinds, and updated upon save or reset to default.
- WaitForKeyPress is also static for it to be shared with the secondary keybind window.
- Fixed a bug where players could press the bottom buttons while the window is waiting for input
=> [Secondary Keybinds] Reworked controls window

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Note these changes are also in #1762 as I had to build that work on top of this.
=> Refactor combat formula to enable modding

Assets/Scripts/Game/Items/DaggerfallUnityItem.cs
Should fix the following issues:
https://forums.dfworkshop.net/viewtopic.php?f=5&t=3497
https://forums.dfworkshop.net/viewtopic.php?f=24&t=3491
=> Fix bug with breaking armor and enchanting unworn armor

Assets/Scripts/Game/Items/ItemCollection.cs
=> Don't (re)stack items during player deserialization

Assets/Prefabs/Player/PlayerAdvanced.prefab
Fix for #1420
I implemented a fix, then noticed there was 5 years old code doing the same thing, just a bit better!
=> Relocate weather particles when world offset changes

Assets/Scripts/Game/EnemySenses.cs, Assets/Scripts/Game/Questing/Actions/ChangeFoeInfighting.cs, Assets/Scripts/Game/Questing/Actions/ChangeFoeInfighting.cs.meta, Assets/Scripts/Game/Questing/Actions/ChangeFoeTeam.cs, Assets/Scripts/Game/Questing/Actions/ChangeFoeTeam.cs.meta, Assets/Scripts/Game/Questing/Actions/JournalNote.cs, Assets/Scripts/Game/Questing/Actions/PayMoney.cs, Assets/Scripts/Game/Questing/Actions/PlaySong.cs, Assets/Scripts/Game/Questing/Actions/PlaySong.cs.meta, Assets/Scripts/Game/Questing/Actions/SetPlayerCrime.cs, Assets/Scripts/Game/Questing/Actions/SetPlayerCrime.cs.meta, Assets/Scripts/Game/Questing/Actions/SpawnCityGuards.cs, Assets/Scripts/Game/Questing/Actions/SpawnCityGuards.cs.meta, Assets/Scripts/Game/Questing/Actions/UnrestrainFoe.cs, Assets/Scripts/Game/Questing/Actions/UnrestrainFoe.cs.meta, Assets/Scripts/Game/Questing/Actions/WhenPcEntersExits.cs, Assets/Scripts/Game/Questing/QuestMachine.cs, Assets/Scripts/Game/Serialization/SerializableEnemy.cs, Assets/Scripts/Game/Serialization/SerializableGameObject.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/HardStrings.cs, Assets/Scripts/Utility/MacroHelper.cs
As previously discussed here: https://forums.dfworkshop.net/viewtopic.php?f=20&t=3019
Also has some fixes for the crimes unused by classic, so the set player crime action works properly for all defined crimes.
I migrated the action code and made it align with core. Kamer has been testing them for over 2 months as he's the one who wants them for his Warm Ashes mod.
=> Ironman quest actions integrated into core

Assets/Scripts/Game/PlayerActivate.cs, Assets/Scripts/Internal/DaggerfallInterior.cs
Seems to work that way in classic, and makes that privilege actually useful.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=3502
=> Make NPCs present if you have HallAccessAnytime privilege

Assets/Scripts/Game/Items/ItemHelper.cs
I will merge this later today unless anyone objects. Thanks to Burt for spotting my typo.
=> Fix typos in registration methods

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
=> Fixed typo in usage handler and missed this reference.

Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenStrikes.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/VampiricEffect.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3593
=> restrict CastWhenStrikes enchantment to weapons

Assets/StreamingAssets/Quests/A0C00Y07.txt, Assets/StreamingAssets/Quests/B0C00Y13.txt, Assets/StreamingAssets/Quests/C0C00Y13.txt, Assets/StreamingAssets/Quests/M0B00Y15.txt, Assets/StreamingAssets/Quests/M0B11Y18.txt, Assets/StreamingAssets/Quests/M0C00Y14.txt, Assets/StreamingAssets/Quests/N0B00Y06.txt, Assets/StreamingAssets/Quests/S0000500.txt, Assets/StreamingAssets/Quests/S0000501.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Related discussions:
https://forums.dfworkshop.net/viewtopic.php?f=25&t=3473#p40923
https://forums.dfworkshop.net/viewtopic.php?f=5&t=3651&p=42749#p42745
Spawning slowed in pest quests due to some forum discussion, can't find it but every 5 seconds is too quick for novice players
=> Apr 2020 Quest Fixes

Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/Player/ClimbingMotor.cs, Assets/Scripts/Game/Player/RappelMotor.cs, Assets/Scripts/Game/Serialization/SaveLoadManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs, Assets/StreamingAssets/Text/DaggerfallUI.txt
Discussion in https://github.com/Interkarma/daggerfall-unity/commit/6a7ca24c52ec7c0cff684feab98a6c274b55b94e
=> Prevent saves while rappelling

Assets/Editor/.Schemas/ModInfo.schema.json, Assets/Game/Addons/ModSupport/ModTypes.cs
- Updated json schema that is used by some text editors to validate file.
- Do not serialize null values.
=> Update support for mod manifest file

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/Player/PlayerSpeedChanger.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/Game/Utility/StartGameBehaviour.cs, Assets/Scripts/SettingsManager.cs, Assets/StreamingAssets/Text/GameSettings.txt
You can now enable the sneak action to be toggled rather than held. Running will break you out of the sneak mode.
=> Added option to toggle sneak

Assets/Scripts/Game/UserInterfaceWindows/CreateCharSummary.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=24&t=3671
=> Prevent leaving character recap screen with unassigned bonuses

Assets/Scripts/Game/Entities/DaggerfallEntity.cs, Assets/Scripts/Game/UserInterface/PaperDoll.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Fixed strengthen armor enchantment - armor modifier is now correctly applied to player entity and correctly reflected in paperdoll
=> Strengthens/Weakens Armor bug fix

Assets/Scripts/Game/UserInterfaceWindows/CreateCharClassQuestions.cs
My current iteration of the GetHeaderIndex method is messy and hard to understand. This is mainly because I manually translated it from assembly code that may have had compiler optimizations applied to it. 
I initially left it as is for fear of breaking it. However, now that I've run it through a driver program to compare results with every possible input on my old and new versions of the method, I'm confident that this won't change functionality.
=> Refactor CreateCharClassQuestions for greater readability

Assets/Scripts/Game/InputManager.cs
=> [Joystick Controls] Added bindings for UI mouse clicks and inversions of axes

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnityMouseControlsWindow.cs
[[Image](https://imgur.com/a/emKM5QD)]
Requested by some people on Reddit a while back. Also reordered the settings to look neater.
=> Added BowDrawback and ToggleSneak settings to advanced controls window

Assets/Scripts/Game/InputManager.cs
@Interkarma - would like you to check you're okay with these changes. I can manage without them, they allow autowalking without using reflection and limiting horse strafe and backup speed.
=> Add motion limits for mods, and expose applying force publicly

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs
Because I'm tired of finding new ones I need
=> Made everything non-public protected

Assets/Scripts/DaggerfallUnity.cs, Assets/Scripts/Terrain/DaggerfallTerrain.cs, Assets/Scripts/Terrain/StreamingWorld.cs, Assets/Scripts/Terrain/TerrainTexturing.cs
Followed same pattern as TerrainSampler
=> Create ITerrainTexturing and allow overriding by mods

Assets/Scripts/Terrain/TerrainHelper.cs
I think this is good change giving a wider area outside city walls before natures can get placed, and it incidentally also feeds into a mod I am making very nicely.
Please say if anyone objects.
=> Increase location extra clearance for cities

Assets/Scripts/Game/Player/FrictionMotor.cs
Problematic cases seem now handled correctly by Unity 2019.4 capsule
=> remove unstick handling

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs
Had to hide some of the UI due to different dimensions of a few pixels. Used panels for this as it was easier than manipulating the base image tex2D.
=> Update item maker to use advanced item list

Assets/Scripts/Game/Entities/PlayerEntity.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Added IsLoitering flag for modding purposes, without having to override the DaggerfallRestWindow (which can cause incompatibilities with other mods that do.)
=> Added IsLoitering flag

Assets/Scripts/Game/Entities/PlayerEntity.cs
Didn't manage to get any in classic, so I assume this is classic behavior
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3678
https://www.reddit.com/r/daggerfallunity/comments/i7xsm2/has_the_ship_bug_been_fixed/g17x6xd/
=> Prevent intermittent enemy spawns on ship

Assets/StreamingAssets/Quests/A0C00Y16.txt, Assets/StreamingAssets/Quests/C0B00Y01.txt, Assets/StreamingAssets/Quests/K0C00Y05.txt, Assets/StreamingAssets/Quests/N0B40Y07.txt, Assets/StreamingAssets/Quests/P0B20L09.txt, Assets/StreamingAssets/Quests/Q0C00Y04.txt
Forums: https://forums.dfworkshop.net/viewtopic.php?f=25&t=4035
=> quests: remove extraneous empty messages

Assets/Scripts/Game/PlayerFootsteps.cs
Make sure water splash sound plays when walking in dungeon shallow water
[SAVE646.zip](https://github.com/Interkarma/daggerfall-unity/files/5112087/SAVE646.zip)
=> Dungeon shallow water splash sound

Assets/Scripts/Utility/MacroHelper.cs
Just grabs first city in region list since it's only used in one joke but appears twice so either needs context or deterministic behaviour... I chose the easy latter.
=> Implemented cn2 macro for jokes

Assets/Scripts/DaggerfallUnityStructs.cs, Assets/Scripts/Terrain/TerrainHelper.cs
Basically gives control over flattening a wider area based on location type. Requested by Kamer for his stables modding work.
=> Allow mods to set extra blend space around locations for placing content

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/Editor/ModDependenciesEditorWindow.cs, Assets/Game/Addons/ModSupport/Editor/ModDependenciesEditorWindow.cs.meta, Assets/Game/Addons/ModSupport/ModTypes.cs
Added an editor window to edit mod dependencies. It's available from Mod Builder window.
=> Mod Dependencies Editor

Assets/Scripts/Game/MagicAndEffects/Effects/Special/VampirismEffect.cs
=> Move satiation check to a public accessor for mod access

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/ItemBuilder.cs, Assets/Scripts/Game/Items/ItemHelper.cs, Assets/Scripts/Internal/DaggerfallLoot.cs
Feels like the calculation of random material for a given level should be exposed for mods
=> Move material selection into overridable formulas

Assets/Scripts/DungeonTextureTables.cs, Assets/Scripts/Internal/DaggerfallDungeon.cs, Assets/Scripts/Internal/DaggerfallMesh.cs, Assets/Scripts/Utility/AssetInjection/Components/RuntimeMaterials.cs, Assets/Scripts/Utility/RDBLayout.cs
Added option for RuntimeMaterials to use the texture table of parent dungeon.
=> UseDungeonTextureTable for RuntimeMaterials

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallJoystickControlsWindow.cs
=> Regression fix for axis rebinding, no duplicate highlighting between left/right click

Assets/Scripts/Utility/DaggerfallDateTime.cs
Make sure full moons happen on 21st and 25th of Morning Star, then
23rd and 27th of Sun Dawn, etc.
Forums: https://forums.dfworkshop.net/viewtopic.php?f=22&t=4203
=> fix lunar computations

Assets/Scripts/Internal/DaggerfallInterior.cs, Assets/Scripts/Utility/RMBLayout.cs
As discussed here: https://forums.dfworkshop.net/viewtopic.php?f=22&t=4309
=> Ensure models with registered actions are not combined for RMB and interiors

Assets/Scripts/Game/Guilds/KnightlyOrder.cs
See: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4306
=> Fix exploit for Kightly Order armor service

Assets/Scripts/Game/LoanChecker.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4346
Save less than 24h before default (but with enough on account to repay the loan). Neutral current reputation.
[SAVE867.zip](https://github.com/Interkarma/daggerfall-unity/files/5646217/SAVE867.zip)
=> only apply reputation drop once in case of bank default

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs
Description of the bug:
https://github.com/Interkarma/daggerfall-unity/pull/1965#issuecomment-744803943
=> Fix regression introduced in #1965

Assets/Scripts/Game/InputManager.cs
There were a couple of odd overlapping bugs I found. Here is one of them that I could reproduce:
1. Reset bindings to default
2. Remove `TurnLeft` and `TurnRight` in the primary bindings
3. Set `TurnLeft` and `TurnRight` as  "Left Arrow" and "Right Arrow", respectively, in the secondary bindings
4. Close windows, observe that TurnLeft has stopped working
Changes:
- Prevent binding `KeyCode` "None" to an action dictionary, so it won't get serialized in KeyBinds.txt
- Fix repopulating `existingKeyDict` when `actionKeyDict` did not contain every action by looping through the `Actions` enum list instead
- In `TestSetBinding`, do not set a default binding if the default `KeyCode` for it is already being used in the secondary bindings
=> Default binding fixes

Assets/Game/Addons/ModSupport/ModTypes.cs, Assets/Scripts/Game/GameManager.cs, Assets/Scripts/Game/PlayerEnterExit.cs
Fixed some issues with xml syntax and improved docs.
=> Fix and improve a few xml docs

Assets/Scripts/Game/Automap.cs
For compatibility with modded models:
https://forums.dfworkshop.net/viewtopic.php?p=51357#p51357
=> recursively update MeshRenderers in Automap

Assets/Scripts/API/Arch3dPatch.cs
Fix a bug reported of the forums: https://forums.dfworkshop.net/viewtopic.php?p=23940#p23940. Can be tested with the save provided by Pango.
=> Fix model 729 main entrance left door

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs
Automatically import mod manifest file after creation or changes from editor window.
=> Import mod manifest after changes

Assets/Scripts/Game/EnablePlayerTorch.cs
For atmosphere. See https://forums.dfworkshop.net/viewtopic.php?f=12&p=52174
=> Adjust position of item based player torch to throw some visible shadows off static geometry

Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
Just a silly oversight on my part.
=> Fix dictionary access for non existant keys

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
To match classic DF see https://forums.dfworkshop.net/viewtopic.php?f=31&t=4587
=> Don't restrict shields by plate or chain

Assets/Scripts/Game/MagicAndEffects/Effects/Special/OghmaInfiniumEffect.cs, Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs, Assets/Scripts/Game/MagicAndEffects/MagicAndEffectsStructs.cs
Suggested fix only - untested, so will need testing first. I just figured this would be the correct way to fix the issue rather than adding remove from wagon into Oghma effect class. Feel free to close if you don't like it.
=> Change removal of Oghma to be handled by effect manager

Assets/Game/Addons/ModSupport/Mod.cs
I have been looking at improving support for localization of custom text used by mods. Ideally the process should be similar to core translation but it doesn't look like new databases can be discovered at runtime, so this is still based on old csv tables, at least until we find a better solution.
A mod with custom text should have a main table named **textdatabase.txt** for fallback (this was already supported), while built-in translations now can be provided with language identifiers (for example **[en]textdatabase.txt**, **[fr]textdatabase.txt**, ...). Other mods can supply missing translations via GUID (for example **[fr(7e0510a9-be7d-4fd4-9c89-ed2f2b2e5fb3)]textdatabase.txt**).
=> Improve support of mod localization

Assets/Game/Addons/ModSupport/ModManager.cs
[Win 10 - When I set "region format" to Turkish (Turkey) 90% of the DREAM mod gets compromised](https://forums.dfworkshop.net/viewtopic.php?f=31&t=4526&p=52693#p52693)
=> Fix mod asset loading on turkish culture

Assets/Scripts/Game/UserInterface/HUDLarge.cs
Doesn't prevent mouse cursor from moving while cursor is disabled though
Forums: https://forums.dfworkshop.net/viewtopic.php?f=31&t=4630
=> Only interact with large HUD when cursor active on Linux

Assets/Game/Addons/ModSupport/Editor/CreateModEditorWindow.cs, Assets/Game/Addons/ModSupport/ModManager.cs, Assets/Game/Addons/ModSupport/ModSettings/ModSettingsData.cs
Automatically import mod settings and presets files after creation or changes from editor window.
=> Import mod settings after changes

Assets/Scripts/Game/UserInterface/DaggerfallShortcut.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallHUD.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPauseOptionsWindow.cs, Assets/StreamingAssets/Text/DialogShortcuts.txt
Minimum implementation.
By the way, while implementing this, I noticed what looks like an unrelated bug: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4630
=> Toggle large HUD with F10 like classic

Assets/Scripts/Internal/DaggerfallActionDoor.cs
This PR adds the option of using a MeshCollider to provide a door's collision instead of a BoxCollider. To do so, you have to disable the door's BoxCollider and add a MeshCollider.
This allows modders to design doors that are not box shaped yet have accurate collision. In fact, there are at least 2 such doors in the base game (specifically, 55007 and 55008).
=> ActionDoor: Add support for MeshCollider

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs
As requested by forum user Macadaynu
=> Open up spell book for mods

Assets/Scripts/Game/MagicAndEffects/EntityEffectManager.cs
=> Don't reset lastSpell when using magic missile items

Assets/Scripts/Game/EnablePlayerTorch.cs
=> Enable player torch shadows based on spell shadows setting

Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/Items/ItemCollection.cs
If you ever tried to collect all existing books, you probably know the pain of checking manually if you already have one book.
Having identical books stack together makes that easier.
=> Stack identical books together

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Poisons/PoisonEffect.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Added formula overrides for the following formulas:
- InflictPoison
- InflictDisease
- SavingThrow
Also fixed OnMonsterHit formula not returning after invoking the formula override.
For "formulas" that don't return a value, it's better to use Action than have a Func with an unused return value.
=> Added "resistance" formula overrides. 

Assets/Scripts/Game/DaggerfallBankManager.cs, Assets/Scripts/Game/Formulas/FormulaHelper.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs
Also exposes some for overriding that were not before.
=> Add formula for bank loans

Assets/Game/Addons/ModSupport/Editor/CreateModScript.cs, Assets/Game/Addons/ModSupport/Editor/CreateModScript.cs.meta, Assets/Game/Addons/ModSupport/Editor/ModScript.cs.txt, Assets/Game/Addons/ModSupport/Editor/ModScript.cs.txt.meta
Adds menu item "Create > C# Mod Script" to quickly create new mod scripts.
=> Add mod script asset template

Assets/Scripts/Utility/AssetInjection/MeshReplacement.cs
=> Fix cache issue with climate/season model variants

Assets/Scripts/Game/TalkManager.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTalkWindow.cs
The Talk window is inside the UI window factory, and therefore can technically be overriden by mods, but there's not really anything useful they can change.
Changes minimized compared to the version in PR #2137.
=> Exposed more functions and data in the Talk window 

Assets/Scripts/API/BlocksFile.cs
N22 + N23, remove bad door object entirely
N35, reposition door in doorframe
=> Fix RDB door data in runtime patching

Assets/StreamingAssets/Quests/N0B11Y18.txt, Assets/StreamingAssets/Quests/S0000502.txt, Assets/StreamingAssets/Quests/S0000503.txt, Assets/StreamingAssets/Tables/QuestList-Classic.txt
Thoroughly playtested... but I'm sure bugs will get reported. Bring on the reports!
I had to change the place symbols L.00 and L.01 to other ones I created. After that, the quest loaded fine! No idea why those symbols caused problems. But this is done.
=> Implements Baltham Greyman questline

Assets/Shaders/DaggerfallRetroPalettization.shader, Assets/Shaders/DaggerfallRetroPosterization.shader
Do palette transformations in gamma colorspace
=> Retrorendering in linear colorspace

Assets/Scripts/Game/TalkManager.cs
Added new behavior "AlwaysFriendly" to force NPCs to respond helpfully even if they don't like you numerically. This is particularly helpful when debugging quests and you simply want answers from a mobile NPC instead of playing whack-a-mole to find one that likes you; `talk_npcBehavior 3` gets you omniscient, affable NPCs wherever you go.
Refactored "talk_npcsKnowEverything" and "talk_npcsKnowUsual" commands to drive a variant of new flags-based enum field for behavior states.
Finally, added a know-everything check to `GetAnswerWhereIs` method to fix an issue where extant mobile NPCs did not know answers to Where Is questions if they were not omniscient when spawned (i.e. developer changes behavior state to KnowEverything after NPC spawned).
=> Add console var "talk_npcBehavior" to override behavior in dialogs

Assets/Scripts/Game/StaticNPC.cs
Fixes xml comment that couldn't be parsed by docfx.
=> Fix badly formed XML comment

Assets/StreamingAssets/Tables/QuestList-Classic.txt
Contingent on recent quest engine fixes getting merged, see issues 2190, 2191
=> Enables K0C00Y06, A0C00Y16

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
No functional changes, just permissions.
=> Change protection to allow mod overriding for save/load UI window

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCourtWindow.cs
This contains a slight refactoring of the main logic outside of the Update() method since this is called up the hierarchy. All other changes are protection only.
=> Change protection to allow mod overriding for court UI window

Assets/StreamingAssets/Quests/C0B10Y07.txt, Assets/StreamingAssets/Quests/S0000502.txt
Referenced in https://www.reddit.com/r/daggerfallunity/comments/plj9ah/quest_former_student_part_ii_broken/hcgdgj2/
=> Removes leftover elements of Baltham Greyman Pt2

Assets/Scripts/Game/Questing/Task.cs
Request to add a new "Actions" get property to the Task.cs class. This is to enable a mod to automatically add notes to the player's notebook with main story NPC quest dialogue, issue request [here](https://forums.dfworkshop.net/viewtopic.php?f=12&t=4942).
Also to help with the implementation of a hidden map location mod idea found [here](https://forums.dfworkshop.net/viewtopic.php?f=12&t=5117).
=> added actions property to task class

Assets/Scripts/Game/Questing/Item.cs
I just had a chat with Jehuty about how this code is used and the glaring problem for clothing item generation is that quest code has no way to check for gender, so it can only ask to generate male or female clothes with no way of knowing if that is correct for the current player character. So I avoid doing any gender checks and came up with this.
From the tests I did, this should produce the correct item each time but with a randomly picked dye.
=> Randomize dye color for clothing items created by quests.

Assets/StreamingAssets/Quests/S0000106.txt
Fixes bug reported in http://forums.dfworkshop.net/viewtopic.php?f=5&t=5234&p=58362
=> KoW Totem Reputation fix

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelPopUp.cs
Needed for next release of Travel Options mod
=> Allow setting properties from override classes

Assets/Scripts/Utility/DaggerfallDateTime.cs
Fixes the second most offensive part of this screenshot: https://www.reddit.com/r/Daggerfall/comments/sdq1qx/wtf_daggerfall/
=> Fixed calendar showing "23th of Sun's Dusk"

Assets/Scripts/Game/PlayerActivate.cs
Necessary for my mod: https://forums.dfworkshop.net/viewtopic.php?t=5373.
=> Option to change interaction mode without notification

Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs, Assets/Scripts/Game/Entities/PlayerEntity.cs
This is the "simplest" method,
but a bit hacky - hence experimental.
=> Add toggle noclip console command

Assets/Game/Addons/ModSupport/ModManager.cs
Forums: https://forums.dfworkshop.net/viewtopic.php?p=56707#p56707
=> Only warn about non-optional missing dependencies

Assets/Scripts/Game/UserInterface/PaperDoll.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallCharacterSheetWindow.cs
Request from a modder doing lots of paperdolls. The numbers are still in the Inventory window of course
EDIT: 
Images for comparison
=> "Fixed" armor values showing up in the Character Sheet paperdoll­

Assets/Scripts/Game/Player/PersistentFactionData.cs
Unintended bug in my code that i spotted.
=> Fix bug where ally/enemy propagation is not performed for Knightly Orders

Assets/StreamingAssets/Quests/C0B00Y02.txt, Assets/StreamingAssets/Quests/M0B40Y05.txt, Assets/StreamingAssets/Quests/R0C10Y06.txt
I tested The Possessed Child fix in live game, to be certain of it.
=> Quest fixes May 2022

Assets/Scripts/Game/UserInterface/FolderBrowser.cs
=> Do not attempt to list drives on unix

Assets/Scripts/Utility/MacroHelper.cs, Assets/StreamingAssets/Quests/L0A01L00.txt
Makes %pgX macros consistent with %gX set as agreed.
=> Change for issue #2339

Assets/Scripts/Game/Items/ItemBuilder.cs
Fixes remainder of issue #2349
=> Fix edge case for arrow generation which would still set the material properties

Assets/StreamingAssets/Quests/$CUREVAM.txt, Assets/StreamingAssets/Quests/$CUREWER.txt, Assets/StreamingAssets/Quests/K0C00Y06.txt, Assets/StreamingAssets/Quests/M0B00Y07.txt, Assets/StreamingAssets/Quests/S0000016.txt, Assets/StreamingAssets/Quests/S0000500.txt, Assets/StreamingAssets/Quests/S0000501.txt
Reference http://forums.dfworkshop.net/viewtopic.php?t=5651
=> Displayname fixes for quests

Assets/Scripts/Game/Guilds/GuildManager.cs
These guilds require a init parameter to set the variant
=> Allow overriding temple and knightly orders

Assets/Game/Addons/WorldDataEditor/Editor/WorldDataEditor.cs
Link flags, magnitude and action to rbd flat records correctly in WDE
=> World Data Editor fixes

Assets/Game/Addons/ModSupport/ImportedComponentAttribute.cs
I am getting a warning but it gets logged as an error.
=> Log FsSerializer Warnings with LogWarningFormat()

Assets/Scripts/Utility/RMBLayout.cs
WHen I made the location cache only for !editor I didn't do the same with the const. I am sick of seeing that warning.
=> Fix editor warning I introduced

Assets/Resources/defaults.ini.txt, Assets/Scripts/Game/Automap.cs, Assets/Scripts/Game/DaggerfallUI.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAdvancedSettingsWindow.cs, Assets/Scripts/SettingsManager.cs, Assets/StreamingAssets/Text/GameSettings.txt
This is a revised version of this PR from a few days ago. https://github.com/Interkarma/daggerfall-unity/pull/2374
=> Micro map settings revision 7/5/2022

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallUnitySaveGameWindow.cs
Name of latest save game gets auto populated in the saveNameTextBox inside Save Game Window
=> latest-savegame-name-automated

Assets/Scripts/DaggerfallUnityStructs.cs, Assets/Scripts/Game/EnemyDeath.cs
Kamer would really like if we could have unique corpses for each enemy, but human enemies have uh, sexual dimorphism that's not reflected on their gender neutral corpse.
With this simple change, ladies can now turn to dust on death
=> Mods can provide a female corpse texture for classic or custom enemies

Assets/StreamingAssets/Quests/J0B00Y00.txt
I may a job -> I may have a jpb
=> typo quest exposition J0B00Y00

Assets/StreamingAssets/Quests/S0000008.txt
=> would go -> would you go

Assets/Localization/StringTables/Internal_RSC_en.asset
my near unanimous vote -> by near unanimous vote
=> Warlock promotion typo

Assets/StreamingAssets/Quests/Q0C00Y07.txt
=> typo coven quest: in imprisoned -> imprisoned

Assets/Scripts/Internal/DaggerfallBillboardBatch.cs
Reverts Interkarma/daggerfall-unity#2427
=> Revert "DaggerfallBillboardBatch: mesh data creation process multi-threaded"

Assets/StreamingAssets/Quests/R0C11Y28.txt, Assets/StreamingAssets/Quests/S0000500.txt, Assets/StreamingAssets/Quests/S0000501.txt
r0c11y28, Mad Slayer: this one didn't have "clearclick" mechanisms in place. Also removing every element of the "dead body," which appears for no reason and has no function. Am cutting it out as a presumed mistake.
=> Quest fix Nov 2022

Assets/StreamingAssets/Quests/L0A01L00.txt
Another case with a time limit the game doesn't explain. Better declared than not.
=> Add time limit reminder to DB entrance quest

Assets/StreamingAssets/Quests/C0B00Y01.txt
Dialogue fix for misplaced rumor, see https://forums.dfworkshop.net/viewtopic.php?t=6368
=> C0B00Y01 fix

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallInventoryWindow.cs
Spotted this and figured it should be corrected before release.
=> Add null check to inventory window

Assets/StreamingAssets/Quests/S0000017.txt
Reference topic: https://forums.dfworkshop.net/viewtopic.php?t=6452
=> Akorithi Painting clearclick

Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenHeld.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenStrikes.cs, Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/CastWhenUsed.cs
=> Fix SecondaryDisplayName localization

Assets/Scripts/Game/TalkManager.cs
Building location in %fcn localized
=> Building location in %fcn localized

Assets/Scripts/Utility/AssetInjection/WorldDataVariants.cs
The return values were all inverted erroneously, rather embarrassing. Not seen anyone using these return values yet, so should cause no issues.
=> Fix booleans returned when setting variants

Assets/StreamingAssets/Quests/A0C01Y01.txt, Assets/StreamingAssets/Quests/C0B00Y01.txt, Assets/StreamingAssets/Quests/M0B00Y06.txt, Assets/StreamingAssets/Quests/M0B21Y19.txt, Assets/StreamingAssets/Quests/N0B00Y16.txt, Assets/StreamingAssets/Quests/S0000009.txt, Assets/StreamingAssets/Quests/S0000015.txt, Assets/StreamingAssets/Quests/_TUTOR__.txt
Warning: I don't know what "multiple PRs" look like. I am a github novice.
This contains very basic quest fixes, almost unnoticeable. It also has my updated DFU tutorial in file _TUTOR__.txt.
=> Updated DFU tutorial, minor quest fixes

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallAutomapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankPurchasePopUp.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallExteriorAutomapWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallItemMakerWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantRepairPopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallMerchantServicePopupWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallPotionMakerWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestJournalWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallRestWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallStartWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTavernWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTeleportPopUp.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTransportWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallWitchesCovenPopupWindow.cs
Continue and expand work, started in https://github.com/Interkarma/daggerfall-unity/pull/2555
Some of the UI windows are already do expose `protected` UI elements, others are addressed here.
=> Added ability to move UI elements

Assets/Scripts/Utility/MacroHelper.cs
Added new terminator for macros that could be used for postfixes
=> Added new terminator for macros that could be used for postfixes

Assets/Scripts/Game/Serialization/SaveLoadManager.cs
This PR fixes the following issue: #2594 (Deleting and creating new save can preserve old mod save data)
The update changes the logic of `SaveGameManager.DeleteSaveFolder` to move any folder to `DELETED` should it contain unexpected files or otherwise fail to delete. If a backup folder already exists with the same, a numbered suffix is appended beginning with `_2`.
=> Added functionality to move deleted saves to DELETED dir

Assets/Scripts/Internal/DaggerfallInterior.cs
Forums:
https://forums.dfworkshop.net/viewtopic.php?t=3482 (original) 
https://forums.dfworkshop.net/viewtopic.php?t=6720 (new)
=> Fix more one-way staircases

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallBankingWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallSpellBookWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTravelMapWindow.cs, Assets/Scripts/Internal/DaggerfallBookshelf.cs
Answer to request #2684
- set limit to 50 characters instead of 29 when SDF fonts (that are narrower) are enabled;
- make that limit more accessible to modding (did I get that part right? I'm not familiar with that aspect)
=> Allow for longer names in location picker

Assets/Scripts/Game/UserInterfaceWindows/DaggerfallTradeWindow.cs, Assets/Scripts/Game/UserInterfaceWindows/DaggerfallWitchesCovenPopupWindow.cs
Adding access to UI controls that I missed in https://github.com/Interkarma/daggerfall-unity/pull/2618
=> Missed 2 UI classes
